/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.panels;

import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelPressureSetpoint extends AbstractPanelWidget
        implements UpdateReceiver {

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);

        // Make action receiver interface from controller available to elements
        // of this Panel so they can send their actions to it directly.
        setpointControlPressureOffset.registerActionReceiver(controller);
    }

    /**
     * Creates new form PanelPressureSetpoint
     */
    public PanelPressureSetpoint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCaptionBar = new javax.swing.JLabel();
        setpointControlPressureOffset = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        jLabelCaptionOffset = new javax.swing.JLabel();
        jLabelCaptionSelection2 = new javax.swing.JLabel();
        jLabelCaptionFull = new javax.swing.JLabel();
        jToggleButtonTurboSetpoint = new javax.swing.JToggleButton();
        jLabelCaptionStartup = new javax.swing.JLabel();
        jLabelReadingActiveSetpoint = new javax.swing.JLabel();
        jLabelCaptionActiveSetpoint = new javax.swing.JLabel();
        jLabelCaptionSelection1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(190, 86));
        setMinimumSize(new java.awt.Dimension(190, 86));
        setPreferredSize(new java.awt.Dimension(190, 86));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCaptionBar.setFont(jLabelCaptionBar.getFont().deriveFont(jLabelCaptionBar.getFont().getSize()-2f));
        jLabelCaptionBar.setText("bar");
        jLabelCaptionBar.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBar.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBar.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 62, 38, 14));

        setpointControlPressureOffset.setComponent("Loop#PressureSetpointOffset");
        add(setpointControlPressureOffset, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabelCaptionOffset.setFont(jLabelCaptionOffset.getFont().deriveFont(jLabelCaptionOffset.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionOffset.getFont().getSize()-2));
        jLabelCaptionOffset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionOffset.setText("Offset");
        jLabelCaptionOffset.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionOffset.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionOffset.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionOffset, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 2, 84, 14));

        jLabelCaptionSelection2.setFont(jLabelCaptionSelection2.getFont().deriveFont(jLabelCaptionSelection2.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSelection2.getFont().getSize()-2));
        jLabelCaptionSelection2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSelection2.setText("Selection");
        jLabelCaptionSelection2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSelection2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSelection2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSelection2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, 76, 14));

        jLabelCaptionFull.setFont(jLabelCaptionFull.getFont().deriveFont(jLabelCaptionFull.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionFull.getFont().getSize()-2));
        jLabelCaptionFull.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionFull.setText("Full");
        jLabelCaptionFull.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionFull.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionFull.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionFull, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 26, 14));

        jToggleButtonTurboSetpoint.setText("←");
        jToggleButtonTurboSetpoint.setToolTipText("Toggles the startup pressure setpoint to start the plant with a lower pressure that is linked to the thermal power output.");
        jToggleButtonTurboSetpoint.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonTurboSetpoint.addActionListener(this::jToggleButtonTurboSetpointActionPerformed);
        add(jToggleButtonTurboSetpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 58, 20, 20));

        jLabelCaptionStartup.setFont(jLabelCaptionStartup.getFont().deriveFont(jLabelCaptionStartup.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionStartup.getFont().getSize()-2));
        jLabelCaptionStartup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionStartup.setText("Startup");
        jLabelCaptionStartup.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionStartup.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionStartup.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionStartup, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 40, 46, 14));

        jLabelReadingActiveSetpoint.setBackground(new java.awt.Color(51, 51, 51));
        jLabelReadingActiveSetpoint.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingActiveSetpoint.setForeground(new java.awt.Color(0, 255, 153));
        jLabelReadingActiveSetpoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingActiveSetpoint.setText("___,_");
        jLabelReadingActiveSetpoint.setToolTipText("Active pressure setpoint for steam drums");
        jLabelReadingActiveSetpoint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelReadingActiveSetpoint.setMaximumSize(new java.awt.Dimension(52, 18));
        jLabelReadingActiveSetpoint.setMinimumSize(new java.awt.Dimension(52, 18));
        jLabelReadingActiveSetpoint.setOpaque(true);
        jLabelReadingActiveSetpoint.setPreferredSize(new java.awt.Dimension(52, 18));
        add(jLabelReadingActiveSetpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 60, 48, 18));

        jLabelCaptionActiveSetpoint.setFont(jLabelCaptionActiveSetpoint.getFont().deriveFont(jLabelCaptionActiveSetpoint.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionActiveSetpoint.getFont().getSize()-2));
        jLabelCaptionActiveSetpoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionActiveSetpoint.setText("Active");
        jLabelCaptionActiveSetpoint.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionActiveSetpoint.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionActiveSetpoint.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionActiveSetpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 44, 50, 14));

        jLabelCaptionSelection1.setFont(jLabelCaptionSelection1.getFont().deriveFont(jLabelCaptionSelection1.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSelection1.getFont().getSize()-2));
        jLabelCaptionSelection1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSelection1.setText("Setpoint");
        jLabelCaptionSelection1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSelection1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSelection1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSelection1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 76, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonTurboSetpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTurboSetpointActionPerformed
        if (jToggleButtonTurboSetpoint.isSelected()) {
            jToggleButtonTurboSetpoint.setText("↑");
            controller.userAction(new ActionCommand("Main#StartupPressureSetpoint", true));
        } else {
            jToggleButtonTurboSetpoint.setText("←");
            controller.userAction(new ActionCommand("Main#StartupPressureSetpoint", false));
        }
    }//GEN-LAST:event_jToggleButtonTurboSetpointActionPerformed

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals("Main#StartupPressureSetpoint")) {
            // Set the initial position of the switch button, this will be
            // received when opening the panel.
            if ((boolean) evt.getNewValue()
                    && !jToggleButtonTurboSetpoint.isSelected()) {
                jToggleButtonTurboSetpoint.setSelected(true);
                jToggleButtonTurboSetpoint.setText("↑");
            }
        }
        setpointControlPressureOffset.updateComponent(evt);
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        setpointControlPressureOffset.updateComponent(propertyName, newValue);
        if (propertyName.equals("LoopPressureSetpoint")) {
            jLabelReadingActiveSetpoint.setText(
                    String.format("%03.1f", newValue));
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

        setpointControlPressureOffset.updateComponent(propertyName, newValue);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCaptionActiveSetpoint;
    private javax.swing.JLabel jLabelCaptionBar;
    private javax.swing.JLabel jLabelCaptionFull;
    private javax.swing.JLabel jLabelCaptionOffset;
    private javax.swing.JLabel jLabelCaptionSelection1;
    private javax.swing.JLabel jLabelCaptionSelection2;
    private javax.swing.JLabel jLabelCaptionStartup;
    private javax.swing.JLabel jLabelReadingActiveSetpoint;
    private javax.swing.JToggleButton jToggleButtonTurboSetpoint;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControlPressureOffset;
    // End of variables declaration//GEN-END:variables
}
