/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.panels;

import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelPreheaters extends AbstractPanelWidget
        implements UpdateReceiver {

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);
        loopControlPreHeater1Condensate.registerActionReceiver(controller);
        loopControlPreHeater2Condensate.registerActionReceiver(controller);
        loopControlPreHeater3Condensate.registerActionReceiver(controller);
    }

    /**
     * Creates new form PanelPreheaters
     */
    public PanelPreheaters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Close = new javax.swing.JButton();
        jButton1Open = new javax.swing.JButton();
        jButton2Open = new javax.swing.JButton();
        jButton2Close = new javax.swing.JButton();
        jButton3Open = new javax.swing.JButton();
        jButton3Close = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loopControlPreHeater1Condensate = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        jLabelDA1Press1 = new javax.swing.JLabel();
        jLabelDA1Press2 = new javax.swing.JLabel();
        loopControlPreHeater2Condensate = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        jLabelDA1Press3 = new javax.swing.JLabel();
        jLabelDA1Press4 = new javax.swing.JLabel();
        loopControlPreHeater3Condensate = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        jLabelDA1Press5 = new javax.swing.JLabel();
        jLabelDA1Press6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(260, 130));
        setMinimumSize(new java.awt.Dimension(260, 130));
        setPreferredSize(new java.awt.Dimension(260, 130));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1Close.setBackground(new java.awt.Color(0, 128, 0));
        jButton1Close.setText("C");
        jButton1Close.setToolTipText("");
        jButton1Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CloseActionPerformed(evt);
            }
        });
        add(jButton1Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 20, 20));

        jButton1Open.setBackground(new java.awt.Color(128, 0, 0));
        jButton1Open.setText("O");
        jButton1Open.setToolTipText("");
        jButton1Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1OpenActionPerformed(evt);
            }
        });
        add(jButton1Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 20, 20, 20));

        jButton2Open.setBackground(new java.awt.Color(128, 0, 0));
        jButton2Open.setText("O");
        jButton2Open.setToolTipText("");
        jButton2Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2OpenActionPerformed(evt);
            }
        });
        add(jButton2Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 62, 20, 20));

        jButton2Close.setBackground(new java.awt.Color(0, 128, 0));
        jButton2Close.setText("C");
        jButton2Close.setToolTipText("");
        jButton2Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CloseActionPerformed(evt);
            }
        });
        add(jButton2Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 20, 20));

        jButton3Open.setBackground(new java.awt.Color(128, 0, 0));
        jButton3Open.setText("O");
        jButton3Open.setToolTipText("");
        jButton3Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3OpenActionPerformed(evt);
            }
        });
        add(jButton3Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 104, 20, 20));

        jButton3Close.setBackground(new java.awt.Color(0, 128, 0));
        jButton3Close.setText("C");
        jButton3Close.setToolTipText("");
        jButton3Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3CloseActionPerformed(evt);
            }
        });
        add(jButton3Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, 20, 20));

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, jLabel3.getFont().getSize()-2));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Steam 3");
        jLabel3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 88, 58, 14));

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()-2));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Steam 1");
        jLabel2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 58, 14));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()-2));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Steam 2");
        jLabel1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 46, 58, 14));

        loopControlPreHeater1Condensate.setControlComponent("Preheater1#CondensateValve");
        loopControlPreHeater1Condensate.setFeedbackComponent("Preheater1#Level");
        loopControlPreHeater1Condensate.setMaxValue(150.0);
        loopControlPreHeater1Condensate.setSetpoint(8.0);
        loopControlPreHeater1Condensate.setSetpointComponent("Preheater1#LevelSetpoint");
        loopControlPreHeater1Condensate.setUnit("cm");
        add(loopControlPreHeater1Condensate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 6, -1, -1));

        jLabelDA1Press1.setFont(jLabelDA1Press1.getFont().deriveFont(jLabelDA1Press1.getFont().getSize()-2f));
        jLabelDA1Press1.setText("Prh. 1");
        add(jLabelDA1Press1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 12, 36, 14));

        jLabelDA1Press2.setFont(jLabelDA1Press2.getFont().deriveFont(jLabelDA1Press2.getFont().getSize()-2f));
        jLabelDA1Press2.setText("Level");
        add(jLabelDA1Press2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 26, 36, 14));

        loopControlPreHeater2Condensate.setControlComponent("Preheater2#CondensateValve");
        loopControlPreHeater2Condensate.setFeedbackComponent("Preheater2#Level");
        loopControlPreHeater2Condensate.setMaxValue(150.0);
        loopControlPreHeater2Condensate.setSetpoint(8.0);
        loopControlPreHeater2Condensate.setSetpointComponent("Preheater2#LevelSetpoint");
        loopControlPreHeater2Condensate.setUnit("cm");
        add(loopControlPreHeater2Condensate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 46, -1, -1));

        jLabelDA1Press3.setFont(jLabelDA1Press3.getFont().deriveFont(jLabelDA1Press3.getFont().getSize()-2f));
        jLabelDA1Press3.setText("Prh. 2");
        add(jLabelDA1Press3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 52, 36, 14));

        jLabelDA1Press4.setFont(jLabelDA1Press4.getFont().deriveFont(jLabelDA1Press4.getFont().getSize()-2f));
        jLabelDA1Press4.setText("Level");
        add(jLabelDA1Press4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 66, 36, 14));

        loopControlPreHeater3Condensate.setControlComponent("Preheater3#CondensateValve");
        loopControlPreHeater3Condensate.setFeedbackComponent("Preheater3#Level");
        loopControlPreHeater3Condensate.setMaxValue(150.0);
        loopControlPreHeater3Condensate.setSetpoint(8.0);
        loopControlPreHeater3Condensate.setSetpointComponent("Preheater3#LevelSetpoint");
        loopControlPreHeater3Condensate.setUnit("cm");
        add(loopControlPreHeater3Condensate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 86, -1, -1));

        jLabelDA1Press5.setFont(jLabelDA1Press5.getFont().deriveFont(jLabelDA1Press5.getFont().getSize()-2f));
        jLabelDA1Press5.setText("Prh 3.");
        add(jLabelDA1Press5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 92, 36, 14));

        jLabelDA1Press6.setFont(jLabelDA1Press6.getFont().deriveFont(jLabelDA1Press6.getFont().getSize()-2f));
        jLabelDA1Press6.setText("Level");
        add(jLabelDA1Press6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 106, 36, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CloseActionPerformed
        controller.userAction(new ActionCommand("Turbine3#LowPressureTapValve", false));
    }//GEN-LAST:event_jButton1CloseActionPerformed

    private void jButton1OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1OpenActionPerformed
        controller.userAction(new ActionCommand("Turbine3#LowPressureTapValve", true));
    }//GEN-LAST:event_jButton1OpenActionPerformed

    private void jButton2OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2OpenActionPerformed
        controller.userAction(new ActionCommand("Turbine2#LowPressureTapValve", true));
    }//GEN-LAST:event_jButton2OpenActionPerformed

    private void jButton2CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CloseActionPerformed
        controller.userAction(new ActionCommand("Turbine2#LowPressureTapValve", false));
    }//GEN-LAST:event_jButton2CloseActionPerformed

    private void jButton3OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3OpenActionPerformed
        controller.userAction(new ActionCommand("Turbine1#LowPressureTapValve", true));
    }//GEN-LAST:event_jButton3OpenActionPerformed

    private void jButton3CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3CloseActionPerformed
        controller.userAction(new ActionCommand("Turbine1#LowPressureTapValve", false));
    }//GEN-LAST:event_jButton3CloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Close;
    private javax.swing.JButton jButton1Open;
    private javax.swing.JButton jButton2Close;
    private javax.swing.JButton jButton2Open;
    private javax.swing.JButton jButton3Close;
    private javax.swing.JButton jButton3Open;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDA1Press1;
    private javax.swing.JLabel jLabelDA1Press2;
    private javax.swing.JLabel jLabelDA1Press3;
    private javax.swing.JLabel jLabelDA1Press4;
    private javax.swing.JLabel jLabelDA1Press5;
    private javax.swing.JLabel jLabelDA1Press6;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop loopControlPreHeater1Condensate;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop loopControlPreHeater2Condensate;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop loopControlPreHeater3Condensate;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        switch (evt.getPropertyName()) {
            case "Turbine3#LowPressureTapValve_Pos" ->
                setValveButtons(jButton1Close,
                        jButton1Open, evt.getNewValue());
            case "Turbine2#LowPressureTapValve_Pos" ->
                setValveButtons(jButton2Close,
                        jButton2Open, evt.getNewValue());
            case "Turbine1#LowPressureTapValve_Pos" ->
                setValveButtons(jButton3Close,
                        jButton3Open, evt.getNewValue());
        }
        loopControlPreHeater1Condensate.updateComponent(evt);
        loopControlPreHeater2Condensate.updateComponent(evt);
        loopControlPreHeater3Condensate.updateComponent(evt);
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        loopControlPreHeater1Condensate.updateComponent(propertyName, newValue);
        loopControlPreHeater2Condensate.updateComponent(propertyName, newValue);
        loopControlPreHeater3Condensate.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
