/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.panels;

import com.hartrusion.control.ControlCommand;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelCondensation extends AbstractPanelWidget {

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);
        panelWidgetMakeupPump1.registerActionReceiver(controller);
        panelWidgetMakeupPump2.registerActionReceiver(controller);
        panelWidgetPumpCondensate1.registerActionReceiver(controller);
        panelWidgetPumpCondensate2.registerActionReceiver(controller);
        panelWidgetPumpCondensate3.registerActionReceiver(controller);
        panelWidgetPumpBoost1.registerActionReceiver(controller);
        panelWidgetPumpBoost2.registerActionReceiver(controller);
        panelWidgetPumpBoost3.registerActionReceiver(controller);
        controlLoopHotwellFill.registerActionReceiver(controller);
        controlLoopHotwellDrain.registerActionReceiver(controller);
        integralSwitch1.registerActionReceiver(controller);
        integralSwitch2.registerActionReceiver(controller);
        integralSwitch3.registerActionReceiver(controller);
        integralSwitch4.registerActionReceiver(controller);
        integralSwitch5.registerActionReceiver(controller);
    }

    /**
     * Creates new form PanelCondensation
     */
    public PanelCondensation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWidgetPumpBoost3 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPumpBoost2 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPumpBoost1 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPumpCondensate3 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPumpCondensate2 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPumpCondensate1 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        controlLoopHotwellFill = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        controlLoopHotwellDrain = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        jLabelHotwellDrain1 = new javax.swing.JLabel();
        jLabelHotwellDrain2 = new javax.swing.JLabel();
        jLabelHotwellFill2 = new javax.swing.JLabel();
        jLabelHotwellFill1 = new javax.swing.JLabel();
        integralSwitch1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitch2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitch3 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        jLabelEjectorSuction = new javax.swing.JLabel();
        jButtonEjector1SuctionClose = new javax.swing.JButton();
        jButtonEjector1SuctionOpen = new javax.swing.JButton();
        jButtonEjector1InClose = new javax.swing.JButton();
        jButtonEjector1InOpen = new javax.swing.JButton();
        jButtonEjector2InOpen = new javax.swing.JButton();
        jButtonEjector2InClose = new javax.swing.JButton();
        jLabelEjectorInlet = new javax.swing.JLabel();
        jLabelEjectorSteam = new javax.swing.JLabel();
        jButtonEjector3InOpen = new javax.swing.JButton();
        jButtonEjector3InClose = new javax.swing.JButton();
        jButtonEjector1OutClose = new javax.swing.JButton();
        jButtonEjector1OutOpen = new javax.swing.JButton();
        jButtonEjector2OutOpen = new javax.swing.JButton();
        jButtonEjector2OutClose = new javax.swing.JButton();
        jButtonEjector3OutOpen = new javax.swing.JButton();
        jButtonEjector3OutClose = new javax.swing.JButton();
        jButtonEjector2SuctionOpen = new javax.swing.JButton();
        jButtonEjector2SuctionClose = new javax.swing.JButton();
        jButtonEjector3SuctionOpen = new javax.swing.JButton();
        jButtonEjector3SuctionClose = new javax.swing.JButton();
        jLabelEjectorOutlet = new javax.swing.JLabel();
        jLabelBypass = new javax.swing.JLabel();
        jButtonEjectorBypassClose = new javax.swing.JButton();
        jButtonEjectorBypassOpen = new javax.swing.JButton();
        jLabelCaptionEjector3 = new javax.swing.JLabel();
        jLabelCaptionEjector1 = new javax.swing.JLabel();
        jLabelCaptionEjector2 = new javax.swing.JLabel();
        jButtonColdCondensateDrainClose = new javax.swing.JButton();
        jLabelColdCondensateDrain = new javax.swing.JLabel();
        jButtonColdCondensateDrainOpen = new javax.swing.JButton();
        jLabelCaptionPump14 = new javax.swing.JLabel();
        jLabelDA1Level1 = new javax.swing.JLabel();
        jLabelDA1Level2 = new javax.swing.JLabel();
        chornobylGaugeLevel = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        panelWidgetMakeupPump2 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetMakeupPump1 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        jButtonColdCondensateFillClose = new javax.swing.JButton();
        jLabelColdCondensateFill = new javax.swing.JLabel();
        jButtonColdCondensateFillOpen = new javax.swing.JButton();
        jLabelCaptionPump16 = new javax.swing.JLabel();
        jLabelCaptionPump17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        chornobylGaugeHotwellLevel = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chornobylGaugeCondensateFlow = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabelCaptionPump18 = new javax.swing.JLabel();
        jLabelCaptionPump19 = new javax.swing.JLabel();
        jLabelCaptionPump20 = new javax.swing.JLabel();
        jLabelCaptionPump21 = new javax.swing.JLabel();
        jLabelCaptionPump22 = new javax.swing.JLabel();
        jLabelCaptionPump23 = new javax.swing.JLabel();
        jLabelCaptionPump24 = new javax.swing.JLabel();
        jLabelCaptionPump25 = new javax.swing.JLabel();
        integralSwitch4 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitch5 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        chornobylGaugeVacuum = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelCaption1 = new javax.swing.JLabel();
        jLabelCaption2 = new javax.swing.JLabel();
        jLabelCaption3 = new javax.swing.JLabel();
        jLabelCaption4 = new javax.swing.JLabel();
        jLabelEjectorCondensate = new javax.swing.JLabel();
        jLabelBypass1 = new javax.swing.JLabel();
        jButtonEjectorTurbineTapClose = new javax.swing.JButton();
        jButtonEjectorTurbineTapOpen = new javax.swing.JButton();
        jLabelBypass2 = new javax.swing.JLabel();
        jButtonEjector1CondensateClose = new javax.swing.JButton();
        jButtonEjector1CondensateOpen = new javax.swing.JButton();
        jButtonEjector2CondensateOpen = new javax.swing.JButton();
        jButtonEjector2CondensateClose = new javax.swing.JButton();
        jButtonEjector3CondensateOpen = new javax.swing.JButton();
        jButtonEjector3CondensateClose = new javax.swing.JButton();
        jLabelBypass3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(568, 340));
        setMinimumSize(new java.awt.Dimension(568, 340));
        setPreferredSize(new java.awt.Dimension(568, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelWidgetPumpBoost3.setChornobylPrefix("Condensation3#CondensatePump");
        add(panelWidgetPumpBoost3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        panelWidgetPumpBoost2.setChornobylPrefix("Condensation2#CondensatePump");
        add(panelWidgetPumpBoost2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        panelWidgetPumpBoost1.setChornobylPrefix("Condensation1#CondensatePump");
        add(panelWidgetPumpBoost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        panelWidgetPumpCondensate3.setChornobylPrefix("Condensation3#HotwellPump");
        add(panelWidgetPumpCondensate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        panelWidgetPumpCondensate2.setChornobylPrefix("Condensation2#HotwellPump");
        add(panelWidgetPumpCondensate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        panelWidgetPumpCondensate1.setChornobylPrefix("Condensation1#HotwellPump");
        add(panelWidgetPumpCondensate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        controlLoopHotwellFill.setControlComponent("Hotwell#FillValve");
        controlLoopHotwellFill.setFeedbackComponent("Hotwell#Level");
        controlLoopHotwellFill.setSetpointComponent("Hotwell#LowerSetpoint");
        controlLoopHotwellFill.setUnit("cm");
        add(controlLoopHotwellFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 76, -1, -1));

        controlLoopHotwellDrain.setControlComponent("Hotwell#DrainValve");
        controlLoopHotwellDrain.setFeedbackComponent("Hotwell#Level");
        controlLoopHotwellDrain.setSetpointComponent("Hotwell#UpperSetpoint");
        controlLoopHotwellDrain.setUnit("cm");
        add(controlLoopHotwellDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jLabelHotwellDrain1.setFont(jLabelHotwellDrain1.getFont().deriveFont(jLabelHotwellDrain1.getFont().getSize()-2f));
        jLabelHotwellDrain1.setText("Hotwell");
        add(jLabelHotwellDrain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 126, 50, 14));

        jLabelHotwellDrain2.setFont(jLabelHotwellDrain2.getFont().deriveFont(jLabelHotwellDrain2.getFont().getSize()-2f));
        jLabelHotwellDrain2.setText("Drain");
        add(jLabelHotwellDrain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 140, 50, 14));

        jLabelHotwellFill2.setFont(jLabelHotwellFill2.getFont().deriveFont(jLabelHotwellFill2.getFont().getSize()-2f));
        jLabelHotwellFill2.setText("Fill");
        add(jLabelHotwellFill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 98, 50, 14));

        jLabelHotwellFill1.setFont(jLabelHotwellFill1.getFont().deriveFont(jLabelHotwellFill1.getFont().getSize()-2f));
        jLabelHotwellFill1.setText("Hotwell");
        add(jLabelHotwellFill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 84, 50, 14));

        integralSwitch1.setComponent("EjectorMain1#SteamValve");
        add(integralSwitch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 226, -1, -1));

        integralSwitch2.setComponent("EjectorMain2#SteamValve");
        add(integralSwitch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 226, -1, -1));

        integralSwitch3.setComponent("EjectorMain3#SteamValve");
        add(integralSwitch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 226, -1, -1));

        jLabelEjectorSuction.setFont(jLabelEjectorSuction.getFont().deriveFont(jLabelEjectorSuction.getFont().getSize()-2f));
        jLabelEjectorSuction.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelEjectorSuction.setText("Suction");
        jLabelEjectorSuction.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelEjectorSuction.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelEjectorSuction.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelEjectorSuction, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 200, 40, 14));

        jButtonEjector1SuctionClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector1SuctionClose.setText("C");
        jButtonEjector1SuctionClose.setToolTipText("");
        jButtonEjector1SuctionClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector1SuctionClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector1SuctionCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector1SuctionClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 198, 20, 20));

        jButtonEjector1SuctionOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector1SuctionOpen.setText("O");
        jButtonEjector1SuctionOpen.setToolTipText("");
        jButtonEjector1SuctionOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector1SuctionOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector1SuctionOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector1SuctionOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 198, 20, 20));

        jButtonEjector1InClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector1InClose.setText("C");
        jButtonEjector1InClose.setToolTipText("");
        jButtonEjector1InClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector1InClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector1InCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector1InClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 258, 20, 20));

        jButtonEjector1InOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector1InOpen.setText("O");
        jButtonEjector1InOpen.setToolTipText("");
        jButtonEjector1InOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector1InOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector1InOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector1InOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 258, 20, 20));

        jButtonEjector2InOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector2InOpen.setText("O");
        jButtonEjector2InOpen.setToolTipText("");
        jButtonEjector2InOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector2InOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector2InOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector2InOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 258, 20, 20));

        jButtonEjector2InClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector2InClose.setText("C");
        jButtonEjector2InClose.setToolTipText("");
        jButtonEjector2InClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector2InClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector2InCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector2InClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 258, 20, 20));

        jLabelEjectorInlet.setFont(jLabelEjectorInlet.getFont().deriveFont(jLabelEjectorInlet.getFont().getSize()-2f));
        jLabelEjectorInlet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelEjectorInlet.setText("Inlet");
        jLabelEjectorInlet.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelEjectorInlet.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelEjectorInlet.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelEjectorInlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 260, 40, 14));

        jLabelEjectorSteam.setFont(jLabelEjectorSteam.getFont().deriveFont(jLabelEjectorSteam.getFont().getSize()-2f));
        jLabelEjectorSteam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelEjectorSteam.setText("Steam");
        jLabelEjectorSteam.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelEjectorSteam.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelEjectorSteam.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelEjectorSteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 234, 40, 14));

        jButtonEjector3InOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector3InOpen.setText("O");
        jButtonEjector3InOpen.setToolTipText("");
        jButtonEjector3InOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector3InOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector3InOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector3InOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 258, 20, 20));

        jButtonEjector3InClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector3InClose.setText("C");
        jButtonEjector3InClose.setToolTipText("");
        jButtonEjector3InClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector3InClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector3InCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector3InClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 258, 20, 20));

        jButtonEjector1OutClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector1OutClose.setText("C");
        jButtonEjector1OutClose.setToolTipText("");
        jButtonEjector1OutClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector1OutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector1OutCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector1OutClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 284, 20, 20));

        jButtonEjector1OutOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector1OutOpen.setText("O");
        jButtonEjector1OutOpen.setToolTipText("");
        jButtonEjector1OutOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector1OutOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector1OutOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector1OutOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 284, 20, 20));

        jButtonEjector2OutOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector2OutOpen.setText("O");
        jButtonEjector2OutOpen.setToolTipText("");
        jButtonEjector2OutOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector2OutOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector2OutOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector2OutOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 284, 20, 20));

        jButtonEjector2OutClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector2OutClose.setText("C");
        jButtonEjector2OutClose.setToolTipText("");
        jButtonEjector2OutClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector2OutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector2OutCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector2OutClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 284, 20, 20));

        jButtonEjector3OutOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector3OutOpen.setText("O");
        jButtonEjector3OutOpen.setToolTipText("");
        jButtonEjector3OutOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector3OutOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector3OutOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector3OutOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 284, 20, 20));

        jButtonEjector3OutClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector3OutClose.setText("C");
        jButtonEjector3OutClose.setToolTipText("");
        jButtonEjector3OutClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector3OutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector3OutCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector3OutClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 284, 20, 20));

        jButtonEjector2SuctionOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector2SuctionOpen.setText("O");
        jButtonEjector2SuctionOpen.setToolTipText("");
        jButtonEjector2SuctionOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector2SuctionOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector2SuctionOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector2SuctionOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 198, 20, 20));

        jButtonEjector2SuctionClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector2SuctionClose.setText("C");
        jButtonEjector2SuctionClose.setToolTipText("");
        jButtonEjector2SuctionClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector2SuctionClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector2SuctionCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector2SuctionClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 198, 20, 20));

        jButtonEjector3SuctionOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector3SuctionOpen.setText("O");
        jButtonEjector3SuctionOpen.setToolTipText("");
        jButtonEjector3SuctionOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector3SuctionOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector3SuctionOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector3SuctionOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 198, 20, 20));

        jButtonEjector3SuctionClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector3SuctionClose.setText("C");
        jButtonEjector3SuctionClose.setToolTipText("");
        jButtonEjector3SuctionClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector3SuctionClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector3SuctionCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector3SuctionClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 198, 20, 20));

        jLabelEjectorOutlet.setFont(jLabelEjectorOutlet.getFont().deriveFont(jLabelEjectorOutlet.getFont().getSize()-2f));
        jLabelEjectorOutlet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelEjectorOutlet.setText("Outliet");
        jLabelEjectorOutlet.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelEjectorOutlet.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelEjectorOutlet.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelEjectorOutlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 286, 40, 14));

        jLabelBypass.setFont(jLabelBypass.getFont().deriveFont(jLabelBypass.getFont().getSize()-2f));
        jLabelBypass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBypass.setText("Bypass");
        jLabelBypass.setToolTipText("Main Ejector Bypass");
        jLabelBypass.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelBypass.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelBypass.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelBypass, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 296, 52, 14));

        jButtonEjectorBypassClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjectorBypassClose.setText("C");
        jButtonEjectorBypassClose.setToolTipText("Main Ejector Bypass");
        jButtonEjectorBypassClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjectorBypassClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjectorBypassCloseActionPerformed(evt);
            }
        });
        add(jButtonEjectorBypassClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 310, 20, 20));

        jButtonEjectorBypassOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjectorBypassOpen.setText("O");
        jButtonEjectorBypassOpen.setToolTipText("Main Ejector Bypass");
        jButtonEjectorBypassOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjectorBypassOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjectorBypassOpenActionPerformed(evt);
            }
        });
        add(jButtonEjectorBypassOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 310, 20, 20));

        jLabelCaptionEjector3.setFont(jLabelCaptionEjector3.getFont().deriveFont(jLabelCaptionEjector3.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionEjector3.getFont().getSize()-2));
        jLabelCaptionEjector3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionEjector3.setText("Ejector 3");
        jLabelCaptionEjector3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionEjector3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionEjector3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionEjector3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 180, 64, 14));

        jLabelCaptionEjector1.setFont(jLabelCaptionEjector1.getFont().deriveFont(jLabelCaptionEjector1.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionEjector1.getFont().getSize()-2));
        jLabelCaptionEjector1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionEjector1.setText("Ejector 1");
        jLabelCaptionEjector1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionEjector1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionEjector1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionEjector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 64, 14));

        jLabelCaptionEjector2.setFont(jLabelCaptionEjector2.getFont().deriveFont(jLabelCaptionEjector2.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionEjector2.getFont().getSize()-2));
        jLabelCaptionEjector2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionEjector2.setText("Ejector2");
        jLabelCaptionEjector2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionEjector2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionEjector2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionEjector2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 180, 64, 14));

        jButtonColdCondensateDrainClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonColdCondensateDrainClose.setText("C");
        jButtonColdCondensateDrainClose.setToolTipText("Drains the cold condensate storage tank");
        jButtonColdCondensateDrainClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonColdCondensateDrainClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColdCondensateDrainCloseActionPerformed(evt);
            }
        });
        add(jButtonColdCondensateDrainClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 20, 20));

        jLabelColdCondensateDrain.setFont(jLabelColdCondensateDrain.getFont().deriveFont(jLabelColdCondensateDrain.getFont().getSize()-2f));
        jLabelColdCondensateDrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelColdCondensateDrain.setText("Drain");
        jLabelColdCondensateDrain.setToolTipText("Drains the cold condensate storage tank");
        jLabelColdCondensateDrain.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelColdCondensateDrain.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelColdCondensateDrain.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelColdCondensateDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 106, 52, 14));

        jButtonColdCondensateDrainOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonColdCondensateDrainOpen.setText("O");
        jButtonColdCondensateDrainOpen.setToolTipText("Drains the cold condensate storage tank");
        jButtonColdCondensateDrainOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonColdCondensateDrainOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColdCondensateDrainOpenActionPerformed(evt);
            }
        });
        add(jButtonColdCondensateDrainOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 20, 20));

        jLabelCaptionPump14.setFont(jLabelCaptionPump14.getFont().deriveFont(jLabelCaptionPump14.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump14.getFont().getSize()-2));
        jLabelCaptionPump14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump14.setText("Pump 2");
        jLabelCaptionPump14.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump14.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump14.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump14, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 50, 48, 14));

        jLabelDA1Level1.setFont(jLabelDA1Level1.getFont().deriveFont(jLabelDA1Level1.getFont().getSize()-2f));
        jLabelDA1Level1.setText("Cold Cnd.");
        add(jLabelDA1Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 52, 14));

        jLabelDA1Level2.setFont(jLabelDA1Level2.getFont().deriveFont(jLabelDA1Level2.getFont().getSize()-2f));
        jLabelDA1Level2.setText("Level");
        add(jLabelDA1Level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 52, 14));

        chornobylGaugeLevel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeLevel.setChornobylMaximum(10.0F);
        chornobylGaugeLevel.setChornobylMinimum(0.0F);
        chornobylGaugeLevel.setChornobylTicks(new float[] {0.0f, 2.0f, 4.0f, 6.0f, 8.0f, 10.0f});
        chornobylGaugeLevel.setChornobylUnitText("m");
        chornobylGaugeLevel.setChornobylValue(0.0F);
        add(chornobylGaugeLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, -1, -1));

        panelWidgetMakeupPump2.setChornobylPrefix("Makeup2#Pumps");
        add(panelWidgetMakeupPump2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 68, -1, -1));

        panelWidgetMakeupPump1.setChornobylPrefix("Makeup1#Pumps");
        add(panelWidgetMakeupPump1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 68, -1, -1));

        jButtonColdCondensateFillClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonColdCondensateFillClose.setText("C");
        jButtonColdCondensateFillClose.setToolTipText("Fills the cold condensate tank with additional demineralized water");
        jButtonColdCondensateFillClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonColdCondensateFillClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColdCondensateFillCloseActionPerformed(evt);
            }
        });
        add(jButtonColdCondensateFillClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 74, 20, 20));

        jLabelColdCondensateFill.setFont(jLabelColdCondensateFill.getFont().deriveFont(jLabelColdCondensateFill.getFont().getSize()-2f));
        jLabelColdCondensateFill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelColdCondensateFill.setText("Fill");
        jLabelColdCondensateFill.setToolTipText("Fills the cold condensate tank with additional demineralized water");
        jLabelColdCondensateFill.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelColdCondensateFill.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelColdCondensateFill.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelColdCondensateFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 60, 52, 14));

        jButtonColdCondensateFillOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonColdCondensateFillOpen.setText("O");
        jButtonColdCondensateFillOpen.setToolTipText("Fills the cold condensate tank with additional demineralized water");
        jButtonColdCondensateFillOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonColdCondensateFillOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColdCondensateFillOpenActionPerformed(evt);
            }
        });
        add(jButtonColdCondensateFillOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 74, 20, 20));

        jLabelCaptionPump16.setFont(jLabelCaptionPump16.getFont().deriveFont(jLabelCaptionPump16.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump16.getFont().getSize()-2));
        jLabelCaptionPump16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump16.setText("Pump 3");
        jLabelCaptionPump16.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump16.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump16.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump16, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 54, 54, 14));

        jLabelCaptionPump17.setFont(jLabelCaptionPump17.getFont().deriveFont(jLabelCaptionPump17.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump17.getFont().getSize()-2));
        jLabelCaptionPump17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump17.setText("Makeup");
        jLabelCaptionPump17.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump17.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump17.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump17, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 34, 54, 14));

        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getSize()-2f));
        jLabel24.setText("Hotwell");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 4, 52, 14));

        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getSize()-2f));
        jLabel18.setText("Level");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 16, 52, 14));

        chornobylGaugeHotwellLevel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeHotwellLevel.setChornobylMaximum(120.0F);
        chornobylGaugeHotwellLevel.setChornobylMinimum(0.0F);
        chornobylGaugeHotwellLevel.setChornobylTicks(new float[] {0.0f, 30.0f, 60.0f, 90.0f, 120.0f});
        chornobylGaugeHotwellLevel.setChornobylValue(0.0F);
        add(chornobylGaugeHotwellLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 4, -1, -1));

        jLabel25.setFont(jLabel25.getFont().deriveFont(jLabel25.getFont().getSize()-2f));
        jLabel25.setText("Cond.");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 4, 36, 14));

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getSize()-2f));
        jLabel19.setText("Flow");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 16, 36, 14));

        chornobylGaugeCondensateFlow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeCondensateFlow.setChornobylMaximum(4000.0F);
        chornobylGaugeCondensateFlow.setChornobylMinimum(0.0F);
        chornobylGaugeCondensateFlow.setChornobylTicks(new float[] {0.0f, 2000.0f, 3500.0f});
        chornobylGaugeCondensateFlow.setChornobylUnitText("kg/s");
        add(chornobylGaugeCondensateFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 4, -1, -1));

        jLabelCaptionPump18.setFont(jLabelCaptionPump18.getFont().deriveFont(jLabelCaptionPump18.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump18.getFont().getSize()-2));
        jLabelCaptionPump18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump18.setText("Pump 1");
        jLabelCaptionPump18.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump18.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump18.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump18, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 50, 54, 14));

        jLabelCaptionPump19.setFont(jLabelCaptionPump19.getFont().deriveFont(jLabelCaptionPump19.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump19.getFont().getSize()-2));
        jLabelCaptionPump19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump19.setText("Pump 1");
        jLabelCaptionPump19.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump19.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump19.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 54, 54, 14));

        jLabelCaptionPump20.setFont(jLabelCaptionPump20.getFont().deriveFont(jLabelCaptionPump20.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump20.getFont().getSize()-2));
        jLabelCaptionPump20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump20.setText("Pump 2");
        jLabelCaptionPump20.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump20.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump20.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 54, 54, 14));

        jLabelCaptionPump21.setFont(jLabelCaptionPump21.getFont().deriveFont(jLabelCaptionPump21.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump21.getFont().getSize()-2));
        jLabelCaptionPump21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump21.setText("Booster Pumps");
        jLabelCaptionPump21.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump21.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump21.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump21, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 190, 132, 14));

        jLabelCaptionPump22.setFont(jLabelCaptionPump22.getFont().deriveFont(jLabelCaptionPump22.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump22.getFont().getSize()-2));
        jLabelCaptionPump22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump22.setText("Pump 2");
        jLabelCaptionPump22.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump22.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump22.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump22, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 206, 54, 14));

        jLabelCaptionPump23.setFont(jLabelCaptionPump23.getFont().deriveFont(jLabelCaptionPump23.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump23.getFont().getSize()-2));
        jLabelCaptionPump23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump23.setText("Pump 3");
        jLabelCaptionPump23.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump23.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump23.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump23, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 206, 54, 14));

        jLabelCaptionPump24.setFont(jLabelCaptionPump24.getFont().deriveFont(jLabelCaptionPump24.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump24.getFont().getSize()-2));
        jLabelCaptionPump24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump24.setText("Pump 1");
        jLabelCaptionPump24.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump24.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump24.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump24, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 206, 54, 14));

        jLabelCaptionPump25.setFont(jLabelCaptionPump25.getFont().deriveFont(jLabelCaptionPump25.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump25.getFont().getSize()-2));
        jLabelCaptionPump25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump25.setText("Condensate Pumps");
        jLabelCaptionPump25.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump25.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump25.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 38, 132, 14));

        integralSwitch4.setComponent("EjectorStartup1");
        add(integralSwitch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 194, -1, -1));

        integralSwitch5.setComponent("EjectorStartup2");
        add(integralSwitch5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 194, -1, -1));

        chornobylGaugeVacuum.setChornobylMaximum(100.0F);
        chornobylGaugeVacuum.setChornobylMinimum(0.0F);
        chornobylGaugeVacuum.setChornobylTicks(new float[] {0.0f, 25.0f, 50.0f, 75.0f, 100.0f});
        chornobylGaugeVacuum.setChornobylUnitText("kPa");
        chornobylGaugeVacuum.setChornobylValue(1.0F);
        add(chornobylGaugeVacuum, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 34, -1, -1));

        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getSize()-2f));
        jLabel23.setText("Condens.");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 34, 52, 14));

        jLabel17.setFont(jLabel17.getFont().deriveFont(jLabel17.getFont().getSize()-2f));
        jLabel17.setText("Vacuum");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 46, 52, 14));

        jLabelCaption1.setFont(jLabelCaption1.getFont().deriveFont(jLabelCaption1.getFont().getSize()-2f));
        jLabelCaption1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption1.setText("Startup");
        jLabelCaption1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 166, 51, 14));

        jLabelCaption2.setFont(jLabelCaption2.getFont().deriveFont(jLabelCaption2.getFont().getSize()-2f));
        jLabelCaption2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption2.setText("Ejector 2");
        jLabelCaption2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 178, 51, 14));

        jLabelCaption3.setFont(jLabelCaption3.getFont().deriveFont(jLabelCaption3.getFont().getSize()-2f));
        jLabelCaption3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption3.setText("Startup");
        jLabelCaption3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 166, 51, 14));

        jLabelCaption4.setFont(jLabelCaption4.getFont().deriveFont(jLabelCaption4.getFont().getSize()-2f));
        jLabelCaption4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption4.setText("Ejector 1");
        jLabelCaption4.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption4.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption4.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 178, 51, 14));

        jLabelEjectorCondensate.setFont(jLabelEjectorCondensate.getFont().deriveFont(jLabelEjectorCondensate.getFont().getSize()-2f));
        jLabelEjectorCondensate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelEjectorCondensate.setText("Cond.");
        jLabelEjectorCondensate.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelEjectorCondensate.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelEjectorCondensate.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelEjectorCondensate, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 312, 40, 14));

        jLabelBypass1.setFont(jLabelBypass1.getFont().deriveFont(jLabelBypass1.getFont().getSize()-2f));
        jLabelBypass1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBypass1.setText("Ejectors");
        jLabelBypass1.setToolTipText("Steam Supply for Main Ejectors from Turbine Tap");
        jLabelBypass1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelBypass1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelBypass1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelBypass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 230, 52, 14));

        jButtonEjectorTurbineTapClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjectorTurbineTapClose.setText("C");
        jButtonEjectorTurbineTapClose.setToolTipText("Steam Supply for Main Ejectors from Turbine Tap");
        jButtonEjectorTurbineTapClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjectorTurbineTapClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjectorTurbineTapCloseActionPerformed(evt);
            }
        });
        add(jButtonEjectorTurbineTapClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 256, 20, 20));

        jButtonEjectorTurbineTapOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjectorTurbineTapOpen.setText("O");
        jButtonEjectorTurbineTapOpen.setToolTipText("Steam Supply for Main Ejectors from Turbine Tap");
        jButtonEjectorTurbineTapOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjectorTurbineTapOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjectorTurbineTapOpenActionPerformed(evt);
            }
        });
        add(jButtonEjectorTurbineTapOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 256, 20, 20));

        jLabelBypass2.setFont(jLabelBypass2.getFont().deriveFont(jLabelBypass2.getFont().getSize()-2f));
        jLabelBypass2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBypass2.setText("Turbine Tap");
        jLabelBypass2.setToolTipText("Steam Supply for Main Ejectors from Turbine Tap");
        jLabelBypass2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelBypass2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelBypass2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelBypass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 242, 78, 14));

        jButtonEjector1CondensateClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector1CondensateClose.setText("C");
        jButtonEjector1CondensateClose.setToolTipText("");
        jButtonEjector1CondensateClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector1CondensateClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector1CondensateCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector1CondensateClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 310, 20, 20));

        jButtonEjector1CondensateOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector1CondensateOpen.setText("O");
        jButtonEjector1CondensateOpen.setToolTipText("");
        jButtonEjector1CondensateOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector1CondensateOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector1CondensateOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector1CondensateOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 310, 20, 20));

        jButtonEjector2CondensateOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector2CondensateOpen.setText("O");
        jButtonEjector2CondensateOpen.setToolTipText("");
        jButtonEjector2CondensateOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector2CondensateOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector2CondensateOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector2CondensateOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 310, 20, 20));

        jButtonEjector2CondensateClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector2CondensateClose.setText("C");
        jButtonEjector2CondensateClose.setToolTipText("");
        jButtonEjector2CondensateClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector2CondensateClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector2CondensateCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector2CondensateClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 20, 20));

        jButtonEjector3CondensateOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonEjector3CondensateOpen.setText("O");
        jButtonEjector3CondensateOpen.setToolTipText("");
        jButtonEjector3CondensateOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector3CondensateOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector3CondensateOpenActionPerformed(evt);
            }
        });
        add(jButtonEjector3CondensateOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 310, 20, 20));

        jButtonEjector3CondensateClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonEjector3CondensateClose.setText("C");
        jButtonEjector3CondensateClose.setToolTipText("");
        jButtonEjector3CondensateClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEjector3CondensateClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjector3CondensateCloseActionPerformed(evt);
            }
        });
        add(jButtonEjector3CondensateClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 310, 20, 20));

        jLabelBypass3.setFont(jLabelBypass3.getFont().deriveFont(jLabelBypass3.getFont().getSize()-2f));
        jLabelBypass3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBypass3.setText("Ejectors");
        jLabelBypass3.setToolTipText("Main Ejector Bypass");
        jLabelBypass3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelBypass3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelBypass3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelBypass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 284, 76, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEjector1SuctionCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector1SuctionCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain1#SuctionValve", false));
    }//GEN-LAST:event_jButtonEjector1SuctionCloseActionPerformed

    private void jButtonEjector1SuctionOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector1SuctionOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain1#SuctionValve", true));
    }//GEN-LAST:event_jButtonEjector1SuctionOpenActionPerformed

    private void jButtonEjector1InCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector1InCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain1#FlowIn", false));
    }//GEN-LAST:event_jButtonEjector1InCloseActionPerformed

    private void jButtonEjector1InOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector1InOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain1#FlowIn", true));
    }//GEN-LAST:event_jButtonEjector1InOpenActionPerformed

    private void jButtonEjector2InOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector2InOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain2#FlowIn", true));
    }//GEN-LAST:event_jButtonEjector2InOpenActionPerformed

    private void jButtonEjector2InCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector2InCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain2#FlowIn", false));
    }//GEN-LAST:event_jButtonEjector2InCloseActionPerformed

    private void jButtonEjector3InOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector3InOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain3#FlowIn", true));
    }//GEN-LAST:event_jButtonEjector3InOpenActionPerformed

    private void jButtonEjector3InCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector3InCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain3#FlowIn", false));
    }//GEN-LAST:event_jButtonEjector3InCloseActionPerformed

    private void jButtonEjector1OutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector1OutCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain1#FlowOut", false));
    }//GEN-LAST:event_jButtonEjector1OutCloseActionPerformed

    private void jButtonEjector1OutOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector1OutOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain1#FlowOut", true));
    }//GEN-LAST:event_jButtonEjector1OutOpenActionPerformed

    private void jButtonEjector2OutOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector2OutOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain2#FlowOut", true));
    }//GEN-LAST:event_jButtonEjector2OutOpenActionPerformed

    private void jButtonEjector2OutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector2OutCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain2#FlowOut", false));
    }//GEN-LAST:event_jButtonEjector2OutCloseActionPerformed

    private void jButtonEjector3OutOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector3OutOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain3#FlowOut", true));
    }//GEN-LAST:event_jButtonEjector3OutOpenActionPerformed

    private void jButtonEjector3OutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector3OutCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain3#FlowOut", false));
    }//GEN-LAST:event_jButtonEjector3OutCloseActionPerformed

    private void jButtonEjector2SuctionOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector2SuctionOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain2#SuctionValve", true));
    }//GEN-LAST:event_jButtonEjector2SuctionOpenActionPerformed

    private void jButtonEjector2SuctionCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector2SuctionCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain2#SuctionValve", false));
    }//GEN-LAST:event_jButtonEjector2SuctionCloseActionPerformed

    private void jButtonEjector3SuctionOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector3SuctionOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain3#SuctionValve", true));
    }//GEN-LAST:event_jButtonEjector3SuctionOpenActionPerformed

    private void jButtonEjector3SuctionCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector3SuctionCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain3#SuctionValve", false));
    }//GEN-LAST:event_jButtonEjector3SuctionCloseActionPerformed

    private void jButtonEjectorBypassCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjectorBypassCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain#Bypass", false));
    }//GEN-LAST:event_jButtonEjectorBypassCloseActionPerformed

    private void jButtonEjectorBypassOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjectorBypassOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain#Bypass", true));
    }//GEN-LAST:event_jButtonEjectorBypassOpenActionPerformed

    private void jButtonColdCondensateDrainCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColdCondensateDrainCloseActionPerformed
        controller.userAction(new ActionCommand("Makeup#DrainValve", false));
    }//GEN-LAST:event_jButtonColdCondensateDrainCloseActionPerformed

    private void jButtonColdCondensateDrainOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColdCondensateDrainOpenActionPerformed
        controller.userAction(new ActionCommand("Makeup#DrainValve", true));
    }//GEN-LAST:event_jButtonColdCondensateDrainOpenActionPerformed

    private void jButtonColdCondensateFillCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColdCondensateFillCloseActionPerformed
        controller.userAction(new ActionCommand("Makeup#FillValve", false));
    }//GEN-LAST:event_jButtonColdCondensateFillCloseActionPerformed

    private void jButtonColdCondensateFillOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColdCondensateFillOpenActionPerformed
        controller.userAction(new ActionCommand("Makeup#FillValve", true));
    }//GEN-LAST:event_jButtonColdCondensateFillOpenActionPerformed

    private void jButtonEjectorTurbineTapCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjectorTurbineTapCloseActionPerformed
        controller.userAction(new ActionCommand("Turbine4#LowPressureTapValve", false));
    }//GEN-LAST:event_jButtonEjectorTurbineTapCloseActionPerformed

    private void jButtonEjectorTurbineTapOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjectorTurbineTapOpenActionPerformed
        controller.userAction(new ActionCommand("Turbine4#LowPressureTapValve", true));
    }//GEN-LAST:event_jButtonEjectorTurbineTapOpenActionPerformed

    private void jButtonEjector1CondensateCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector1CondensateCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain1#CondensateValve", false));
    }//GEN-LAST:event_jButtonEjector1CondensateCloseActionPerformed

    private void jButtonEjector1CondensateOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector1CondensateOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain1#CondensateValve", true));
    }//GEN-LAST:event_jButtonEjector1CondensateOpenActionPerformed

    private void jButtonEjector2CondensateOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector2CondensateOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain2#CondensateValve", true));
    }//GEN-LAST:event_jButtonEjector2CondensateOpenActionPerformed

    private void jButtonEjector2CondensateCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector2CondensateCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain1#CondensateValve", false));
    }//GEN-LAST:event_jButtonEjector2CondensateCloseActionPerformed

    private void jButtonEjector3CondensateOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector3CondensateOpenActionPerformed
        controller.userAction(new ActionCommand("EjectorMain3#CondensateValve", true));
    }//GEN-LAST:event_jButtonEjector3CondensateOpenActionPerformed

    private void jButtonEjector3CondensateCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjector3CondensateCloseActionPerformed
        controller.userAction(new ActionCommand("EjectorMain3#CondensateValve", false));
    }//GEN-LAST:event_jButtonEjector3CondensateCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeCondensateFlow;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeHotwellLevel;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLevel;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeVacuum;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop controlLoopHotwellDrain;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop controlLoopHotwellFill;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch2;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch3;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch4;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch5;
    private javax.swing.JButton jButtonColdCondensateDrainClose;
    private javax.swing.JButton jButtonColdCondensateDrainOpen;
    private javax.swing.JButton jButtonColdCondensateFillClose;
    private javax.swing.JButton jButtonColdCondensateFillOpen;
    private javax.swing.JButton jButtonEjector1CondensateClose;
    private javax.swing.JButton jButtonEjector1CondensateOpen;
    private javax.swing.JButton jButtonEjector1InClose;
    private javax.swing.JButton jButtonEjector1InOpen;
    private javax.swing.JButton jButtonEjector1OutClose;
    private javax.swing.JButton jButtonEjector1OutOpen;
    private javax.swing.JButton jButtonEjector1SuctionClose;
    private javax.swing.JButton jButtonEjector1SuctionOpen;
    private javax.swing.JButton jButtonEjector2CondensateClose;
    private javax.swing.JButton jButtonEjector2CondensateOpen;
    private javax.swing.JButton jButtonEjector2InClose;
    private javax.swing.JButton jButtonEjector2InOpen;
    private javax.swing.JButton jButtonEjector2OutClose;
    private javax.swing.JButton jButtonEjector2OutOpen;
    private javax.swing.JButton jButtonEjector2SuctionClose;
    private javax.swing.JButton jButtonEjector2SuctionOpen;
    private javax.swing.JButton jButtonEjector3CondensateClose;
    private javax.swing.JButton jButtonEjector3CondensateOpen;
    private javax.swing.JButton jButtonEjector3InClose;
    private javax.swing.JButton jButtonEjector3InOpen;
    private javax.swing.JButton jButtonEjector3OutClose;
    private javax.swing.JButton jButtonEjector3OutOpen;
    private javax.swing.JButton jButtonEjector3SuctionClose;
    private javax.swing.JButton jButtonEjector3SuctionOpen;
    private javax.swing.JButton jButtonEjectorBypassClose;
    private javax.swing.JButton jButtonEjectorBypassOpen;
    private javax.swing.JButton jButtonEjectorTurbineTapClose;
    private javax.swing.JButton jButtonEjectorTurbineTapOpen;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabelBypass;
    private javax.swing.JLabel jLabelBypass1;
    private javax.swing.JLabel jLabelBypass2;
    private javax.swing.JLabel jLabelBypass3;
    private javax.swing.JLabel jLabelCaption1;
    private javax.swing.JLabel jLabelCaption2;
    private javax.swing.JLabel jLabelCaption3;
    private javax.swing.JLabel jLabelCaption4;
    private javax.swing.JLabel jLabelCaptionEjector1;
    private javax.swing.JLabel jLabelCaptionEjector2;
    private javax.swing.JLabel jLabelCaptionEjector3;
    private javax.swing.JLabel jLabelCaptionPump14;
    private javax.swing.JLabel jLabelCaptionPump16;
    private javax.swing.JLabel jLabelCaptionPump17;
    private javax.swing.JLabel jLabelCaptionPump18;
    private javax.swing.JLabel jLabelCaptionPump19;
    private javax.swing.JLabel jLabelCaptionPump20;
    private javax.swing.JLabel jLabelCaptionPump21;
    private javax.swing.JLabel jLabelCaptionPump22;
    private javax.swing.JLabel jLabelCaptionPump23;
    private javax.swing.JLabel jLabelCaptionPump24;
    private javax.swing.JLabel jLabelCaptionPump25;
    private javax.swing.JLabel jLabelColdCondensateDrain;
    private javax.swing.JLabel jLabelColdCondensateFill;
    private javax.swing.JLabel jLabelDA1Level1;
    private javax.swing.JLabel jLabelDA1Level2;
    private javax.swing.JLabel jLabelEjectorCondensate;
    private javax.swing.JLabel jLabelEjectorInlet;
    private javax.swing.JLabel jLabelEjectorOutlet;
    private javax.swing.JLabel jLabelEjectorSteam;
    private javax.swing.JLabel jLabelEjectorSuction;
    private javax.swing.JLabel jLabelHotwellDrain1;
    private javax.swing.JLabel jLabelHotwellDrain2;
    private javax.swing.JLabel jLabelHotwellFill1;
    private javax.swing.JLabel jLabelHotwellFill2;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetMakeupPump1;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetMakeupPump2;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpBoost1;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpBoost2;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpBoost3;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpCondensate1;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpCondensate2;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpCondensate3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        panelWidgetMakeupPump1.updateComponent(evt);
        panelWidgetMakeupPump2.updateComponent(evt);
        panelWidgetPumpCondensate1.updateComponent(evt);
        panelWidgetPumpCondensate2.updateComponent(evt);
        panelWidgetPumpCondensate3.updateComponent(evt);
        panelWidgetPumpBoost1.updateComponent(evt);
        panelWidgetPumpBoost2.updateComponent(evt);
        panelWidgetPumpBoost3.updateComponent(evt);
        controlLoopHotwellFill.updateComponent(evt);
        controlLoopHotwellDrain.updateComponent(evt);
        integralSwitch1.updateComponent(evt);
        integralSwitch2.updateComponent(evt);
        integralSwitch3.updateComponent(evt);
        integralSwitch4.updateComponent(evt);
        integralSwitch5.updateComponent(evt);

        switch (evt.getPropertyName()) {
            case "Makeup#DrainValve_Pos" ->
                setValveButtons(jButtonColdCondensateDrainClose,
                        jButtonColdCondensateDrainOpen, evt.getNewValue());
            case "Makeup#FillValve_Pos" ->
                setValveButtons(jButtonColdCondensateFillClose,
                        jButtonColdCondensateFillOpen, evt.getNewValue());
            case "EjectorMain1#FlowIn_Pos" ->
                setValveButtons(jButtonEjector1InClose,
                        jButtonEjector1InOpen, evt.getNewValue());
            case "EjectorMain1#FlowOut_Pos" ->
                setValveButtons(jButtonEjector1OutClose,
                        jButtonEjector1OutOpen, evt.getNewValue());
            case "EjectorMain2#FlowIn_Pos" ->
                setValveButtons(jButtonEjector2InClose,
                        jButtonEjector2InOpen, evt.getNewValue());
            case "EjectorMain2#FlowOut_Pos" ->
                setValveButtons(jButtonEjector2OutClose,
                        jButtonEjector2OutOpen, evt.getNewValue());
            case "EjectorMain3#FlowIn_Pos" ->
                setValveButtons(jButtonEjector3InClose,
                        jButtonEjector3InOpen, evt.getNewValue());
            case "EjectorMain3#FlowOut_Pos" ->
                setValveButtons(jButtonEjector3OutClose,
                        jButtonEjector3OutOpen, evt.getNewValue());
            case "EjectorMain#Bypass_Pos" ->
                setValveButtons(jButtonEjectorBypassClose,
                        jButtonEjectorBypassOpen, evt.getNewValue());
            case "Turbine4#LowPressureTapValve_Pos" ->
                setValveButtons(jButtonEjectorTurbineTapClose,
                        jButtonEjectorTurbineTapOpen, evt.getNewValue());
            case "EjectorMain1#CondensateValve_Pos" ->
                setValveButtons(jButtonEjector1CondensateClose,
                        jButtonEjector1CondensateOpen, evt.getNewValue());
            case "EjectorMain2#CondensateValve_Pos" ->
                setValveButtons(jButtonEjector2CondensateClose,
                        jButtonEjector2CondensateOpen, evt.getNewValue());
            case "EjectorMain3#CondensateValve_Pos" ->
                setValveButtons(jButtonEjector3CondensateClose,
                        jButtonEjector3CondensateOpen, evt.getNewValue());
            case "EjectorMain1#SuctionValve_Pos" ->
                setValveButtons(jButtonEjector1SuctionClose,
                        jButtonEjector1SuctionOpen, evt.getNewValue());
            case "EjectorMain2#SuctionValve_Pos" ->
                setValveButtons(jButtonEjector2SuctionClose,
                        jButtonEjector2SuctionOpen, evt.getNewValue());
            case "EjectorMain3#SuctionValve_Pos" ->
                setValveButtons(jButtonEjector3SuctionClose,
                        jButtonEjector3SuctionOpen, evt.getNewValue());
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        switch (propertyName) {
            case "MakeupStorage#Level" ->
                chornobylGaugeLevel.setChornobylValue((float) newValue);
            case "Hotwell#Level" ->
                chornobylGaugeHotwellLevel.setChornobylValue((float) newValue);
            case "Condenser#Vacuum" ->
                chornobylGaugeVacuum.setChornobylValue((float) newValue);
        }
        controlLoopHotwellFill.updateComponent(propertyName, newValue);
        controlLoopHotwellDrain.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
