/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 * An internal frame that holds exactly one Panel class for the control desk
 * layout. It is made somehow more abstract as its only purpose is to serve as a
 * container for those panels, those panels itself are expanding the
 * AbstractPanelWidget and knowledge of methods of that superclass is
 * sufficient.
 *
 * @author Viktor Alexander Hartung
 */
public class ControlPanelFrame extends javax.swing.JInternalFrame implements UpdateReceiver {

    private AbstractPanelWidget child;

    /**
     * Creates new form ControlPanelFrame
     */
    public ControlPanelFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Initializes a control panel Element by adding the Panel
     *
     * @param panel
     * @param title
     * @param controller
     */
    public void initPanel(AbstractPanelWidget panel, String title,
            ActionReceiver controller) {
        child = panel;
        child.registerActionReceiver(controller);
        setTitle(title);
        getContentPane().add(panel, java.awt.BorderLayout.CENTER);
        pack();
    }

    /**
     * Returns a unique name to identify this instance.
     *
     * @return String
     */
    public String getPanelName() {
        // return child.getClass().getSimpleName();
        return getTitle();
    }

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        child.updateComponent(evt);
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        child.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        child.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
        child.updateComponent(propertyName, newValue);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
