/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.ActionReceiver;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author viktor
 */
public class ControlPanelCondensation extends javax.swing.JFrame 
        implements InteractiveComponent {
    /**
     * Creates new form ControlPanelCondensation
     */
    public ControlPanelCondensation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCondensation1 = new com.hartrusion.rbmksim.gui.PanelCondensation();
        panelAuxCondenser1 = new com.hartrusion.rbmksim.gui.PanelAuxCondenser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Condensation Control Panel");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelAuxCondenser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCondensation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAuxCondenser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelCondensation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.PanelAuxCondenser panelAuxCondenser1;
    private com.hartrusion.rbmksim.gui.PanelCondensation panelCondensation1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        panelAuxCondenser1.registerActionReceiver(controller);
        panelCondensation1.registerActionReceiver(controller);
    }

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        panelAuxCondenser1.updateComponent(evt);
        panelCondensation1.updateComponent(evt);
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        panelAuxCondenser1.updateComponent(propertyName, newValue);
        panelCondensation1.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        panelAuxCondenser1.updateComponent(propertyName, newValue);
        panelCondensation1.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
        panelAuxCondenser1.updateComponent(propertyName, newValue);
        panelCondensation1.updateComponent(propertyName, newValue);
    }
}
