/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.plot.Line;
import com.hartrusion.plot.YYAxes;
import com.hartrusion.values.ValueHandler;
import java.awt.Color;

/**
 *
 * @author viktor
 */
public class FrameDiagramLoopLevel extends javax.swing.JFrame {
  
    /**
     * Creates new form FrameDiagramLoop1Level
     */
    public FrameDiagramLoopLevel() {
        initComponents();
    }

    public void initPlots(ValueHandler plotData, int loop) {
        setTitle("Loop " + loop + " Level Control");
        YYAxes ax = (YYAxes) figureJPane1.getLastAxes();
        ax.setHold(true);
        Line l;
        l = new Line();
        l.setDataSource(plotData.getTime60(5),
                plotData.getParameterDoubleSeries("Loop" + loop + "#DrumLevel", 5));
        ax.addLine(1, l);
        l = new Line();
        l.setDataSource(plotData.getTime60(5),
                plotData.getParameterDoubleSeries("Loop" + loop + "#DrumLevelSetpoint", 5));
        l.setLineColor(Color.BLACK);
        ax.addLine(1, l);
        l = new Line();
        l.setDataSource(plotData.getTime60(5),
                plotData.getParameterDoubleSeries("Feedwater" + loop + "#FlowRegulationValve1", 5));
        l.setLineColor(new Color(0,128,0));
        ax.addLine(2, l);
        l = new Line();
        l.setDataSource(plotData.getTime60(5),
                plotData.getParameterDoubleSeries("Feedwater" + loop + "#FlowRegulationValve2", 5));
        l.setLineColor(new Color(0,128,0));
        ax.addLine(2, l);
        l = new Line();
        l.setDataSource(plotData.getTime60(5),
                plotData.getParameterDoubleSeries("Feedwater" + loop + "#FlowRegulationValve3", 5));
        l.setLineColor(new Color(0,128,0));
        ax.addLine(2, l);
        
        ax.yLim(1, -20, 20);
        ax.yLim(2, 0, 100);
        
        ax.autoX();
        
        ax.ylabel(1, "Drum Level and Setpoint (cm)");
        ax.ylabel(2, "Flow Valve Positions (%)");
    }

    public void updatePlots() {
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        figureJPane1 = new com.hartrusion.plot.FigureJPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loop N Level Control");

        figureJPane1.setYRulers(2);
        figureJPane1.setLayout(new javax.swing.BoxLayout(figureJPane1, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(figureJPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(figureJPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.plot.FigureJPane figureJPane1;
    // End of variables declaration//GEN-END:variables
}
