/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.plot.Line;
import com.hartrusion.plot.YYAxes;
import com.hartrusion.values.ValueHandler;
import java.awt.Color;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class FrameDiagramGlobalControl extends javax.swing.JFrame
        implements DiagramFrame {

    /**
     * Creates new form FrameDiagramGlobalControl
     */
    public FrameDiagramGlobalControl() {
        initComponents();
    }

    @Override
    public void initPlots(ValueHandler plotData, int number) {
        YYAxes ax = (YYAxes) figureJPane1.getLastAxes();
        ax.setHold(true);
        Line l;

        l = new Line();
        l.setDataSource(plotData.getTime60(5),
                plotData.getParameterDoubleSeries("Reactor#TargetNeutronFlux", 5));
        l.setLineColor(Color.GRAY);
        ax.addLine(1, l);
        l = new Line();
        l.setDataSource(plotData.getTime60(5),
                plotData.getParameterDoubleSeries("Reactor#SetpointNeutronFlux", 5));
        l.setLineColor(Color.BLACK);
        ax.addLine(1, l);
        l = new Line();
        l.setDataSource(plotData.getTime60(5),
                plotData.getParameterDoubleSeries("Reactor#NeutronFlux", 5));
        l.setLineColor(Color.BLUE);
        ax.addLine(1, l);

        l = new Line();
        l.setDataSource(plotData.getTime60(5),
                plotData.getParameterDoubleSeries("GlobalControl#AvgActiveAutoRodsPos", 5));
        ax.addLine(2, l);

        ax.yLim(1, 0, 100F);
        ax.yLim(2, 0, 7.3F);

        ax.autoX();

        ax.ylabel(1, "Neutron Flux (%)");
        ax.ylabel(2, "Avg. Auto Rods Position (m)");
    }

    @Override
    public void updatePlots() {
        repaint();
    }

    @Override
    public String getPlotName() {
        return "GlobalControl";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        figureJPane1 = new com.hartrusion.plot.FigureJPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Global Control");
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        figureJPane1.setYRulers(2);
        getContentPane().add(figureJPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.plot.FigureJPane figureJPane1;
    // End of variables declaration//GEN-END:variables
}
