/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.UpdateReceiver;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class FrameDebugFissionPower extends javax.swing.JFrame implements UpdateReceiver {
    /**
     * Creates new form FrameDebugFissionPower
     */
    public FrameDebugFissionPower() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCoreDebugValues1 = new com.hartrusion.rbmksim.gui.PanelCoreDebugValues();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fission power per fuel rod (MW)");

        panelCoreDebugValues1.setSuffix("FissionPower");
        panelCoreDebugValues1.setToolTipText("");
        panelCoreDebugValues1.setValueFormat("%.3f");
        panelCoreDebugValues1.setPreferredSize(new java.awt.Dimension(779, 529));
        getContentPane().add(panelCoreDebugValues1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.PanelCoreDebugValues panelCoreDebugValues1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {

    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }
    
    @Override
    public void updateComponent(String propertyName, double newValue) {
        panelCoreDebugValues1.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
