/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.alarm.AlarmObject;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import java.util.List;

/**
 *
 * @author viktor
 */
public class FrameAlarmTable extends javax.swing.JFrame {
    
    private ActionReceiver controller;

    /**
     * Creates new form FrameAlarmTable
     */
    public FrameAlarmTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alarmTablePanel1 = new com.hartrusion.rbmksim.gui.AlarmTablePanel();
        jButtonAcknowledge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alarms");
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(250, 340));

        alarmTablePanel1.setPreferredSize(new java.awt.Dimension(250, 316));
        getContentPane().add(alarmTablePanel1, java.awt.BorderLayout.CENTER);

        jButtonAcknowledge.setText("Acknowledge");
        jButtonAcknowledge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcknowledgeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcknowledge, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcknowledgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcknowledgeActionPerformed
        controller.userAction(new ActionCommand("AcknowledgeAlarms", null));
    }//GEN-LAST:event_jButtonAcknowledgeActionPerformed
    
    // redirect to panel
    public void setAlarms(List<AlarmObject> alarms) {
        alarmTablePanel1.setAlarms(alarms);
    }
    
    public void registerActionReceiver(ActionReceiver controller) {
        this.controller = controller;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.AlarmTablePanel alarmTablePanel1;
    private javax.swing.JButton jButtonAcknowledge;
    // End of variables declaration//GEN-END:variables
}
