/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.plot.Axes;
import com.hartrusion.plot.Line;
import com.hartrusion.values.ValueHandler;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class FrameDiagramTurbineWarmup extends javax.swing.JFrame
        implements DiagramFrame {

    /**
     * Creates new form FrameDiagramTurbineWarmup
     */
    public FrameDiagramTurbineWarmup() {
        initComponents();
    }
    
    @Override
    public void initPlots(ValueHandler plotData, int number) {
        Axes ax = figureJPane1.getLastAxes();
        ax.setHold(true);
        Line l;
        l = new Line();
        l.setDataSource(plotData.getTime60(2),
                plotData.getParameterDoubleSeries("Turbine#DebugHPInTemp", 2));
        ax.addLine(l);
        l = new Line();
        l.setDataSource(plotData.getTime60(2),
                plotData.getParameterDoubleSeries("Turbine#DebugHPOutTemp", 2));
        ax.addLine(l);
        l = new Line();
        l.setDataSource(plotData.getTime60(2),
                plotData.getParameterDoubleSeries("Turbine#DebugLPInTemp", 2));
        ax.addLine(l);

        ax.yLim(0, 300);
        ax.autoX();

        ax.ylabel("Temperature (°C)");

    }

    @Override
    public void updatePlots() {
        repaint();
    }

    @Override
    public String getPlotName() {
        return "DrumsOverview";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        figureJPane1 = new com.hartrusion.plot.FigureJPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Turbine Warmup");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(figureJPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.plot.FigureJPane figureJPane1;
    // End of variables declaration//GEN-END:variables
}
