/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.alarm.AlarmObject;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * A simple list to display all active alarms, this is likely to be replaced
 * with something better at a a later time. It does not have any nice colors or
 * the ability to acknowledge alarms.
 *
 * @author Viktor Alexander Hartung
 */
public class InterimAlarmList extends javax.swing.JFrame {

    private List<AlarmObject> alarmList;
    private final DefaultListModel<AlarmObject> alarmListModel
            = new DefaultListModel<>();

    /**
     * Creates new form InterimAlarmList
     */
    public InterimAlarmList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jListAlarms = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alarms");
        setPreferredSize(new java.awt.Dimension(200, 200));

        jScrollPane.setPreferredSize(new java.awt.Dimension(280, 200));

        jListAlarms.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jListAlarms.setModel(alarmListModel);
        jScrollPane.setViewportView(jListAlarms);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setAlarmList(List<AlarmObject> alarmList) {
        this.alarmList = alarmList;
    }

    public void updateAlarmListModel() {
        // remember selected value
        AlarmObject prevSelected = jListAlarms.getSelectedValue();
        
        // refresh list
        alarmListModel.clear();
        for (AlarmObject ao : alarmList) {
            alarmListModel.addElement(ao);
        }
        
        if (prevSelected != null) {
            int idx = alarmListModel.indexOf(prevSelected);
            if (idx >= 0) {
                jListAlarms.setSelectedIndex(idx);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<AlarmObject> jListAlarms;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
