/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.UpdateReceiver;
import java.beans.PropertyChangeEvent;

/**
 * Holds a mnemonics panel to be displayed in a JDesktopPane.
 *
 * @author Viktor Alexander Hartung
 */
public class InternalFrameMnemonic extends javax.swing.JInternalFrame 
    implements UpdateReceiver{
    
    private UpdateReceiver child;

    /**
     * Creates new form InternalFrameMnemonic
     */
    public InternalFrameMnemonic() {
        initComponents();
    }
    
    /**
     * Initializes a control panel Element by adding the Panel
     *
     * @param panel The mnemonic display panel object
     * @param title Title of the Internal Frame
     */
    public void initPanel(javax.swing.JPanel panel, String title) {
        child = (UpdateReceiver) panel;
        setTitle(title);
        getContentPane().add(panel, java.awt.BorderLayout.CENTER);
        pack();
    }

    /**
     * Returns a unique name to identify this instance.
     *
     * @return String
     */
    public String getPanelName() {
        return getTitle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        child.updateComponent(evt);
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        child.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        child.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
        child.updateComponent(propertyName, newValue);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
