/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.alarm.AlarmObject;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import java.util.List;

/**
 * An internal frame displaying the alarm list and a button for acknowledging
 * alarms.
 *
 * @author Viktor Alexander Hartung
 */
public class InternalFrameAlarmTable extends javax.swing.JInternalFrame {

    private ActionReceiver controller;

    /**
     * Creates new form InternalFrameAlarmTable
     */
    public InternalFrameAlarmTable() {
        initComponents();
        // Reflect the current global mute state (selected == muted).
        jToggleButton1.setSelected(!AlarmSound.isSoundEnabled());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        alarmTablePanel1 = new com.hartrusion.rbmksim.gui.AlarmTablePanel();
        jButtonAcknowledge = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Alarms");
        setPreferredSize(new java.awt.Dimension(250, 340));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        alarmTablePanel1.setPreferredSize(new java.awt.Dimension(250, 316));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(alarmTablePanel1, gridBagConstraints);

        jButtonAcknowledge.setText("Acknowledge");
        jButtonAcknowledge.addActionListener(this::jButtonAcknowledgeActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jButtonAcknowledge, gridBagConstraints);

        jToggleButton1.setText("Silent");
        jToggleButton1.setToolTipText("Mute the alarm sound");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jToggleButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcknowledgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcknowledgeActionPerformed
        controller.userAction(new ActionCommand("AcknowledgeAlarms", null));
    }//GEN-LAST:event_jButtonAcknowledgeActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // "Silent" pressed in == muted.
        AlarmSound.setSoundEnabled(!jToggleButton1.isSelected());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // redirect to panel
    public void setAlarms(List<AlarmObject> alarms) {
        alarmTablePanel1.setAlarms(alarms);
    }

    public void registerActionReceiver(ActionReceiver controller) {
        this.controller = controller;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.AlarmTablePanel alarmTablePanel1;
    private javax.swing.JButton jButtonAcknowledge;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
