/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import java.beans.PropertyChangeEvent;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelFeedwater extends AbstractPanelWidget
        implements UpdateReceiver {

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);
        // Make action receiver interface from controller available to elements
        // of this Panel so they can send their actions to it directly.
        panelWidgetPump11.registerActionReceiver(controller);
        panelWidgetPump12.registerActionReceiver(controller);
        panelWidgetPump21.registerActionReceiver(controller);
        panelWidgetPump22.registerActionReceiver(controller);
        panelWidgetPump3.registerActionReceiver(controller);
        
        panelWidgetControlLoopValve11.registerActionReceiver(controller);
        panelWidgetControlLoopValve12.registerActionReceiver(controller);
        panelWidgetControlLoopValve1s.registerActionReceiver(controller);
        panelWidgetControlLoopValve21.registerActionReceiver(controller);
        panelWidgetControlLoopValve22.registerActionReceiver(controller);
        panelWidgetControlLoopValve2s.registerActionReceiver(controller);

    }

    /**
     * Creates new form PanelFeedwater
     */
    public PanelFeedwater() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCaptionFeed22 = new javax.swing.JLabel();
        jButtonFeed23Open = new javax.swing.JButton();
        jButtonFeed23Close = new javax.swing.JButton();
        panelWidgetControlLoopValve11 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        panelWidgetControlLoopValve12 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        panelWidgetControlLoopValve1s = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        panelWidgetControlLoopValve21 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        panelWidgetControlLoopValve22 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        panelWidgetControlLoopValve2s = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        integralSwitchStartupReduction1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchStartupReduction2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        jLabeljLabelCaptionRegenToCooler4 = new javax.swing.JLabel();
        jButtonLoop2Open2 = new javax.swing.JButton();
        jButtonLoop2Close2 = new javax.swing.JButton();
        jLabeljLabelCaptionRegenToCooler5 = new javax.swing.JLabel();
        jButtonLoop2Open3 = new javax.swing.JButton();
        jButtonLoop2Close3 = new javax.swing.JButton();
        jLabeljLabelCaptionRegenToCooler6 = new javax.swing.JLabel();
        jButtonLoop2Open4 = new javax.swing.JButton();
        jButtonLoop2Close4 = new javax.swing.JButton();
        jLabeljLabelCaptionRegenToCooler7 = new javax.swing.JLabel();
        jButtonLoop2Open5 = new javax.swing.JButton();
        jButtonLoop2Close5 = new javax.swing.JButton();
        jLabeljLabelCaptionRegenToCooler8 = new javax.swing.JLabel();
        jButtonLoop2Open6 = new javax.swing.JButton();
        jButtonLoop2Close6 = new javax.swing.JButton();
        panelWidgetPump11 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPump12 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPump21 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPump22 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPump3 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        jLabeljLabelCaptionRegenToCooler9 = new javax.swing.JLabel();
        jButtonLoop2Open7 = new javax.swing.JButton();
        jButtonLoop2Close7 = new javax.swing.JButton();
        jLabeljLabelCaptionRegenToCooler10 = new javax.swing.JLabel();
        jButtonLoop2Open8 = new javax.swing.JButton();
        jButtonLoop2Close8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelCaptionDrain = new javax.swing.JLabel();
        jLabelCaptionDrain1 = new javax.swing.JLabel();
        jLabelCaptionDrain2 = new javax.swing.JLabel();
        jLabelCaptionDrain3 = new javax.swing.JLabel();
        jLabelCaptionDrain4 = new javax.swing.JLabel();
        jLabeljLabelCaptionRegenToCooler11 = new javax.swing.JLabel();
        jButtonLoop2Open9 = new javax.swing.JButton();
        jButtonLoop2Close9 = new javax.swing.JButton();
        jLabeljLabelCaptionRegenToCooler12 = new javax.swing.JLabel();
        jButtonLoop2Open10 = new javax.swing.JButton();
        jButtonLoop2Close10 = new javax.swing.JButton();
        jLabelCaptionDrain5 = new javax.swing.JLabel();
        jLabelCaptionDrain6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chornobylGaugeLoop1Pressure = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeLoop1Level = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        chornobylGaugeLoop2Pressure1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeLoop2Level1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        setpointControl1 = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        setpointControl2 = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        jLabel9 = new javax.swing.JLabel();
        jLabelCaptionDrain7 = new javax.swing.JLabel();
        jLabelCaptionDrain8 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(460, 340));
        setMinimumSize(new java.awt.Dimension(460, 340));
        setPreferredSize(new java.awt.Dimension(460, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCaptionFeed22.setFont(jLabelCaptionFeed22.getFont().deriveFont(jLabelCaptionFeed22.getFont().getSize()-2f));
        jLabelCaptionFeed22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionFeed22.setText("Feed 2.2");
        jLabelCaptionFeed22.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionFeed22.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionFeed22.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionFeed22, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 198, 52, 14));

        jButtonFeed23Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed23Open.setText("O");
        jButtonFeed23Open.setToolTipText("");
        jButtonFeed23Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed23Open.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonFeed23Open.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonFeed23Open.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonFeed23Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed23OpenActionPerformed(evt);
            }
        });
        add(jButtonFeed23Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 212, 20, 20));

        jButtonFeed23Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed23Close.setText("C");
        jButtonFeed23Close.setToolTipText("");
        jButtonFeed23Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed23Close.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonFeed23Close.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonFeed23Close.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonFeed23Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed23CloseActionPerformed(evt);
            }
        });
        add(jButtonFeed23Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 212, 20, 20));

        panelWidgetControlLoopValve11.setComponent("Feedwater1#FlowRegulationValve2");
        add(panelWidgetControlLoopValve11, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 72, -1, -1));

        panelWidgetControlLoopValve12.setComponent("Feedwater1#FlowRegulationValve3");
        add(panelWidgetControlLoopValve12, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 114, -1, -1));

        panelWidgetControlLoopValve1s.setComponent("Feedwater2#FlowRegulationValve2");
        add(panelWidgetControlLoopValve1s, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 156, -1, -1));

        panelWidgetControlLoopValve21.setComponent("Feedwater2#FlowRegulationValve3");
        add(panelWidgetControlLoopValve21, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 198, -1, -1));

        panelWidgetControlLoopValve22.setComponent("Feedwater1#FlowRegulationValve1");
        add(panelWidgetControlLoopValve22, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 254, -1, -1));

        panelWidgetControlLoopValve2s.setComponent("Feedwater2#FlowRegulationValve1");
        add(panelWidgetControlLoopValve2s, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 296, -1, -1));

        integralSwitchStartupReduction1.setComponent("Feedwater1#StartupReductionValve");
        add(integralSwitchStartupReduction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 260, -1, -1));

        integralSwitchStartupReduction2.setComponent("Feedwater2#StartupReductionValve");
        add(integralSwitchStartupReduction2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 302, -1, -1));

        jLabeljLabelCaptionRegenToCooler4.setFont(jLabeljLabelCaptionRegenToCooler4.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler4.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler4.setText("Feed 1.1");
        jLabeljLabelCaptionRegenToCooler4.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler4.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler4.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler4, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 72, 52, 14));

        jButtonLoop2Open2.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open2.setText("O");
        jButtonLoop2Open2.setToolTipText("");
        jButtonLoop2Open2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open2.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open2.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open2.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open2ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 86, 20, 20));

        jButtonLoop2Close2.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close2.setText("C");
        jButtonLoop2Close2.setToolTipText("");
        jButtonLoop2Close2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close2.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close2.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close2.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close2ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 86, 20, 20));

        jLabeljLabelCaptionRegenToCooler5.setFont(jLabeljLabelCaptionRegenToCooler5.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler5.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler5.setText("Startup 1");
        jLabeljLabelCaptionRegenToCooler5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler5, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 252, 52, 14));

        jButtonLoop2Open3.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open3.setText("O");
        jButtonLoop2Open3.setToolTipText("");
        jButtonLoop2Open3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open3.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open3.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open3.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open3ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open3, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 266, 20, 20));

        jButtonLoop2Close3.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close3.setText("C");
        jButtonLoop2Close3.setToolTipText("");
        jButtonLoop2Close3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close3.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close3.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close3.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close3ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 266, 20, 20));

        jLabeljLabelCaptionRegenToCooler6.setFont(jLabeljLabelCaptionRegenToCooler6.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler6.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler6.setText("Startup 2");
        jLabeljLabelCaptionRegenToCooler6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler6, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 296, 52, 14));

        jButtonLoop2Open4.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open4.setText("O");
        jButtonLoop2Open4.setToolTipText("");
        jButtonLoop2Open4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open4.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open4.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open4.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open4ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open4, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 310, 20, 20));

        jButtonLoop2Close4.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close4.setText("C");
        jButtonLoop2Close4.setToolTipText("");
        jButtonLoop2Close4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close4.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close4.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close4.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close4ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close4, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 310, 20, 20));

        jLabeljLabelCaptionRegenToCooler7.setFont(jLabeljLabelCaptionRegenToCooler7.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler7.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler7.setText("Feed 2.1");
        jLabeljLabelCaptionRegenToCooler7.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler7.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler7.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler7, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 156, 52, 14));

        jButtonLoop2Open5.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open5.setText("O");
        jButtonLoop2Open5.setToolTipText("");
        jButtonLoop2Open5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open5.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open5.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open5.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open5ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open5, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 170, 20, 20));

        jButtonLoop2Close5.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close5.setText("C");
        jButtonLoop2Close5.setToolTipText("");
        jButtonLoop2Close5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close5.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close5.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close5.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close5ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close5, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 170, 20, 20));

        jLabeljLabelCaptionRegenToCooler8.setFont(jLabeljLabelCaptionRegenToCooler8.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler8.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler8.setText("Feed 1.2");
        jLabeljLabelCaptionRegenToCooler8.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler8.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler8.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler8, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 114, 52, 14));

        jButtonLoop2Open6.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open6.setText("O");
        jButtonLoop2Open6.setToolTipText("");
        jButtonLoop2Open6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open6.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open6.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open6.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open6ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open6, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 128, 20, 20));

        jButtonLoop2Close6.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close6.setText("C");
        jButtonLoop2Close6.setToolTipText("");
        jButtonLoop2Close6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close6.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close6.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close6.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close6ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close6, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 128, 20, 20));

        panelWidgetPump11.setChornobylPrefix("Feedwater1#Pump1");
        add(panelWidgetPump11, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 86, -1, -1));

        panelWidgetPump12.setChornobylPrefix("Feedwater1#Pump2");
        add(panelWidgetPump12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 86, -1, -1));

        panelWidgetPump21.setChornobylPrefix("Feedwater2#Pump1");
        add(panelWidgetPump21, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 86, -1, -1));

        panelWidgetPump22.setChornobylPrefix("Feedwater2#Pump2");
        add(panelWidgetPump22, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 86, -1, -1));

        panelWidgetPump3.setChornobylPrefix("Feedwater#Pump3");
        add(panelWidgetPump3, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 86, -1, -1));

        jLabeljLabelCaptionRegenToCooler9.setFont(jLabeljLabelCaptionRegenToCooler9.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler9.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler9.setText("Loop 1");
        jLabeljLabelCaptionRegenToCooler9.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler9.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler9.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler9, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 296, 52, 14));

        jButtonLoop2Open7.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open7.setText("O");
        jButtonLoop2Open7.setToolTipText("");
        jButtonLoop2Open7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open7.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open7.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open7.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open7ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open7, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 310, 20, 20));

        jButtonLoop2Close7.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close7.setText("C");
        jButtonLoop2Close7.setToolTipText("");
        jButtonLoop2Close7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close7.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close7.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close7.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close7ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close7, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 310, 20, 20));

        jLabeljLabelCaptionRegenToCooler10.setFont(jLabeljLabelCaptionRegenToCooler10.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler10.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler10.setText("DA 1");
        jLabeljLabelCaptionRegenToCooler10.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler10.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler10.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler10, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 242, 52, 14));

        jButtonLoop2Open8.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open8.setText("O");
        jButtonLoop2Open8.setToolTipText("");
        jButtonLoop2Open8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open8.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open8.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open8.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open8ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open8, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 256, 20, 20));

        jButtonLoop2Close8.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close8.setText("C");
        jButtonLoop2Close8.setToolTipText("");
        jButtonLoop2Close8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close8.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close8.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close8.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close8ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close8, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 256, 20, 20));

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()-2f));
        jLabel8.setText("Drum 2");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 314, 44, 14));

        jLabelCaptionDrain.setFont(jLabelCaptionDrain.getFont().deriveFont(jLabelCaptionDrain.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain.getFont().getSize()-2));
        jLabelCaptionDrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain.setText("Pump 2.2");
        jLabelCaptionDrain.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 70, 64, 14));

        jLabelCaptionDrain1.setFont(jLabelCaptionDrain1.getFont().deriveFont(jLabelCaptionDrain1.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain1.getFont().getSize()-2));
        jLabelCaptionDrain1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain1.setText("Pump 1.1");
        jLabelCaptionDrain1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 70, 64, 14));

        jLabelCaptionDrain2.setFont(jLabelCaptionDrain2.getFont().deriveFont(jLabelCaptionDrain2.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain2.getFont().getSize()-2));
        jLabelCaptionDrain2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain2.setText("Pump 1.2");
        jLabelCaptionDrain2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 70, 64, 14));

        jLabelCaptionDrain3.setFont(jLabelCaptionDrain3.getFont().deriveFont(jLabelCaptionDrain3.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain3.getFont().getSize()-2));
        jLabelCaptionDrain3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain3.setText("Discharge Side");
        jLabelCaptionDrain3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 282, 102, 14));

        jLabelCaptionDrain4.setFont(jLabelCaptionDrain4.getFont().deriveFont(jLabelCaptionDrain4.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain4.getFont().getSize()-2));
        jLabelCaptionDrain4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain4.setText("Pump 2.1");
        jLabelCaptionDrain4.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain4.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain4.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain4, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 70, 64, 14));

        jLabeljLabelCaptionRegenToCooler11.setFont(jLabeljLabelCaptionRegenToCooler11.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler11.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler11.setText("Loop 2");
        jLabeljLabelCaptionRegenToCooler11.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler11.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler11.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler11, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 296, 52, 14));

        jButtonLoop2Open9.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open9.setText("O");
        jButtonLoop2Open9.setToolTipText("");
        jButtonLoop2Open9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open9.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open9.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open9.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open9ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open9, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 310, 20, 20));

        jButtonLoop2Close9.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close9.setText("C");
        jButtonLoop2Close9.setToolTipText("");
        jButtonLoop2Close9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close9.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close9.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close9.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close9ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close9, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 310, 20, 20));

        jLabeljLabelCaptionRegenToCooler12.setFont(jLabeljLabelCaptionRegenToCooler12.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler12.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler12.setText("DA 2");
        jLabeljLabelCaptionRegenToCooler12.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler12.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler12.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler12, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 242, 52, 14));

        jButtonLoop2Open10.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open10.setText("O");
        jButtonLoop2Open10.setToolTipText("");
        jButtonLoop2Open10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open10.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open10.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open10.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Open10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open10ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open10, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 256, 20, 20));

        jButtonLoop2Close10.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close10.setText("C");
        jButtonLoop2Close10.setToolTipText("");
        jButtonLoop2Close10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close10.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close10.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close10.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonLoop2Close10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close10ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close10, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 256, 20, 20));

        jLabelCaptionDrain5.setFont(jLabelCaptionDrain5.getFont().deriveFont(jLabelCaptionDrain5.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain5.getFont().getSize()-2));
        jLabelCaptionDrain5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain5.setText("Pump 3");
        jLabelCaptionDrain5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain5, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 70, 64, 14));

        jLabelCaptionDrain6.setFont(jLabelCaptionDrain6.getFont().deriveFont(jLabelCaptionDrain6.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain6.getFont().getSize()-2));
        jLabelCaptionDrain6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain6.setText("Drum Level Setpoint");
        jLabelCaptionDrain6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 266, 124, 14));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()-2f));
        jLabel5.setText("Feed 1");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 52, 14));

        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getSize()-2f));
        jLabel20.setText("Flow");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 52, 14));

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()-2f));
        jLabel7.setText("Feed 1");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 52, 14));

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getSize()-2f));
        jLabel19.setText("Temp");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 52, 14));

        chornobylGaugeLoop1Pressure.setChornobylMaximum(200.0F);
        chornobylGaugeLoop1Pressure.setChornobylMinimum(20.0F);
        chornobylGaugeLoop1Pressure.setChornobylTicks(new float[] {50.0f, 100.0f, 150.0f});
        chornobylGaugeLoop1Pressure.setChornobylUnitText("°C");
        add(chornobylGaugeLoop1Pressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 34, -1, -1));

        chornobylGaugeLoop1Level.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeLoop1Level.setChornobylMaximum(1800.0F);
        chornobylGaugeLoop1Level.setChornobylMinimum(0.0F);
        chornobylGaugeLoop1Level.setChornobylTicks(new float[] {0.0f, 500.0f, 1000.0f, 1600.0f});
        chornobylGaugeLoop1Level.setChornobylUnitText("kg/s");
        add(chornobylGaugeLoop1Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, -1, -1));

        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getSize()-2f));
        jLabel24.setText("Feed 2");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 4, 52, 14));

        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getSize()-2f));
        jLabel18.setText("Flow");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 16, 52, 14));

        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getSize()-2f));
        jLabel23.setText("Feed 2");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 34, 52, 14));

        jLabel17.setFont(jLabel17.getFont().deriveFont(jLabel17.getFont().getSize()-2f));
        jLabel17.setText("Temp");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 46, 52, 14));

        chornobylGaugeLoop2Pressure1.setChornobylMaximum(200.0F);
        chornobylGaugeLoop2Pressure1.setChornobylMinimum(20.0F);
        chornobylGaugeLoop2Pressure1.setChornobylTicks(new float[] {50.0f, 100.0f, 150.0f});
        chornobylGaugeLoop2Pressure1.setChornobylUnitText("°C");
        add(chornobylGaugeLoop2Pressure1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 34, -1, -1));

        chornobylGaugeLoop2Level1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeLoop2Level1.setChornobylMaximum(1800.0F);
        chornobylGaugeLoop2Level1.setChornobylMinimum(0.0F);
        chornobylGaugeLoop2Level1.setChornobylTicks(new float[] {0.0f, 500.0f, 1000.0f, 1600.0f});
        chornobylGaugeLoop2Level1.setChornobylUnitText("kg/s");
        add(chornobylGaugeLoop2Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 4, -1, -1));
        add(setpointControl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 284, -1, -1));
        add(setpointControl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getSize()-2f));
        jLabel9.setText("Drum 1");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 288, 44, 14));

        jLabelCaptionDrain7.setFont(jLabelCaptionDrain7.getFont().deriveFont(jLabelCaptionDrain7.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain7.getFont().getSize()-2));
        jLabelCaptionDrain7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain7.setText("Suction Side");
        jLabelCaptionDrain7.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain7.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain7.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain7, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 226, 102, 14));

        jLabelCaptionDrain8.setFont(jLabelCaptionDrain8.getFont().deriveFont(jLabelCaptionDrain8.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain8.getFont().getSize()-2));
        jLabelCaptionDrain8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain8.setText("Pump 3 System");
        jLabelCaptionDrain8.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain8.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain8.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 208, 102, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFeed23OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed23OpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed23OpenActionPerformed

    private void jButtonFeed23CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed23CloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed23CloseActionPerformed

    private void jButtonLoop2Open2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open2ActionPerformed

    private void jButtonLoop2Close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close2ActionPerformed

    private void jButtonLoop2Open3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open3ActionPerformed

    private void jButtonLoop2Close3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close3ActionPerformed

    private void jButtonLoop2Open4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open4ActionPerformed

    private void jButtonLoop2Close4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close4ActionPerformed

    private void jButtonLoop2Open5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open5ActionPerformed

    private void jButtonLoop2Close5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close5ActionPerformed

    private void jButtonLoop2Open6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open6ActionPerformed

    private void jButtonLoop2Close6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close6ActionPerformed

    private void jButtonLoop2Close10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close10ActionPerformed

    private void jButtonLoop2Open10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open10ActionPerformed

    private void jButtonLoop2Close9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close9ActionPerformed

    private void jButtonLoop2Open9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open9ActionPerformed

    private void jButtonLoop2Close8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close8ActionPerformed

    private void jButtonLoop2Open8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open8ActionPerformed

    private void jButtonLoop2Close7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close7ActionPerformed

    private void jButtonLoop2Open7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop1Level;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop1Pressure;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop2Level1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop2Pressure1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchStartupReduction1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchStartupReduction2;
    private javax.swing.JButton jButtonFeed23Close;
    private javax.swing.JButton jButtonFeed23Open;
    private javax.swing.JButton jButtonLoop2Close10;
    private javax.swing.JButton jButtonLoop2Close2;
    private javax.swing.JButton jButtonLoop2Close3;
    private javax.swing.JButton jButtonLoop2Close4;
    private javax.swing.JButton jButtonLoop2Close5;
    private javax.swing.JButton jButtonLoop2Close6;
    private javax.swing.JButton jButtonLoop2Close7;
    private javax.swing.JButton jButtonLoop2Close8;
    private javax.swing.JButton jButtonLoop2Close9;
    private javax.swing.JButton jButtonLoop2Open10;
    private javax.swing.JButton jButtonLoop2Open2;
    private javax.swing.JButton jButtonLoop2Open3;
    private javax.swing.JButton jButtonLoop2Open4;
    private javax.swing.JButton jButtonLoop2Open5;
    private javax.swing.JButton jButtonLoop2Open6;
    private javax.swing.JButton jButtonLoop2Open7;
    private javax.swing.JButton jButtonLoop2Open8;
    private javax.swing.JButton jButtonLoop2Open9;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCaptionDrain;
    private javax.swing.JLabel jLabelCaptionDrain1;
    private javax.swing.JLabel jLabelCaptionDrain2;
    private javax.swing.JLabel jLabelCaptionDrain3;
    private javax.swing.JLabel jLabelCaptionDrain4;
    private javax.swing.JLabel jLabelCaptionDrain5;
    private javax.swing.JLabel jLabelCaptionDrain6;
    private javax.swing.JLabel jLabelCaptionDrain7;
    private javax.swing.JLabel jLabelCaptionDrain8;
    private javax.swing.JLabel jLabelCaptionFeed22;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler10;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler11;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler12;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler4;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler5;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler6;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler7;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler8;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler9;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve11;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve12;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve1s;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve21;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve22;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve2s;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump11;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump12;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump21;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump22;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump3;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControl1;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControl2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        panelWidgetPump11.updateComponent(evt);
        panelWidgetPump12.updateComponent(evt);
        panelWidgetPump21.updateComponent(evt);
        panelWidgetPump22.updateComponent(evt);
        panelWidgetPump3.updateComponent(evt);
        panelWidgetControlLoopValve11.updateComponent(evt);
        panelWidgetControlLoopValve12.updateComponent(evt);
        panelWidgetControlLoopValve1s.updateComponent(evt);
        panelWidgetControlLoopValve21.updateComponent(evt);
        panelWidgetControlLoopValve22.updateComponent(evt);
        panelWidgetControlLoopValve2s.updateComponent(evt);
        
        integralSwitchStartupReduction1.updateComponent(evt);
        integralSwitchStartupReduction2.updateComponent(evt);
        
        switch (evt.getPropertyName()) {
            case "Feedwater1#ShutoffValve1_Pos":
                setValveButtons(jButtonLoop2Close3, 
                        jButtonLoop2Open3, evt.getNewValue());
                break;
            case "Feedwater2#ShutoffValve1_Pos":
                setValveButtons(jButtonLoop2Close4, 
                        jButtonLoop2Open4, evt.getNewValue());
                break;
            case "Feedwater1#ShutoffValve2_Pos":
                setValveButtons(jButtonLoop2Close2, 
                        jButtonLoop2Open2, evt.getNewValue());
                break;
            case "Feedwater2#ShutoffValve2_Pos":
                setValveButtons(jButtonLoop2Close5, 
                        jButtonLoop2Open5, evt.getNewValue());
                break;
            case "Feedwater1#ShutoffValve3_Pos":
                setValveButtons(jButtonLoop2Close6, 
                        jButtonLoop2Open6, evt.getNewValue());
                break;
            case "Feedwater2#ShutoffValve3_Pos":
                setValveButtons(jButtonFeed23Close, 
                        jButtonFeed23Open, evt.getNewValue());
                break;
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        panelWidgetControlLoopValve11.updateComponent(propertyName, newValue);
        panelWidgetControlLoopValve12.updateComponent(propertyName, newValue);
        panelWidgetControlLoopValve1s.updateComponent(propertyName, newValue);
        panelWidgetControlLoopValve21.updateComponent(propertyName, newValue);
        panelWidgetControlLoopValve22.updateComponent(propertyName, newValue);
        panelWidgetControlLoopValve2s.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
