/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelTurbine extends AbstractPanelWidget
        implements UpdateReceiver {

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);
        controlLoopStartupValve1.registerActionReceiver(controller);
        controlLoopStartupValve2.registerActionReceiver(controller);
        controlLoopValveReheater1.registerActionReceiver(controller);
        controlLoopValveReheater2.registerActionReceiver(controller);
        controlLoopValveSteamIn.registerActionReceiver(controller);
        setpointControlTemperature.registerActionReceiver(controller);
        controlLoopValve3.registerActionReceiver(controller);
        controlLoopValve4.registerActionReceiver(controller);
        controlLoopValveCondToHotwell.registerActionReceiver(controller);
        controlLoopValveCondToDA1.registerActionReceiver(controller);
        controlLoopValveCondToDA2.registerActionReceiver(controller);
    }

    /**
     * Creates new form PanelTurbine
     */
    public PanelTurbine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTrip1Close = new javax.swing.JButton();
        jButtonTrip1Open = new javax.swing.JButton();
        jLabelCaptionLPShut1 = new javax.swing.JLabel();
        jLabelCaptionLPShut2 = new javax.swing.JLabel();
        jButtonLPShutClose = new javax.swing.JButton();
        jButtenLPShutOpen = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        setpointControlTemperature = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        jLabelTempSetpoint = new javax.swing.JLabel();
        controlLoopValveSteamIn = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        jLabelCaptionsuperheaterCond2 = new javax.swing.JLabel();
        jLabelCaptionsuperheaterCond1 = new javax.swing.JLabel();
        controlLoopValveCondToDA1 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopValveCondToDA2 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        jLabelCaptionsuperheaterCond3 = new javax.swing.JLabel();
        jLabelCaptionsuperheaterCond4 = new javax.swing.JLabel();
        setpointControlTemperature1 = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        jLabelTempSetpoint1 = new javax.swing.JLabel();
        controlLoopValveCondToHotwell = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        jLabelCaptionsuperheaterCond5 = new javax.swing.JLabel();
        jLabelCaptionsuperheaterCond6 = new javax.swing.JLabel();
        jLabelCaption1 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl1 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl2 = new javax.swing.JLabel();
        jButtonProtectionRest = new javax.swing.JButton();
        jButtonProtectionTrip = new javax.swing.JButton();
        lightBulbSpeed6 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jLabelCaption2 = new javax.swing.JLabel();
        jLabelCaption3 = new javax.swing.JLabel();
        controlLoopStartupValve1 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopStartupValve2 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopValve3 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopValve4 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chornobylGaugeFeed1Temp = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeFeed1Flow = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeFeed2Flow = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeFeed2Flow1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        chornobylGaugeFeed1Temp1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp2 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp3 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabelCaption4 = new javax.swing.JLabel();
        jLabelCaption5 = new javax.swing.JLabel();
        jLabelCaption6 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl4 = new javax.swing.JLabel();
        jLabelCaption7 = new javax.swing.JLabel();
        jToggleButtonAutoDrain1 = new javax.swing.JToggleButton();
        jLabelCaptionLPShut3 = new javax.swing.JLabel();
        jLabelCaptionLPShut4 = new javax.swing.JLabel();
        jButtonDrainsClose = new javax.swing.JButton();
        jButtenDrainsOpen = new javax.swing.JButton();
        jButtonTrip2Close = new javax.swing.JButton();
        jButtonTrip2Open = new javax.swing.JButton();
        controlLoopValveReheater1 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopValveReheater2 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        jLabelCaption8 = new javax.swing.JLabel();
        jLabelCaptionLPShut7 = new javax.swing.JLabel();
        jLabelCaptionLPShut8 = new javax.swing.JLabel();
        jLabelCaptionLPShut9 = new javax.swing.JLabel();
        jLabelCaptionLPShut10 = new javax.swing.JLabel();
        jToggleButtonAutoDrain2 = new javax.swing.JToggleButton();
        jLabelCaption9 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl7 = new javax.swing.JLabel();
        jLabelCaption10 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl8 = new javax.swing.JLabel();
        jButtonSuperheaterShutoffClose = new javax.swing.JButton();
        jButtonSuperheaterShutoffOpen = new javax.swing.JButton();
        jLabelCaptionSuperheaterControl5 = new javax.swing.JLabel();
        jLabelCaptionLPShut5 = new javax.swing.JLabel();
        jLabelCaptionLPShut6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(574, 340));
        setPreferredSize(new java.awt.Dimension(574, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTrip1Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonTrip1Close.setText("C");
        jButtonTrip1Close.setToolTipText("");
        jButtonTrip1Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTrip1Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrip1CloseActionPerformed(evt);
            }
        });
        add(jButtonTrip1Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 20, 20));

        jButtonTrip1Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonTrip1Open.setText("O");
        jButtonTrip1Open.setToolTipText("");
        jButtonTrip1Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTrip1Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrip1OpenActionPerformed(evt);
            }
        });
        add(jButtonTrip1Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 130, 20, 20));

        jLabelCaptionLPShut1.setFont(jLabelCaptionLPShut1.getFont().deriveFont(jLabelCaptionLPShut1.getFont().getSize()-2f));
        jLabelCaptionLPShut1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut1.setText("LP Trip");
        jLabelCaptionLPShut1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 282, 51, 14));

        jLabelCaptionLPShut2.setFont(jLabelCaptionLPShut2.getFont().deriveFont(jLabelCaptionLPShut2.getFont().getSize()-2f));
        jLabelCaptionLPShut2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut2.setText("Valve");
        jLabelCaptionLPShut2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 294, 51, 14));

        jButtonLPShutClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLPShutClose.setText("C");
        jButtonLPShutClose.setToolTipText("");
        jButtonLPShutClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLPShutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLPShutCloseActionPerformed(evt);
            }
        });
        add(jButtonLPShutClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 308, 20, 20));

        jButtenLPShutOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtenLPShutOpen.setText("O");
        jButtenLPShutOpen.setToolTipText("");
        jButtenLPShutOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtenLPShutOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtenLPShutOpenActionPerformed(evt);
            }
        });
        add(jButtenLPShutOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 308, 20, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(setpointControlTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 24, -1, -1));

        jLabelTempSetpoint.setFont(jLabelTempSetpoint.getFont().deriveFont(jLabelTempSetpoint.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelTempSetpoint.getFont().getSize()-2));
        jLabelTempSetpoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTempSetpoint.setText("Temperature");
        jLabelTempSetpoint.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelTempSetpoint.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelTempSetpoint.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelTempSetpoint.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel2.add(jLabelTempSetpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 88, -1));

        controlLoopValveSteamIn.setComponent("Turbine#ReheaterPriControlValve");
        jPanel2.add(controlLoopValveSteamIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabelCaptionsuperheaterCond2.setFont(jLabelCaptionsuperheaterCond2.getFont().deriveFont(jLabelCaptionsuperheaterCond2.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond2.setText("DA 1");
        jPanel2.add(jLabelCaptionsuperheaterCond2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 28, 50, 14));

        jLabelCaptionsuperheaterCond1.setFont(jLabelCaptionsuperheaterCond1.getFont().deriveFont(jLabelCaptionsuperheaterCond1.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond1.setText("Cond.");
        jPanel2.add(jLabelCaptionsuperheaterCond1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 14, 50, 14));

        controlLoopValveCondToDA1.setComponent("Turbine1#ReheaterCondensateValve");
        jPanel2.add(controlLoopValveCondToDA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 10, -1, -1));

        controlLoopValveCondToDA2.setComponent("Turbine2#ReheaterCondensateValve");
        jPanel2.add(controlLoopValveCondToDA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 50, -1, -1));

        jLabelCaptionsuperheaterCond3.setFont(jLabelCaptionsuperheaterCond3.getFont().deriveFont(jLabelCaptionsuperheaterCond3.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond3.setText("Cond.");
        jPanel2.add(jLabelCaptionsuperheaterCond3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 54, 50, 14));

        jLabelCaptionsuperheaterCond4.setFont(jLabelCaptionsuperheaterCond4.getFont().deriveFont(jLabelCaptionsuperheaterCond4.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond4.setText("DA 2");
        jPanel2.add(jLabelCaptionsuperheaterCond4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 68, 50, 14));
        jPanel2.add(setpointControlTemperature1, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 14, -1, -1));

        jLabelTempSetpoint1.setFont(jLabelTempSetpoint1.getFont().deriveFont(jLabelTempSetpoint1.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelTempSetpoint1.getFont().getSize()-2));
        jLabelTempSetpoint1.setText("Level");
        jLabelTempSetpoint1.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelTempSetpoint1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelTempSetpoint1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelTempSetpoint1.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel2.add(jLabelTempSetpoint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 18, 36, -1));

        controlLoopValveCondToHotwell.setComponent("Turbine#ReheaterCondensateDrain");
        jPanel2.add(controlLoopValveCondToHotwell, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 50, -1, -1));

        jLabelCaptionsuperheaterCond5.setFont(jLabelCaptionsuperheaterCond5.getFont().deriveFont(jLabelCaptionsuperheaterCond5.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond5.setText("Cond.");
        jPanel2.add(jLabelCaptionsuperheaterCond5, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 54, 50, 14));

        jLabelCaptionsuperheaterCond6.setFont(jLabelCaptionsuperheaterCond6.getFont().deriveFont(jLabelCaptionsuperheaterCond6.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond6.setText("Drain");
        jPanel2.add(jLabelCaptionsuperheaterCond6, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 68, 50, 14));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 238, 396, 96));

        jLabelCaption1.setFont(jLabelCaption1.getFont().deriveFont(jLabelCaption1.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption1.getFont().getSize()-2));
        jLabelCaption1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption1.setText("Reheater");
        jLabelCaption1.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 118, 90, 14));

        jLabelCaptionSuperheaterControl1.setFont(jLabelCaptionSuperheaterControl1.getFont().deriveFont(jLabelCaptionSuperheaterControl1.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl1.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl1.setText("High Pressure Steam Valve Controls");
        jLabelCaptionSuperheaterControl1.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 102, 244, 14));

        jLabelCaptionSuperheaterControl2.setFont(jLabelCaptionSuperheaterControl2.getFont().deriveFont(jLabelCaptionSuperheaterControl2.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl2.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl2.setText("Selection");
        jLabelCaptionSuperheaterControl2.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 124, 56, 14));

        jButtonProtectionRest.setFont(jButtonProtectionRest.getFont().deriveFont(jButtonProtectionRest.getFont().getSize()-2f));
        jButtonProtectionRest.setText("●");
        jButtonProtectionRest.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonProtectionRest.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonProtectionRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProtectionRestActionPerformed(evt);
            }
        });
        add(jButtonProtectionRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 148, 20, 20));

        jButtonProtectionTrip.setFont(jButtonProtectionTrip.getFont().deriveFont(jButtonProtectionTrip.getFont().getSize()-2f));
        jButtonProtectionTrip.setText("●");
        jButtonProtectionTrip.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonProtectionTrip.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonProtectionTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProtectionTripActionPerformed(evt);
            }
        });
        add(jButtonProtectionTrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 148, 20, 20));

        lightBulbSpeed6.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbSpeed6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 154, -1, -1));

        jLabelCaption2.setFont(jLabelCaption2.getFont().deriveFont(jLabelCaption2.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption2.getFont().getSize()-2));
        jLabelCaption2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption2.setText("Reset");
        jLabelCaption2.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 132, 32, 14));

        jLabelCaption3.setFont(jLabelCaption3.getFont().deriveFont(jLabelCaption3.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption3.getFont().getSize()-2));
        jLabelCaption3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption3.setText("Trip");
        jLabelCaption3.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 132, 32, 14));

        controlLoopStartupValve1.setComponent("Turbine1#StartupSteamValve");
        add(controlLoopStartupValve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 134, -1, -1));

        controlLoopStartupValve2.setComponent("Turbine2#StartupSteamValve");
        add(controlLoopStartupValve2, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 176, -1, -1));

        controlLoopValve3.setComponent("Turbine1#MainSteamValve");
        add(controlLoopValve3, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 134, -1, -1));

        controlLoopValve4.setComponent("Turbine2#MainSteamValve");
        add(controlLoopValve4, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 176, -1, -1));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()-2f));
        jLabel5.setText("Turbine");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 52, 14));

        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getSize()-2f));
        jLabel20.setText("Speed");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 52, 14));

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()-2f));
        jLabel7.setText("HP");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 52, 14));

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getSize()-2f));
        jLabel19.setText("Flow");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 52, 14));

        chornobylGaugeFeed1Temp.setChornobylMaximum(200.0F);
        chornobylGaugeFeed1Temp.setChornobylMinimum(20.0F);
        chornobylGaugeFeed1Temp.setChornobylTicks(new float[] {50.0f, 100.0f, 150.0f});
        chornobylGaugeFeed1Temp.setChornobylUnitText("°C");
        add(chornobylGaugeFeed1Temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 34, -1, -1));

        chornobylGaugeFeed1Flow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeFeed1Flow.setChornobylMaximum(3200.0F);
        chornobylGaugeFeed1Flow.setChornobylMinimum(0.0F);
        chornobylGaugeFeed1Flow.setChornobylTicks(new float[] {500.0f, 1500.0f, 3000.0f});
        chornobylGaugeFeed1Flow.setChornobylUnitText("1/min");
        add(chornobylGaugeFeed1Flow, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, -1, -1));

        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getSize()-2f));
        jLabel24.setText("HP Case");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 4, 52, 14));

        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getSize()-2f));
        jLabel18.setText("Temp");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 16, 52, 14));

        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getSize()-2f));
        jLabel23.setText("HP Rotor");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 34, 52, 14));

        jLabel17.setFont(jLabel17.getFont().deriveFont(jLabel17.getFont().getSize()-2f));
        jLabel17.setText("Temp");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 46, 52, 14));

        chornobylGaugeFeed2Temp.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Temp.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Temp.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Temp.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 34, -1, -1));

        chornobylGaugeFeed2Flow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeFeed2Flow.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Flow.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Flow.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Flow.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Flow, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 4, -1, -1));

        jLabel25.setFont(jLabel25.getFont().deriveFont(jLabel25.getFont().getSize()-2f));
        jLabel25.setText("LP Case");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 4, 52, 14));

        jLabel21.setFont(jLabel21.getFont().deriveFont(jLabel21.getFont().getSize()-2f));
        jLabel21.setText("Temp");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 16, 52, 14));

        jLabel26.setFont(jLabel26.getFont().deriveFont(jLabel26.getFont().getSize()-2f));
        jLabel26.setText("LP Rotor");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 34, 52, 14));

        jLabel22.setFont(jLabel22.getFont().deriveFont(jLabel22.getFont().getSize()-2f));
        jLabel22.setText("Temp");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 46, 52, 14));

        chornobylGaugeFeed2Temp1.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Temp1.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Temp1.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Temp1.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Temp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 34, -1, -1));

        chornobylGaugeFeed2Flow1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeFeed2Flow1.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Flow1.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Flow1.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Flow1.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Flow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 4, -1, -1));

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()-2f));
        jLabel8.setText("Total");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 52, 14));

        jLabel27.setFont(jLabel27.getFont().deriveFont(jLabel27.getFont().getSize()-2f));
        jLabel27.setText("Expans.");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 52, 14));

        chornobylGaugeFeed1Temp1.setChornobylMaximum(50.0F);
        chornobylGaugeFeed1Temp1.setChornobylMinimum(0.0F);
        chornobylGaugeFeed1Temp1.setChornobylTicks(new float[] {0.0f, 10.0f, 20.0f, 30.0f, 40.0f});
        chornobylGaugeFeed1Temp1.setChornobylUnitText("mm");
        chornobylGaugeFeed1Temp1.setChornobylValue(0.0F);
        add(chornobylGaugeFeed1Temp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 64, -1, -1));

        jLabel28.setFont(jLabel28.getFont().deriveFont(jLabel28.getFont().getSize()-2f));
        jLabel28.setText("HP Diff");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 64, 52, 14));

        jLabel29.setFont(jLabel29.getFont().deriveFont(jLabel29.getFont().getSize()-2f));
        jLabel29.setText("Expans.");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 76, 52, 14));

        chornobylGaugeFeed2Temp2.setChornobylMaximum(4.0F);
        chornobylGaugeFeed2Temp2.setChornobylMinimum(-2.0F);
        chornobylGaugeFeed2Temp2.setChornobylTicks(new float[] {-1.0f, 0.0f, 1.0f, 2.0f});
        chornobylGaugeFeed2Temp2.setChornobylUnitText("mm");
        chornobylGaugeFeed2Temp2.setChornobylValue(0.0F);
        add(chornobylGaugeFeed2Temp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 64, -1, -1));

        jLabel30.setFont(jLabel30.getFont().deriveFont(jLabel30.getFont().getSize()-2f));
        jLabel30.setText("LP Diff");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 64, 52, 14));

        jLabel31.setFont(jLabel31.getFont().deriveFont(jLabel31.getFont().getSize()-2f));
        jLabel31.setText("Expans.");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 76, 52, 14));

        chornobylGaugeFeed2Temp3.setChornobylMaximum(6.0F);
        chornobylGaugeFeed2Temp3.setChornobylMinimum(-3.0F);
        chornobylGaugeFeed2Temp3.setChornobylTicks(new float[] {-2.5f, 0.0f, 2.5f, 5.0f});
        chornobylGaugeFeed2Temp3.setChornobylUnitText("mm");
        chornobylGaugeFeed2Temp3.setChornobylValue(0.0F);
        add(chornobylGaugeFeed2Temp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 64, -1, -1));

        jLabelCaption4.setFont(jLabelCaption4.getFont().deriveFont(jLabelCaption4.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption4.getFont().getSize()-2));
        jLabelCaption4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption4.setText("2");
        jLabelCaption4.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption4.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption4.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption4.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption4, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 188, 10, 14));

        jLabelCaption5.setFont(jLabelCaption5.getFont().deriveFont(jLabelCaption5.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption5.getFont().getSize()-2));
        jLabelCaption5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption5.setText("Startup Valves");
        jLabelCaption5.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption5, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 118, 86, 14));

        jLabelCaption6.setFont(jLabelCaption6.getFont().deriveFont(jLabelCaption6.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption6.getFont().getSize()-2));
        jLabelCaption6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption6.setText("Speed");
        jLabelCaption6.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption6, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 184, 54, 14));

        jLabelCaptionSuperheaterControl4.setFont(jLabelCaptionSuperheaterControl4.getFont().deriveFont(jLabelCaptionSuperheaterControl4.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl4.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl4.setText("Turbine");
        jLabelCaptionSuperheaterControl4.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl4.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl4.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl4.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 104, 56, 14));

        jLabelCaption7.setFont(jLabelCaption7.getFont().deriveFont(jLabelCaption7.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption7.getFont().getSize()-2));
        jLabelCaption7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption7.setText("1");
        jLabelCaption7.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption7.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption7.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption7.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption7, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 142, 10, 14));

        jToggleButtonAutoDrain1.setText("←");
        jToggleButtonAutoDrain1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonAutoDrain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAutoDrain1ActionPerformed(evt);
            }
        });
        add(jToggleButtonAutoDrain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 158, 20, 20));

        jLabelCaptionLPShut3.setFont(jLabelCaptionLPShut3.getFont().deriveFont(jLabelCaptionLPShut3.getFont().getSize()-2f));
        jLabelCaptionLPShut3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut3.setText("Steam");
        jLabelCaptionLPShut3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 226, 51, 14));

        jLabelCaptionLPShut4.setFont(jLabelCaptionLPShut4.getFont().deriveFont(jLabelCaptionLPShut4.getFont().getSize()-2f));
        jLabelCaptionLPShut4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut4.setText("Drains");
        jLabelCaptionLPShut4.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut4.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut4.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 238, 51, 14));

        jButtonDrainsClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonDrainsClose.setText("C");
        jButtonDrainsClose.setToolTipText("");
        jButtonDrainsClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDrainsClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrainsCloseActionPerformed(evt);
            }
        });
        add(jButtonDrainsClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 252, 20, 20));

        jButtenDrainsOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtenDrainsOpen.setText("O");
        jButtenDrainsOpen.setToolTipText("");
        jButtenDrainsOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtenDrainsOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtenDrainsOpenActionPerformed(evt);
            }
        });
        add(jButtenDrainsOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 252, 20, 20));

        jButtonTrip2Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonTrip2Close.setText("C");
        jButtonTrip2Close.setToolTipText("");
        jButtonTrip2Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTrip2Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrip2CloseActionPerformed(evt);
            }
        });
        add(jButtonTrip2Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 186, 20, 20));

        jButtonTrip2Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonTrip2Open.setText("O");
        jButtonTrip2Open.setToolTipText("");
        jButtonTrip2Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTrip2Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrip2OpenActionPerformed(evt);
            }
        });
        add(jButtonTrip2Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 186, 20, 20));

        controlLoopValveReheater1.setComponent("Turbine1#ReheaterSteamValve");
        add(controlLoopValveReheater1, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 134, -1, -1));

        controlLoopValveReheater2.setComponent("Turbine2#ReheaterSteamValve");
        add(controlLoopValveReheater2, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 176, -1, -1));

        jLabelCaption8.setFont(jLabelCaption8.getFont().deriveFont(jLabelCaption8.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption8.getFont().getSize()-2));
        jLabelCaption8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption8.setText("Main Valves");
        jLabelCaption8.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption8.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption8.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption8.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption8, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 118, 90, 14));

        jLabelCaptionLPShut7.setFont(jLabelCaptionLPShut7.getFont().deriveFont(jLabelCaptionLPShut7.getFont().getSize()-2f));
        jLabelCaptionLPShut7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut7.setText("Loop 1");
        jLabelCaptionLPShut7.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut7.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut7.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut7, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 104, 51, 14));

        jLabelCaptionLPShut8.setFont(jLabelCaptionLPShut8.getFont().deriveFont(jLabelCaptionLPShut8.getFont().getSize()-2f));
        jLabelCaptionLPShut8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut8.setText("Trp Vlv");
        jLabelCaptionLPShut8.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut8.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut8.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut8, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 116, 51, 14));

        jLabelCaptionLPShut9.setFont(jLabelCaptionLPShut9.getFont().deriveFont(jLabelCaptionLPShut9.getFont().getSize()-2f));
        jLabelCaptionLPShut9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut9.setText("Trp Vlv");
        jLabelCaptionLPShut9.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut9.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut9.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut9, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 170, 51, 14));

        jLabelCaptionLPShut10.setFont(jLabelCaptionLPShut10.getFont().deriveFont(jLabelCaptionLPShut10.getFont().getSize()-2f));
        jLabelCaptionLPShut10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut10.setText("Loop 2");
        jLabelCaptionLPShut10.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut10.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut10.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut10, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 158, 51, 14));

        jToggleButtonAutoDrain2.setText("←");
        jToggleButtonAutoDrain2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonAutoDrain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAutoDrain2ActionPerformed(evt);
            }
        });
        add(jToggleButtonAutoDrain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 178, 20, 20));

        jLabelCaption9.setFont(jLabelCaption9.getFont().deriveFont(jLabelCaption9.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption9.getFont().getSize()-2));
        jLabelCaption9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption9.setText("Override");
        jLabelCaption9.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption9.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption9.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption9.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 54, 14));

        jLabelCaptionSuperheaterControl7.setFont(jLabelCaptionSuperheaterControl7.getFont().deriveFont(jLabelCaptionSuperheaterControl7.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl7.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl7.setText("Protection");
        jLabelCaptionSuperheaterControl7.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl7.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl7.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl7.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, 72, 14));

        jLabelCaption10.setFont(jLabelCaption10.getFont().deriveFont(jLabelCaption10.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption10.getFont().getSize()-2));
        jLabelCaption10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption10.setText("Pressure");
        jLabelCaption10.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption10.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption10.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption10.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption10, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 140, 54, 14));

        jLabelCaptionSuperheaterControl8.setFont(jLabelCaptionSuperheaterControl8.getFont().deriveFont(jLabelCaptionSuperheaterControl8.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl8.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl8.setText("Setpoint");
        jLabelCaptionSuperheaterControl8.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl8.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl8.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl8.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 110, 56, 14));

        jButtonSuperheaterShutoffClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonSuperheaterShutoffClose.setText("C");
        jButtonSuperheaterShutoffClose.setToolTipText("");
        jButtonSuperheaterShutoffClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSuperheaterShutoffClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuperheaterShutoffCloseActionPerformed(evt);
            }
        });
        add(jButtonSuperheaterShutoffClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 308, 20, 20));

        jButtonSuperheaterShutoffOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonSuperheaterShutoffOpen.setText("O");
        jButtonSuperheaterShutoffOpen.setToolTipText("");
        jButtonSuperheaterShutoffOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSuperheaterShutoffOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuperheaterShutoffOpenActionPerformed(evt);
            }
        });
        add(jButtonSuperheaterShutoffOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 308, 20, 20));

        jLabelCaptionSuperheaterControl5.setFont(jLabelCaptionSuperheaterControl5.getFont().deriveFont(jLabelCaptionSuperheaterControl5.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl5.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl5.setText("Reheater Temperature and Condensate Control");
        jLabelCaptionSuperheaterControl5.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 222, 394, 14));

        jLabelCaptionLPShut5.setFont(jLabelCaptionLPShut5.getFont().deriveFont(jLabelCaptionLPShut5.getFont().getSize()-2f));
        jLabelCaptionLPShut5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut5.setText("Reheater");
        jLabelCaptionLPShut5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 282, 51, 14));

        jLabelCaptionLPShut6.setFont(jLabelCaptionLPShut6.getFont().deriveFont(jLabelCaptionLPShut6.getFont().getSize()-2f));
        jLabelCaptionLPShut6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut6.setText("Valve");
        jLabelCaptionLPShut6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 294, 51, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTrip1CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrip1CloseActionPerformed
        controller.userAction(new ActionCommand("Turbine1#TripValve", false));
    }//GEN-LAST:event_jButtonTrip1CloseActionPerformed

    private void jButtonTrip1OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrip1OpenActionPerformed
        controller.userAction(new ActionCommand("Turbine1#TripValve", true));
    }//GEN-LAST:event_jButtonTrip1OpenActionPerformed

    private void jButtonLPShutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLPShutCloseActionPerformed
        controller.userAction(new ActionCommand("Turbine#LowPressureTripValve", false));
    }//GEN-LAST:event_jButtonLPShutCloseActionPerformed

    private void jButtenLPShutOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtenLPShutOpenActionPerformed
        controller.userAction(new ActionCommand("Turbine#LowPressureTripValve", true));
    }//GEN-LAST:event_jButtenLPShutOpenActionPerformed

    private void jButtonSuperheaterShutoffCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuperheaterShutoffCloseActionPerformed
        controller.userAction(new ActionCommand("Turbine#ReheaterTripValve", false));
    }//GEN-LAST:event_jButtonSuperheaterShutoffCloseActionPerformed

    private void jButtonSuperheaterShutoffOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuperheaterShutoffOpenActionPerformed
        controller.userAction(new ActionCommand("Turbine#ReheaterTripValve", true));
    }//GEN-LAST:event_jButtonSuperheaterShutoffOpenActionPerformed

    private void jButtonProtectionRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProtectionRestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProtectionRestActionPerformed

    private void jButtonProtectionTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProtectionTripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProtectionTripActionPerformed

    private void jToggleButtonAutoDrain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAutoDrain1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonAutoDrain1ActionPerformed

    private void jButtonDrainsCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrainsCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDrainsCloseActionPerformed

    private void jButtenDrainsOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtenDrainsOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtenDrainsOpenActionPerformed

    private void jButtonTrip2CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrip2CloseActionPerformed
        controller.userAction(new ActionCommand("Turbine2#TripValve", false));
    }//GEN-LAST:event_jButtonTrip2CloseActionPerformed

    private void jButtonTrip2OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrip2OpenActionPerformed
        controller.userAction(new ActionCommand("Turbine2#TripValve", true));
    }//GEN-LAST:event_jButtonTrip2OpenActionPerformed

    private void jToggleButtonAutoDrain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAutoDrain2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonAutoDrain2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed1Flow;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed1Temp;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed1Temp1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Flow;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Flow1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp2;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp3;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopStartupValve1;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopStartupValve2;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValve3;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValve4;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveCondToDA1;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveCondToDA2;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveCondToHotwell;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveReheater1;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveReheater2;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveSteamIn;
    private javax.swing.JButton jButtenDrainsOpen;
    private javax.swing.JButton jButtenLPShutOpen;
    private javax.swing.JButton jButtonDrainsClose;
    private javax.swing.JButton jButtonLPShutClose;
    private javax.swing.JButton jButtonProtectionRest;
    private javax.swing.JButton jButtonProtectionTrip;
    private javax.swing.JButton jButtonSuperheaterShutoffClose;
    private javax.swing.JButton jButtonSuperheaterShutoffOpen;
    private javax.swing.JButton jButtonTrip1Close;
    private javax.swing.JButton jButtonTrip1Open;
    private javax.swing.JButton jButtonTrip2Close;
    private javax.swing.JButton jButtonTrip2Open;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCaption1;
    private javax.swing.JLabel jLabelCaption10;
    private javax.swing.JLabel jLabelCaption2;
    private javax.swing.JLabel jLabelCaption3;
    private javax.swing.JLabel jLabelCaption4;
    private javax.swing.JLabel jLabelCaption5;
    private javax.swing.JLabel jLabelCaption6;
    private javax.swing.JLabel jLabelCaption7;
    private javax.swing.JLabel jLabelCaption8;
    private javax.swing.JLabel jLabelCaption9;
    private javax.swing.JLabel jLabelCaptionLPShut1;
    private javax.swing.JLabel jLabelCaptionLPShut10;
    private javax.swing.JLabel jLabelCaptionLPShut2;
    private javax.swing.JLabel jLabelCaptionLPShut3;
    private javax.swing.JLabel jLabelCaptionLPShut4;
    private javax.swing.JLabel jLabelCaptionLPShut5;
    private javax.swing.JLabel jLabelCaptionLPShut6;
    private javax.swing.JLabel jLabelCaptionLPShut7;
    private javax.swing.JLabel jLabelCaptionLPShut8;
    private javax.swing.JLabel jLabelCaptionLPShut9;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl1;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl2;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl4;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl5;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl7;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl8;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond1;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond2;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond3;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond4;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond5;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond6;
    private javax.swing.JLabel jLabelTempSetpoint;
    private javax.swing.JLabel jLabelTempSetpoint1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButtonAutoDrain1;
    private javax.swing.JToggleButton jToggleButtonAutoDrain2;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbSpeed6;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControlTemperature;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControlTemperature1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        controlLoopStartupValve1.updateComponent(evt);
        controlLoopStartupValve2.updateComponent(evt);
        controlLoopValveReheater1.updateComponent(evt);
        controlLoopValveReheater2.updateComponent(evt);
        controlLoopValve3.updateComponent(evt);
        controlLoopValve4.updateComponent(evt);
        controlLoopValveSteamIn.updateComponent(evt);
        setpointControlTemperature.updateComponent(evt);
        controlLoopValveCondToHotwell.updateComponent(evt);
        controlLoopValveCondToDA1.updateComponent(evt);
        controlLoopValveCondToDA2.updateComponent(evt);
        switch (evt.getPropertyName()) {
            case "Turbine#ReheaterTripValve_Pos":
                setValveButtons(jButtonSuperheaterShutoffClose,
                        jButtonSuperheaterShutoffOpen, evt.getNewValue());
                break;
            case "Turbine1#TripValve_Pos":
                setValveButtons(jButtonTrip1Close,
                        jButtonTrip1Open, evt.getNewValue());
                break;
            case "Turbine2#TripValve_Pos":
                setValveButtons(jButtonTrip2Close,
                        jButtonTrip2Open, evt.getNewValue());
                break;
            case "Turbine#LowPressureTripValve_Pos":
                setValveButtons(jButtonLPShutClose,
                        jButtenLPShutOpen, evt.getNewValue());
                break;
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        controlLoopStartupValve1.updateComponent(propertyName, newValue);
        controlLoopStartupValve2.updateComponent(propertyName, newValue);
        controlLoopValveReheater1.updateComponent(propertyName, newValue);
        controlLoopValveReheater2.updateComponent(propertyName, newValue);
        controlLoopValve3.updateComponent(propertyName, newValue);
        controlLoopValve4.updateComponent(propertyName, newValue);
        controlLoopValveSteamIn.updateComponent(propertyName, newValue);
        setpointControlTemperature.updateComponent(propertyName, newValue);
        controlLoopValveCondToDA1.updateComponent(propertyName, newValue);
        controlLoopValveCondToDA2.updateComponent(propertyName, newValue);
        controlLoopValveCondToHotwell.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
