/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author viktor
 */
public class PanelCoolant extends AbstractPanelWidget {

    /**
     * Creates new form PanelCoolant
     */
    public PanelCoolant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(200, 130));
        setPreferredSize(new java.awt.Dimension(200, 130));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
 
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
  
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {

    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
 
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
