/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;
import com.hartrusion.control.ControlCommand;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelBlowdown extends AbstractPanelWidget {

    ActionReceiver controller;

    /**
     * Creates new form PanelBlowdown
     */
    public PanelBlowdown() {
        initComponents();
    }

    public void registerActionReceiver(ActionReceiver controller) {
        this.controller = controller;

        panelWidgetPump1.registerActionReceiver(controller);
        panelWidgetPump2.registerActionReceiver(controller);
        integralSwitchBlowdownLoop1.registerActionReceiver(controller);
        integralSwitchBlowdownLoop2.registerActionReceiver(controller);
        integralSwitchDrain.registerActionReceiver(controller);
        integralSwitchReturn1.registerActionReceiver(controller);
        integralSwitchReturn2.registerActionReceiver(controller);
        integralSwitchCoolant.registerActionReceiver(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCaptionPumpsToRegen1 = new javax.swing.JLabel();
        jLabelCaptionPumpsToRegen2 = new javax.swing.JLabel();
        jButtonPumpsToRegenClose = new javax.swing.JButton();
        jButtonPumpsToRegenOpen = new javax.swing.JButton();
        panelWidgetPump1 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPump2 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        jLabelCaptionPumpsToCooler1 = new javax.swing.JLabel();
        jLabelCaptionPumpsToCooler2 = new javax.swing.JLabel();
        jButtonPumpsToCoolerClose = new javax.swing.JButton();
        jButtonPumpsToCoolerOpen = new javax.swing.JButton();
        jLabelCaptionRegenToCooler1 = new javax.swing.JLabel();
        jLabeljLabelCaptionRegenToCooler2 = new javax.swing.JLabel();
        jButtonRegenToCoolerClose = new javax.swing.JButton();
        jButtonRegenToCoolerOpen = new javax.swing.JButton();
        jLabelCaptionTreatmentBypass1 = new javax.swing.JLabel();
        jLabelCaptionTreatmentBypass2 = new javax.swing.JLabel();
        jButtonTreatmentBypassClose = new javax.swing.JButton();
        jButtonTreatmentBypassOpen = new javax.swing.JButton();
        jToggleButtonBalanceControl = new javax.swing.JToggleButton();
        jLabelCaptionBlowdownLoop2 = new javax.swing.JLabel();
        jLabelCaptionBlowdownLoop1 = new javax.swing.JLabel();
        jLabelCaptionSuction11 = new javax.swing.JLabel();
        jLabelCaptionReturnLoop2 = new javax.swing.JLabel();
        jLabelCaptionReturnLoop1 = new javax.swing.JLabel();
        jLabelCaptionReturnValve = new javax.swing.JLabel();
        jLabelCaptionPump1 = new javax.swing.JLabel();
        jLabelCaptionRegenToDrums1 = new javax.swing.JLabel();
        jLabelCaptionRegenToDrums2 = new javax.swing.JLabel();
        jButtonRegenToDrumsClose = new javax.swing.JButton();
        jButtonRegenToDrumsOpen = new javax.swing.JButton();
        jLabelCaptionBlowdown = new javax.swing.JLabel();
        jLabelCaptionPassiveFlow2 = new javax.swing.JLabel();
        jButtonPassiveFlowOpen = new javax.swing.JButton();
        jButtonPassiveFlowClose = new javax.swing.JButton();
        jLabelCaptionPassiveFlow1 = new javax.swing.JLabel();
        jLabelCaptionBalanceControl1 = new javax.swing.JLabel();
        jLabelCaptionCoolant1 = new javax.swing.JLabel();
        jLabelCaptionDrain = new javax.swing.JLabel();
        integralSwitchBlowdownLoop1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchDrain = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchBlowdownLoop2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchReturn1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchReturn2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        chornobylGaugeFlow = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chornobylGaugeTemperature = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jButtonCloseInput = new javax.swing.JButton();
        jLabelCaptionInClose = new javax.swing.JLabel();
        jButtonCloseOutput = new javax.swing.JButton();
        jLabelCaptionBalanceControl2 = new javax.swing.JLabel();
        jLabelCaptionOutClose1 = new javax.swing.JLabel();
        jToggleButtonAutoDrain = new javax.swing.JToggleButton();
        jLabelCaptionBalanceControl3 = new javax.swing.JLabel();
        integralSwitchCoolant = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        jLabelCaptionCoolant2 = new javax.swing.JLabel();
        jLabelCaptionBlodownLoop1 = new javax.swing.JLabel();
        jButtonDrumBlowdown1Close = new javax.swing.JButton();
        jButtonDrumBlowdown1Open = new javax.swing.JButton();
        jLabelCaptionBlodownLoop2 = new javax.swing.JLabel();
        jButtonDrumBlowdown2Close = new javax.swing.JButton();
        jButtonDrumBlowdown2Open = new javax.swing.JButton();
        jLabelCaptionHeaderIntakeMCP = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(250, 340));
        setMinimumSize(new java.awt.Dimension(250, 340));
        setPreferredSize(new java.awt.Dimension(250, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCaptionPumpsToRegen1.setFont(jLabelCaptionPumpsToRegen1.getFont().deriveFont(jLabelCaptionPumpsToRegen1.getFont().getSize()-2f));
        jLabelCaptionPumpsToRegen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPumpsToRegen1.setText("Pumps to");
        jLabelCaptionPumpsToRegen1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPumpsToRegen1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPumpsToRegen1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPumpsToRegen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 158, 51, 14));

        jLabelCaptionPumpsToRegen2.setFont(jLabelCaptionPumpsToRegen2.getFont().deriveFont(jLabelCaptionPumpsToRegen2.getFont().getSize()-2f));
        jLabelCaptionPumpsToRegen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPumpsToRegen2.setText("regen.");
        jLabelCaptionPumpsToRegen2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPumpsToRegen2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPumpsToRegen2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPumpsToRegen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 170, 51, 14));

        jButtonPumpsToRegenClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonPumpsToRegenClose.setText("C");
        jButtonPumpsToRegenClose.setToolTipText("");
        jButtonPumpsToRegenClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonPumpsToRegenClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPumpsToRegenCloseActionPerformed(evt);
            }
        });
        add(jButtonPumpsToRegenClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 184, 20, 20));

        jButtonPumpsToRegenOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonPumpsToRegenOpen.setText("O");
        jButtonPumpsToRegenOpen.setToolTipText("");
        jButtonPumpsToRegenOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonPumpsToRegenOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPumpsToRegenOpenActionPerformed(evt);
            }
        });
        add(jButtonPumpsToRegenOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 184, 20, 20));

        panelWidgetPump1.setChornobylPrefix("Blowdown#CooldownPump1");
        add(panelWidgetPump1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 224, -1, -1));

        panelWidgetPump2.setChornobylPrefix("Blowdown#CooldownPump2");
        add(panelWidgetPump2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 224, -1, -1));

        jLabelCaptionPumpsToCooler1.setFont(jLabelCaptionPumpsToCooler1.getFont().deriveFont(jLabelCaptionPumpsToCooler1.getFont().getSize()-2f));
        jLabelCaptionPumpsToCooler1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPumpsToCooler1.setText("Pumps to");
        jLabelCaptionPumpsToCooler1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPumpsToCooler1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPumpsToCooler1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPumpsToCooler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 158, 51, 14));

        jLabelCaptionPumpsToCooler2.setFont(jLabelCaptionPumpsToCooler2.getFont().deriveFont(jLabelCaptionPumpsToCooler2.getFont().getSize()-2f));
        jLabelCaptionPumpsToCooler2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPumpsToCooler2.setText("cooler");
        jLabelCaptionPumpsToCooler2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPumpsToCooler2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPumpsToCooler2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPumpsToCooler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 170, 51, 14));

        jButtonPumpsToCoolerClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonPumpsToCoolerClose.setText("C");
        jButtonPumpsToCoolerClose.setToolTipText("");
        jButtonPumpsToCoolerClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonPumpsToCoolerClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPumpsToCoolerCloseActionPerformed(evt);
            }
        });
        add(jButtonPumpsToCoolerClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 184, 22, 20));

        jButtonPumpsToCoolerOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonPumpsToCoolerOpen.setText("O");
        jButtonPumpsToCoolerOpen.setToolTipText("");
        jButtonPumpsToCoolerOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonPumpsToCoolerOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPumpsToCoolerOpenActionPerformed(evt);
            }
        });
        add(jButtonPumpsToCoolerOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 184, 20, 20));

        jLabelCaptionRegenToCooler1.setFont(jLabelCaptionRegenToCooler1.getFont().deriveFont(jLabelCaptionRegenToCooler1.getFont().getSize()-2f));
        jLabelCaptionRegenToCooler1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionRegenToCooler1.setText("Regen. to");
        jLabelCaptionRegenToCooler1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionRegenToCooler1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionRegenToCooler1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionRegenToCooler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 112, 51, 14));

        jLabeljLabelCaptionRegenToCooler2.setFont(jLabeljLabelCaptionRegenToCooler2.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler2.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler2.setText("cooler");
        jLabeljLabelCaptionRegenToCooler2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 124, 51, 14));

        jButtonRegenToCoolerClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonRegenToCoolerClose.setText("C");
        jButtonRegenToCoolerClose.setToolTipText("");
        jButtonRegenToCoolerClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonRegenToCoolerClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegenToCoolerCloseActionPerformed(evt);
            }
        });
        add(jButtonRegenToCoolerClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 138, 20, 20));

        jButtonRegenToCoolerOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonRegenToCoolerOpen.setText("O");
        jButtonRegenToCoolerOpen.setToolTipText("");
        jButtonRegenToCoolerOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonRegenToCoolerOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegenToCoolerOpenActionPerformed(evt);
            }
        });
        add(jButtonRegenToCoolerOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 138, 20, 20));

        jLabelCaptionTreatmentBypass1.setFont(jLabelCaptionTreatmentBypass1.getFont().deriveFont(jLabelCaptionTreatmentBypass1.getFont().getSize()-2f));
        jLabelCaptionTreatmentBypass1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionTreatmentBypass1.setText("Treatment");
        jLabelCaptionTreatmentBypass1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionTreatmentBypass1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionTreatmentBypass1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionTreatmentBypass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 66, 51, 14));

        jLabelCaptionTreatmentBypass2.setFont(jLabelCaptionTreatmentBypass2.getFont().deriveFont(jLabelCaptionTreatmentBypass2.getFont().getSize()-2f));
        jLabelCaptionTreatmentBypass2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionTreatmentBypass2.setText("bypass");
        jLabelCaptionTreatmentBypass2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionTreatmentBypass2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionTreatmentBypass2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionTreatmentBypass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 78, 51, 14));

        jButtonTreatmentBypassClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonTreatmentBypassClose.setText("C");
        jButtonTreatmentBypassClose.setToolTipText("");
        jButtonTreatmentBypassClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTreatmentBypassClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreatmentBypassCloseActionPerformed(evt);
            }
        });
        add(jButtonTreatmentBypassClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 92, 20, 20));

        jButtonTreatmentBypassOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonTreatmentBypassOpen.setText("O");
        jButtonTreatmentBypassOpen.setToolTipText("");
        jButtonTreatmentBypassOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTreatmentBypassOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreatmentBypassOpenActionPerformed(evt);
            }
        });
        add(jButtonTreatmentBypassOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 92, 20, 20));

        jToggleButtonBalanceControl.setText("←");
        jToggleButtonBalanceControl.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonBalanceControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonjToggleButtonBalanceControlActionPerformed(evt);
            }
        });
        add(jToggleButtonBalanceControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 40, 20, 20));

        jLabelCaptionBlowdownLoop2.setFont(jLabelCaptionBlowdownLoop2.getFont().deriveFont(jLabelCaptionBlowdownLoop2.getFont().getSize()-2f));
        jLabelCaptionBlowdownLoop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionBlowdownLoop2.setText("Loop 2");
        jLabelCaptionBlowdownLoop2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBlowdownLoop2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBlowdownLoop2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionBlowdownLoop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 292, 51, 14));

        jLabelCaptionBlowdownLoop1.setFont(jLabelCaptionBlowdownLoop1.getFont().deriveFont(jLabelCaptionBlowdownLoop1.getFont().getSize()-2f));
        jLabelCaptionBlowdownLoop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionBlowdownLoop1.setText("Loop 1");
        jLabelCaptionBlowdownLoop1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBlowdownLoop1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBlowdownLoop1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionBlowdownLoop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 292, 51, 14));

        jLabelCaptionSuction11.setFont(jLabelCaptionSuction11.getFont().deriveFont(jLabelCaptionSuction11.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuction11.getFont().getSize()-2));
        jLabelCaptionSuction11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuction11.setText("Pump 2");
        jLabelCaptionSuction11.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuction11.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuction11.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuction11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 51, 14));

        jLabelCaptionReturnLoop2.setFont(jLabelCaptionReturnLoop2.getFont().deriveFont(jLabelCaptionReturnLoop2.getFont().getSize()-2f));
        jLabelCaptionReturnLoop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionReturnLoop2.setText("Loop 2");
        jLabelCaptionReturnLoop2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionReturnLoop2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionReturnLoop2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionReturnLoop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 82, 50, 14));

        jLabelCaptionReturnLoop1.setFont(jLabelCaptionReturnLoop1.getFont().deriveFont(jLabelCaptionReturnLoop1.getFont().getSize()-2f));
        jLabelCaptionReturnLoop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionReturnLoop1.setText("Loop 1");
        jLabelCaptionReturnLoop1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionReturnLoop1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionReturnLoop1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionReturnLoop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 82, 46, 14));

        jLabelCaptionReturnValve.setFont(jLabelCaptionReturnValve.getFont().deriveFont(jLabelCaptionReturnValve.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionReturnValve.getFont().getSize()-2));
        jLabelCaptionReturnValve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionReturnValve.setText("Return Valve");
        jLabelCaptionReturnValve.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionReturnValve.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionReturnValve.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionReturnValve, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 68, 102, 14));

        jLabelCaptionPump1.setFont(jLabelCaptionPump1.getFont().deriveFont(jLabelCaptionPump1.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump1.getFont().getSize()-2));
        jLabelCaptionPump1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump1.setText("Pump 1");
        jLabelCaptionPump1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 210, 51, 14));

        jLabelCaptionRegenToDrums1.setFont(jLabelCaptionRegenToDrums1.getFont().deriveFont(jLabelCaptionRegenToDrums1.getFont().getSize()-2f));
        jLabelCaptionRegenToDrums1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionRegenToDrums1.setText("Regen.");
        jLabelCaptionRegenToDrums1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionRegenToDrums1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionRegenToDrums1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionRegenToDrums1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 66, 51, 14));

        jLabelCaptionRegenToDrums2.setFont(jLabelCaptionRegenToDrums2.getFont().deriveFont(jLabelCaptionRegenToDrums2.getFont().getSize()-2f));
        jLabelCaptionRegenToDrums2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionRegenToDrums2.setText("to drums");
        jLabelCaptionRegenToDrums2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionRegenToDrums2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionRegenToDrums2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionRegenToDrums2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 78, 51, 14));

        jButtonRegenToDrumsClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonRegenToDrumsClose.setText("C");
        jButtonRegenToDrumsClose.setToolTipText("");
        jButtonRegenToDrumsClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonRegenToDrumsClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegenToDrumsCloseActionPerformed(evt);
            }
        });
        add(jButtonRegenToDrumsClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 92, 20, 20));

        jButtonRegenToDrumsOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonRegenToDrumsOpen.setText("O");
        jButtonRegenToDrumsOpen.setToolTipText("");
        jButtonRegenToDrumsOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonRegenToDrumsOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegenToDrumsOpenActionPerformed(evt);
            }
        });
        add(jButtonRegenToDrumsOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 92, 20, 20));

        jLabelCaptionBlowdown.setFont(jLabelCaptionBlowdown.getFont().deriveFont(jLabelCaptionBlowdown.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionBlowdown.getFont().getSize()-2));
        jLabelCaptionBlowdown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionBlowdown.setText("Drum blowdown");
        jLabelCaptionBlowdown.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBlowdown.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBlowdown.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionBlowdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 214, 130, 14));

        jLabelCaptionPassiveFlow2.setFont(jLabelCaptionPassiveFlow2.getFont().deriveFont(jLabelCaptionPassiveFlow2.getFont().getSize()-2f));
        jLabelCaptionPassiveFlow2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPassiveFlow2.setText("flow");
        jLabelCaptionPassiveFlow2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPassiveFlow2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPassiveFlow2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPassiveFlow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 124, 51, 14));

        jButtonPassiveFlowOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonPassiveFlowOpen.setText("O");
        jButtonPassiveFlowOpen.setToolTipText("");
        jButtonPassiveFlowOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonPassiveFlowOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassiveFlowOpenActionPerformed(evt);
            }
        });
        add(jButtonPassiveFlowOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 138, 20, 20));

        jButtonPassiveFlowClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonPassiveFlowClose.setText("C");
        jButtonPassiveFlowClose.setToolTipText("");
        jButtonPassiveFlowClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonPassiveFlowClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassiveFlowCloseActionPerformed(evt);
            }
        });
        add(jButtonPassiveFlowClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 138, 20, 20));

        jLabelCaptionPassiveFlow1.setFont(jLabelCaptionPassiveFlow1.getFont().deriveFont(jLabelCaptionPassiveFlow1.getFont().getSize()-2f));
        jLabelCaptionPassiveFlow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPassiveFlow1.setText("Passive");
        jLabelCaptionPassiveFlow1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPassiveFlow1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPassiveFlow1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPassiveFlow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 112, 51, 14));

        jLabelCaptionBalanceControl1.setFont(jLabelCaptionBalanceControl1.getFont().deriveFont(jLabelCaptionBalanceControl1.getFont().getSize()-2f));
        jLabelCaptionBalanceControl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionBalanceControl1.setText("Balance");
        jLabelCaptionBalanceControl1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBalanceControl1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBalanceControl1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionBalanceControl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 24, 50, 16));

        jLabelCaptionCoolant1.setFont(jLabelCaptionCoolant1.getFont().deriveFont(jLabelCaptionCoolant1.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionCoolant1.getFont().getSize()-2));
        jLabelCaptionCoolant1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionCoolant1.setText("Coolant");
        jLabelCaptionCoolant1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionCoolant1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionCoolant1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionCoolant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 154, 51, 14));

        jLabelCaptionDrain.setFont(jLabelCaptionDrain.getFont().deriveFont(jLabelCaptionDrain.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain.getFont().getSize()-2));
        jLabelCaptionDrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain.setText("Drain");
        jLabelCaptionDrain.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 130, -1, 14));

        integralSwitchBlowdownLoop1.setComponent("Blowdown#ValveFromLoop1");
        add(integralSwitchBlowdownLoop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 308, -1, -1));

        integralSwitchDrain.setComponent("Blowdown#ValveDrain");
        add(integralSwitchDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 146, -1, -1));

        integralSwitchBlowdownLoop2.setComponent("Blowdown#ValveFromLoop2");
        add(integralSwitchBlowdownLoop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 308, -1, -1));

        integralSwitchReturn1.setComponent("Blowdown#ReturnValve1");
        add(integralSwitchReturn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 96, -1, -1));

        integralSwitchReturn2.setComponent("Blowdown#ReturnValve2");
        add(integralSwitchReturn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 96, -1, -1));

        chornobylGaugeFlow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeFlow.setChornobylMaximum(800.0F);
        chornobylGaugeFlow.setChornobylMinimum(0.0F);
        chornobylGaugeFlow.setChornobylTicks(new float[] {0.0f, 200.0f, 400.0f, 600.0f});
        add(chornobylGaugeFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, -1, -1));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()-2f));
        jLabel5.setText("Treatment");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 52, 14));

        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getSize()-2f));
        jLabel20.setText("Flow");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 52, 14));

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()-2f));
        jLabel7.setText("Return");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 52, 14));

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getSize()-2f));
        jLabel19.setText("Temp.");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 52, 14));

        chornobylGaugeTemperature.setChornobylMaximum(150.0F);
        chornobylGaugeTemperature.setChornobylMinimum(20.0F);
        chornobylGaugeTemperature.setChornobylTicks(new float[] {20.0f, 50.0f, 100.0f, 150.0f});
        chornobylGaugeTemperature.setChornobylUnitText("°C");
        add(chornobylGaugeTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 34, -1, -1));

        jButtonCloseInput.setFont(jButtonCloseInput.getFont().deriveFont(jButtonCloseInput.getFont().getSize()-2f));
        jButtonCloseInput.setText("●");
        jButtonCloseInput.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonCloseInput.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonCloseInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseInputActionPerformed(evt);
            }
        });
        add(jButtonCloseInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 314, 20, 20));

        jLabelCaptionInClose.setFont(jLabelCaptionInClose.getFont().deriveFont(jLabelCaptionInClose.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionInClose.getFont().getSize()-2));
        jLabelCaptionInClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionInClose.setText("Close");
        jLabelCaptionInClose.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionInClose.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionInClose.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionInClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 298, 48, 14));

        jButtonCloseOutput.setFont(jButtonCloseOutput.getFont().deriveFont(jButtonCloseOutput.getFont().getSize()-2f));
        jButtonCloseOutput.setText("●");
        jButtonCloseOutput.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonCloseOutput.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonCloseOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseOutputActionPerformed(evt);
            }
        });
        add(jButtonCloseOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 102, 20, 20));

        jLabelCaptionBalanceControl2.setFont(jLabelCaptionBalanceControl2.getFont().deriveFont(jLabelCaptionBalanceControl2.getFont().getSize()-2f));
        jLabelCaptionBalanceControl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionBalanceControl2.setText("Level");
        jLabelCaptionBalanceControl2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBalanceControl2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBalanceControl2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionBalanceControl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 12, 50, 16));

        jLabelCaptionOutClose1.setFont(jLabelCaptionOutClose1.getFont().deriveFont(jLabelCaptionOutClose1.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionOutClose1.getFont().getSize()-2));
        jLabelCaptionOutClose1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionOutClose1.setText("Close");
        jLabelCaptionOutClose1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionOutClose1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionOutClose1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionOutClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 86, 48, 14));

        jToggleButtonAutoDrain.setText("←");
        jToggleButtonAutoDrain.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonAutoDrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAutoDrainActionPerformed(evt);
            }
        });
        add(jToggleButtonAutoDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 188, 20, 20));

        jLabelCaptionBalanceControl3.setFont(jLabelCaptionBalanceControl3.getFont().deriveFont(jLabelCaptionBalanceControl3.getFont().getSize()-2f));
        jLabelCaptionBalanceControl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionBalanceControl3.setText("Auto");
        jLabelCaptionBalanceControl3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBalanceControl3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBalanceControl3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionBalanceControl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 172, 50, 16));

        integralSwitchCoolant.setComponent("Blowdown#ValveCoolant");
        add(integralSwitchCoolant, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 172, -1, -1));

        jLabelCaptionCoolant2.setFont(jLabelCaptionCoolant2.getFont().deriveFont(jLabelCaptionCoolant2.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionCoolant2.getFont().getSize()-2));
        jLabelCaptionCoolant2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionCoolant2.setText("Aftercooler");
        jLabelCaptionCoolant2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionCoolant2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionCoolant2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionCoolant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 138, 72, 14));

        jLabelCaptionBlodownLoop1.setFont(jLabelCaptionBlodownLoop1.getFont().deriveFont(jLabelCaptionBlodownLoop1.getFont().getSize()-2f));
        jLabelCaptionBlodownLoop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionBlodownLoop1.setText("Loop 1");
        jLabelCaptionBlodownLoop1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBlodownLoop1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBlodownLoop1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionBlodownLoop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 228, 51, 14));

        jButtonDrumBlowdown1Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonDrumBlowdown1Close.setText("C");
        jButtonDrumBlowdown1Close.setToolTipText("");
        jButtonDrumBlowdown1Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDrumBlowdown1Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrumBlowdown1CloseActionPerformed(evt);
            }
        });
        add(jButtonDrumBlowdown1Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 242, 20, 20));

        jButtonDrumBlowdown1Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonDrumBlowdown1Open.setText("O");
        jButtonDrumBlowdown1Open.setToolTipText("");
        jButtonDrumBlowdown1Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDrumBlowdown1Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrumBlowdown1OpenActionPerformed(evt);
            }
        });
        add(jButtonDrumBlowdown1Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 242, 20, 20));

        jLabelCaptionBlodownLoop2.setFont(jLabelCaptionBlodownLoop2.getFont().deriveFont(jLabelCaptionBlodownLoop2.getFont().getSize()-2f));
        jLabelCaptionBlodownLoop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionBlodownLoop2.setText("Loop 2");
        jLabelCaptionBlodownLoop2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBlodownLoop2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBlodownLoop2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionBlodownLoop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 228, 51, 14));

        jButtonDrumBlowdown2Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonDrumBlowdown2Close.setText("C");
        jButtonDrumBlowdown2Close.setToolTipText("");
        jButtonDrumBlowdown2Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDrumBlowdown2Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrumBlowdown2CloseActionPerformed(evt);
            }
        });
        add(jButtonDrumBlowdown2Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 242, 22, 20));

        jButtonDrumBlowdown2Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonDrumBlowdown2Open.setText("O");
        jButtonDrumBlowdown2Open.setToolTipText("");
        jButtonDrumBlowdown2Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDrumBlowdown2Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrumBlowdown2OpenActionPerformed(evt);
            }
        });
        add(jButtonDrumBlowdown2Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 242, 20, 20));

        jLabelCaptionHeaderIntakeMCP.setFont(jLabelCaptionHeaderIntakeMCP.getFont().deriveFont(jLabelCaptionHeaderIntakeMCP.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionHeaderIntakeMCP.getFont().getSize()-2));
        jLabelCaptionHeaderIntakeMCP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionHeaderIntakeMCP.setText("MCP header Intake");
        jLabelCaptionHeaderIntakeMCP.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionHeaderIntakeMCP.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionHeaderIntakeMCP.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionHeaderIntakeMCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 276, 130, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPumpsToRegenOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPumpsToRegenOpenActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValvePumpsToRegenerator", true));
    }//GEN-LAST:event_jButtonPumpsToRegenOpenActionPerformed

    private void jButtonPumpsToRegenCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPumpsToRegenCloseActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValvePumpsToRegenerator", false));
    }//GEN-LAST:event_jButtonPumpsToRegenCloseActionPerformed

    private void jButtonPumpsToCoolerCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPumpsToCoolerCloseActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValvePumpsToCooler", false));
    }//GEN-LAST:event_jButtonPumpsToCoolerCloseActionPerformed

    private void jButtonPumpsToCoolerOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPumpsToCoolerOpenActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValvePumpsToCooler", true));
    }//GEN-LAST:event_jButtonPumpsToCoolerOpenActionPerformed

    private void jButtonRegenToCoolerCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegenToCoolerCloseActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValveRegeneratorToCooler", false));
    }//GEN-LAST:event_jButtonRegenToCoolerCloseActionPerformed

    private void jButtonRegenToCoolerOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegenToCoolerOpenActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValveRegeneratorToCooler", true));
    }//GEN-LAST:event_jButtonRegenToCoolerOpenActionPerformed

    private void jButtonTreatmentBypassCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreatmentBypassCloseActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValveTreatmentBypass", false));
    }//GEN-LAST:event_jButtonTreatmentBypassCloseActionPerformed

    private void jButtonTreatmentBypassOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreatmentBypassOpenActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValveTreatmentBypass", true));
    }//GEN-LAST:event_jButtonTreatmentBypassOpenActionPerformed

    private void jToggleButtonjToggleButtonBalanceControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonjToggleButtonBalanceControlActionPerformed
        if (jToggleButtonBalanceControl.isSelected()) {
            jToggleButtonBalanceControl.setText("↑");
            controller.userAction(new ActionCommand("Blowdown#Balance_ControlCommand", ControlCommand.AUTOMATIC));
        } else {
            jToggleButtonBalanceControl.setText("←");
            controller.userAction(new ActionCommand("Blowdown#Balance_ControlCommand", ControlCommand.MANUAL_OPERATION));
        }

    }//GEN-LAST:event_jToggleButtonjToggleButtonBalanceControlActionPerformed

    private void jButtonRegenToDrumsCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegenToDrumsCloseActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValveRegeneratedToDrums", false));
    }//GEN-LAST:event_jButtonRegenToDrumsCloseActionPerformed

    private void jButtonRegenToDrumsOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegenToDrumsOpenActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValveRegeneratedToDrums", true));
    }//GEN-LAST:event_jButtonRegenToDrumsOpenActionPerformed

    private void jButtonPassiveFlowOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassiveFlowOpenActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValvePassiveFlow", true));
    }//GEN-LAST:event_jButtonPassiveFlowOpenActionPerformed

    private void jButtonPassiveFlowCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassiveFlowCloseActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValvePassiveFlow", false));
    }//GEN-LAST:event_jButtonPassiveFlowCloseActionPerformed

    private void jButtonCloseInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseInputActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValveFromLoop1", false));
        controller.userAction(new ActionCommand("Blowdown#ValveFromLoop2", false));
    }//GEN-LAST:event_jButtonCloseInputActionPerformed

    private void jButtonCloseOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseOutputActionPerformed
        controller.userAction(new ActionCommand("Blowdown#Balance_ControlCommand", ControlCommand.MANUAL_OPERATION));
        controller.userAction(new ActionCommand("Blowdown#ReturnValve1", false));
        controller.userAction(new ActionCommand("Blowdown#ReturnValve2", false));
    }//GEN-LAST:event_jButtonCloseOutputActionPerformed

    private void jToggleButtonAutoDrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAutoDrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonAutoDrainActionPerformed

    private void jButtonDrumBlowdown1CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrumBlowdown1CloseActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValveFromDrum1", false));
    }//GEN-LAST:event_jButtonDrumBlowdown1CloseActionPerformed

    private void jButtonDrumBlowdown1OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrumBlowdown1OpenActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValveFromDrum1", true));
    }//GEN-LAST:event_jButtonDrumBlowdown1OpenActionPerformed

    private void jButtonDrumBlowdown2CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrumBlowdown2CloseActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValveFromDrum2", false));
    }//GEN-LAST:event_jButtonDrumBlowdown2CloseActionPerformed

    private void jButtonDrumBlowdown2OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrumBlowdown2OpenActionPerformed
        controller.userAction(new ActionCommand("Blowdown#ValveFromDrum2", true));
    }//GEN-LAST:event_jButtonDrumBlowdown2OpenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFlow;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeTemperature;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchBlowdownLoop1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchBlowdownLoop2;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchCoolant;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchDrain;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchReturn1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchReturn2;
    private javax.swing.JButton jButtonCloseInput;
    private javax.swing.JButton jButtonCloseOutput;
    private javax.swing.JButton jButtonDrumBlowdown1Close;
    private javax.swing.JButton jButtonDrumBlowdown1Open;
    private javax.swing.JButton jButtonDrumBlowdown2Close;
    private javax.swing.JButton jButtonDrumBlowdown2Open;
    private javax.swing.JButton jButtonPassiveFlowClose;
    private javax.swing.JButton jButtonPassiveFlowOpen;
    private javax.swing.JButton jButtonPumpsToCoolerClose;
    private javax.swing.JButton jButtonPumpsToCoolerOpen;
    private javax.swing.JButton jButtonPumpsToRegenClose;
    private javax.swing.JButton jButtonPumpsToRegenOpen;
    private javax.swing.JButton jButtonRegenToCoolerClose;
    private javax.swing.JButton jButtonRegenToCoolerOpen;
    private javax.swing.JButton jButtonRegenToDrumsClose;
    private javax.swing.JButton jButtonRegenToDrumsOpen;
    private javax.swing.JButton jButtonTreatmentBypassClose;
    private javax.swing.JButton jButtonTreatmentBypassOpen;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCaptionBalanceControl1;
    private javax.swing.JLabel jLabelCaptionBalanceControl2;
    private javax.swing.JLabel jLabelCaptionBalanceControl3;
    private javax.swing.JLabel jLabelCaptionBlodownLoop1;
    private javax.swing.JLabel jLabelCaptionBlodownLoop2;
    private javax.swing.JLabel jLabelCaptionBlowdown;
    private javax.swing.JLabel jLabelCaptionBlowdownLoop1;
    private javax.swing.JLabel jLabelCaptionBlowdownLoop2;
    private javax.swing.JLabel jLabelCaptionCoolant1;
    private javax.swing.JLabel jLabelCaptionCoolant2;
    private javax.swing.JLabel jLabelCaptionDrain;
    private javax.swing.JLabel jLabelCaptionHeaderIntakeMCP;
    private javax.swing.JLabel jLabelCaptionInClose;
    private javax.swing.JLabel jLabelCaptionOutClose1;
    private javax.swing.JLabel jLabelCaptionPassiveFlow1;
    private javax.swing.JLabel jLabelCaptionPassiveFlow2;
    private javax.swing.JLabel jLabelCaptionPump1;
    private javax.swing.JLabel jLabelCaptionPumpsToCooler1;
    private javax.swing.JLabel jLabelCaptionPumpsToCooler2;
    private javax.swing.JLabel jLabelCaptionPumpsToRegen1;
    private javax.swing.JLabel jLabelCaptionPumpsToRegen2;
    private javax.swing.JLabel jLabelCaptionRegenToCooler1;
    private javax.swing.JLabel jLabelCaptionRegenToDrums1;
    private javax.swing.JLabel jLabelCaptionRegenToDrums2;
    private javax.swing.JLabel jLabelCaptionReturnLoop1;
    private javax.swing.JLabel jLabelCaptionReturnLoop2;
    private javax.swing.JLabel jLabelCaptionReturnValve;
    private javax.swing.JLabel jLabelCaptionSuction11;
    private javax.swing.JLabel jLabelCaptionTreatmentBypass1;
    private javax.swing.JLabel jLabelCaptionTreatmentBypass2;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler2;
    private javax.swing.JToggleButton jToggleButtonAutoDrain;
    private javax.swing.JToggleButton jToggleButtonBalanceControl;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump1;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        if (!evt.getPropertyName().startsWith("Blowdown")) {
            return;
        }
        if (evt.getPropertyName().startsWith("Blowdown#CooldownPump")) {
            panelWidgetPump1.updateComponent(evt);
            panelWidgetPump2.updateComponent(evt);
            return;
        }
        switch (evt.getPropertyName()) {
            case "Blowdown#ValvePumpsToRegenerator_Pos":
                setValveButtons(jButtonPumpsToRegenClose,
                        jButtonPumpsToRegenOpen, evt.getNewValue());
                break;
            case "Blowdown#ValvePumpsToCooler_Pos":
                setValveButtons(jButtonPumpsToCoolerClose,
                        jButtonPumpsToCoolerOpen, evt.getNewValue());
                break;
            case "Blowdown#ValveRegeneratorToCooler_Pos":
                setValveButtons(jButtonRegenToCoolerClose,
                        jButtonRegenToCoolerOpen, evt.getNewValue());
                break;
            case "Blowdown#ValvePassiveFlow_Pos":
                setValveButtons(jButtonPassiveFlowClose,
                        jButtonPassiveFlowOpen, evt.getNewValue());
                break;
            case "Blowdown#ValveTreatmentBypass_Pos":
                setValveButtons(jButtonTreatmentBypassClose,
                        jButtonTreatmentBypassOpen, evt.getNewValue());
                break;
            case "Blowdown#ValveRegeneratedToDrums_Pos":
                setValveButtons(jButtonRegenToDrumsClose,
                        jButtonRegenToDrumsOpen, evt.getNewValue());
                break;
            case "Blowdown#ValveFromDrum1_Pos":
                setValveButtons(jButtonDrumBlowdown1Close,
                        jButtonDrumBlowdown1Open, evt.getNewValue());
                break;
            case "Blowdown#ValveFromDrum2_Pos":
                setValveButtons(jButtonDrumBlowdown2Close,
                        jButtonDrumBlowdown2Open, evt.getNewValue());
                break;
            case "Blowdown#BalanceControlControlState":
                // Set the initial position of the switch button, this will be
                // received when opening the panel.
                if (ControlCommand.AUTOMATIC
                        == (ControlCommand) evt.getNewValue()
                        && !jToggleButtonBalanceControl.isSelected()) {
                    jToggleButtonBalanceControl.setSelected(true);
                    jToggleButtonBalanceControl.setText("↑");
                }
        }
        integralSwitchBlowdownLoop1.updateComponent(evt);
        integralSwitchBlowdownLoop2.updateComponent(evt);
        integralSwitchDrain.updateComponent(evt);
        integralSwitchReturn1.updateComponent(evt);
        integralSwitchReturn2.updateComponent(evt);
        integralSwitchCoolant.updateComponent(evt);
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        if (!propertyName.startsWith("Blowdown")) {
            return;
        }
        switch (propertyName) {
            case "Blowdown#SumFlowToDrums" ->
                chornobylGaugeFlow.setChornobylValue((float) newValue);
            case "Blowdown#ReturnTemp" ->
                chornobylGaugeTemperature.setChornobylValue((float) newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
    }
}
