/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.ActionCommand;
import java.beans.PropertyChangeEvent;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelMCP extends AbstractPanelWidget
        implements UpdateReceiver {


    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);
        
        // Make action receiver interface from controller available to elements
        // of this Panel so they can send their actions to it directly.
        controlPanelMCPPumpColumn1.registerActionReceiver(controller);
        controlPanelMCPPumpColumn10.registerActionReceiver(controller);
        controlPanelMCPPumpColumn11.registerActionReceiver(controller);
        controlPanelMCPPumpColumn12.registerActionReceiver(controller);
        controlPanelMCPPumpColumn2.registerActionReceiver(controller);
        controlPanelMCPPumpColumn3.registerActionReceiver(controller);
        controlPanelMCPPumpColumn4.registerActionReceiver(controller);
        controlPanelMCPPumpColumn9.registerActionReceiver(controller);
        setpointControl1.registerActionReceiver(controller);
    }

    /**
     * Creates new form ControlPanelMCP
     */
    public PanelMCP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chornobylGaugeLoop1Level = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeLoop1Pressure = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chornobylGaugeLoop1Temperature = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeLoop1RecircFlow = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel8 = new javax.swing.JLabel();
        chornobylGaugeLoop2RecircFlow = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeLoop2Temperature = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButtonLoop1Close = new javax.swing.JButton();
        jButtonLoop1Open = new javax.swing.JButton();
        jLabelCaptionPassiveFlow2 = new javax.swing.JLabel();
        jButtonLoop2Close = new javax.swing.JButton();
        jButtonLoop2Open = new javax.swing.JButton();
        jLabeljLabelCaptionRegenToCooler2 = new javax.swing.JLabel();
        chornobylGaugeLoop2Pressure1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        chornobylGaugeLoop2Level1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabelCaptionDrain5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        chornobylGaugeLoop1Cooldown = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel25 = new javax.swing.JLabel();
        chornobylGaugeLoop2Cooldown = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        controlPanelMCPPumpColumn4 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump();
        jLabel4 = new javax.swing.JLabel();
        controlPanelMCPPumpColumn3 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        controlPanelMCPPumpColumn2 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump();
        controlPanelMCPPumpColumn1 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump();
        jLabel1 = new javax.swing.JLabel();
        controlPanelMCPPumpColumn9 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump();
        jLabel9 = new javax.swing.JLabel();
        controlPanelMCPPumpColumn10 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        controlPanelMCPPumpColumn11 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump();
        controlPanelMCPPumpColumn12 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump();
        jLabel12 = new javax.swing.JLabel();
        jLabelCaptionDrain6 = new javax.swing.JLabel();
        setpointControl1 = new com.hartrusion.rbmksim.gui.elements.SetpointControl();

        setMaximumSize(new java.awt.Dimension(480, 340));
        setMinimumSize(new java.awt.Dimension(480, 340));
        setPreferredSize(new java.awt.Dimension(480, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chornobylGaugeLoop1Level.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeLoop1Level.setChornobylMaximum(70.0F);
        chornobylGaugeLoop1Level.setChornobylMinimum(-70.0F);
        chornobylGaugeLoop1Level.setChornobylTicks(new float[] {-60.0f, -30.0f, 0.0f, 30.0f, 60.0f});
        add(chornobylGaugeLoop1Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, -1, -1));

        chornobylGaugeLoop1Pressure.setChornobylTicks(new float[] {0.0f, 20.0f, 70.0f, 100.0f});
        chornobylGaugeLoop1Pressure.setChornobylUnitText("bar");
        add(chornobylGaugeLoop1Pressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 34, -1, -1));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()-2f));
        jLabel5.setText("Drum 1");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 52, 14));

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()-2f));
        jLabel6.setText("Drum 1");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 52, 14));

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()-2f));
        jLabel7.setText("Drum 1");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 52, 14));

        chornobylGaugeLoop1Temperature.setChornobylMaximum(350.0F);
        chornobylGaugeLoop1Temperature.setChornobylMinimum(20.0F);
        chornobylGaugeLoop1Temperature.setChornobylTicks(new float[] {40.0f, 100.0f, 200.0f, 300.0f});
        chornobylGaugeLoop1Temperature.setChornobylUnitText("°C");
        add(chornobylGaugeLoop1Temperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 64, -1, -1));

        chornobylGaugeLoop1RecircFlow.setChornobylMaximum(8000.0F);
        chornobylGaugeLoop1RecircFlow.setChornobylTicks(new float[] {0.0f, 2000.0f, 5000.0f, 8000.0f});
        chornobylGaugeLoop1RecircFlow.setChornobylUnitText("kg/s");
        add(chornobylGaugeLoop1RecircFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 94, -1, -1));

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()-2f));
        jLabel8.setText("Loop 1");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 94, 52, 14));

        chornobylGaugeLoop2RecircFlow.setChornobylMaximum(8000.0F);
        chornobylGaugeLoop2RecircFlow.setChornobylTicks(new float[] {0.0f, 2000.0f, 5000.0f, 8000.0f});
        chornobylGaugeLoop2RecircFlow.setChornobylUnitText("kg/s");
        add(chornobylGaugeLoop2RecircFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 94, -1, -1));

        chornobylGaugeLoop2Temperature.setChornobylMaximum(350.0F);
        chornobylGaugeLoop2Temperature.setChornobylMinimum(20.0F);
        chornobylGaugeLoop2Temperature.setChornobylTicks(new float[] {40.0f, 100.0f, 200.0f, 300.0f});
        chornobylGaugeLoop2Temperature.setChornobylUnitText("°C");
        add(chornobylGaugeLoop2Temperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 64, -1, -1));

        jLabel15.setFont(jLabel15.getFont().deriveFont(jLabel15.getFont().getSize()-2f));
        jLabel15.setText("Temp");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 78, 52, 14));

        jLabel16.setFont(jLabel16.getFont().deriveFont(jLabel16.getFont().getSize()-2f));
        jLabel16.setText("Rc. Flow");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 108, 52, 14));

        jButtonLoop1Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop1Close.setText("C");
        jButtonLoop1Close.setToolTipText("");
        jButtonLoop1Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop1Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop1CloseActionPerformed(evt);
            }
        });
        add(jButtonLoop1Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 90, 20, 20));

        jButtonLoop1Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop1Open.setText("O");
        jButtonLoop1Open.setToolTipText("");
        jButtonLoop1Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop1Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop1OpenActionPerformed(evt);
            }
        });
        add(jButtonLoop1Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 90, 20, 20));

        jLabelCaptionPassiveFlow2.setFont(jLabelCaptionPassiveFlow2.getFont().deriveFont(jLabelCaptionPassiveFlow2.getFont().getSize()-2f));
        jLabelCaptionPassiveFlow2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPassiveFlow2.setText("Bypass 1");
        jLabelCaptionPassiveFlow2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPassiveFlow2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPassiveFlow2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPassiveFlow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 76, 51, 14));

        jButtonLoop2Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close.setText("C");
        jButtonLoop2Close.setToolTipText("");
        jButtonLoop2Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2CloseActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 130, 20, 20));

        jButtonLoop2Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open.setText("O");
        jButtonLoop2Open.setToolTipText("");
        jButtonLoop2Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2OpenActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 130, 20, 20));

        jLabeljLabelCaptionRegenToCooler2.setFont(jLabeljLabelCaptionRegenToCooler2.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler2.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler2.setText("Bypass 2");
        jLabeljLabelCaptionRegenToCooler2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 116, 51, 14));

        chornobylGaugeLoop2Pressure1.setChornobylTicks(new float[] {0.0f, 20.0f, 70.0f, 100.0f});
        chornobylGaugeLoop2Pressure1.setChornobylUnitText("bar");
        add(chornobylGaugeLoop2Pressure1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 34, -1, -1));

        jLabel17.setFont(jLabel17.getFont().deriveFont(jLabel17.getFont().getSize()-2f));
        jLabel17.setText("Pressure");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 48, 52, 14));

        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getSize()-2f));
        jLabel18.setText("Level");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 16, 52, 14));

        chornobylGaugeLoop2Level1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeLoop2Level1.setChornobylMaximum(70.0F);
        chornobylGaugeLoop2Level1.setChornobylMinimum(-70.0F);
        chornobylGaugeLoop2Level1.setChornobylTicks(new float[] {-60.0f, -30.0f, 0.0f, 30.0f, 60.0f});
        add(chornobylGaugeLoop2Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 4, -1, -1));

        jLabelCaptionDrain5.setFont(jLabelCaptionDrain5.getFont().deriveFont(jLabelCaptionDrain5.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain5.getFont().getSize()-2));
        jLabelCaptionDrain5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain5.setText("Setpoint");
        jLabelCaptionDrain5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain5, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 22, 86, 14));

        jLabel13.setFont(jLabel13.getFont().deriveFont(jLabel13.getFont().getSize()-2f));
        jLabel13.setText("Rc. Flow");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, 52, 14));

        jLabel14.setFont(jLabel14.getFont().deriveFont(jLabel14.getFont().getSize()-2f));
        jLabel14.setText("Temp.");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 52, 14));

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getSize()-2f));
        jLabel19.setText("Pressure");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, 52, 14));

        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getSize()-2f));
        jLabel20.setText("Level");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 52, 14));

        jLabel21.setFont(jLabel21.getFont().deriveFont(jLabel21.getFont().getSize()-2f));
        jLabel21.setText("Loop 2");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 94, 52, 14));

        jLabel22.setFont(jLabel22.getFont().deriveFont(jLabel22.getFont().getSize()-2f));
        jLabel22.setText("Drum 2");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 64, 52, 14));

        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getSize()-2f));
        jLabel23.setText("Drum 2");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 34, 52, 14));

        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getSize()-2f));
        jLabel24.setText("Drum 2");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 4, 52, 14));

        chornobylGaugeLoop1Cooldown.setChornobylMaximum(5.0F);
        chornobylGaugeLoop1Cooldown.setChornobylMinimum(-30.0F);
        chornobylGaugeLoop1Cooldown.setChornobylTicks(new float[] {-30.0f, -20.0f, -10.0f, 0.0f});
        chornobylGaugeLoop1Cooldown.setChornobylUnitText("K");
        chornobylGaugeLoop1Cooldown.setChornobylValue(-10.0F);
        add(chornobylGaugeLoop1Cooldown, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 124, -1, -1));

        jLabel25.setFont(jLabel25.getFont().deriveFont(jLabel25.getFont().getSize()-2f));
        jLabel25.setText("MCP 1");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, 52, 14));

        chornobylGaugeLoop2Cooldown.setChornobylMaximum(5.0F);
        chornobylGaugeLoop2Cooldown.setChornobylMinimum(-30.0F);
        chornobylGaugeLoop2Cooldown.setChornobylTicks(new float[] {-30.0f, -20.0f, -10.0f, 0.0f});
        chornobylGaugeLoop2Cooldown.setChornobylUnitText("K");
        chornobylGaugeLoop2Cooldown.setChornobylValue(-10.0F);
        add(chornobylGaugeLoop2Cooldown, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 124, -1, -1));

        jLabel26.setFont(jLabel26.getFont().deriveFont(jLabel26.getFont().getSize()-2f));
        jLabel26.setText("Cooldown");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 138, 52, 14));

        jLabel27.setFont(jLabel27.getFont().deriveFont(jLabel27.getFont().getSize()-2f));
        jLabel27.setText("Cooldown");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 138, 52, 14));

        jLabel28.setFont(jLabel28.getFont().deriveFont(jLabel28.getFont().getSize()-2f));
        jLabel28.setText("MCP 2");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 124, 52, 14));

        controlPanelMCPPumpColumn4.setChornobylPrefix("Loop1#mcp4");
        add(controlPanelMCPPumpColumn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 184, -1, -1));

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, jLabel4.getFont().getSize()-2));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MCP 1.4");
        jLabel4.setToolTipText("");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 168, 52, -1));

        controlPanelMCPPumpColumn3.setChornobylPrefix("Loop1#mcp3");
        add(controlPanelMCPPumpColumn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 184, -1, -1));

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, jLabel3.getFont().getSize()-2));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MCP 1.2");
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 168, 52, -1));

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()-2));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MCP 1.2");
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 168, 52, -1));

        controlPanelMCPPumpColumn2.setChornobylPrefix("Loop1#mcp2");
        add(controlPanelMCPPumpColumn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 184, -1, -1));

        controlPanelMCPPumpColumn1.setChornobylPrefix("Loop1#mcp1");
        add(controlPanelMCPPumpColumn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 184, -1, -1));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()-2));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MCP 1.1");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 168, 52, -1));

        controlPanelMCPPumpColumn9.setChornobylPrefix("Loop2#mcp1");
        add(controlPanelMCPPumpColumn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 184, -1, -1));

        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getStyle() | java.awt.Font.BOLD, jLabel9.getFont().getSize()-2));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MCP 2.1");
        jLabel9.setToolTipText("");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 168, 52, -1));

        controlPanelMCPPumpColumn10.setChornobylPrefix("Loop2#mcp2");
        add(controlPanelMCPPumpColumn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 184, -1, -1));

        jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getStyle() | java.awt.Font.BOLD, jLabel10.getFont().getSize()-2));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("MCP 2.2");
        jLabel10.setToolTipText("");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 168, 52, -1));

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getStyle() | java.awt.Font.BOLD, jLabel11.getFont().getSize()-2));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MCP 2.2");
        jLabel11.setToolTipText("");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 168, 52, -1));

        controlPanelMCPPumpColumn11.setChornobylPrefix("Loop2#mcp3");
        add(controlPanelMCPPumpColumn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 184, -1, -1));

        controlPanelMCPPumpColumn12.setChornobylPrefix("Loop2#mcp4");
        add(controlPanelMCPPumpColumn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 184, 52, -1));

        jLabel12.setFont(jLabel12.getFont().deriveFont(jLabel12.getFont().getStyle() | java.awt.Font.BOLD, jLabel12.getFont().getSize()-2));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("MCP 2.4");
        jLabel12.setToolTipText("");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 168, 52, -1));

        jLabelCaptionDrain6.setFont(jLabelCaptionDrain6.getFont().deriveFont(jLabelCaptionDrain6.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain6.getFont().getSize()-2));
        jLabelCaptionDrain6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain6.setText("Pressure");
        jLabelCaptionDrain6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain6, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 8, 86, 14));

        setpointControl1.setComponent("LoopPressureSetpoint");
        add(setpointControl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoop1CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop1CloseActionPerformed
        controller.userAction(new ActionCommand("Loop1#Bypass", false));
    }//GEN-LAST:event_jButtonLoop1CloseActionPerformed

    private void jButtonLoop1OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop1OpenActionPerformed
        controller.userAction(new ActionCommand("Loop1#Bypass", true));
    }//GEN-LAST:event_jButtonLoop1OpenActionPerformed

    private void jButtonLoop2CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2CloseActionPerformed
        controller.userAction(new ActionCommand("Loop2#Bypass", false));
    }//GEN-LAST:event_jButtonLoop2CloseActionPerformed

    private void jButtonLoop2OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2OpenActionPerformed
        controller.userAction(new ActionCommand("Loop2#Bypass", true));
    }//GEN-LAST:event_jButtonLoop2OpenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop1Cooldown;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop1Level;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop1Pressure;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop1RecircFlow;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop1Temperature;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop2Cooldown;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop2Level1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop2Pressure1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop2RecircFlow;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop2Temperature;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump controlPanelMCPPumpColumn1;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump controlPanelMCPPumpColumn10;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump controlPanelMCPPumpColumn11;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump controlPanelMCPPumpColumn12;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump controlPanelMCPPumpColumn2;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump controlPanelMCPPumpColumn3;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump controlPanelMCPPumpColumn4;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetTrimmablePump controlPanelMCPPumpColumn9;
    private javax.swing.JButton jButtonLoop1Close;
    private javax.swing.JButton jButtonLoop1Open;
    private javax.swing.JButton jButtonLoop2Close;
    private javax.swing.JButton jButtonLoop2Open;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCaptionDrain5;
    private javax.swing.JLabel jLabelCaptionDrain6;
    private javax.swing.JLabel jLabelCaptionPassiveFlow2;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler2;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControl1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        controlPanelMCPPumpColumn1.updateComponent(evt);
        controlPanelMCPPumpColumn10.updateComponent(evt);
        controlPanelMCPPumpColumn11.updateComponent(evt);
        controlPanelMCPPumpColumn12.updateComponent(evt);
        controlPanelMCPPumpColumn2.updateComponent(evt);
        controlPanelMCPPumpColumn3.updateComponent(evt);
        controlPanelMCPPumpColumn4.updateComponent(evt);
        controlPanelMCPPumpColumn9.updateComponent(evt);
        setpointControl1.updateComponent(evt);
        
        switch (evt.getPropertyName()) {
            case "Loop1#Bypass_Pos":
                setValveButtons(jButtonLoop1Close, jButtonLoop1Open, 
                        evt.getNewValue());
                break;
            case "Loop2#Bypass_Pos":
                setValveButtons(jButtonLoop2Close, jButtonLoop2Open, 
                        evt.getNewValue());
                break;
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        switch (propertyName) {
            case "Loop1#ReactorOutFlow" ->
                chornobylGaugeLoop1RecircFlow.setChornobylValue((float) newValue);
            case "Loop1#DrumTemperature" ->
                chornobylGaugeLoop1Temperature.setChornobylValue((float) newValue);
            case "Loop1#DrumLevel" ->
                chornobylGaugeLoop1Level.setChornobylValue((float) newValue);
            case "Loop1#DrumPressure" ->
                chornobylGaugeLoop1Pressure.setChornobylValue((float) newValue);
            case "Loop1#McpCooldown" ->
                chornobylGaugeLoop1Cooldown.setChornobylValue((float) newValue);
            case "Loop2#ReactorOutFlow" ->
                chornobylGaugeLoop2RecircFlow.setChornobylValue((float) newValue);
            case "Loop2#DrumTemperature" ->
                chornobylGaugeLoop2Temperature.setChornobylValue((float) newValue);
            case "Loop2#DrumLevel" ->
                chornobylGaugeLoop2Level1.setChornobylValue((float) newValue);
            case "Loop2#DrumPressure" ->
                chornobylGaugeLoop2Pressure1.setChornobylValue((float) newValue);
            case "Loop2#McpCooldown" ->
                chornobylGaugeLoop2Cooldown.setChornobylValue((float) newValue);
                
        }
        setpointControl1.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
        controlPanelMCPPumpColumn1.updateComponent(propertyName, newValue);
        controlPanelMCPPumpColumn10.updateComponent(propertyName, newValue);
        controlPanelMCPPumpColumn11.updateComponent(propertyName, newValue);
        controlPanelMCPPumpColumn12.updateComponent(propertyName, newValue);
        controlPanelMCPPumpColumn2.updateComponent(propertyName, newValue);
        controlPanelMCPPumpColumn3.updateComponent(propertyName, newValue);
        controlPanelMCPPumpColumn4.updateComponent(propertyName, newValue);
        controlPanelMCPPumpColumn9.updateComponent(propertyName, newValue);
        setpointControl1.updateComponent(propertyName, newValue);
    }
}
