/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelDeaerators extends AbstractPanelWidget {

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);
        controlLoopValveDA1Flow.registerActionReceiver(controller);
        controlLoopValveDA2Flow.registerActionReceiver(controller);
        loopControlDA1Pressure.registerActionReceiver(controller);
        loopControlDA2Pressure.registerActionReceiver(controller);
        setpointControlDA1Level.registerActionReceiver(controller);
        setpointControlDA2Level.registerActionReceiver(controller);
        integralSwitchDrain1.registerActionReceiver(controller);
        integralSwitchDrain2.registerActionReceiver(controller);
        integralSwitchDromSDA2.registerActionReceiver(controller);
        integralSwitchFromSDA1.registerActionReceiver(controller);
        integralSwitchFromTDA1.registerActionReceiver(controller);
        integralSwitchFromTDA2.registerActionReceiver(controller);
        integralSwitchVent1.registerActionReceiver(controller);
        integralSwitchVent2.registerActionReceiver(controller);

    }

    /**
     * Creates new form PanelDeaerators
     */
    public PanelDeaerators() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chornobylGaugeDA1Level = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeDA2Level = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabelDA1Press1 = new javax.swing.JLabel();
        jLabelDA1FromT = new javax.swing.JLabel();
        jLabelDA1Level1 = new javax.swing.JLabel();
        jLabelDA1Level2 = new javax.swing.JLabel();
        jLabelDA2Level1 = new javax.swing.JLabel();
        jLabelDA2Level2 = new javax.swing.JLabel();
        loopControlDA2Pressure = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        loopControlDA1Pressure = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        jLabelDA1Press2 = new javax.swing.JLabel();
        jLabelDA2Press2 = new javax.swing.JLabel();
        integralSwitchFromTDA1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchFromTDA2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchFromSDA1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchDromSDA2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchDrain2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchDrain1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        jLabelDA2Press1 = new javax.swing.JLabel();
        jLabelDA2FromS = new javax.swing.JLabel();
        jLabelDA2FromT = new javax.swing.JLabel();
        jLabelDA1FromS = new javax.swing.JLabel();
        jLabelCaptionMainSteam = new javax.swing.JLabel();
        jLabelCaptionFromTurbine = new javax.swing.JLabel();
        jLabelVent1 = new javax.swing.JLabel();
        jLabelDrain = new javax.swing.JLabel();
        controlLoopValveDA1Flow = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopValveDA2Flow = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        integralSwitchVent1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchVent2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        jLabelVent2 = new javax.swing.JLabel();
        setpointControlDA2Level = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        setpointControlDA1Level = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        jLabelDA1Flow1 = new javax.swing.JLabel();
        jLabelDA1Flow2 = new javax.swing.JLabel();
        jLabelDA2Flow1 = new javax.swing.JLabel();
        jLabelDA2Flow2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(190, 340));
        setMinimumSize(new java.awt.Dimension(190, 340));
        setPreferredSize(new java.awt.Dimension(190, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chornobylGaugeDA1Level.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeDA1Level.setChornobylMaximum(220.0F);
        chornobylGaugeDA1Level.setChornobylMinimum(0.0F);
        chornobylGaugeDA1Level.setChornobylTicks(new float[] {50.0f, 100.0f, 150.0f, 200.0f});
        chornobylGaugeDA1Level.setChornobylValue(0.0F);
        add(chornobylGaugeDA1Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, -1, -1));

        chornobylGaugeDA2Level.setChornobylMaximum(220.0F);
        chornobylGaugeDA2Level.setChornobylMinimum(0.0F);
        chornobylGaugeDA2Level.setChornobylTicks(new float[] {50.0f, 100.0f, 150.0f, 200.0f});
        chornobylGaugeDA2Level.setChornobylValue(0.0F);
        add(chornobylGaugeDA2Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 34, -1, -1));

        jLabelDA1Press1.setFont(jLabelDA1Press1.getFont().deriveFont(jLabelDA1Press1.getFont().getSize()-2f));
        jLabelDA1Press1.setText("DA 1");
        add(jLabelDA1Press1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 208, 36, 14));

        jLabelDA1FromT.setFont(jLabelDA1FromT.getFont().deriveFont(jLabelDA1FromT.getFont().getSize()-2f));
        jLabelDA1FromT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDA1FromT.setText("DA 1");
        add(jLabelDA1FromT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 296, 36, 14));

        jLabelDA1Level1.setFont(jLabelDA1Level1.getFont().deriveFont(jLabelDA1Level1.getFont().getSize()-2f));
        jLabelDA1Level1.setText("DA 1");
        add(jLabelDA1Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 52, 14));

        jLabelDA1Level2.setFont(jLabelDA1Level2.getFont().deriveFont(jLabelDA1Level2.getFont().getSize()-2f));
        jLabelDA1Level2.setText("Level");
        add(jLabelDA1Level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 52, 14));

        jLabelDA2Level1.setFont(jLabelDA2Level1.getFont().deriveFont(jLabelDA2Level1.getFont().getSize()-2f));
        jLabelDA2Level1.setText("DA 2");
        add(jLabelDA2Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 52, 14));

        jLabelDA2Level2.setFont(jLabelDA2Level2.getFont().deriveFont(jLabelDA2Level2.getFont().getSize()-2f));
        jLabelDA2Level2.setText("Level");
        add(jLabelDA2Level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 52, 14));

        loopControlDA2Pressure.setControlComponent("Main2#SteamToDAValve");
        loopControlDA2Pressure.setFeedbackComponent("Deaerator2#Pressure");
        loopControlDA2Pressure.setMaxValue(10.0);
        loopControlDA2Pressure.setSetpoint(8.0);
        loopControlDA2Pressure.setSetpointComponent("Deaerator2#PressureSetpoint");
        add(loopControlDA2Pressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 242, -1, -1));

        loopControlDA1Pressure.setControlComponent("Main1#SteamToDAValve");
        loopControlDA1Pressure.setFeedbackComponent("Deaerator1#Pressure");
        loopControlDA1Pressure.setMaxValue(10.0);
        loopControlDA1Pressure.setSetpoint(8.0);
        loopControlDA1Pressure.setSetpointComponent("Deaerator1#PressureSetpoint");
        add(loopControlDA1Pressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 202, -1, -1));

        jLabelDA1Press2.setFont(jLabelDA1Press2.getFont().deriveFont(jLabelDA1Press2.getFont().getSize()-2f));
        jLabelDA1Press2.setText("Press.");
        add(jLabelDA1Press2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, 36, 14));

        jLabelDA2Press2.setFont(jLabelDA2Press2.getFont().deriveFont(jLabelDA2Press2.getFont().getSize()-2f));
        jLabelDA2Press2.setText("Press.");
        add(jLabelDA2Press2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 260, 36, 14));
        add(integralSwitchFromTDA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 310, -1, -1));
        add(integralSwitchFromTDA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 310, -1, -1));
        add(integralSwitchFromSDA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));
        add(integralSwitchDromSDA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 310, -1, -1));

        integralSwitchDrain2.setComponent("Deaerator2#Drain");
        add(integralSwitchDrain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 112, -1, -1));

        integralSwitchDrain1.setComponent("Deaerator1#Drain");
        add(integralSwitchDrain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 82, -1, -1));

        jLabelDA2Press1.setFont(jLabelDA2Press1.getFont().deriveFont(jLabelDA2Press1.getFont().getSize()-2f));
        jLabelDA2Press1.setText("DA 2");
        add(jLabelDA2Press1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 246, 36, 14));

        jLabelDA2FromS.setFont(jLabelDA2FromS.getFont().deriveFont(jLabelDA2FromS.getFont().getSize()-2f));
        jLabelDA2FromS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDA2FromS.setText("DA 2");
        add(jLabelDA2FromS, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 296, 36, 14));

        jLabelDA2FromT.setFont(jLabelDA2FromT.getFont().deriveFont(jLabelDA2FromT.getFont().getSize()-2f));
        jLabelDA2FromT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDA2FromT.setText("DA 2");
        add(jLabelDA2FromT, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 296, 36, 14));

        jLabelDA1FromS.setFont(jLabelDA1FromS.getFont().deriveFont(jLabelDA1FromS.getFont().getSize()-2f));
        jLabelDA1FromS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDA1FromS.setText("DA 1");
        add(jLabelDA1FromS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 296, 36, 14));

        jLabelCaptionMainSteam.setFont(jLabelCaptionMainSteam.getFont().deriveFont(jLabelCaptionMainSteam.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionMainSteam.getFont().getSize()-2));
        jLabelCaptionMainSteam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionMainSteam.setText("Main Steam");
        jLabelCaptionMainSteam.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionMainSteam.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionMainSteam.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionMainSteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 282, 88, 14));

        jLabelCaptionFromTurbine.setFont(jLabelCaptionFromTurbine.getFont().deriveFont(jLabelCaptionFromTurbine.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionFromTurbine.getFont().getSize()-2));
        jLabelCaptionFromTurbine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionFromTurbine.setText("From Turbine");
        jLabelCaptionFromTurbine.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionFromTurbine.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionFromTurbine.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionFromTurbine, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 282, 88, 14));

        jLabelVent1.setFont(jLabelVent1.getFont().deriveFont(jLabelVent1.getFont().getSize()-2f));
        jLabelVent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVent1.setText("Vent 1");
        add(jLabelVent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 150, 36, 14));

        jLabelDrain.setFont(jLabelDrain.getFont().deriveFont(jLabelDrain.getFont().getSize()-2f));
        jLabelDrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDrain.setText("Drain");
        add(jLabelDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 64, 36, 14));

        controlLoopValveDA1Flow.setComponent("Deaerator1#FlowValve");
        add(controlLoopValveDA1Flow, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 66, -1, -1));

        controlLoopValveDA2Flow.setComponent("Deaerator2#FlowValve");
        add(controlLoopValveDA2Flow, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 104, -1, -1));
        add(integralSwitchVent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 166, -1, -1));
        add(integralSwitchVent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 166, -1, -1));

        jLabelVent2.setFont(jLabelVent2.getFont().deriveFont(jLabelVent2.getFont().getSize()-2f));
        jLabelVent2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVent2.setText("Vent 2");
        add(jLabelVent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 150, 36, 14));

        setpointControlDA2Level.setComponent("Deaerator2#LevelSetpoint");
        setpointControlDA2Level.setFormat("%.0f");
        add(setpointControlDA2Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 172, -1, -1));

        setpointControlDA1Level.setComponent("Deaerator1#LevelSetpoint");
        setpointControlDA1Level.setFormat("%.0f");
        add(setpointControlDA1Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 146, -1, -1));

        jLabelDA1Flow1.setFont(jLabelDA1Flow1.getFont().deriveFont(jLabelDA1Flow1.getFont().getSize()-2f));
        jLabelDA1Flow1.setText("DA 1");
        add(jLabelDA1Flow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 38, 14));

        jLabelDA1Flow2.setFont(jLabelDA1Flow2.getFont().deriveFont(jLabelDA1Flow2.getFont().getSize()-2f));
        jLabelDA1Flow2.setText("Flow");
        add(jLabelDA1Flow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 84, 38, 14));

        jLabelDA2Flow1.setFont(jLabelDA2Flow1.getFont().deriveFont(jLabelDA2Flow1.getFont().getSize()-2f));
        jLabelDA2Flow1.setText("DA 2");
        add(jLabelDA2Flow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, 38, 14));

        jLabelDA2Flow2.setFont(jLabelDA2Flow2.getFont().deriveFont(jLabelDA2Flow2.getFont().getSize()-2f));
        jLabelDA2Flow2.setText("Flow");
        add(jLabelDA2Flow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, 38, 14));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeDA1Level;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeDA2Level;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveDA1Flow;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveDA2Flow;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchDrain1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchDrain2;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchDromSDA2;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchFromSDA1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchFromTDA1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchFromTDA2;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchVent1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchVent2;
    private javax.swing.JLabel jLabelCaptionFromTurbine;
    private javax.swing.JLabel jLabelCaptionMainSteam;
    private javax.swing.JLabel jLabelDA1Flow1;
    private javax.swing.JLabel jLabelDA1Flow2;
    private javax.swing.JLabel jLabelDA1FromS;
    private javax.swing.JLabel jLabelDA1FromT;
    private javax.swing.JLabel jLabelDA1Level1;
    private javax.swing.JLabel jLabelDA1Level2;
    private javax.swing.JLabel jLabelDA1Press1;
    private javax.swing.JLabel jLabelDA1Press2;
    private javax.swing.JLabel jLabelDA2Flow1;
    private javax.swing.JLabel jLabelDA2Flow2;
    private javax.swing.JLabel jLabelDA2FromS;
    private javax.swing.JLabel jLabelDA2FromT;
    private javax.swing.JLabel jLabelDA2Level1;
    private javax.swing.JLabel jLabelDA2Level2;
    private javax.swing.JLabel jLabelDA2Press1;
    private javax.swing.JLabel jLabelDA2Press2;
    private javax.swing.JLabel jLabelDrain;
    private javax.swing.JLabel jLabelVent1;
    private javax.swing.JLabel jLabelVent2;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop loopControlDA1Pressure;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop loopControlDA2Pressure;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControlDA1Level;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControlDA2Level;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        controlLoopValveDA1Flow.updateComponent(evt);
        controlLoopValveDA2Flow.updateComponent(evt);
        loopControlDA1Pressure.updateComponent(evt);
        loopControlDA2Pressure.updateComponent(evt);
        setpointControlDA1Level.updateComponent(evt);
        setpointControlDA2Level.updateComponent(evt);
        setpointControlDA1Level.updateComponent(evt);
        setpointControlDA2Level.updateComponent(evt);
        integralSwitchDrain1.updateComponent(evt);
        integralSwitchDrain2.updateComponent(evt);
        integralSwitchDromSDA2.updateComponent(evt);
        integralSwitchFromSDA1.updateComponent(evt);
        integralSwitchFromTDA1.updateComponent(evt);
        integralSwitchFromTDA2.updateComponent(evt);
        integralSwitchVent1.updateComponent(evt);
        integralSwitchVent2.updateComponent(evt);
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        switch (propertyName) {
            case "Deaerator1#Level" ->
                chornobylGaugeDA1Level.setChornobylValue((float) newValue);
            case "Deaerator2#Level" ->
                chornobylGaugeDA2Level.setChornobylValue((float) newValue);
        }
        loopControlDA1Pressure.updateComponent(propertyName, newValue);
        loopControlDA2Pressure.updateComponent(propertyName, newValue);
        setpointControlDA1Level.updateComponent(propertyName, newValue);
        setpointControlDA2Level.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
