/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelCondensation extends AbstractPanelWidget {

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);
        panelWidgetMakeupPump1.registerActionReceiver(controller);
        panelWidgetMakeupPump2.registerActionReceiver(controller);
        panelWidgetPumpHotwell1.registerActionReceiver(controller);
        panelWidgetPumpHotwell2.registerActionReceiver(controller);
        panelWidgetPumpHotwell3.registerActionReceiver(controller);
        panelWidgetPumpCondensate1.registerActionReceiver(controller);
        panelWidgetPumpCondensate2.registerActionReceiver(controller);
        panelWidgetPumpCondensate3.registerActionReceiver(controller);
        controlLoopHotwellFill.registerActionReceiver(controller);
        controlLoopHotwellDrain.registerActionReceiver(controller);
    }

    /**
     * Creates new form PanelCondensation
     */
    public PanelCondensation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWidgetPumpCondensate3 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPumpCondensate2 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPumpCondensate1 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPumpHotwell3 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPumpHotwell2 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPumpHotwell1 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        controlLoopHotwellFill = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        controlLoopHotwellDrain = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        jLabelDA1Press1 = new javax.swing.JLabel();
        jLabelDA1Press2 = new javax.swing.JLabel();
        jLabelDA1Press3 = new javax.swing.JLabel();
        jLabelDA1Press4 = new javax.swing.JLabel();
        integralSwitch1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitch2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitch3 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        jLabelFeed13 = new javax.swing.JLabel();
        jButtonFeed12Close = new javax.swing.JButton();
        jButtonFeed12Open = new javax.swing.JButton();
        jButtonFeed12Close1 = new javax.swing.JButton();
        jButtonFeed12Open1 = new javax.swing.JButton();
        jButtonFeed12Open2 = new javax.swing.JButton();
        jButtonFeed12Close2 = new javax.swing.JButton();
        jLabelFeed15 = new javax.swing.JLabel();
        jLabelFeed16 = new javax.swing.JLabel();
        jButtonFeed12Open3 = new javax.swing.JButton();
        jButtonFeed12Close3 = new javax.swing.JButton();
        jButtonFeed12Close4 = new javax.swing.JButton();
        jButtonFeed12Open4 = new javax.swing.JButton();
        jButtonFeed12Open5 = new javax.swing.JButton();
        jButtonFeed12Close5 = new javax.swing.JButton();
        jButtonFeed12Open6 = new javax.swing.JButton();
        jButtonFeed12Close6 = new javax.swing.JButton();
        jButtonFeed12Open7 = new javax.swing.JButton();
        jButtonFeed12Close7 = new javax.swing.JButton();
        jButtonFeed12Open8 = new javax.swing.JButton();
        jButtonFeed12Close8 = new javax.swing.JButton();
        jLabelFeed17 = new javax.swing.JLabel();
        jLabelFeed14 = new javax.swing.JLabel();
        jButtonFeed12Close9 = new javax.swing.JButton();
        jButtonFeed12Open9 = new javax.swing.JButton();
        jLabelCaptionPump11 = new javax.swing.JLabel();
        jLabelCaptionPump12 = new javax.swing.JLabel();
        jLabelCaptionPump13 = new javax.swing.JLabel();
        jButtonColdCondensateDrainClose = new javax.swing.JButton();
        jLabelColdCondensateDrain = new javax.swing.JLabel();
        jButtonColdCondensateDrainOpen = new javax.swing.JButton();
        jLabelCaptionPump14 = new javax.swing.JLabel();
        jLabelDA1Level1 = new javax.swing.JLabel();
        jLabelDA1Level2 = new javax.swing.JLabel();
        chornobylGaugeLevel = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        panelWidgetMakeupPump2 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetMakeupPump1 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        jButtonColdCondensateFillOpen = new javax.swing.JButton();
        jLabelColdCondensateFill = new javax.swing.JLabel();
        jButtonColdCondensateFillClose = new javax.swing.JButton();
        jLabelCaptionPump16 = new javax.swing.JLabel();
        jLabelCaptionPump17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        chornobylGaugeHotwellLevel = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chornobylGaugeCondensateFlow = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabelCaptionPump18 = new javax.swing.JLabel();
        jLabelCaptionPump19 = new javax.swing.JLabel();
        jLabelCaptionPump20 = new javax.swing.JLabel();
        jLabelCaptionPump21 = new javax.swing.JLabel();
        jLabelCaptionPump22 = new javax.swing.JLabel();
        jLabelCaptionPump23 = new javax.swing.JLabel();
        jLabelCaptionPump24 = new javax.swing.JLabel();
        jLabelCaptionPump25 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(580, 340));
        setMinimumSize(new java.awt.Dimension(580, 340));
        setPreferredSize(new java.awt.Dimension(580, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelWidgetPumpCondensate3.setChornobylPrefix("Condensation3#CondensatePump");
        add(panelWidgetPumpCondensate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 222, -1, -1));

        panelWidgetPumpCondensate2.setChornobylPrefix("Condensation2#CondensatePump");
        add(panelWidgetPumpCondensate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 222, -1, -1));

        panelWidgetPumpCondensate1.setChornobylPrefix("Condensation1#CondensatePump");
        add(panelWidgetPumpCondensate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 222, -1, -1));

        panelWidgetPumpHotwell3.setChornobylPrefix("Condensation3#HotwellPump");
        add(panelWidgetPumpHotwell3, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 72, -1, -1));

        panelWidgetPumpHotwell2.setChornobylPrefix("Condensation2#HotwellPump");
        add(panelWidgetPumpHotwell2, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 72, -1, -1));

        panelWidgetPumpHotwell1.setChornobylPrefix("Condensation1#HotwellPump");
        add(panelWidgetPumpHotwell1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 72, -1, -1));

        controlLoopHotwellFill.setControlComponent("Hotwell#FillValve");
        controlLoopHotwellFill.setFeedbackComponent("Hotwell#Level");
        controlLoopHotwellFill.setSetpointComponent("Hotwell#LowerSetpoint");
        add(controlLoopHotwellFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 46, -1, -1));

        controlLoopHotwellDrain.setControlComponent("Hotwell#DrainValve");
        controlLoopHotwellDrain.setFeedbackComponent("Hotwell#Level");
        controlLoopHotwellDrain.setSetpointComponent("Hotwell#UpperSetpoint");
        add(controlLoopHotwellDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 90, -1, -1));

        jLabelDA1Press1.setFont(jLabelDA1Press1.getFont().deriveFont(jLabelDA1Press1.getFont().getSize()-2f));
        jLabelDA1Press1.setText("Hotwell");
        add(jLabelDA1Press1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 96, 50, 14));

        jLabelDA1Press2.setFont(jLabelDA1Press2.getFont().deriveFont(jLabelDA1Press2.getFont().getSize()-2f));
        jLabelDA1Press2.setText("Drain");
        add(jLabelDA1Press2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 110, 50, 14));

        jLabelDA1Press3.setFont(jLabelDA1Press3.getFont().deriveFont(jLabelDA1Press3.getFont().getSize()-2f));
        jLabelDA1Press3.setText("Fill");
        add(jLabelDA1Press3, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 68, 50, 14));

        jLabelDA1Press4.setFont(jLabelDA1Press4.getFont().deriveFont(jLabelDA1Press4.getFont().getSize()-2f));
        jLabelDA1Press4.setText("Hotwell");
        add(jLabelDA1Press4, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 54, 50, 14));
        add(integralSwitch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 252, -1, -1));
        add(integralSwitch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 252, -1, -1));
        add(integralSwitch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 252, -1, -1));

        jLabelFeed13.setFont(jLabelFeed13.getFont().deriveFont(jLabelFeed13.getFont().getSize()-2f));
        jLabelFeed13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFeed13.setText("Suction");
        jLabelFeed13.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelFeed13.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelFeed13.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelFeed13, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 226, 40, 14));

        jButtonFeed12Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed12Close.setText("C");
        jButtonFeed12Close.setToolTipText("");
        jButtonFeed12Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12CloseActionPerformed(evt);
            }
        });
        add(jButtonFeed12Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 224, 20, 20));

        jButtonFeed12Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed12Open.setText("O");
        jButtonFeed12Open.setToolTipText("");
        jButtonFeed12Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12OpenActionPerformed(evt);
            }
        });
        add(jButtonFeed12Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 224, 20, 20));

        jButtonFeed12Close1.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed12Close1.setText("C");
        jButtonFeed12Close1.setToolTipText("");
        jButtonFeed12Close1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Close1ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 284, 20, 20));

        jButtonFeed12Open1.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed12Open1.setText("O");
        jButtonFeed12Open1.setToolTipText("");
        jButtonFeed12Open1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Open1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Open1ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Open1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 284, 20, 20));

        jButtonFeed12Open2.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed12Open2.setText("O");
        jButtonFeed12Open2.setToolTipText("");
        jButtonFeed12Open2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Open2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Open2ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Open2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 284, 20, 20));

        jButtonFeed12Close2.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed12Close2.setText("C");
        jButtonFeed12Close2.setToolTipText("");
        jButtonFeed12Close2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Close2ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 284, 20, 20));

        jLabelFeed15.setFont(jLabelFeed15.getFont().deriveFont(jLabelFeed15.getFont().getSize()-2f));
        jLabelFeed15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFeed15.setText("Inlet");
        jLabelFeed15.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelFeed15.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelFeed15.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelFeed15, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 286, 40, 14));

        jLabelFeed16.setFont(jLabelFeed16.getFont().deriveFont(jLabelFeed16.getFont().getSize()-2f));
        jLabelFeed16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFeed16.setText("Steam");
        jLabelFeed16.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelFeed16.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelFeed16.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelFeed16, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 260, 40, 14));

        jButtonFeed12Open3.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed12Open3.setText("O");
        jButtonFeed12Open3.setToolTipText("");
        jButtonFeed12Open3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Open3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Open3ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Open3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 284, 20, 20));

        jButtonFeed12Close3.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed12Close3.setText("C");
        jButtonFeed12Close3.setToolTipText("");
        jButtonFeed12Close3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Close3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Close3ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 284, 20, 20));

        jButtonFeed12Close4.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed12Close4.setText("C");
        jButtonFeed12Close4.setToolTipText("");
        jButtonFeed12Close4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Close4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Close4ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Close4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 310, 20, 20));

        jButtonFeed12Open4.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed12Open4.setText("O");
        jButtonFeed12Open4.setToolTipText("");
        jButtonFeed12Open4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Open4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Open4ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Open4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 310, 20, 20));

        jButtonFeed12Open5.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed12Open5.setText("O");
        jButtonFeed12Open5.setToolTipText("");
        jButtonFeed12Open5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Open5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Open5ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Open5, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 310, 20, 20));

        jButtonFeed12Close5.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed12Close5.setText("C");
        jButtonFeed12Close5.setToolTipText("");
        jButtonFeed12Close5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Close5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Close5ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Close5, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 310, 20, 20));

        jButtonFeed12Open6.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed12Open6.setText("O");
        jButtonFeed12Open6.setToolTipText("");
        jButtonFeed12Open6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Open6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Open6ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Open6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 20, 20));

        jButtonFeed12Close6.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed12Close6.setText("C");
        jButtonFeed12Close6.setToolTipText("");
        jButtonFeed12Close6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Close6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Close6ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Close6, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 310, 20, 20));

        jButtonFeed12Open7.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed12Open7.setText("O");
        jButtonFeed12Open7.setToolTipText("");
        jButtonFeed12Open7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Open7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Open7ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Open7, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 224, 20, 20));

        jButtonFeed12Close7.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed12Close7.setText("C");
        jButtonFeed12Close7.setToolTipText("");
        jButtonFeed12Close7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Close7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Close7ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Close7, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 224, 20, 20));

        jButtonFeed12Open8.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed12Open8.setText("O");
        jButtonFeed12Open8.setToolTipText("");
        jButtonFeed12Open8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Open8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Open8ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Open8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 224, 20, 20));

        jButtonFeed12Close8.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed12Close8.setText("C");
        jButtonFeed12Close8.setToolTipText("");
        jButtonFeed12Close8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Close8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Close8ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Close8, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 224, 20, 20));

        jLabelFeed17.setFont(jLabelFeed17.getFont().deriveFont(jLabelFeed17.getFont().getSize()-2f));
        jLabelFeed17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFeed17.setText("Outliet");
        jLabelFeed17.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelFeed17.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelFeed17.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelFeed17, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 312, 40, 14));

        jLabelFeed14.setFont(jLabelFeed14.getFont().deriveFont(jLabelFeed14.getFont().getSize()-2f));
        jLabelFeed14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFeed14.setText("Bypass");
        jLabelFeed14.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelFeed14.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelFeed14.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelFeed14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 164, 52, 14));

        jButtonFeed12Close9.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed12Close9.setText("C");
        jButtonFeed12Close9.setToolTipText("");
        jButtonFeed12Close9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Close9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Close9ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Close9, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 178, 20, 20));

        jButtonFeed12Open9.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed12Open9.setText("O");
        jButtonFeed12Open9.setToolTipText("");
        jButtonFeed12Open9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Open9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12Open9ActionPerformed(evt);
            }
        });
        add(jButtonFeed12Open9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 178, 20, 20));

        jLabelCaptionPump11.setFont(jLabelCaptionPump11.getFont().deriveFont(jLabelCaptionPump11.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump11.getFont().getSize()-2));
        jLabelCaptionPump11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump11.setText("Ejector 3");
        jLabelCaptionPump11.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump11.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump11.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump11, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 206, 64, 14));

        jLabelCaptionPump12.setFont(jLabelCaptionPump12.getFont().deriveFont(jLabelCaptionPump12.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump12.getFont().getSize()-2));
        jLabelCaptionPump12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump12.setText("Ejector 1");
        jLabelCaptionPump12.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump12.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump12.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump12, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 206, 64, 14));

        jLabelCaptionPump13.setFont(jLabelCaptionPump13.getFont().deriveFont(jLabelCaptionPump13.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump13.getFont().getSize()-2));
        jLabelCaptionPump13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump13.setText("Ejector2");
        jLabelCaptionPump13.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump13.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump13.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 206, 64, 14));

        jButtonColdCondensateDrainClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonColdCondensateDrainClose.setText("C");
        jButtonColdCondensateDrainClose.setToolTipText("");
        jButtonColdCondensateDrainClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonColdCondensateDrainClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColdCondensateDrainCloseActionPerformed(evt);
            }
        });
        add(jButtonColdCondensateDrainClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 20, 20));

        jLabelColdCondensateDrain.setFont(jLabelColdCondensateDrain.getFont().deriveFont(jLabelColdCondensateDrain.getFont().getSize()-2f));
        jLabelColdCondensateDrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelColdCondensateDrain.setText("Drain");
        jLabelColdCondensateDrain.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelColdCondensateDrain.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelColdCondensateDrain.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelColdCondensateDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 96, 52, 14));

        jButtonColdCondensateDrainOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonColdCondensateDrainOpen.setText("O");
        jButtonColdCondensateDrainOpen.setToolTipText("");
        jButtonColdCondensateDrainOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonColdCondensateDrainOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColdCondensateDrainOpenActionPerformed(evt);
            }
        });
        add(jButtonColdCondensateDrainOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 110, 20, 20));

        jLabelCaptionPump14.setFont(jLabelCaptionPump14.getFont().deriveFont(jLabelCaptionPump14.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump14.getFont().getSize()-2));
        jLabelCaptionPump14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump14.setText("Pump 2");
        jLabelCaptionPump14.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump14.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump14.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump14, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 50, 48, 14));

        jLabelDA1Level1.setFont(jLabelDA1Level1.getFont().deriveFont(jLabelDA1Level1.getFont().getSize()-2f));
        jLabelDA1Level1.setText("Cold Cnd.");
        add(jLabelDA1Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 52, 14));

        jLabelDA1Level2.setFont(jLabelDA1Level2.getFont().deriveFont(jLabelDA1Level2.getFont().getSize()-2f));
        jLabelDA1Level2.setText("Level");
        add(jLabelDA1Level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 52, 14));

        chornobylGaugeLevel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeLevel.setChornobylMaximum(10.0F);
        chornobylGaugeLevel.setChornobylMinimum(0.0F);
        chornobylGaugeLevel.setChornobylTicks(new float[] {0.0f, 2.0f, 4.0f, 6.0f, 8.0f, 10.0f});
        chornobylGaugeLevel.setChornobylUnitText("m");
        chornobylGaugeLevel.setChornobylValue(0.0F);
        add(chornobylGaugeLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, -1, -1));

        panelWidgetMakeupPump2.setChornobylPrefix("Makeup2#Pumps");
        add(panelWidgetMakeupPump2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 68, -1, -1));

        panelWidgetMakeupPump1.setChornobylPrefix("Makeup1#Pumps");
        add(panelWidgetMakeupPump1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 68, -1, -1));

        jButtonColdCondensateFillOpen.setBackground(new java.awt.Color(0, 128, 0));
        jButtonColdCondensateFillOpen.setText("C");
        jButtonColdCondensateFillOpen.setToolTipText("");
        jButtonColdCondensateFillOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonColdCondensateFillOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColdCondensateFillOpenActionPerformed(evt);
            }
        });
        add(jButtonColdCondensateFillOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 74, 20, 20));

        jLabelColdCondensateFill.setFont(jLabelColdCondensateFill.getFont().deriveFont(jLabelColdCondensateFill.getFont().getSize()-2f));
        jLabelColdCondensateFill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelColdCondensateFill.setText("Fill");
        jLabelColdCondensateFill.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelColdCondensateFill.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelColdCondensateFill.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelColdCondensateFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 60, 52, 14));

        jButtonColdCondensateFillClose.setBackground(new java.awt.Color(128, 0, 0));
        jButtonColdCondensateFillClose.setText("O");
        jButtonColdCondensateFillClose.setToolTipText("");
        jButtonColdCondensateFillClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonColdCondensateFillClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColdCondensateFillCloseActionPerformed(evt);
            }
        });
        add(jButtonColdCondensateFillClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 74, 20, 20));

        jLabelCaptionPump16.setFont(jLabelCaptionPump16.getFont().deriveFont(jLabelCaptionPump16.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump16.getFont().getSize()-2));
        jLabelCaptionPump16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump16.setText("Pump 3");
        jLabelCaptionPump16.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump16.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump16.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump16, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 56, 54, 14));

        jLabelCaptionPump17.setFont(jLabelCaptionPump17.getFont().deriveFont(jLabelCaptionPump17.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump17.getFont().getSize()-2));
        jLabelCaptionPump17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump17.setText("Makeup");
        jLabelCaptionPump17.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump17.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump17.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump17, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 34, 54, 14));

        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getSize()-2f));
        jLabel24.setText("Hotwell");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 4, 52, 14));

        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getSize()-2f));
        jLabel18.setText("Level");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 16, 52, 14));

        chornobylGaugeHotwellLevel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeHotwellLevel.setChornobylMaximum(120.0F);
        chornobylGaugeHotwellLevel.setChornobylMinimum(0.0F);
        chornobylGaugeHotwellLevel.setChornobylTicks(new float[] {0.0f, 30.0f, 60.0f, 90.0f, 120.0f});
        chornobylGaugeHotwellLevel.setChornobylValue(0.0F);
        add(chornobylGaugeHotwellLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 4, -1, -1));

        jLabel25.setFont(jLabel25.getFont().deriveFont(jLabel25.getFont().getSize()-2f));
        jLabel25.setText("Cond.");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 4, 52, 14));

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getSize()-2f));
        jLabel19.setText("Flow");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 16, 52, 14));

        chornobylGaugeCondensateFlow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeCondensateFlow.setChornobylMaximum(4000.0F);
        chornobylGaugeCondensateFlow.setChornobylMinimum(0.0F);
        chornobylGaugeCondensateFlow.setChornobylTicks(new float[] {0.0f, 2000.0f, 3500.0f});
        chornobylGaugeCondensateFlow.setChornobylUnitText("kg/s");
        add(chornobylGaugeCondensateFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 4, -1, -1));

        jLabelCaptionPump18.setFont(jLabelCaptionPump18.getFont().deriveFont(jLabelCaptionPump18.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump18.getFont().getSize()-2));
        jLabelCaptionPump18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump18.setText("Pump 1");
        jLabelCaptionPump18.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump18.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump18.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump18, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 50, 54, 14));

        jLabelCaptionPump19.setFont(jLabelCaptionPump19.getFont().deriveFont(jLabelCaptionPump19.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump19.getFont().getSize()-2));
        jLabelCaptionPump19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump19.setText("Pump 1");
        jLabelCaptionPump19.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump19.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump19.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump19, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 56, 54, 14));

        jLabelCaptionPump20.setFont(jLabelCaptionPump20.getFont().deriveFont(jLabelCaptionPump20.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump20.getFont().getSize()-2));
        jLabelCaptionPump20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump20.setText("Pump 2");
        jLabelCaptionPump20.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump20.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump20.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump20, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 56, 54, 14));

        jLabelCaptionPump21.setFont(jLabelCaptionPump21.getFont().deriveFont(jLabelCaptionPump21.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump21.getFont().getSize()-2));
        jLabelCaptionPump21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump21.setText("Condensate Pumps");
        jLabelCaptionPump21.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump21.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump21.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 192, 132, 14));

        jLabelCaptionPump22.setFont(jLabelCaptionPump22.getFont().deriveFont(jLabelCaptionPump22.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump22.getFont().getSize()-2));
        jLabelCaptionPump22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump22.setText("Pump 2");
        jLabelCaptionPump22.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump22.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump22.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump22, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 208, 54, 14));

        jLabelCaptionPump23.setFont(jLabelCaptionPump23.getFont().deriveFont(jLabelCaptionPump23.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump23.getFont().getSize()-2));
        jLabelCaptionPump23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump23.setText("Pump 3");
        jLabelCaptionPump23.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump23.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump23.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump23, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 208, 54, 14));

        jLabelCaptionPump24.setFont(jLabelCaptionPump24.getFont().deriveFont(jLabelCaptionPump24.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump24.getFont().getSize()-2));
        jLabelCaptionPump24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump24.setText("Pump 1");
        jLabelCaptionPump24.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump24.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump24.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump24, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 208, 54, 14));

        jLabelCaptionPump25.setFont(jLabelCaptionPump25.getFont().deriveFont(jLabelCaptionPump25.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump25.getFont().getSize()-2));
        jLabelCaptionPump25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump25.setText("Hotwell Pumps");
        jLabelCaptionPump25.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump25.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump25.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump25, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 40, 132, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFeed12CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12CloseActionPerformed

    }//GEN-LAST:event_jButtonFeed12CloseActionPerformed

    private void jButtonFeed12OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12OpenActionPerformed

    }//GEN-LAST:event_jButtonFeed12OpenActionPerformed

    private void jButtonFeed12Close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Close1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Close1ActionPerformed

    private void jButtonFeed12Open1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Open1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Open1ActionPerformed

    private void jButtonFeed12Open2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Open2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Open2ActionPerformed

    private void jButtonFeed12Close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Close2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Close2ActionPerformed

    private void jButtonFeed12Open3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Open3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Open3ActionPerformed

    private void jButtonFeed12Close3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Close3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Close3ActionPerformed

    private void jButtonFeed12Close4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Close4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Close4ActionPerformed

    private void jButtonFeed12Open4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Open4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Open4ActionPerformed

    private void jButtonFeed12Open5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Open5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Open5ActionPerformed

    private void jButtonFeed12Close5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Close5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Close5ActionPerformed

    private void jButtonFeed12Open6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Open6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Open6ActionPerformed

    private void jButtonFeed12Close6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Close6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Close6ActionPerformed

    private void jButtonFeed12Open7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Open7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Open7ActionPerformed

    private void jButtonFeed12Close7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Close7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Close7ActionPerformed

    private void jButtonFeed12Open8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Open8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Open8ActionPerformed

    private void jButtonFeed12Close8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Close8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Close8ActionPerformed

    private void jButtonFeed12Close9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Close9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Close9ActionPerformed

    private void jButtonFeed12Open9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12Open9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFeed12Open9ActionPerformed

    private void jButtonColdCondensateDrainCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColdCondensateDrainCloseActionPerformed

    }//GEN-LAST:event_jButtonColdCondensateDrainCloseActionPerformed

    private void jButtonColdCondensateDrainOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColdCondensateDrainOpenActionPerformed

    }//GEN-LAST:event_jButtonColdCondensateDrainOpenActionPerformed

    private void jButtonColdCondensateFillOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColdCondensateFillOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonColdCondensateFillOpenActionPerformed

    private void jButtonColdCondensateFillCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColdCondensateFillCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonColdCondensateFillCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeCondensateFlow;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeHotwellLevel;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLevel;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop controlLoopHotwellDrain;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop controlLoopHotwellFill;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch2;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch3;
    private javax.swing.JButton jButtonColdCondensateDrainClose;
    private javax.swing.JButton jButtonColdCondensateDrainOpen;
    private javax.swing.JButton jButtonColdCondensateFillClose;
    private javax.swing.JButton jButtonColdCondensateFillOpen;
    private javax.swing.JButton jButtonFeed12Close;
    private javax.swing.JButton jButtonFeed12Close1;
    private javax.swing.JButton jButtonFeed12Close2;
    private javax.swing.JButton jButtonFeed12Close3;
    private javax.swing.JButton jButtonFeed12Close4;
    private javax.swing.JButton jButtonFeed12Close5;
    private javax.swing.JButton jButtonFeed12Close6;
    private javax.swing.JButton jButtonFeed12Close7;
    private javax.swing.JButton jButtonFeed12Close8;
    private javax.swing.JButton jButtonFeed12Close9;
    private javax.swing.JButton jButtonFeed12Open;
    private javax.swing.JButton jButtonFeed12Open1;
    private javax.swing.JButton jButtonFeed12Open2;
    private javax.swing.JButton jButtonFeed12Open3;
    private javax.swing.JButton jButtonFeed12Open4;
    private javax.swing.JButton jButtonFeed12Open5;
    private javax.swing.JButton jButtonFeed12Open6;
    private javax.swing.JButton jButtonFeed12Open7;
    private javax.swing.JButton jButtonFeed12Open8;
    private javax.swing.JButton jButtonFeed12Open9;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabelCaptionPump11;
    private javax.swing.JLabel jLabelCaptionPump12;
    private javax.swing.JLabel jLabelCaptionPump13;
    private javax.swing.JLabel jLabelCaptionPump14;
    private javax.swing.JLabel jLabelCaptionPump16;
    private javax.swing.JLabel jLabelCaptionPump17;
    private javax.swing.JLabel jLabelCaptionPump18;
    private javax.swing.JLabel jLabelCaptionPump19;
    private javax.swing.JLabel jLabelCaptionPump20;
    private javax.swing.JLabel jLabelCaptionPump21;
    private javax.swing.JLabel jLabelCaptionPump22;
    private javax.swing.JLabel jLabelCaptionPump23;
    private javax.swing.JLabel jLabelCaptionPump24;
    private javax.swing.JLabel jLabelCaptionPump25;
    private javax.swing.JLabel jLabelColdCondensateDrain;
    private javax.swing.JLabel jLabelColdCondensateFill;
    private javax.swing.JLabel jLabelDA1Level1;
    private javax.swing.JLabel jLabelDA1Level2;
    private javax.swing.JLabel jLabelDA1Press1;
    private javax.swing.JLabel jLabelDA1Press2;
    private javax.swing.JLabel jLabelDA1Press3;
    private javax.swing.JLabel jLabelDA1Press4;
    private javax.swing.JLabel jLabelFeed13;
    private javax.swing.JLabel jLabelFeed14;
    private javax.swing.JLabel jLabelFeed15;
    private javax.swing.JLabel jLabelFeed16;
    private javax.swing.JLabel jLabelFeed17;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetMakeupPump1;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetMakeupPump2;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpCondensate1;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpCondensate2;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpCondensate3;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpHotwell1;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpHotwell2;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPumpHotwell3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        panelWidgetMakeupPump1.updateComponent(evt);
        panelWidgetMakeupPump2.updateComponent(evt);
        panelWidgetPumpHotwell1.updateComponent(evt);
        panelWidgetPumpHotwell2.updateComponent(evt);
        panelWidgetPumpHotwell3.updateComponent(evt);
        panelWidgetPumpCondensate1.updateComponent(evt);
        panelWidgetPumpCondensate2.updateComponent(evt);
        panelWidgetPumpCondensate3.updateComponent(evt);
        controlLoopHotwellFill.updateComponent(evt);
        controlLoopHotwellDrain.updateComponent(evt);
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        switch (propertyName) {
            case "MakeupStorage#Level" ->
                chornobylGaugeLevel.setChornobylValue((float) newValue);
            case "Hotwell#Level" ->
                chornobylGaugeHotwellLevel.setChornobylValue((float) newValue);
        }
        controlLoopHotwellFill.updateComponent(propertyName, newValue);
        controlLoopHotwellDrain.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
