/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelTurbineAux extends AbstractPanelWidget
        implements UpdateReceiver {

    /**
     * Creates new form PanelTurbineAux
     */
    public PanelTurbineAux() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButtonPump = new javax.swing.JToggleButton();
        lightBulbReady = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jToggleButtonPump1 = new javax.swing.JToggleButton();
        lightBulbReady1 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService1 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jToggleButtonPump2 = new javax.swing.JToggleButton();
        lightBulbReady2 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService2 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jLabelCaptionSuperheaterControl5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp4 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabelCaptionSuperheaterControl6 = new javax.swing.JLabel();
        jLabelCaptionLPShut5 = new javax.swing.JLabel();
        jLabelCaptionLPShut6 = new javax.swing.JLabel();
        jToggleButtonPump4 = new javax.swing.JToggleButton();
        lightBulbReady4 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService4 = new com.hartrusion.rbmksim.gui.elements.LightBulb();

        setMinimumSize(new java.awt.Dimension(208, 130));
        setPreferredSize(new java.awt.Dimension(208, 130));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButtonPump.setText("←");
        jToggleButtonPump.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPumpActionPerformed(evt);
            }
        });
        add(jToggleButtonPump, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 96, 20, 20));

        lightBulbReady.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 88, -1, -1));

        lightBulbInService.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 88, -1, -1));

        jToggleButtonPump1.setText("←");
        jToggleButtonPump1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPump1ActionPerformed(evt);
            }
        });
        add(jToggleButtonPump1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 58, 20, 20));

        lightBulbReady1.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        lightBulbInService1.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jToggleButtonPump2.setText("←");
        jToggleButtonPump2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPump2ActionPerformed(evt);
            }
        });
        add(jToggleButtonPump2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 58, 20, 20));

        lightBulbReady2.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 50, -1, -1));

        lightBulbInService2.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 50, -1, -1));

        jLabelCaptionSuperheaterControl5.setFont(jLabelCaptionSuperheaterControl5.getFont().deriveFont(jLabelCaptionSuperheaterControl5.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl5.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl5.setText("Hydraulic");
        jLabelCaptionSuperheaterControl5.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 98, -1, 14));

        jLabel32.setFont(jLabel32.getFont().deriveFont(jLabel32.getFont().getSize()-2f));
        jLabel32.setText("Oil");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 10, 32, 14));

        jLabel33.setFont(jLabel33.getFont().deriveFont(jLabel33.getFont().getSize()-2f));
        jLabel33.setText("press");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 22, 32, 14));

        chornobylGaugeFeed2Temp4.setChornobylMaximum(10.0F);
        chornobylGaugeFeed2Temp4.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Temp4.setChornobylTicks(new float[] {0.0f, 2.0f, 4.0f, 6.0f, 8.0f, 10.0f});
        chornobylGaugeFeed2Temp4.setChornobylUnitText("bar");
        chornobylGaugeFeed2Temp4.setChornobylValue(0.0F);
        add(chornobylGaugeFeed2Temp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 10, -1, -1));

        jLabelCaptionSuperheaterControl6.setFont(jLabelCaptionSuperheaterControl6.getFont().deriveFont(jLabelCaptionSuperheaterControl6.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl6.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl6.setText("Aux lube oil");
        jLabelCaptionSuperheaterControl6.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 62, 68, 14));

        jLabelCaptionLPShut5.setFont(jLabelCaptionLPShut5.getFont().deriveFont(jLabelCaptionLPShut5.getFont().getSize()-2f));
        jLabelCaptionLPShut5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut5.setText("Turning");
        jLabelCaptionLPShut5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 51, 14));

        jLabelCaptionLPShut6.setFont(jLabelCaptionLPShut6.getFont().deriveFont(jLabelCaptionLPShut6.getFont().getSize()-2f));
        jLabelCaptionLPShut6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut6.setText("Gear");
        jLabelCaptionLPShut6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 51, 14));

        jToggleButtonPump4.setText("←");
        jToggleButtonPump4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPump4ActionPerformed(evt);
            }
        });
        add(jToggleButtonPump4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 92, 20, 20));

        lightBulbReady4.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 84, -1, -1));

        lightBulbInService4.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 84, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonPumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPumpActionPerformed

    }//GEN-LAST:event_jToggleButtonPumpActionPerformed

    private void jToggleButtonPump1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPump1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPump1ActionPerformed

    private void jToggleButtonPump2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPump2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPump2ActionPerformed

    private void jToggleButtonPump4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPump4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPump4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp4;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabelCaptionLPShut5;
    private javax.swing.JLabel jLabelCaptionLPShut6;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl5;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl6;
    private javax.swing.JToggleButton jToggleButtonPump;
    private javax.swing.JToggleButton jToggleButtonPump1;
    private javax.swing.JToggleButton jToggleButtonPump2;
    private javax.swing.JToggleButton jToggleButtonPump4;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService1;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService2;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService4;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady1;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady2;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
        
    }
}
