/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelAuxCondenser extends AbstractPanelWidget
        implements UpdateReceiver {

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);
        // Make action receiver interface from controller available to elements
        // of this Panel so they can send their actions to it directly.
        controlLoopCondLevel1.registerActionReceiver(controller);
        controlLoopCondLevel2.registerActionReceiver(controller);
        integralSwitchToHotwell.registerActionReceiver(controller);
        integralSwitchCoolant1.registerActionReceiver(controller);
        integralSwitchCoolant2.registerActionReceiver(controller);
        integralSwitch1.registerActionReceiver(controller);
        integralSwitch2.registerActionReceiver(controller);
        integralSwitchToDrain.registerActionReceiver(controller);
        panelCondensatePump1.registerActionReceiver(controller);
        panelCondensatePump2.registerActionReceiver(controller);
    }

    /**
     * Creates new form PanelInternalLoad
     */
    public PanelAuxCondenser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCondensatePump2 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetSmallPump();
        panelCondensatePump1 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetSmallPump();
        jButtonBypassClose = new javax.swing.JButton();
        jButtonBypassOpen = new javax.swing.JButton();
        integralSwitchToHotwell = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchToDrain = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchCoolant1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchCoolant2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        jLabelCaptionDrain = new javax.swing.JLabel();
        jLabelCaptionHotwell = new javax.swing.JLabel();
        jLabelCaptionBypass = new javax.swing.JLabel();
        jLabelCaptionSteamIn = new javax.swing.JLabel();
        controlLoopCondLevel1 = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        controlLoopCondLevel2 = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        chornobylGaugeCondTemperature = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabelCaptionGaugeNeutronRate2 = new javax.swing.JLabel();
        jLabelFeed20 = new javax.swing.JLabel();
        jLabelCaptionPump13 = new javax.swing.JLabel();
        jLabelDA1Press1 = new javax.swing.JLabel();
        jLabelDA1Press2 = new javax.swing.JLabel();
        jLabelDA1Press3 = new javax.swing.JLabel();
        jLabelDA1Press4 = new javax.swing.JLabel();
        jLabelCaptionGaugeNeutronRate3 = new javax.swing.JLabel();
        chornobylGaugeFlow1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chornobylGaugeFlow2 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        integralSwitch1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitch2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        jTogglePressureControl1 = new javax.swing.JToggleButton();
        jToggleButtonGlobalEnable1 = new javax.swing.JToggleButton();
        jLabelCaptionSteamIn1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(190, 340));
        setMinimumSize(new java.awt.Dimension(190, 340));
        setPreferredSize(new java.awt.Dimension(190, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCondensatePump2.setChornobylPrefix("AuxCond2#CondPumps");
        add(panelCondensatePump2, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 266, -1, -1));

        panelCondensatePump1.setChornobylPrefix("AuxCond1#CondPumps");
        add(panelCondensatePump1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 194, -1, -1));

        jButtonBypassClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonBypassClose.setText("C");
        jButtonBypassClose.setToolTipText("");
        jButtonBypassClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonBypassClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBypassCloseActionPerformed(evt);
            }
        });
        add(jButtonBypassClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 218, 20, 20));

        jButtonBypassOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonBypassOpen.setText("O");
        jButtonBypassOpen.setToolTipText("");
        jButtonBypassOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonBypassOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBypassOpenActionPerformed(evt);
            }
        });
        add(jButtonBypassOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 218, 20, 20));

        integralSwitchToHotwell.setComponent("AuxCond#ToHotwell");
        integralSwitchToHotwell.setToolTipText("Condensate to Hotwell");
        add(integralSwitchToHotwell, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 262, -1, -1));

        integralSwitchToDrain.setComponent("AuxCond#ToDrain");
        integralSwitchToDrain.setToolTipText("Condensate to clean condensate container");
        add(integralSwitchToDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 308, -1, -1));

        integralSwitchCoolant1.setComponent("AuxCond1#CoolantValve");
        integralSwitchCoolant1.setToolTipText("Condeser 1 Cooland Flow");
        add(integralSwitchCoolant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 308, -1, -1));

        integralSwitchCoolant2.setComponent("AuxCond2#CoolantValve");
        integralSwitchCoolant2.setToolTipText("Condeser 2 Cooland Flow");
        add(integralSwitchCoolant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 308, -1, -1));

        jLabelCaptionDrain.setFont(jLabelCaptionDrain.getFont().deriveFont(jLabelCaptionDrain.getFont().getSize()-2f));
        jLabelCaptionDrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain.setText("Drain");
        jLabelCaptionDrain.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 292, 42, 16));

        jLabelCaptionHotwell.setFont(jLabelCaptionHotwell.getFont().deriveFont(jLabelCaptionHotwell.getFont().getSize()-2f));
        jLabelCaptionHotwell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionHotwell.setText("Hotwell");
        jLabelCaptionHotwell.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionHotwell.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionHotwell.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionHotwell, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 244, 42, 16));

        jLabelCaptionBypass.setFont(jLabelCaptionBypass.getFont().deriveFont(jLabelCaptionBypass.getFont().getSize()-2f));
        jLabelCaptionBypass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionBypass.setText("Bypass");
        jLabelCaptionBypass.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBypass.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionBypass.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionBypass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 202, 52, 14));

        jLabelCaptionSteamIn.setFont(jLabelCaptionSteamIn.getFont().deriveFont(jLabelCaptionSteamIn.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSteamIn.getFont().getSize()-2));
        jLabelCaptionSteamIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSteamIn.setText("Steam 2");
        jLabelCaptionSteamIn.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSteamIn.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSteamIn.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSteamIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 234, 60, 14));

        controlLoopCondLevel1.setControlComponent("AuxCond1#CondensateValve");
        controlLoopCondLevel1.setFeedbackComponent("AuxCond1#Level");
        controlLoopCondLevel1.setMaxValue(160.0);
        controlLoopCondLevel1.setSetpointComponent("AuxCond1#LevelSetpoint");
        add(controlLoopCondLevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 94, -1, -1));

        controlLoopCondLevel2.setControlComponent("AuxCond2#CondensateValve");
        controlLoopCondLevel2.setFeedbackComponent("AuxCond2#Level");
        controlLoopCondLevel2.setMaxValue(160.0);
        controlLoopCondLevel2.setSetpointComponent("AuxCond2#LevelSetpoint");
        add(controlLoopCondLevel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 134, -1, -1));

        chornobylGaugeCondTemperature.setChornobylMaximum(100.0F);
        chornobylGaugeCondTemperature.setChornobylMinimum(0.0F);
        chornobylGaugeCondTemperature.setChornobylTicks(new float[] {20.0f, 40.0f, 60.0f, 80.0f, 100.0f});
        chornobylGaugeCondTemperature.setChornobylUnitText("°C");
        chornobylGaugeCondTemperature.setChornobylValue(0.0F);
        add(chornobylGaugeCondTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 64, -1, -1));

        jLabelCaptionGaugeNeutronRate2.setFont(jLabelCaptionGaugeNeutronRate2.getFont().deriveFont(jLabelCaptionGaugeNeutronRate2.getFont().getSize()-2f));
        jLabelCaptionGaugeNeutronRate2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCaptionGaugeNeutronRate2.setText("Temp.");
        jLabelCaptionGaugeNeutronRate2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionGaugeNeutronRate2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionGaugeNeutronRate2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionGaugeNeutronRate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 52, 14));

        jLabelFeed20.setFont(jLabelFeed20.getFont().deriveFont(jLabelFeed20.getFont().getStyle() | java.awt.Font.BOLD, jLabelFeed20.getFont().getSize()-2));
        jLabelFeed20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFeed20.setText("Coolant");
        jLabelFeed20.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelFeed20.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelFeed20.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelFeed20, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 290, 54, 14));

        jLabelCaptionPump13.setFont(jLabelCaptionPump13.getFont().deriveFont(jLabelCaptionPump13.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump13.getFont().getSize()-2));
        jLabelCaptionPump13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump13.setText("Condensate");
        jLabelCaptionPump13.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump13.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump13.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump13, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 178, 88, 14));

        jLabelDA1Press1.setFont(jLabelDA1Press1.getFont().deriveFont(jLabelDA1Press1.getFont().getSize()-2f));
        jLabelDA1Press1.setText("Cond 1");
        add(jLabelDA1Press1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 100, 50, 14));

        jLabelDA1Press2.setFont(jLabelDA1Press2.getFont().deriveFont(jLabelDA1Press2.getFont().getSize()-2f));
        jLabelDA1Press2.setText("Level");
        add(jLabelDA1Press2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 114, 50, 14));

        jLabelDA1Press3.setFont(jLabelDA1Press3.getFont().deriveFont(jLabelDA1Press3.getFont().getSize()-2f));
        jLabelDA1Press3.setText("Cond 2");
        add(jLabelDA1Press3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 140, 50, 14));

        jLabelDA1Press4.setFont(jLabelDA1Press4.getFont().deriveFont(jLabelDA1Press4.getFont().getSize()-2f));
        jLabelDA1Press4.setText("Level");
        add(jLabelDA1Press4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 154, 50, 14));

        jLabelCaptionGaugeNeutronRate3.setFont(jLabelCaptionGaugeNeutronRate3.getFont().deriveFont(jLabelCaptionGaugeNeutronRate3.getFont().getSize()-2f));
        jLabelCaptionGaugeNeutronRate3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCaptionGaugeNeutronRate3.setText("Condens");
        jLabelCaptionGaugeNeutronRate3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionGaugeNeutronRate3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionGaugeNeutronRate3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionGaugeNeutronRate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 52, 14));

        chornobylGaugeFlow1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeFlow1.setChornobylMaximum(25.0F);
        chornobylGaugeFlow1.setChornobylMinimum(0.0F);
        chornobylGaugeFlow1.setChornobylTicks(new float[] {0.0f, 5.0f, 10.0f, 15.0f, 20.0f});
        chornobylGaugeFlow1.setChornobylUnitText("kg/s");
        chornobylGaugeFlow1.setChornobylValue(2.0F);
        add(chornobylGaugeFlow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, -1, -1));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()-2f));
        jLabel5.setText("Loop 1");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 52, 14));

        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getSize()-2f));
        jLabel20.setText("Flow");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 52, 14));

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()-2f));
        jLabel7.setText("Loop 2");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 52, 14));

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getSize()-2f));
        jLabel19.setText("Flow");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 52, 14));

        chornobylGaugeFlow2.setChornobylMaximum(25.0F);
        chornobylGaugeFlow2.setChornobylMinimum(0.0F);
        chornobylGaugeFlow2.setChornobylTicks(new float[] {0.0f, 5.0f, 10.0f, 15.0f, 20.0f});
        chornobylGaugeFlow2.setChornobylUnitText("kg/s");
        chornobylGaugeFlow2.setChornobylValue(2.0F);
        add(chornobylGaugeFlow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 34, -1, -1));

        integralSwitch1.setComponent("AuxCond1#SteamValve");
        integralSwitch1.setControlledValve(true);
        integralSwitch1.setToolTipText("From main steam line 1 valve to auxiliary condenser 1");
        add(integralSwitch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 200, -1, -1));

        integralSwitch2.setComponent("AuxCond2#SteamValve");
        integralSwitch2.setControlledValve(true);
        integralSwitch2.setToolTipText("From main steam line 2 valve to auxiliary condenser 2");
        add(integralSwitch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 250, -1, -1));

        jTogglePressureControl1.setFont(jTogglePressureControl1.getFont().deriveFont(jTogglePressureControl1.getFont().getStyle() | java.awt.Font.BOLD));
        jTogglePressureControl1.setText("←");
        jTogglePressureControl1.setToolTipText("Enables valve control by pressure regulator");
        jTogglePressureControl1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTogglePressureControl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTogglePressureControl1ActionPerformed(evt);
            }
        });
        add(jTogglePressureControl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 256, 22, 20));

        jToggleButtonGlobalEnable1.setFont(jToggleButtonGlobalEnable1.getFont().deriveFont(jToggleButtonGlobalEnable1.getFont().getStyle() | java.awt.Font.BOLD));
        jToggleButtonGlobalEnable1.setText("←");
        jToggleButtonGlobalEnable1.setToolTipText("Enables valve control by pressure regulator");
        jToggleButtonGlobalEnable1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonGlobalEnable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonGlobalEnable1ActionPerformed(evt);
            }
        });
        add(jToggleButtonGlobalEnable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 206, 22, 20));

        jLabelCaptionSteamIn1.setFont(jLabelCaptionSteamIn1.getFont().deriveFont(jLabelCaptionSteamIn1.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSteamIn1.getFont().getSize()-2));
        jLabelCaptionSteamIn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSteamIn1.setText("Steam 1");
        jLabelCaptionSteamIn1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSteamIn1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSteamIn1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSteamIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, 64, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBypassCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBypassCloseActionPerformed
        controller.userAction(new ActionCommand("AuxCond#Bypass", false));
    }//GEN-LAST:event_jButtonBypassCloseActionPerformed

    private void jButtonBypassOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBypassOpenActionPerformed
        controller.userAction(new ActionCommand("AuxCond#Bypass", true));
    }//GEN-LAST:event_jButtonBypassOpenActionPerformed

    private void jTogglePressureControl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTogglePressureControl1ActionPerformed
        
    }//GEN-LAST:event_jTogglePressureControl1ActionPerformed

    private void jToggleButtonGlobalEnable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonGlobalEnable1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonGlobalEnable1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeCondTemperature;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFlow1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFlow2;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop controlLoopCondLevel1;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop controlLoopCondLevel2;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch2;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchCoolant1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchCoolant2;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchToDrain;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchToHotwell;
    private javax.swing.JButton jButtonBypassClose;
    private javax.swing.JButton jButtonBypassOpen;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCaptionBypass;
    private javax.swing.JLabel jLabelCaptionDrain;
    private javax.swing.JLabel jLabelCaptionGaugeNeutronRate2;
    private javax.swing.JLabel jLabelCaptionGaugeNeutronRate3;
    private javax.swing.JLabel jLabelCaptionHotwell;
    private javax.swing.JLabel jLabelCaptionPump13;
    private javax.swing.JLabel jLabelCaptionSteamIn;
    private javax.swing.JLabel jLabelCaptionSteamIn1;
    private javax.swing.JLabel jLabelDA1Press1;
    private javax.swing.JLabel jLabelDA1Press2;
    private javax.swing.JLabel jLabelDA1Press3;
    private javax.swing.JLabel jLabelDA1Press4;
    private javax.swing.JLabel jLabelFeed20;
    private javax.swing.JToggleButton jToggleButtonGlobalEnable1;
    private javax.swing.JToggleButton jTogglePressureControl1;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetSmallPump panelCondensatePump1;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetSmallPump panelCondensatePump2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        if (!evt.getPropertyName().startsWith("AuxCond")) {
            return;
        }
        panelCondensatePump1.updateComponent(evt);
        panelCondensatePump2.updateComponent(evt);
        controlLoopCondLevel1.updateComponent(evt);
        controlLoopCondLevel2.updateComponent(evt);
        integralSwitchToHotwell.updateComponent(evt);
        integralSwitchCoolant1.updateComponent(evt);
        integralSwitchCoolant2.updateComponent(evt);
        integralSwitch1.updateComponent(evt);
        integralSwitch2.updateComponent(evt);
        integralSwitchToDrain.updateComponent(evt);
        switch (evt.getPropertyName()) {
            case "AuxCond#Bypass_Pos" ->
                setValveButtons(jButtonBypassClose,
                        jButtonBypassOpen, evt.getNewValue());
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        controlLoopCondLevel1.updateComponent(propertyName, newValue);
        controlLoopCondLevel2.updateComponent(propertyName, newValue);
        switch (propertyName) {
            case "AuxCond1#SteamFlow" ->
                chornobylGaugeFlow1.setChornobylValue((float) newValue);
            case "AuxCond2#SteamFlow" ->
                chornobylGaugeFlow2.setChornobylValue((float) newValue);
            case "AuxCond#CondensateTemperature" ->
                chornobylGaugeCondTemperature.setChornobylValue(
                        (float) newValue);
        }

    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
