/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelTurbine extends AbstractPanelWidget
        implements UpdateReceiver {

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);
        controlLoopStartupValve1.registerActionReceiver(controller);
        controlLoopStartupValve2.registerActionReceiver(controller);
        controlLoopValveReheater1.registerActionReceiver(controller);
        controlLoopValveReheater2.registerActionReceiver(controller);
        integralSwitchReheaterSteam.registerActionReceiver(controller);
        setpointControlTemperature.registerActionReceiver(controller);
        controlLoopValve3.registerActionReceiver(controller);
        controlLoopValve4.registerActionReceiver(controller);
        controlLoopValveCondToHotwell.registerActionReceiver(controller);
        controlLoopValveCondToDA1.registerActionReceiver(controller);
        controlLoopValveCondToDA2.registerActionReceiver(controller);
        setpointControlLevel.registerActionReceiver(controller);
    }

    /**
     * Creates new form PanelTurbine
     */
    public PanelTurbine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelCaptionsuperheaterCond2 = new javax.swing.JLabel();
        jLabelCaptionsuperheaterCond1 = new javax.swing.JLabel();
        controlLoopValveCondToDA1 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopValveCondToDA2 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        jLabelCaptionsuperheaterCond3 = new javax.swing.JLabel();
        jLabelCaptionsuperheaterCond4 = new javax.swing.JLabel();
        setpointControlLevel = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        jLabelTempSetpoint1 = new javax.swing.JLabel();
        controlLoopValveCondToHotwell = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        jLabelCaptionsuperheaterCond5 = new javax.swing.JLabel();
        jLabelCaptionsuperheaterCond6 = new javax.swing.JLabel();
        jLabelCaption1 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl1 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl2 = new javax.swing.JLabel();
        jButtonProtectionRest = new javax.swing.JButton();
        jButtonProtectionTrip = new javax.swing.JButton();
        lightBulbSpeed6 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jLabelCaption2 = new javax.swing.JLabel();
        jLabelCaption3 = new javax.swing.JLabel();
        controlLoopStartupValve1 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopStartupValve2 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopValve3 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopValve4 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chornobylGaugeFeed1Temp = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeFeed1Flow = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeFeed2Flow = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeFeed2Flow1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        chornobylGaugeFeed1Temp1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp2 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp3 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabelCaption4 = new javax.swing.JLabel();
        jLabelCaption5 = new javax.swing.JLabel();
        jLabelCaption6 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl4 = new javax.swing.JLabel();
        jLabelCaption7 = new javax.swing.JLabel();
        jToggleButtonTurboSetpoint = new javax.swing.JToggleButton();
        jLabelCaptionDrains1 = new javax.swing.JLabel();
        jLabelCaptionDrains2 = new javax.swing.JLabel();
        jButtonDrainsClose = new javax.swing.JButton();
        jButtenDrainsOpen = new javax.swing.JButton();
        controlLoopValveReheater1 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopValveReheater2 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        jLabelCaption8 = new javax.swing.JLabel();
        jToggleButtonAutoDrain2 = new javax.swing.JToggleButton();
        jLabelCaption9 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl7 = new javax.swing.JLabel();
        jLabelCaption10 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl8 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonTrip1Close = new javax.swing.JButton();
        jButtonTrip1Open = new javax.swing.JButton();
        jLabelCaptionLPShut1 = new javax.swing.JLabel();
        jButtonLPShutClose = new javax.swing.JButton();
        jButtenLPShutOpen = new javax.swing.JButton();
        jButtonTrip2Close = new javax.swing.JButton();
        jButtonTrip2Open = new javax.swing.JButton();
        jLabelCaptionLPShut7 = new javax.swing.JLabel();
        jLabelCaptionLPShut10 = new javax.swing.JLabel();
        jButtonSuperheaterShutoffClose = new javax.swing.JButton();
        jButtonSuperheaterShutoffOpen = new javax.swing.JButton();
        jLabelCaptionLPShut5 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl6 = new javax.swing.JLabel();
        jToggleButtonPump = new javax.swing.JToggleButton();
        lightBulbReady = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jToggleButtonPump1 = new javax.swing.JToggleButton();
        lightBulbReady1 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService1 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jToggleButtonPump2 = new javax.swing.JToggleButton();
        lightBulbReady2 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService2 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jLabelCaptionSuperheaterControl9 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        chornobylGaugeOilPressure = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabelCaptionAuxLubeOil = new javax.swing.JLabel();
        jLabelCaptionTG1 = new javax.swing.JLabel();
        jLabelCaptionTG2 = new javax.swing.JLabel();
        jToggleButtonTurningGear = new javax.swing.JToggleButton();
        lightBulbReady4 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService4 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        setpointControlTemperature = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        jLabelTempSetpoint = new javax.swing.JLabel();
        integralSwitchReheaterSteam = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        jLabelCaptionReheatTrim1 = new javax.swing.JLabel();
        jLabelCaptionReheatTrim2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(574, 340));
        setPreferredSize(new java.awt.Dimension(574, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCaptionsuperheaterCond2.setFont(jLabelCaptionsuperheaterCond2.getFont().deriveFont(jLabelCaptionsuperheaterCond2.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond2.setText("DA 1");
        jPanel2.add(jLabelCaptionsuperheaterCond2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, 50, 14));

        jLabelCaptionsuperheaterCond1.setFont(jLabelCaptionsuperheaterCond1.getFont().deriveFont(jLabelCaptionsuperheaterCond1.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond1.setText("Cond.");
        jPanel2.add(jLabelCaptionsuperheaterCond1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 50, 14));

        controlLoopValveCondToDA1.setComponent("Turbine1#ReheaterCondensateValve");
        jPanel2.add(controlLoopValveCondToDA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 12, -1, -1));

        controlLoopValveCondToDA2.setComponent("Turbine2#ReheaterCondensateValve");
        jPanel2.add(controlLoopValveCondToDA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 52, -1, -1));

        jLabelCaptionsuperheaterCond3.setFont(jLabelCaptionsuperheaterCond3.getFont().deriveFont(jLabelCaptionsuperheaterCond3.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond3.setText("Cond.");
        jPanel2.add(jLabelCaptionsuperheaterCond3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 50, 14));

        jLabelCaptionsuperheaterCond4.setFont(jLabelCaptionsuperheaterCond4.getFont().deriveFont(jLabelCaptionsuperheaterCond4.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond4.setText("DA 2");
        jPanel2.add(jLabelCaptionsuperheaterCond4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, 50, 14));

        setpointControlLevel.setComponent("Turbine#SetpointReheaterLevel");
        setpointControlLevel.setFormat("%.0f");
        jPanel2.add(setpointControlLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 26, -1, -1));

        jLabelTempSetpoint1.setFont(jLabelTempSetpoint1.getFont().deriveFont(jLabelTempSetpoint1.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelTempSetpoint1.getFont().getSize()-2));
        jLabelTempSetpoint1.setText("Level Setpoint");
        jLabelTempSetpoint1.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelTempSetpoint1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelTempSetpoint1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelTempSetpoint1.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel2.add(jLabelTempSetpoint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 8, 86, -1));

        controlLoopValveCondToHotwell.setComponent("Turbine#ReheaterCondensateDrain");
        jPanel2.add(controlLoopValveCondToHotwell, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 52, -1, -1));

        jLabelCaptionsuperheaterCond5.setFont(jLabelCaptionsuperheaterCond5.getFont().deriveFont(jLabelCaptionsuperheaterCond5.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond5.setText("Cond.");
        jPanel2.add(jLabelCaptionsuperheaterCond5, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 56, 50, 14));

        jLabelCaptionsuperheaterCond6.setFont(jLabelCaptionsuperheaterCond6.getFont().deriveFont(jLabelCaptionsuperheaterCond6.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond6.setText("Drain");
        jPanel2.add(jLabelCaptionsuperheaterCond6, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 70, 50, 14));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 238, 280, 96));

        jLabelCaption1.setFont(jLabelCaption1.getFont().deriveFont(jLabelCaption1.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption1.getFont().getSize()-2));
        jLabelCaption1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption1.setText("Reheater");
        jLabelCaption1.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 118, 90, 14));

        jLabelCaptionSuperheaterControl1.setFont(jLabelCaptionSuperheaterControl1.getFont().deriveFont(jLabelCaptionSuperheaterControl1.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl1.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl1.setText("High Pressure Steam Valve Controls");
        jLabelCaptionSuperheaterControl1.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 102, 244, 14));

        jLabelCaptionSuperheaterControl2.setFont(jLabelCaptionSuperheaterControl2.getFont().deriveFont(jLabelCaptionSuperheaterControl2.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl2.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl2.setText("Selection");
        jLabelCaptionSuperheaterControl2.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 126, 56, 14));

        jButtonProtectionRest.setFont(jButtonProtectionRest.getFont().deriveFont(jButtonProtectionRest.getFont().getSize()-2f));
        jButtonProtectionRest.setText("●");
        jButtonProtectionRest.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonProtectionRest.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonProtectionRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProtectionRestActionPerformed(evt);
            }
        });
        add(jButtonProtectionRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 144, 20, 20));

        jButtonProtectionTrip.setFont(jButtonProtectionTrip.getFont().deriveFont(jButtonProtectionTrip.getFont().getSize()-2f));
        jButtonProtectionTrip.setText("●");
        jButtonProtectionTrip.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonProtectionTrip.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonProtectionTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProtectionTripActionPerformed(evt);
            }
        });
        add(jButtonProtectionTrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, 20, 20));

        lightBulbSpeed6.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbSpeed6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 150, -1, -1));

        jLabelCaption2.setFont(jLabelCaption2.getFont().deriveFont(jLabelCaption2.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption2.getFont().getSize()-2));
        jLabelCaption2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption2.setText("Reset");
        jLabelCaption2.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 128, 32, 14));

        jLabelCaption3.setFont(jLabelCaption3.getFont().deriveFont(jLabelCaption3.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption3.getFont().getSize()-2));
        jLabelCaption3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption3.setText("Trip");
        jLabelCaption3.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 128, 32, 14));

        controlLoopStartupValve1.setComponent("Turbine1#StartupSteamValve");
        add(controlLoopStartupValve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 134, -1, -1));

        controlLoopStartupValve2.setComponent("Turbine2#StartupSteamValve");
        add(controlLoopStartupValve2, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 176, -1, -1));

        controlLoopValve3.setComponent("Turbine1#MainSteamValve");
        add(controlLoopValve3, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 134, -1, -1));

        controlLoopValve4.setComponent("Turbine2#MainSteamValve");
        add(controlLoopValve4, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 176, -1, -1));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()-2f));
        jLabel5.setText("Turbine");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 52, 14));

        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getSize()-2f));
        jLabel20.setText("Speed");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 52, 14));

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()-2f));
        jLabel7.setText("HP");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 52, 14));

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getSize()-2f));
        jLabel19.setText("Flow");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 52, 14));

        chornobylGaugeFeed1Temp.setChornobylMaximum(200.0F);
        chornobylGaugeFeed1Temp.setChornobylMinimum(20.0F);
        chornobylGaugeFeed1Temp.setChornobylTicks(new float[] {50.0f, 100.0f, 150.0f});
        chornobylGaugeFeed1Temp.setChornobylUnitText("°C");
        add(chornobylGaugeFeed1Temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 34, -1, -1));

        chornobylGaugeFeed1Flow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeFeed1Flow.setChornobylMaximum(3200.0F);
        chornobylGaugeFeed1Flow.setChornobylMinimum(0.0F);
        chornobylGaugeFeed1Flow.setChornobylTicks(new float[] {500.0f, 1500.0f, 3000.0f});
        chornobylGaugeFeed1Flow.setChornobylUnitText("1/min");
        add(chornobylGaugeFeed1Flow, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, -1, -1));

        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getSize()-2f));
        jLabel24.setText("HP Case");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 4, 52, 14));

        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getSize()-2f));
        jLabel18.setText("Temp");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 16, 52, 14));

        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getSize()-2f));
        jLabel23.setText("HP Rotor");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 34, 52, 14));

        jLabel17.setFont(jLabel17.getFont().deriveFont(jLabel17.getFont().getSize()-2f));
        jLabel17.setText("Temp");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 46, 52, 14));

        chornobylGaugeFeed2Temp.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Temp.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Temp.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Temp.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 34, -1, -1));

        chornobylGaugeFeed2Flow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeFeed2Flow.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Flow.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Flow.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Flow.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Flow, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 4, -1, -1));

        jLabel25.setFont(jLabel25.getFont().deriveFont(jLabel25.getFont().getSize()-2f));
        jLabel25.setText("LP Case");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 4, 52, 14));

        jLabel21.setFont(jLabel21.getFont().deriveFont(jLabel21.getFont().getSize()-2f));
        jLabel21.setText("Temp");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 16, 52, 14));

        jLabel26.setFont(jLabel26.getFont().deriveFont(jLabel26.getFont().getSize()-2f));
        jLabel26.setText("LP Rotor");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 34, 52, 14));

        jLabel22.setFont(jLabel22.getFont().deriveFont(jLabel22.getFont().getSize()-2f));
        jLabel22.setText("Temp");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 46, 52, 14));

        chornobylGaugeFeed2Temp1.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Temp1.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Temp1.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Temp1.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Temp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 34, -1, -1));

        chornobylGaugeFeed2Flow1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeFeed2Flow1.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Flow1.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Flow1.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Flow1.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Flow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 4, -1, -1));

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()-2f));
        jLabel8.setText("Total");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 52, 14));

        jLabel27.setFont(jLabel27.getFont().deriveFont(jLabel27.getFont().getSize()-2f));
        jLabel27.setText("Expans.");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 52, 14));

        chornobylGaugeFeed1Temp1.setChornobylMaximum(50.0F);
        chornobylGaugeFeed1Temp1.setChornobylMinimum(0.0F);
        chornobylGaugeFeed1Temp1.setChornobylTicks(new float[] {0.0f, 10.0f, 20.0f, 30.0f, 40.0f});
        chornobylGaugeFeed1Temp1.setChornobylUnitText("mm");
        chornobylGaugeFeed1Temp1.setChornobylValue(0.0F);
        add(chornobylGaugeFeed1Temp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 64, -1, -1));

        jLabel28.setFont(jLabel28.getFont().deriveFont(jLabel28.getFont().getSize()-2f));
        jLabel28.setText("HP Diff");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 64, 52, 14));

        jLabel29.setFont(jLabel29.getFont().deriveFont(jLabel29.getFont().getSize()-2f));
        jLabel29.setText("Expans.");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 76, 52, 14));

        chornobylGaugeFeed2Temp2.setChornobylMaximum(4.0F);
        chornobylGaugeFeed2Temp2.setChornobylMinimum(-2.0F);
        chornobylGaugeFeed2Temp2.setChornobylTicks(new float[] {-1.0f, 0.0f, 1.0f, 2.0f});
        chornobylGaugeFeed2Temp2.setChornobylUnitText("mm");
        chornobylGaugeFeed2Temp2.setChornobylValue(0.0F);
        add(chornobylGaugeFeed2Temp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 64, -1, -1));

        jLabel30.setFont(jLabel30.getFont().deriveFont(jLabel30.getFont().getSize()-2f));
        jLabel30.setText("LP Diff");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 64, 52, 14));

        jLabel31.setFont(jLabel31.getFont().deriveFont(jLabel31.getFont().getSize()-2f));
        jLabel31.setText("Expans.");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 76, 52, 14));

        chornobylGaugeFeed2Temp3.setChornobylMaximum(6.0F);
        chornobylGaugeFeed2Temp3.setChornobylMinimum(-3.0F);
        chornobylGaugeFeed2Temp3.setChornobylTicks(new float[] {-2.5f, 0.0f, 2.5f, 5.0f});
        chornobylGaugeFeed2Temp3.setChornobylUnitText("mm");
        chornobylGaugeFeed2Temp3.setChornobylValue(0.0F);
        add(chornobylGaugeFeed2Temp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 64, -1, -1));

        jLabelCaption4.setFont(jLabelCaption4.getFont().deriveFont(jLabelCaption4.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption4.getFont().getSize()-2));
        jLabelCaption4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption4.setText("2");
        jLabelCaption4.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption4.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption4.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption4.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption4, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 188, 10, 14));

        jLabelCaption5.setFont(jLabelCaption5.getFont().deriveFont(jLabelCaption5.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption5.getFont().getSize()-2));
        jLabelCaption5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption5.setText("Startup Valves");
        jLabelCaption5.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption5, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 118, 86, 14));

        jLabelCaption6.setFont(jLabelCaption6.getFont().deriveFont(jLabelCaption6.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption6.getFont().getSize()-2));
        jLabelCaption6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption6.setText("Speed");
        jLabelCaption6.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption6, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 186, 54, 14));

        jLabelCaptionSuperheaterControl4.setFont(jLabelCaptionSuperheaterControl4.getFont().deriveFont(jLabelCaptionSuperheaterControl4.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl4.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl4.setText("Trip Valves");
        jLabelCaptionSuperheaterControl4.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl4.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl4.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl4.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 102, 112, 14));

        jLabelCaption7.setFont(jLabelCaption7.getFont().deriveFont(jLabelCaption7.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption7.getFont().getSize()-2));
        jLabelCaption7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption7.setText("1");
        jLabelCaption7.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption7.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption7.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption7.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption7, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 142, 10, 14));

        jToggleButtonTurboSetpoint.setText("←");
        jToggleButtonTurboSetpoint.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonTurboSetpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTurboSetpointActionPerformed(evt);
            }
        });
        add(jToggleButtonTurboSetpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 20, 20));

        jLabelCaptionDrains1.setFont(jLabelCaptionDrains1.getFont().deriveFont(jLabelCaptionDrains1.getFont().getSize()-2f));
        jLabelCaptionDrains1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrains1.setText("Steam");
        jLabelCaptionDrains1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrains1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrains1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrains1, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 278, 51, 14));

        jLabelCaptionDrains2.setFont(jLabelCaptionDrains2.getFont().deriveFont(jLabelCaptionDrains2.getFont().getSize()-2f));
        jLabelCaptionDrains2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrains2.setText("Drains");
        jLabelCaptionDrains2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrains2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrains2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrains2, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 290, 51, 14));

        jButtonDrainsClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonDrainsClose.setText("C");
        jButtonDrainsClose.setToolTipText("");
        jButtonDrainsClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDrainsClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrainsCloseActionPerformed(evt);
            }
        });
        add(jButtonDrainsClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 304, 20, 20));

        jButtenDrainsOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtenDrainsOpen.setText("O");
        jButtenDrainsOpen.setToolTipText("");
        jButtenDrainsOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtenDrainsOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtenDrainsOpenActionPerformed(evt);
            }
        });
        add(jButtenDrainsOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 304, 20, 20));

        controlLoopValveReheater1.setComponent("Turbine1#ReheaterSteamValve");
        add(controlLoopValveReheater1, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 134, -1, -1));

        controlLoopValveReheater2.setComponent("Turbine2#ReheaterSteamValve");
        add(controlLoopValveReheater2, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 176, -1, -1));

        jLabelCaption8.setFont(jLabelCaption8.getFont().deriveFont(jLabelCaption8.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption8.getFont().getSize()-2));
        jLabelCaption8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption8.setText("Main Valves");
        jLabelCaption8.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption8.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption8.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption8.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption8, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 118, 90, 14));

        jToggleButtonAutoDrain2.setText("←");
        jToggleButtonAutoDrain2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonAutoDrain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAutoDrain2ActionPerformed(evt);
            }
        });
        add(jToggleButtonAutoDrain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 174, 20, 20));

        jLabelCaption9.setFont(jLabelCaption9.getFont().deriveFont(jLabelCaption9.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption9.getFont().getSize()-2));
        jLabelCaption9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption9.setText("Override");
        jLabelCaption9.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption9.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption9.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption9.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 196, 54, 14));

        jLabelCaptionSuperheaterControl7.setFont(jLabelCaptionSuperheaterControl7.getFont().deriveFont(jLabelCaptionSuperheaterControl7.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl7.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl7.setText("Protection");
        jLabelCaptionSuperheaterControl7.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl7.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl7.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl7.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 114, 72, 14));

        jLabelCaption10.setFont(jLabelCaption10.getFont().deriveFont(jLabelCaption10.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption10.getFont().getSize()-2));
        jLabelCaption10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption10.setText("Pressure");
        jLabelCaption10.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption10.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption10.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption10.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption10, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 142, 54, 14));

        jLabelCaptionSuperheaterControl8.setFont(jLabelCaptionSuperheaterControl8.getFont().deriveFont(jLabelCaptionSuperheaterControl8.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl8.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl8.setText("Setpoint");
        jLabelCaptionSuperheaterControl8.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl8.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl8.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl8.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 112, 56, 14));

        jLabelCaptionSuperheaterControl5.setFont(jLabelCaptionSuperheaterControl5.getFont().deriveFont(jLabelCaptionSuperheaterControl5.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl5.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl5.setText("Reheater Condensate Control");
        jLabelCaptionSuperheaterControl5.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 222, 272, 14));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTrip1Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonTrip1Close.setText("C");
        jButtonTrip1Close.setToolTipText("");
        jButtonTrip1Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTrip1Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrip1CloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTrip1Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, 20, 20));

        jButtonTrip1Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonTrip1Open.setText("O");
        jButtonTrip1Open.setToolTipText("");
        jButtonTrip1Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTrip1Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrip1OpenActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTrip1Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 20, 20, 20));

        jLabelCaptionLPShut1.setFont(jLabelCaptionLPShut1.getFont().deriveFont(jLabelCaptionLPShut1.getFont().getSize()-2f));
        jLabelCaptionLPShut1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut1.setText("LP");
        jLabelCaptionLPShut1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut1.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionLPShut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 4, 51, -1));

        jButtonLPShutClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLPShutClose.setText("C");
        jButtonLPShutClose.setToolTipText("");
        jButtonLPShutClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLPShutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLPShutCloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLPShutClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 20, 20, 20));

        jButtenLPShutOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtenLPShutOpen.setText("O");
        jButtenLPShutOpen.setToolTipText("");
        jButtenLPShutOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtenLPShutOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtenLPShutOpenActionPerformed(evt);
            }
        });
        jPanel1.add(jButtenLPShutOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 20, 20, 20));

        jButtonTrip2Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonTrip2Close.setText("C");
        jButtonTrip2Close.setToolTipText("");
        jButtonTrip2Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTrip2Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrip2CloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTrip2Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 20, 20));

        jButtonTrip2Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonTrip2Open.setText("O");
        jButtonTrip2Open.setToolTipText("");
        jButtonTrip2Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTrip2Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrip2OpenActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTrip2Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 60, 20, 20));

        jLabelCaptionLPShut7.setFont(jLabelCaptionLPShut7.getFont().deriveFont(jLabelCaptionLPShut7.getFont().getSize()-2f));
        jLabelCaptionLPShut7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut7.setText("Steam 1");
        jLabelCaptionLPShut7.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut7.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut7.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionLPShut7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 51, -1));

        jLabelCaptionLPShut10.setFont(jLabelCaptionLPShut10.getFont().deriveFont(jLabelCaptionLPShut10.getFont().getSize()-2f));
        jLabelCaptionLPShut10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut10.setText("Steam 2");
        jLabelCaptionLPShut10.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut10.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut10.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionLPShut10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, 51, -1));

        jButtonSuperheaterShutoffClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonSuperheaterShutoffClose.setText("C");
        jButtonSuperheaterShutoffClose.setToolTipText("");
        jButtonSuperheaterShutoffClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSuperheaterShutoffClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuperheaterShutoffCloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSuperheaterShutoffClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 60, 20, 20));

        jButtonSuperheaterShutoffOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonSuperheaterShutoffOpen.setText("O");
        jButtonSuperheaterShutoffOpen.setToolTipText("");
        jButtonSuperheaterShutoffOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSuperheaterShutoffOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuperheaterShutoffOpenActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSuperheaterShutoffOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 60, 20, 20));

        jLabelCaptionLPShut5.setFont(jLabelCaptionLPShut5.getFont().deriveFont(jLabelCaptionLPShut5.getFont().getSize()-2f));
        jLabelCaptionLPShut5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut5.setText("Reheater");
        jLabelCaptionLPShut5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut5.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionLPShut5, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 44, 51, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 120, 122, 90));

        jLabelCaptionSuperheaterControl6.setFont(jLabelCaptionSuperheaterControl6.getFont().deriveFont(jLabelCaptionSuperheaterControl6.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl6.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl6.setText("Turbine");
        jLabelCaptionSuperheaterControl6.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, 56, 14));

        jToggleButtonPump.setText("←");
        jToggleButtonPump.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPumpActionPerformed(evt);
            }
        });
        add(jToggleButtonPump, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 312, 20, 20));

        lightBulbReady.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 304, -1, -1));

        lightBulbInService.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 304, -1, -1));

        jToggleButtonPump1.setText("←");
        jToggleButtonPump1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPump1ActionPerformed(evt);
            }
        });
        add(jToggleButtonPump1, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 280, 20, 20));

        lightBulbReady1.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 272, -1, -1));

        lightBulbInService1.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 272, -1, -1));

        jToggleButtonPump2.setText("←");
        jToggleButtonPump2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPump2ActionPerformed(evt);
            }
        });
        add(jToggleButtonPump2, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 280, 20, 20));

        lightBulbReady2.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady2, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 272, -1, -1));

        lightBulbInService2.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService2, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 272, -1, -1));

        jLabelCaptionSuperheaterControl9.setFont(jLabelCaptionSuperheaterControl9.getFont().deriveFont(jLabelCaptionSuperheaterControl9.getFont().getSize()-2f));
        jLabelCaptionSuperheaterControl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl9.setText("Hydraulic");
        jLabelCaptionSuperheaterControl9.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl9.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl9.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl9.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 316, -1, 14));

        jLabel32.setFont(jLabel32.getFont().deriveFont(jLabel32.getFont().getSize()-2f));
        jLabel32.setText("Oil");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 222, 32, 14));

        jLabel33.setFont(jLabel33.getFont().deriveFont(jLabel33.getFont().getSize()-2f));
        jLabel33.setText("press");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 234, 32, 14));

        chornobylGaugeOilPressure.setChornobylMaximum(10.0F);
        chornobylGaugeOilPressure.setChornobylMinimum(0.0F);
        chornobylGaugeOilPressure.setChornobylTicks(new float[] {0.0f, 2.0f, 4.0f, 6.0f, 8.0f, 10.0f});
        chornobylGaugeOilPressure.setChornobylUnitText("bar");
        chornobylGaugeOilPressure.setChornobylValue(0.0F);
        add(chornobylGaugeOilPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 222, -1, -1));

        jLabelCaptionAuxLubeOil.setFont(jLabelCaptionAuxLubeOil.getFont().deriveFont(jLabelCaptionAuxLubeOil.getFont().getSize()-2f));
        jLabelCaptionAuxLubeOil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionAuxLubeOil.setText("Aux lube oil");
        jLabelCaptionAuxLubeOil.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionAuxLubeOil.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAuxLubeOil.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAuxLubeOil.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionAuxLubeOil, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 254, 68, 14));

        jLabelCaptionTG1.setFont(jLabelCaptionTG1.getFont().deriveFont(jLabelCaptionTG1.getFont().getSize()-2f));
        jLabelCaptionTG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionTG1.setText("Turning");
        jLabelCaptionTG1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionTG1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionTG1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionTG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 256, 51, 14));

        jLabelCaptionTG2.setFont(jLabelCaptionTG2.getFont().deriveFont(jLabelCaptionTG2.getFont().getSize()-2f));
        jLabelCaptionTG2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionTG2.setText("Gear");
        jLabelCaptionTG2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionTG2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionTG2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionTG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 268, 51, 14));

        jToggleButtonTurningGear.setText("←");
        jToggleButtonTurningGear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonTurningGear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTurningGearActionPerformed(evt);
            }
        });
        add(jToggleButtonTurningGear, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 294, 20, 20));

        lightBulbReady4.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady4, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 286, -1, -1));

        lightBulbInService4.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService4, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 286, -1, -1));

        setpointControlTemperature.setComponent("Turbine#SetpointReheaterTemperature");
        setpointControlTemperature.setFormat("%.0f");
        add(setpointControlTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 246, -1, -1));

        jLabelTempSetpoint.setFont(jLabelTempSetpoint.getFont().deriveFont(jLabelTempSetpoint.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelTempSetpoint.getFont().getSize()-2));
        jLabelTempSetpoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTempSetpoint.setText("LP Temp Setp.");
        jLabelTempSetpoint.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelTempSetpoint.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelTempSetpoint.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelTempSetpoint.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelTempSetpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 228, 88, 14));

        integralSwitchReheaterSteam.setComponent("Turbine#ReheaterTrimValve");
        add(integralSwitchReheaterSteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 302, -1, -1));

        jLabelCaptionReheatTrim1.setFont(jLabelCaptionReheatTrim1.getFont().deriveFont(jLabelCaptionReheatTrim1.getFont().getSize()-2f));
        jLabelCaptionReheatTrim1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionReheatTrim1.setText("Reheater");
        jLabelCaptionReheatTrim1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionReheatTrim1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionReheatTrim1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionReheatTrim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 272, 84, 14));

        jLabelCaptionReheatTrim2.setFont(jLabelCaptionReheatTrim2.getFont().deriveFont(jLabelCaptionReheatTrim2.getFont().getSize()-2f));
        jLabelCaptionReheatTrim2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionReheatTrim2.setText("Steam Trim");
        jLabelCaptionReheatTrim2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionReheatTrim2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionReheatTrim2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionReheatTrim2, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 284, 84, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTrip1CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrip1CloseActionPerformed
        controller.userAction(new ActionCommand("Turbine1#TripValve", false));
    }//GEN-LAST:event_jButtonTrip1CloseActionPerformed

    private void jButtonTrip1OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrip1OpenActionPerformed
        controller.userAction(new ActionCommand("Turbine1#TripValve", true));
    }//GEN-LAST:event_jButtonTrip1OpenActionPerformed

    private void jButtonLPShutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLPShutCloseActionPerformed
        controller.userAction(new ActionCommand("Turbine#LowPressureTripValve", false));
    }//GEN-LAST:event_jButtonLPShutCloseActionPerformed

    private void jButtenLPShutOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtenLPShutOpenActionPerformed
        controller.userAction(new ActionCommand("Turbine#LowPressureTripValve", true));
    }//GEN-LAST:event_jButtenLPShutOpenActionPerformed

    private void jButtonSuperheaterShutoffCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuperheaterShutoffCloseActionPerformed
        controller.userAction(new ActionCommand("Turbine#ReheaterTripValve", false));
    }//GEN-LAST:event_jButtonSuperheaterShutoffCloseActionPerformed

    private void jButtonSuperheaterShutoffOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuperheaterShutoffOpenActionPerformed
        controller.userAction(new ActionCommand("Turbine#ReheaterTripValve", true));
    }//GEN-LAST:event_jButtonSuperheaterShutoffOpenActionPerformed

    private void jButtonProtectionRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProtectionRestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProtectionRestActionPerformed

    private void jButtonProtectionTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProtectionTripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProtectionTripActionPerformed

    private void jToggleButtonTurboSetpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTurboSetpointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonTurboSetpointActionPerformed

    private void jButtonDrainsCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrainsCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDrainsCloseActionPerformed

    private void jButtenDrainsOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtenDrainsOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtenDrainsOpenActionPerformed

    private void jButtonTrip2CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrip2CloseActionPerformed
        controller.userAction(new ActionCommand("Turbine2#TripValve", false));
    }//GEN-LAST:event_jButtonTrip2CloseActionPerformed

    private void jButtonTrip2OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrip2OpenActionPerformed
        controller.userAction(new ActionCommand("Turbine2#TripValve", true));
    }//GEN-LAST:event_jButtonTrip2OpenActionPerformed

    private void jToggleButtonAutoDrain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAutoDrain2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonAutoDrain2ActionPerformed

    private void jToggleButtonPumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPumpActionPerformed

    }//GEN-LAST:event_jToggleButtonPumpActionPerformed

    private void jToggleButtonPump1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPump1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPump1ActionPerformed

    private void jToggleButtonPump2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPump2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPump2ActionPerformed

    private void jToggleButtonTurningGearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTurningGearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonTurningGearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed1Flow;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed1Temp;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed1Temp1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Flow;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Flow1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp2;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp3;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeOilPressure;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopStartupValve1;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopStartupValve2;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValve3;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValve4;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveCondToDA1;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveCondToDA2;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveCondToHotwell;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveReheater1;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveReheater2;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchReheaterSteam;
    private javax.swing.JButton jButtenDrainsOpen;
    private javax.swing.JButton jButtenLPShutOpen;
    private javax.swing.JButton jButtonDrainsClose;
    private javax.swing.JButton jButtonLPShutClose;
    private javax.swing.JButton jButtonProtectionRest;
    private javax.swing.JButton jButtonProtectionTrip;
    private javax.swing.JButton jButtonSuperheaterShutoffClose;
    private javax.swing.JButton jButtonSuperheaterShutoffOpen;
    private javax.swing.JButton jButtonTrip1Close;
    private javax.swing.JButton jButtonTrip1Open;
    private javax.swing.JButton jButtonTrip2Close;
    private javax.swing.JButton jButtonTrip2Open;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCaption1;
    private javax.swing.JLabel jLabelCaption10;
    private javax.swing.JLabel jLabelCaption2;
    private javax.swing.JLabel jLabelCaption3;
    private javax.swing.JLabel jLabelCaption4;
    private javax.swing.JLabel jLabelCaption5;
    private javax.swing.JLabel jLabelCaption6;
    private javax.swing.JLabel jLabelCaption7;
    private javax.swing.JLabel jLabelCaption8;
    private javax.swing.JLabel jLabelCaption9;
    private javax.swing.JLabel jLabelCaptionAuxLubeOil;
    private javax.swing.JLabel jLabelCaptionDrains1;
    private javax.swing.JLabel jLabelCaptionDrains2;
    private javax.swing.JLabel jLabelCaptionLPShut1;
    private javax.swing.JLabel jLabelCaptionLPShut10;
    private javax.swing.JLabel jLabelCaptionLPShut5;
    private javax.swing.JLabel jLabelCaptionLPShut7;
    private javax.swing.JLabel jLabelCaptionReheatTrim1;
    private javax.swing.JLabel jLabelCaptionReheatTrim2;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl1;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl2;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl4;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl5;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl6;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl7;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl8;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl9;
    private javax.swing.JLabel jLabelCaptionTG1;
    private javax.swing.JLabel jLabelCaptionTG2;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond1;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond2;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond3;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond4;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond5;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond6;
    private javax.swing.JLabel jLabelTempSetpoint;
    private javax.swing.JLabel jLabelTempSetpoint1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButtonAutoDrain2;
    private javax.swing.JToggleButton jToggleButtonPump;
    private javax.swing.JToggleButton jToggleButtonPump1;
    private javax.swing.JToggleButton jToggleButtonPump2;
    private javax.swing.JToggleButton jToggleButtonTurboSetpoint;
    private javax.swing.JToggleButton jToggleButtonTurningGear;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService1;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService2;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService4;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady1;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady2;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady4;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbSpeed6;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControlLevel;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControlTemperature;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        controlLoopStartupValve1.updateComponent(evt);
        controlLoopStartupValve2.updateComponent(evt);
        controlLoopValveReheater1.updateComponent(evt);
        controlLoopValveReheater2.updateComponent(evt);
        controlLoopValve3.updateComponent(evt);
        controlLoopValve4.updateComponent(evt);
        integralSwitchReheaterSteam.updateComponent(evt);
        setpointControlTemperature.updateComponent(evt);
        controlLoopValveCondToHotwell.updateComponent(evt);
        controlLoopValveCondToDA1.updateComponent(evt);
        controlLoopValveCondToDA2.updateComponent(evt);
        switch (evt.getPropertyName()) {
            case "Turbine#ReheaterTripValve_Pos":
                setValveButtons(jButtonSuperheaterShutoffClose,
                        jButtonSuperheaterShutoffOpen, evt.getNewValue());
                break;
            case "Turbine1#TripValve_Pos":
                setValveButtons(jButtonTrip1Close,
                        jButtonTrip1Open, evt.getNewValue());
                break;
            case "Turbine2#TripValve_Pos":
                setValveButtons(jButtonTrip2Close,
                        jButtonTrip2Open, evt.getNewValue());
                break;
            case "Turbine#LowPressureTripValve_Pos":
                setValveButtons(jButtonLPShutClose,
                        jButtenLPShutOpen, evt.getNewValue());
                break;
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        controlLoopStartupValve1.updateComponent(propertyName, newValue);
        controlLoopStartupValve2.updateComponent(propertyName, newValue);
        controlLoopValveReheater1.updateComponent(propertyName, newValue);
        controlLoopValveReheater2.updateComponent(propertyName, newValue);
        controlLoopValve3.updateComponent(propertyName, newValue);
        controlLoopValve4.updateComponent(propertyName, newValue);
        setpointControlTemperature.updateComponent(propertyName, newValue);
        controlLoopValveCondToDA1.updateComponent(propertyName, newValue);
        controlLoopValveCondToDA2.updateComponent(propertyName, newValue);
        controlLoopValveCondToHotwell.updateComponent(propertyName, newValue);
        setpointControlLevel.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
