/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author viktor
 */
public class PanelTurbine extends AbstractPanelWidget
        implements UpdateReceiver {

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);

        controlLoopHotwellDrain.registerActionReceiver(controller);
        controlLoopStartupValve1.registerActionReceiver(controller);
        controlLoopStartupValve2.registerActionReceiver(controller);
        controlLoopValve3.registerActionReceiver(controller);
        controlLoopValve4.registerActionReceiver(controller);
        controlLoopValveSteamIn.registerActionReceiver(controller);
        setpointControlTemperature.registerActionReceiver(controller);
        integralSwitch1.registerActionReceiver(controller);
        integralSwitch2.registerActionReceiver(controller);
    }

    /**
     * Creates new form PanelTurbine
     */
    public PanelTurbine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lightBulbSpeed1 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jButtonSpeed1 = new javax.swing.JButton();
        lightBulbSpeed2 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jButtonSpeed2 = new javax.swing.JButton();
        lightBulbSpeed3 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jButtonSpeed3 = new javax.swing.JButton();
        lightBulbSpeed4 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jButtonSpeed4 = new javax.swing.JButton();
        lightBulbSpeed5 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jButtonSpeed5 = new javax.swing.JButton();
        lightBulbSpeedGradient1 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jButtonSpeedGradient1 = new javax.swing.JButton();
        lightBulbSpeedGradient2 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jButtonSpeedGradient2 = new javax.swing.JButton();
        lightBulbSpeedGradient3 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jButtonSpeedGradient3 = new javax.swing.JButton();
        jLabelReadingActiveSpeedSetpoint = new javax.swing.JLabel();
        jLabelCaptionAZ7 = new javax.swing.JLabel();
        jLabelCaptionAZ9 = new javax.swing.JLabel();
        jLabelCaptionAZ10 = new javax.swing.JLabel();
        jLabelCaptionAZ11 = new javax.swing.JLabel();
        jLabelCaptionAZ12 = new javax.swing.JLabel();
        jLabelCaptionAZ13 = new javax.swing.JLabel();
        jLabelCaptionAZ14 = new javax.swing.JLabel();
        jLabelCaptionAZ15 = new javax.swing.JLabel();
        jLabelCaptionAZ16 = new javax.swing.JLabel();
        jLabelCaptionHPShut1 = new javax.swing.JLabel();
        jLabelCaptionHPShut2 = new javax.swing.JLabel();
        jButtonHPShutClose = new javax.swing.JButton();
        jButtonHPShutOpen = new javax.swing.JButton();
        jLabelCaptionLPShut1 = new javax.swing.JLabel();
        jLabelCaptionLPShut2 = new javax.swing.JLabel();
        jButtonLPShutClose = new javax.swing.JButton();
        jButtenLPShutOpen = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        setpointControlTemperature = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        jLabelTempSetpoint = new javax.swing.JLabel();
        controlLoopValveSteamIn = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        jLabelCaptionSuperheaterShutoff = new javax.swing.JLabel();
        jButtonSuperheaterShutoffClose = new javax.swing.JButton();
        jButtonSuperheaterShutoffOpen = new javax.swing.JButton();
        controlLoopHotwellDrain = new com.hartrusion.rbmksim.gui.elements.ControlLoop();
        jLabelCaptionsuperheaterCond2 = new javax.swing.JLabel();
        jLabelCaptionsuperheaterCond1 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterCondShutoff = new javax.swing.JLabel();
        jButtonSuperheaterCondShutoffClose = new javax.swing.JButton();
        jButtonSuperheaterCondShutoffOpen = new javax.swing.JButton();
        jLabelCaptionSuperheaterControl = new javax.swing.JLabel();
        jLabelCaption1 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl1 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl2 = new javax.swing.JLabel();
        jButtonProtectionRest = new javax.swing.JButton();
        jButtonProtectionTrip = new javax.swing.JButton();
        lightBulbSpeed6 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jLabelCaption2 = new javax.swing.JLabel();
        jLabelCaption3 = new javax.swing.JLabel();
        controlLoopStartupValve1 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopStartupValve2 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopValve3 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        controlLoopValve4 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chornobylGaugeFeed1Temp = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeFeed1Flow = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeFeed2Flow = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeFeed2Flow1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        chornobylGaugeFeed1Temp1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp2 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp3 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabelCaptionSuperheaterControl3 = new javax.swing.JLabel();
        jLabelCaption4 = new javax.swing.JLabel();
        integralSwitch1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitch2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        jLabelCaption5 = new javax.swing.JLabel();
        jLabelCaption6 = new javax.swing.JLabel();
        jLabelCaptionSuperheaterControl4 = new javax.swing.JLabel();
        jLabelCaption7 = new javax.swing.JLabel();
        jToggleButtonAutoDrain1 = new javax.swing.JToggleButton();
        jToggleButtonPump = new javax.swing.JToggleButton();
        lightBulbReady = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jToggleButtonPump1 = new javax.swing.JToggleButton();
        lightBulbReady1 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService1 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jToggleButtonPump2 = new javax.swing.JToggleButton();
        lightBulbReady2 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService2 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jLabelCaptionSuperheaterControl5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        chornobylGaugeFeed2Temp4 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabelCaptionLPShut3 = new javax.swing.JLabel();
        jLabelCaptionLPShut4 = new javax.swing.JLabel();
        jButtonLPShutClose1 = new javax.swing.JButton();
        jButtenLPShutOpen1 = new javax.swing.JButton();
        jLabelCaptionSuperheaterControl6 = new javax.swing.JLabel();
        jToggleButtonPump3 = new javax.swing.JToggleButton();
        lightBulbReady3 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService3 = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        jLabelCaptionLPShut5 = new javax.swing.JLabel();
        jLabelCaptionLPShut6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(580, 340));
        setPreferredSize(new java.awt.Dimension(580, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lightBulbSpeed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 28, -1, -1));

        jButtonSpeed1.setFont(jButtonSpeed1.getFont().deriveFont(jButtonSpeed1.getFont().getSize()-2f));
        jButtonSpeed1.setText("●");
        jButtonSpeed1.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonSpeed1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSpeed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeed1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSpeed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 20, 20));
        jPanel1.add(lightBulbSpeed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 28, -1, -1));

        jButtonSpeed2.setFont(jButtonSpeed2.getFont().deriveFont(jButtonSpeed2.getFont().getSize()-2f));
        jButtonSpeed2.setText("●");
        jButtonSpeed2.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonSpeed2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSpeed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeed2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSpeed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 22, 20, 20));
        jPanel1.add(lightBulbSpeed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 28, -1, -1));

        jButtonSpeed3.setFont(jButtonSpeed3.getFont().deriveFont(jButtonSpeed3.getFont().getSize()-2f));
        jButtonSpeed3.setText("●");
        jButtonSpeed3.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonSpeed3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSpeed3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeed3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSpeed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 22, 20, 20));
        jPanel1.add(lightBulbSpeed4, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 28, -1, -1));

        jButtonSpeed4.setFont(jButtonSpeed4.getFont().deriveFont(jButtonSpeed4.getFont().getSize()-2f));
        jButtonSpeed4.setText("●");
        jButtonSpeed4.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonSpeed4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSpeed4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeed4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSpeed4, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 22, 20, 20));
        jPanel1.add(lightBulbSpeed5, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 28, -1, -1));

        jButtonSpeed5.setFont(jButtonSpeed5.getFont().deriveFont(jButtonSpeed5.getFont().getSize()-2f));
        jButtonSpeed5.setText("●");
        jButtonSpeed5.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonSpeed5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSpeed5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeed5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSpeed5, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 22, 20, 20));
        jPanel1.add(lightBulbSpeedGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 70, -1, -1));

        jButtonSpeedGradient1.setFont(jButtonSpeedGradient1.getFont().deriveFont(jButtonSpeedGradient1.getFont().getSize()-2f));
        jButtonSpeedGradient1.setText("●");
        jButtonSpeedGradient1.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonSpeedGradient1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSpeedGradient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeedGradient1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSpeedGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 20, 20));
        jPanel1.add(lightBulbSpeedGradient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jButtonSpeedGradient2.setFont(jButtonSpeedGradient2.getFont().deriveFont(jButtonSpeedGradient2.getFont().getSize()-2f));
        jButtonSpeedGradient2.setText("●");
        jButtonSpeedGradient2.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonSpeedGradient2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSpeedGradient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeedGradient2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSpeedGradient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 64, 20, 20));
        jPanel1.add(lightBulbSpeedGradient3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 70, -1, -1));

        jButtonSpeedGradient3.setFont(jButtonSpeedGradient3.getFont().deriveFont(jButtonSpeedGradient3.getFont().getSize()-2f));
        jButtonSpeedGradient3.setText("●");
        jButtonSpeedGradient3.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonSpeedGradient3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSpeedGradient3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeedGradient3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSpeedGradient3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 64, 20, 20));

        jLabelReadingActiveSpeedSetpoint.setBackground(new java.awt.Color(51, 51, 51));
        jLabelReadingActiveSpeedSetpoint.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingActiveSpeedSetpoint.setForeground(new java.awt.Color(0, 255, 153));
        jLabelReadingActiveSpeedSetpoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingActiveSpeedSetpoint.setText("___,_");
        jLabelReadingActiveSpeedSetpoint.setToolTipText("Active setpoint which the global control is currently using");
        jLabelReadingActiveSpeedSetpoint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelReadingActiveSpeedSetpoint.setMaximumSize(new java.awt.Dimension(52, 18));
        jLabelReadingActiveSpeedSetpoint.setMinimumSize(new java.awt.Dimension(52, 18));
        jLabelReadingActiveSpeedSetpoint.setOpaque(true);
        jLabelReadingActiveSpeedSetpoint.setPreferredSize(new java.awt.Dimension(52, 18));
        jPanel1.add(jLabelReadingActiveSpeedSetpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 66, 48, -1));

        jLabelCaptionAZ7.setFont(jLabelCaptionAZ7.getFont().deriveFont(jLabelCaptionAZ7.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionAZ7.getFont().getSize()-2));
        jLabelCaptionAZ7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionAZ7.setText("750");
        jLabelCaptionAZ7.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionAZ7.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ7.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ7.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionAZ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 6, 28, -1));

        jLabelCaptionAZ9.setFont(jLabelCaptionAZ9.getFont().deriveFont(jLabelCaptionAZ9.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionAZ9.getFont().getSize()-2));
        jLabelCaptionAZ9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionAZ9.setText("0");
        jLabelCaptionAZ9.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionAZ9.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ9.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ9.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionAZ9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 28, -1));

        jLabelCaptionAZ10.setFont(jLabelCaptionAZ10.getFont().deriveFont(jLabelCaptionAZ10.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionAZ10.getFont().getSize()-2));
        jLabelCaptionAZ10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionAZ10.setText("3000");
        jLabelCaptionAZ10.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionAZ10.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ10.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ10.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionAZ10, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 6, 28, -1));

        jLabelCaptionAZ11.setFont(jLabelCaptionAZ11.getFont().deriveFont(jLabelCaptionAZ11.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionAZ11.getFont().getSize()-2));
        jLabelCaptionAZ11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionAZ11.setText("1500");
        jLabelCaptionAZ11.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionAZ11.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ11.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ11.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionAZ11, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 6, 28, -1));

        jLabelCaptionAZ12.setFont(jLabelCaptionAZ12.getFont().deriveFont(jLabelCaptionAZ12.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionAZ12.getFont().getSize()-2));
        jLabelCaptionAZ12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionAZ12.setText("2250");
        jLabelCaptionAZ12.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionAZ12.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ12.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ12.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionAZ12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 6, 28, -1));

        jLabelCaptionAZ13.setFont(jLabelCaptionAZ13.getFont().deriveFont(jLabelCaptionAZ13.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionAZ13.getFont().getSize()-2));
        jLabelCaptionAZ13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionAZ13.setText("Slow");
        jLabelCaptionAZ13.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionAZ13.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ13.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ13.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionAZ13, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 48, 36, -1));

        jLabelCaptionAZ14.setFont(jLabelCaptionAZ14.getFont().deriveFont(jLabelCaptionAZ14.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionAZ14.getFont().getSize()-2));
        jLabelCaptionAZ14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionAZ14.setText("Med");
        jLabelCaptionAZ14.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionAZ14.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ14.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ14.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionAZ14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 48, 36, -1));

        jLabelCaptionAZ15.setFont(jLabelCaptionAZ15.getFont().deriveFont(jLabelCaptionAZ15.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionAZ15.getFont().getSize()-2));
        jLabelCaptionAZ15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionAZ15.setText("Setpoint");
        jLabelCaptionAZ15.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionAZ15.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ15.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ15.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionAZ15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 64, -1));

        jLabelCaptionAZ16.setFont(jLabelCaptionAZ16.getFont().deriveFont(jLabelCaptionAZ16.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaptionAZ16.getFont().getSize()-2));
        jLabelCaptionAZ16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionAZ16.setText("Fast");
        jLabelCaptionAZ16.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionAZ16.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ16.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionAZ16.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionAZ16, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 48, 36, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, 200, 96));

        jLabelCaptionHPShut1.setFont(jLabelCaptionHPShut1.getFont().deriveFont(jLabelCaptionHPShut1.getFont().getSize()-2f));
        jLabelCaptionHPShut1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionHPShut1.setText("HP Trip");
        jLabelCaptionHPShut1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionHPShut1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionHPShut1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionHPShut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 228, 51, 14));

        jLabelCaptionHPShut2.setFont(jLabelCaptionHPShut2.getFont().deriveFont(jLabelCaptionHPShut2.getFont().getSize()-2f));
        jLabelCaptionHPShut2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionHPShut2.setText("Valve");
        jLabelCaptionHPShut2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionHPShut2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionHPShut2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionHPShut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 240, 51, 14));

        jButtonHPShutClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonHPShutClose.setText("C");
        jButtonHPShutClose.setToolTipText("");
        jButtonHPShutClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonHPShutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPShutCloseActionPerformed(evt);
            }
        });
        add(jButtonHPShutClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 254, 20, 20));

        jButtonHPShutOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonHPShutOpen.setText("O");
        jButtonHPShutOpen.setToolTipText("");
        jButtonHPShutOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonHPShutOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHPShutOpenActionPerformed(evt);
            }
        });
        add(jButtonHPShutOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 254, 20, 20));

        jLabelCaptionLPShut1.setFont(jLabelCaptionLPShut1.getFont().deriveFont(jLabelCaptionLPShut1.getFont().getSize()-2f));
        jLabelCaptionLPShut1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut1.setText("LP Trip");
        jLabelCaptionLPShut1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 282, 51, 14));

        jLabelCaptionLPShut2.setFont(jLabelCaptionLPShut2.getFont().deriveFont(jLabelCaptionLPShut2.getFont().getSize()-2f));
        jLabelCaptionLPShut2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut2.setText("Valve");
        jLabelCaptionLPShut2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 294, 51, 14));

        jButtonLPShutClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLPShutClose.setText("C");
        jButtonLPShutClose.setToolTipText("");
        jButtonLPShutClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLPShutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLPShutCloseActionPerformed(evt);
            }
        });
        add(jButtonLPShutClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 308, 20, 20));

        jButtenLPShutOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtenLPShutOpen.setText("O");
        jButtenLPShutOpen.setToolTipText("");
        jButtenLPShutOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtenLPShutOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtenLPShutOpenActionPerformed(evt);
            }
        });
        add(jButtenLPShutOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 308, 20, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(setpointControlTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 24, -1, -1));

        jLabelTempSetpoint.setFont(jLabelTempSetpoint.getFont().deriveFont(jLabelTempSetpoint.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelTempSetpoint.getFont().getSize()-2));
        jLabelTempSetpoint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTempSetpoint.setText("Setpoint");
        jLabelTempSetpoint.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelTempSetpoint.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelTempSetpoint.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelTempSetpoint.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel2.add(jLabelTempSetpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 88, -1));

        controlLoopValveSteamIn.setComponent("Turbine#ReheaterPriControlValve");
        jPanel2.add(controlLoopValveSteamIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 10, -1, -1));

        jLabelCaptionSuperheaterShutoff.setFont(jLabelCaptionSuperheaterShutoff.getFont().deriveFont(jLabelCaptionSuperheaterShutoff.getFont().getSize()-2f));
        jLabelCaptionSuperheaterShutoff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterShutoff.setText("Trip Vlv");
        jLabelCaptionSuperheaterShutoff.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterShutoff.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterShutoff.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel2.add(jLabelCaptionSuperheaterShutoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 10, 51, -1));

        jButtonSuperheaterShutoffClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonSuperheaterShutoffClose.setText("C");
        jButtonSuperheaterShutoffClose.setToolTipText("");
        jButtonSuperheaterShutoffClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSuperheaterShutoffClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuperheaterShutoffCloseActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSuperheaterShutoffClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 24, 20, 20));

        jButtonSuperheaterShutoffOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonSuperheaterShutoffOpen.setText("O");
        jButtonSuperheaterShutoffOpen.setToolTipText("");
        jButtonSuperheaterShutoffOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSuperheaterShutoffOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuperheaterShutoffOpenActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSuperheaterShutoffOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 24, 20, 20));

        controlLoopHotwellDrain.setControlComponent("Turbine#ReheaterCondensateValve");
        controlLoopHotwellDrain.setFeedbackComponent("unknown");
        controlLoopHotwellDrain.setSetpointComponent("unknown");
        controlLoopHotwellDrain.setToolTipText("");
        jPanel2.add(controlLoopHotwellDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 52, -1, -1));

        jLabelCaptionsuperheaterCond2.setFont(jLabelCaptionsuperheaterCond2.getFont().deriveFont(jLabelCaptionsuperheaterCond2.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond2.setText("Level");
        jPanel2.add(jLabelCaptionsuperheaterCond2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 72, 50, 14));

        jLabelCaptionsuperheaterCond1.setFont(jLabelCaptionsuperheaterCond1.getFont().deriveFont(jLabelCaptionsuperheaterCond1.getFont().getSize()-2f));
        jLabelCaptionsuperheaterCond1.setText("Cond.");
        jPanel2.add(jLabelCaptionsuperheaterCond1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 58, 50, 14));

        jLabelCaptionSuperheaterCondShutoff.setFont(jLabelCaptionSuperheaterCondShutoff.getFont().deriveFont(jLabelCaptionSuperheaterCondShutoff.getFont().getSize()-2f));
        jLabelCaptionSuperheaterCondShutoff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterCondShutoff.setText("Trip vlv");
        jLabelCaptionSuperheaterCondShutoff.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterCondShutoff.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterCondShutoff.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel2.add(jLabelCaptionSuperheaterCondShutoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 52, 51, -1));

        jButtonSuperheaterCondShutoffClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonSuperheaterCondShutoffClose.setText("C");
        jButtonSuperheaterCondShutoffClose.setToolTipText("");
        jButtonSuperheaterCondShutoffClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSuperheaterCondShutoffClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuperheaterCondShutoffCloseActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSuperheaterCondShutoffClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 66, 20, 20));

        jButtonSuperheaterCondShutoffOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonSuperheaterCondShutoffOpen.setText("O");
        jButtonSuperheaterCondShutoffOpen.setToolTipText("");
        jButtonSuperheaterCondShutoffOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSuperheaterCondShutoffOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuperheaterCondShutoffOpenActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSuperheaterCondShutoffOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 66, 20, 20));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 238, 266, 96));

        jLabelCaptionSuperheaterControl.setFont(jLabelCaptionSuperheaterControl.getFont().deriveFont(jLabelCaptionSuperheaterControl.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl.setText("Reheater Temperature Control");
        jLabelCaptionSuperheaterControl.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 222, 262, 14));

        jLabelCaption1.setFont(jLabelCaption1.getFont().deriveFont(jLabelCaption1.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption1.getFont().getSize()-2));
        jLabelCaption1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption1.setText("Main Valves");
        jLabelCaption1.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 114, 90, 14));

        jLabelCaptionSuperheaterControl1.setFont(jLabelCaptionSuperheaterControl1.getFont().deriveFont(jLabelCaptionSuperheaterControl1.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl1.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl1.setText("High Pressure Valve Controls");
        jLabelCaptionSuperheaterControl1.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl1.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 98, 196, 14));

        jLabelCaptionSuperheaterControl2.setFont(jLabelCaptionSuperheaterControl2.getFont().deriveFont(jLabelCaptionSuperheaterControl2.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl2.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl2.setText("Setpoint");
        jLabelCaptionSuperheaterControl2.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 164, 56, 14));

        jButtonProtectionRest.setFont(jButtonProtectionRest.getFont().deriveFont(jButtonProtectionRest.getFont().getSize()-2f));
        jButtonProtectionRest.setText("●");
        jButtonProtectionRest.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonProtectionRest.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonProtectionRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProtectionRestActionPerformed(evt);
            }
        });
        add(jButtonProtectionRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 132, 20, 20));

        jButtonProtectionTrip.setFont(jButtonProtectionTrip.getFont().deriveFont(jButtonProtectionTrip.getFont().getSize()-2f));
        jButtonProtectionTrip.setText("●");
        jButtonProtectionTrip.setToolTipText("Start auto control. Push this button to start controlling the rods after enabling the global control and selecting the rods.");
        jButtonProtectionTrip.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonProtectionTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProtectionTripActionPerformed(evt);
            }
        });
        add(jButtonProtectionTrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 132, 20, 20));

        lightBulbSpeed6.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbSpeed6, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 138, -1, -1));

        jLabelCaption2.setFont(jLabelCaption2.getFont().deriveFont(jLabelCaption2.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption2.getFont().getSize()-2));
        jLabelCaption2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption2.setText("Reset");
        jLabelCaption2.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption2.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 116, 32, 14));

        jLabelCaption3.setFont(jLabelCaption3.getFont().deriveFont(jLabelCaption3.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption3.getFont().getSize()-2));
        jLabelCaption3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption3.setText("Trip");
        jLabelCaption3.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 116, 32, 14));

        controlLoopStartupValve1.setComponent("Turbine1#StartupSteamValve");
        add(controlLoopStartupValve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 130, -1, -1));

        controlLoopStartupValve2.setComponent("Turbine2#StartupSteamValve");
        add(controlLoopStartupValve2, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 172, -1, -1));

        controlLoopValve3.setComponent("Turbine1#MainSteamValve");
        add(controlLoopValve3, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 130, -1, -1));

        controlLoopValve4.setComponent("Turbine2#MainSteamValve");
        add(controlLoopValve4, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 172, -1, -1));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()-2f));
        jLabel5.setText("Turbine");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 52, 14));

        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getSize()-2f));
        jLabel20.setText("Speed");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 52, 14));

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()-2f));
        jLabel7.setText("HP");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 52, 14));

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getSize()-2f));
        jLabel19.setText("Flow");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 52, 14));

        chornobylGaugeFeed1Temp.setChornobylMaximum(200.0F);
        chornobylGaugeFeed1Temp.setChornobylMinimum(20.0F);
        chornobylGaugeFeed1Temp.setChornobylTicks(new float[] {50.0f, 100.0f, 150.0f});
        chornobylGaugeFeed1Temp.setChornobylUnitText("°C");
        add(chornobylGaugeFeed1Temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 34, -1, -1));

        chornobylGaugeFeed1Flow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeFeed1Flow.setChornobylMaximum(3200.0F);
        chornobylGaugeFeed1Flow.setChornobylMinimum(0.0F);
        chornobylGaugeFeed1Flow.setChornobylTicks(new float[] {500.0f, 1500.0f, 3000.0f});
        chornobylGaugeFeed1Flow.setChornobylUnitText("1/min");
        add(chornobylGaugeFeed1Flow, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, -1, -1));

        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getSize()-2f));
        jLabel24.setText("HP Case");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 4, 52, 14));

        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getSize()-2f));
        jLabel18.setText("Temp");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 16, 52, 14));

        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getSize()-2f));
        jLabel23.setText("HP Rotor");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 34, 52, 14));

        jLabel17.setFont(jLabel17.getFont().deriveFont(jLabel17.getFont().getSize()-2f));
        jLabel17.setText("Temp");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 46, 52, 14));

        chornobylGaugeFeed2Temp.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Temp.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Temp.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Temp.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 34, -1, -1));

        chornobylGaugeFeed2Flow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeFeed2Flow.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Flow.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Flow.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Flow.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Flow, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 4, -1, -1));

        jLabel25.setFont(jLabel25.getFont().deriveFont(jLabel25.getFont().getSize()-2f));
        jLabel25.setText("LP Case");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 4, 52, 14));

        jLabel21.setFont(jLabel21.getFont().deriveFont(jLabel21.getFont().getSize()-2f));
        jLabel21.setText("Temp");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 16, 52, 14));

        jLabel26.setFont(jLabel26.getFont().deriveFont(jLabel26.getFont().getSize()-2f));
        jLabel26.setText("LP Rotor");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 34, 52, 14));

        jLabel22.setFont(jLabel22.getFont().deriveFont(jLabel22.getFont().getSize()-2f));
        jLabel22.setText("Temp");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 46, 52, 14));

        chornobylGaugeFeed2Temp1.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Temp1.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Temp1.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Temp1.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Temp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 34, -1, -1));

        chornobylGaugeFeed2Flow1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeFeed2Flow1.setChornobylMaximum(300.0F);
        chornobylGaugeFeed2Flow1.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Flow1.setChornobylTicks(new float[] {100.0f, 200.0f, 300.0f});
        chornobylGaugeFeed2Flow1.setChornobylUnitText("°C");
        add(chornobylGaugeFeed2Flow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 4, -1, -1));

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()-2f));
        jLabel8.setText("Total");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 52, 14));

        jLabel27.setFont(jLabel27.getFont().deriveFont(jLabel27.getFont().getSize()-2f));
        jLabel27.setText("Expans.");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, 52, 14));

        chornobylGaugeFeed1Temp1.setChornobylMaximum(50.0F);
        chornobylGaugeFeed1Temp1.setChornobylMinimum(0.0F);
        chornobylGaugeFeed1Temp1.setChornobylTicks(new float[] {0.0f, 10.0f, 20.0f, 30.0f, 40.0f});
        chornobylGaugeFeed1Temp1.setChornobylUnitText("mm");
        chornobylGaugeFeed1Temp1.setChornobylValue(0.0F);
        add(chornobylGaugeFeed1Temp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 64, -1, -1));

        jLabel28.setFont(jLabel28.getFont().deriveFont(jLabel28.getFont().getSize()-2f));
        jLabel28.setText("HP Diff");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 64, 52, 14));

        jLabel29.setFont(jLabel29.getFont().deriveFont(jLabel29.getFont().getSize()-2f));
        jLabel29.setText("Expans.");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 76, 52, 14));

        chornobylGaugeFeed2Temp2.setChornobylMaximum(4.0F);
        chornobylGaugeFeed2Temp2.setChornobylMinimum(-2.0F);
        chornobylGaugeFeed2Temp2.setChornobylTicks(new float[] {-1.0f, 0.0f, 1.0f, 2.0f});
        chornobylGaugeFeed2Temp2.setChornobylUnitText("mm");
        chornobylGaugeFeed2Temp2.setChornobylValue(0.0F);
        add(chornobylGaugeFeed2Temp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 64, -1, -1));

        jLabel30.setFont(jLabel30.getFont().deriveFont(jLabel30.getFont().getSize()-2f));
        jLabel30.setText("LP Diff");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 64, 52, 14));

        jLabel31.setFont(jLabel31.getFont().deriveFont(jLabel31.getFont().getSize()-2f));
        jLabel31.setText("Expans.");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 76, 52, 14));

        chornobylGaugeFeed2Temp3.setChornobylMaximum(6.0F);
        chornobylGaugeFeed2Temp3.setChornobylMinimum(-3.0F);
        chornobylGaugeFeed2Temp3.setChornobylTicks(new float[] {-2.5f, 0.0f, 2.5f, 5.0f});
        chornobylGaugeFeed2Temp3.setChornobylUnitText("mm");
        chornobylGaugeFeed2Temp3.setChornobylValue(0.0F);
        add(chornobylGaugeFeed2Temp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 64, -1, -1));

        jLabelCaptionSuperheaterControl3.setFont(jLabelCaptionSuperheaterControl3.getFont().deriveFont(jLabelCaptionSuperheaterControl3.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl3.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl3.setText("Startup Speed Setpoint");
        jLabelCaptionSuperheaterControl3.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 100, 196, 14));

        jLabelCaption4.setFont(jLabelCaption4.getFont().deriveFont(jLabelCaption4.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption4.getFont().getSize()-2));
        jLabelCaption4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption4.setText("2");
        jLabelCaption4.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption4.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption4.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption4.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 186, 22, 14));

        integralSwitch1.setComponent("Turbine1#StartupShutoffValve");
        add(integralSwitch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 136, -1, -1));

        integralSwitch2.setComponent("Turbine2#StartupShutoffValve");
        add(integralSwitch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 178, -1, -1));

        jLabelCaption5.setFont(jLabelCaption5.getFont().deriveFont(jLabelCaption5.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption5.getFont().getSize()-2));
        jLabelCaption5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption5.setText("Startup Valves");
        jLabelCaption5.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption5, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 114, 106, 14));

        jLabelCaption6.setFont(jLabelCaption6.getFont().deriveFont(jLabelCaption6.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption6.getFont().getSize()-2));
        jLabelCaption6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption6.setText("Speed/Pressure");
        jLabelCaption6.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption6, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 202, 100, 14));

        jLabelCaptionSuperheaterControl4.setFont(jLabelCaptionSuperheaterControl4.getFont().deriveFont(jLabelCaptionSuperheaterControl4.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl4.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl4.setText("TPS");
        jLabelCaptionSuperheaterControl4.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl4.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl4.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl4.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 102, 56, 14));

        jLabelCaption7.setFont(jLabelCaption7.getFont().deriveFont(jLabelCaption7.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCaption7.getFont().getSize()-2));
        jLabelCaption7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaption7.setText("1");
        jLabelCaption7.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaption7.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaption7.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaption7.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaption7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 22, 14));

        jToggleButtonAutoDrain1.setText("←");
        jToggleButtonAutoDrain1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonAutoDrain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAutoDrain1ActionPerformed(evt);
            }
        });
        add(jToggleButtonAutoDrain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 180, 20, 20));

        jToggleButtonPump.setText("←");
        jToggleButtonPump.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPumpActionPerformed(evt);
            }
        });
        add(jToggleButtonPump, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 308, 20, 20));

        lightBulbReady.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 300, -1, -1));

        lightBulbInService.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 300, -1, -1));

        jToggleButtonPump1.setText("←");
        jToggleButtonPump1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPump1ActionPerformed(evt);
            }
        });
        add(jToggleButtonPump1, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 268, 20, 20));

        lightBulbReady1.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady1, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 260, -1, -1));

        lightBulbInService1.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService1, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 260, -1, -1));

        jToggleButtonPump2.setText("←");
        jToggleButtonPump2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPump2ActionPerformed(evt);
            }
        });
        add(jToggleButtonPump2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 268, 20, 20));

        lightBulbReady2.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady2, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 260, -1, -1));

        lightBulbInService2.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService2, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 260, -1, -1));

        jLabelCaptionSuperheaterControl5.setFont(jLabelCaptionSuperheaterControl5.getFont().deriveFont(jLabelCaptionSuperheaterControl5.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl5.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl5.setText("Hydraulic");
        jLabelCaptionSuperheaterControl5.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 308, -1, 14));

        jLabel32.setFont(jLabel32.getFont().deriveFont(jLabel32.getFont().getSize()-2f));
        jLabel32.setText("Oil");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 222, 32, 14));

        jLabel33.setFont(jLabel33.getFont().deriveFont(jLabel33.getFont().getSize()-2f));
        jLabel33.setText("press");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 234, 32, 14));

        chornobylGaugeFeed2Temp4.setChornobylMaximum(10.0F);
        chornobylGaugeFeed2Temp4.setChornobylMinimum(0.0F);
        chornobylGaugeFeed2Temp4.setChornobylTicks(new float[] {0.0f, 2.0f, 4.0f, 6.0f, 8.0f, 10.0f});
        chornobylGaugeFeed2Temp4.setChornobylUnitText("bar");
        chornobylGaugeFeed2Temp4.setChornobylValue(0.0F);
        add(chornobylGaugeFeed2Temp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 222, -1, -1));

        jLabelCaptionLPShut3.setFont(jLabelCaptionLPShut3.getFont().deriveFont(jLabelCaptionLPShut3.getFont().getSize()-2f));
        jLabelCaptionLPShut3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut3.setText("Steam");
        jLabelCaptionLPShut3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 282, 51, 14));

        jLabelCaptionLPShut4.setFont(jLabelCaptionLPShut4.getFont().deriveFont(jLabelCaptionLPShut4.getFont().getSize()-2f));
        jLabelCaptionLPShut4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut4.setText("Drains");
        jLabelCaptionLPShut4.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut4.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut4.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 294, 51, 14));

        jButtonLPShutClose1.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLPShutClose1.setText("C");
        jButtonLPShutClose1.setToolTipText("");
        jButtonLPShutClose1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLPShutClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLPShutClose1ActionPerformed(evt);
            }
        });
        add(jButtonLPShutClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 308, 20, 20));

        jButtenLPShutOpen1.setBackground(new java.awt.Color(128, 0, 0));
        jButtenLPShutOpen1.setText("O");
        jButtenLPShutOpen1.setToolTipText("");
        jButtenLPShutOpen1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtenLPShutOpen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtenLPShutOpen1ActionPerformed(evt);
            }
        });
        add(jButtenLPShutOpen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 308, 20, 20));

        jLabelCaptionSuperheaterControl6.setFont(jLabelCaptionSuperheaterControl6.getFont().deriveFont(jLabelCaptionSuperheaterControl6.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSuperheaterControl6.getFont().getSize()-2));
        jLabelCaptionSuperheaterControl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuperheaterControl6.setText("Aux lube oil");
        jLabelCaptionSuperheaterControl6.setToolTipText("Scrams the reactor by immediately inserting all rods");
        jLabelCaptionSuperheaterControl6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuperheaterControl6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuperheaterControl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 272, 68, 14));

        jToggleButtonPump3.setText("←");
        jToggleButtonPump3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPump3ActionPerformed(evt);
            }
        });
        add(jToggleButtonPump3, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 252, 20, 20));

        lightBulbReady3.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady3, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 244, -1, -1));

        lightBulbInService3.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService3, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 244, -1, -1));

        jLabelCaptionLPShut5.setFont(jLabelCaptionLPShut5.getFont().deriveFont(jLabelCaptionLPShut5.getFont().getSize()-2f));
        jLabelCaptionLPShut5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut5.setText("Turning");
        jLabelCaptionLPShut5.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut5.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut5.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut5, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 216, 51, 14));

        jLabelCaptionLPShut6.setFont(jLabelCaptionLPShut6.getFont().deriveFont(jLabelCaptionLPShut6.getFont().getSize()-2f));
        jLabelCaptionLPShut6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionLPShut6.setText("Gear");
        jLabelCaptionLPShut6.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut6.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionLPShut6.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionLPShut6, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 228, 51, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSpeed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeed1ActionPerformed
        controller.userAction(new ActionCommand("Reactor#GlobalControlAuto", null));
    }//GEN-LAST:event_jButtonSpeed1ActionPerformed

    private void jButtonSpeed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeed2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSpeed2ActionPerformed

    private void jButtonSpeed3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeed3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSpeed3ActionPerformed

    private void jButtonSpeed4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeed4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSpeed4ActionPerformed

    private void jButtonSpeed5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeed5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSpeed5ActionPerformed

    private void jButtonSpeedGradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeedGradient1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSpeedGradient1ActionPerformed

    private void jButtonSpeedGradient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeedGradient2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSpeedGradient2ActionPerformed

    private void jButtonSpeedGradient3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeedGradient3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSpeedGradient3ActionPerformed

    private void jButtonHPShutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPShutCloseActionPerformed
        controller.userAction(new ActionCommand("Turbine#HighPressureTripValve", false));
    }//GEN-LAST:event_jButtonHPShutCloseActionPerformed

    private void jButtonHPShutOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHPShutOpenActionPerformed
        controller.userAction(new ActionCommand("Turbine#HighPressureTripValve", true));
    }//GEN-LAST:event_jButtonHPShutOpenActionPerformed

    private void jButtonLPShutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLPShutCloseActionPerformed
        controller.userAction(new ActionCommand("Turbine#LowPressureTripValve", false));
    }//GEN-LAST:event_jButtonLPShutCloseActionPerformed

    private void jButtenLPShutOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtenLPShutOpenActionPerformed
        controller.userAction(new ActionCommand("Turbine#LowPressureTripValve", true));
    }//GEN-LAST:event_jButtenLPShutOpenActionPerformed

    private void jButtonSuperheaterCondShutoffCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuperheaterCondShutoffCloseActionPerformed
        controller.userAction(new ActionCommand("Turbine#ReheaterCondensateShutoffValve", false));
    }//GEN-LAST:event_jButtonSuperheaterCondShutoffCloseActionPerformed

    private void jButtonSuperheaterCondShutoffOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuperheaterCondShutoffOpenActionPerformed
        controller.userAction(new ActionCommand("Turbine#ReheaterCondensateShutoffValve", true));
    }//GEN-LAST:event_jButtonSuperheaterCondShutoffOpenActionPerformed

    private void jButtonSuperheaterShutoffCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuperheaterShutoffCloseActionPerformed
        controller.userAction(new ActionCommand("Turbine#ReheaterPriShutValve", false));
    }//GEN-LAST:event_jButtonSuperheaterShutoffCloseActionPerformed

    private void jButtonSuperheaterShutoffOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuperheaterShutoffOpenActionPerformed
        controller.userAction(new ActionCommand("Turbine#ReheaterPriShutValve", true));
    }//GEN-LAST:event_jButtonSuperheaterShutoffOpenActionPerformed

    private void jButtonProtectionRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProtectionRestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProtectionRestActionPerformed

    private void jButtonProtectionTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProtectionTripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProtectionTripActionPerformed

    private void jToggleButtonAutoDrain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAutoDrain1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonAutoDrain1ActionPerformed

    private void jToggleButtonPumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPumpActionPerformed

    }//GEN-LAST:event_jToggleButtonPumpActionPerformed

    private void jToggleButtonPump1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPump1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPump1ActionPerformed

    private void jToggleButtonPump2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPump2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPump2ActionPerformed

    private void jButtonLPShutClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLPShutClose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLPShutClose1ActionPerformed

    private void jButtenLPShutOpen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtenLPShutOpen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtenLPShutOpen1ActionPerformed

    private void jToggleButtonPump3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPump3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPump3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed1Flow;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed1Temp;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed1Temp1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Flow;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Flow1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp2;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp3;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeFeed2Temp4;
    private com.hartrusion.rbmksim.gui.elements.ControlLoop controlLoopHotwellDrain;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopStartupValve1;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopStartupValve2;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValve3;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValve4;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve controlLoopValveSteamIn;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitch2;
    private javax.swing.JButton jButtenLPShutOpen;
    private javax.swing.JButton jButtenLPShutOpen1;
    private javax.swing.JButton jButtonHPShutClose;
    private javax.swing.JButton jButtonHPShutOpen;
    private javax.swing.JButton jButtonLPShutClose;
    private javax.swing.JButton jButtonLPShutClose1;
    private javax.swing.JButton jButtonProtectionRest;
    private javax.swing.JButton jButtonProtectionTrip;
    private javax.swing.JButton jButtonSpeed1;
    private javax.swing.JButton jButtonSpeed2;
    private javax.swing.JButton jButtonSpeed3;
    private javax.swing.JButton jButtonSpeed4;
    private javax.swing.JButton jButtonSpeed5;
    private javax.swing.JButton jButtonSpeedGradient1;
    private javax.swing.JButton jButtonSpeedGradient2;
    private javax.swing.JButton jButtonSpeedGradient3;
    private javax.swing.JButton jButtonSuperheaterCondShutoffClose;
    private javax.swing.JButton jButtonSuperheaterCondShutoffOpen;
    private javax.swing.JButton jButtonSuperheaterShutoffClose;
    private javax.swing.JButton jButtonSuperheaterShutoffOpen;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCaption1;
    private javax.swing.JLabel jLabelCaption2;
    private javax.swing.JLabel jLabelCaption3;
    private javax.swing.JLabel jLabelCaption4;
    private javax.swing.JLabel jLabelCaption5;
    private javax.swing.JLabel jLabelCaption6;
    private javax.swing.JLabel jLabelCaption7;
    private javax.swing.JLabel jLabelCaptionAZ10;
    private javax.swing.JLabel jLabelCaptionAZ11;
    private javax.swing.JLabel jLabelCaptionAZ12;
    private javax.swing.JLabel jLabelCaptionAZ13;
    private javax.swing.JLabel jLabelCaptionAZ14;
    private javax.swing.JLabel jLabelCaptionAZ15;
    private javax.swing.JLabel jLabelCaptionAZ16;
    private javax.swing.JLabel jLabelCaptionAZ7;
    private javax.swing.JLabel jLabelCaptionAZ9;
    private javax.swing.JLabel jLabelCaptionHPShut1;
    private javax.swing.JLabel jLabelCaptionHPShut2;
    private javax.swing.JLabel jLabelCaptionLPShut1;
    private javax.swing.JLabel jLabelCaptionLPShut2;
    private javax.swing.JLabel jLabelCaptionLPShut3;
    private javax.swing.JLabel jLabelCaptionLPShut4;
    private javax.swing.JLabel jLabelCaptionLPShut5;
    private javax.swing.JLabel jLabelCaptionLPShut6;
    private javax.swing.JLabel jLabelCaptionSuperheaterCondShutoff;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl1;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl2;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl3;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl4;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl5;
    private javax.swing.JLabel jLabelCaptionSuperheaterControl6;
    private javax.swing.JLabel jLabelCaptionSuperheaterShutoff;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond1;
    private javax.swing.JLabel jLabelCaptionsuperheaterCond2;
    private javax.swing.JLabel jLabelReadingActiveSpeedSetpoint;
    private javax.swing.JLabel jLabelTempSetpoint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButtonAutoDrain1;
    private javax.swing.JToggleButton jToggleButtonPump;
    private javax.swing.JToggleButton jToggleButtonPump1;
    private javax.swing.JToggleButton jToggleButtonPump2;
    private javax.swing.JToggleButton jToggleButtonPump3;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService1;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService2;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService3;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady1;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady2;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady3;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbSpeed1;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbSpeed2;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbSpeed3;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbSpeed4;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbSpeed5;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbSpeed6;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbSpeedGradient1;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbSpeedGradient2;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbSpeedGradient3;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControlTemperature;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        controlLoopHotwellDrain.updateComponent(evt);
        controlLoopStartupValve1.updateComponent(evt);
        controlLoopStartupValve2.updateComponent(evt);
        controlLoopValve3.updateComponent(evt);
        controlLoopValve4.updateComponent(evt);
        controlLoopValveSteamIn.updateComponent(evt);
        setpointControlTemperature.updateComponent(evt);
        integralSwitch1.updateComponent(evt);
        integralSwitch2.updateComponent(evt);
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        controlLoopHotwellDrain.updateComponent(propertyName, newValue);
        controlLoopStartupValve1.updateComponent(propertyName, newValue);
        controlLoopStartupValve2.updateComponent(propertyName, newValue);
        controlLoopValve3.updateComponent(propertyName, newValue);
        controlLoopValve4.updateComponent(propertyName, newValue);
        controlLoopValveSteamIn.updateComponent(propertyName, newValue);
        setpointControlTemperature.updateComponent(propertyName, newValue);
        integralSwitch1.updateComponent(propertyName, newValue);
        integralSwitch2.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
