/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui;

import com.hartrusion.mvc.ActionCommand;
import java.beans.PropertyChangeEvent;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelFeedwater extends AbstractPanelWidget
        implements UpdateReceiver {

    @Override
    public void registerActionReceiver(ActionReceiver controller) {
        super.registerActionReceiver(controller);
        // Make action receiver interface from controller available to elements
        // of this Panel so they can send their actions to it directly.
        panelWidgetPump11.registerActionReceiver(controller);
        panelWidgetPump12.registerActionReceiver(controller);
        panelWidgetPump21.registerActionReceiver(controller);
        panelWidgetPump22.registerActionReceiver(controller);
        panelWidgetPump3.registerActionReceiver(controller);
        
        panelWidgetControlLoopValve12.registerActionReceiver(controller);
        panelWidgetControlLoopValve13.registerActionReceiver(controller);
        panelWidgetControlLoopValve22.registerActionReceiver(controller);
        panelWidgetControlLoopValve23.registerActionReceiver(controller);
        panelWidgetControlLoopValve11.registerActionReceiver(controller);
        panelWidgetControlLoopValve21.registerActionReceiver(controller);
        
        setpointControl1.registerActionReceiver(controller);
        setpointControl2.registerActionReceiver(controller);

    }

    /**
     * Creates new form PanelFeedwater
     */
    public PanelFeedwater() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCaptionFeed22 = new javax.swing.JLabel();
        jButtonFeed23Open = new javax.swing.JButton();
        jButtonFeed23Close = new javax.swing.JButton();
        panelWidgetControlLoopValve12 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        panelWidgetControlLoopValve13 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        panelWidgetControlLoopValve22 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        panelWidgetControlLoopValve23 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        panelWidgetControlLoopValve11 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        panelWidgetControlLoopValve21 = new com.hartrusion.rbmksim.gui.elements.ControlLoopValve();
        integralSwitchStartupReduction1 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        integralSwitchStartupReduction2 = new com.hartrusion.rbmksim.gui.elements.IntegralSwitch();
        jLabelFeed12 = new javax.swing.JLabel();
        jButtonFeed12Open = new javax.swing.JButton();
        jButtonFeed12Close = new javax.swing.JButton();
        jLabelFeed11 = new javax.swing.JLabel();
        jButtonFeed11Open = new javax.swing.JButton();
        jButtonFeed11Close = new javax.swing.JButton();
        jLabelFeed21 = new javax.swing.JLabel();
        jButtonFeed21Open = new javax.swing.JButton();
        jButtonFeed21Close = new javax.swing.JButton();
        jLabelFeed22 = new javax.swing.JLabel();
        jButtonFeed22Open = new javax.swing.JButton();
        jButtonFeed22Close = new javax.swing.JButton();
        jLabelFeed13 = new javax.swing.JLabel();
        jButtonFeed13Open = new javax.swing.JButton();
        jButtonFeed13Close = new javax.swing.JButton();
        panelWidgetPump11 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPump12 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPump21 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPump22 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        panelWidgetPump3 = new com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump();
        jLabelLoop1DA1Dis = new javax.swing.JLabel();
        jButtonLoop2Open7 = new javax.swing.JButton();
        jButtonLoop2Close7 = new javax.swing.JButton();
        jLabeljLabelCaptionRegenToCooler10 = new javax.swing.JLabel();
        jButtonLoop2Open8 = new javax.swing.JButton();
        jButtonLoop2Close8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabelCaptionDrain = new javax.swing.JLabel();
        jLabelCaptionPump11 = new javax.swing.JLabel();
        jLabelCaptionPump12 = new javax.swing.JLabel();
        jLabelCaptionDischarge = new javax.swing.JLabel();
        jLabelCaptionump21 = new javax.swing.JLabel();
        jLabeljLabelCaptionRegenToCooler11 = new javax.swing.JLabel();
        jButtonLoop2Open9 = new javax.swing.JButton();
        jButtonLoop2Close9 = new javax.swing.JButton();
        jLabeljLabelCaptionRegenToCooler12 = new javax.swing.JLabel();
        jButtonLoop2Open10 = new javax.swing.JButton();
        jButtonLoop2Close10 = new javax.swing.JButton();
        jLabelCaptionPump3 = new javax.swing.JLabel();
        jLabelCaptionSetpoints = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chornobylGaugeLoop1Pressure = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeLoop1Level = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        chornobylGaugeLoop2Pressure1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        chornobylGaugeLoop2Level1 = new com.hartrusion.rbmksim.gui.elements.ChornobylGauge();
        setpointControl1 = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        setpointControl2 = new com.hartrusion.rbmksim.gui.elements.SetpointControl();
        jLabel9 = new javax.swing.JLabel();
        jLabelCaptionDrain7 = new javax.swing.JLabel();
        jLabelCaptionDrain8 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(460, 340));
        setMinimumSize(new java.awt.Dimension(460, 340));
        setPreferredSize(new java.awt.Dimension(460, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCaptionFeed22.setFont(jLabelCaptionFeed22.getFont().deriveFont(jLabelCaptionFeed22.getFont().getSize()-2f));
        jLabelCaptionFeed22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionFeed22.setText("Feed 2.2");
        jLabelCaptionFeed22.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionFeed22.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionFeed22.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionFeed22, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 198, 52, 14));

        jButtonFeed23Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed23Open.setText("O");
        jButtonFeed23Open.setToolTipText("");
        jButtonFeed23Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed23Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed23OpenActionPerformed(evt);
            }
        });
        add(jButtonFeed23Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 212, 20, 20));

        jButtonFeed23Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed23Close.setText("C");
        jButtonFeed23Close.setToolTipText("");
        jButtonFeed23Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed23Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed23CloseActionPerformed(evt);
            }
        });
        add(jButtonFeed23Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 212, 20, 20));

        panelWidgetControlLoopValve12.setComponent("Feedwater1#FlowRegulationValve2");
        add(panelWidgetControlLoopValve12, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 72, -1, -1));

        panelWidgetControlLoopValve13.setComponent("Feedwater1#FlowRegulationValve3");
        add(panelWidgetControlLoopValve13, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 114, -1, -1));

        panelWidgetControlLoopValve22.setComponent("Feedwater2#FlowRegulationValve2");
        add(panelWidgetControlLoopValve22, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 156, -1, -1));

        panelWidgetControlLoopValve23.setComponent("Feedwater2#FlowRegulationValve3");
        add(panelWidgetControlLoopValve23, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 198, -1, -1));

        panelWidgetControlLoopValve11.setComponent("Feedwater1#FlowRegulationValve1");
        add(panelWidgetControlLoopValve11, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 254, -1, -1));

        panelWidgetControlLoopValve21.setComponent("Feedwater2#FlowRegulationValve1");
        add(panelWidgetControlLoopValve21, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 296, -1, -1));

        integralSwitchStartupReduction1.setComponent("Feedwater1#StartupReductionValve");
        add(integralSwitchStartupReduction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 260, -1, -1));

        integralSwitchStartupReduction2.setComponent("Feedwater2#StartupReductionValve");
        add(integralSwitchStartupReduction2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 302, -1, -1));

        jLabelFeed12.setFont(jLabelFeed12.getFont().deriveFont(jLabelFeed12.getFont().getSize()-2f));
        jLabelFeed12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFeed12.setText("Feed 1.1");
        jLabelFeed12.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelFeed12.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelFeed12.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelFeed12, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 72, 52, 14));

        jButtonFeed12Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed12Open.setText("O");
        jButtonFeed12Open.setToolTipText("");
        jButtonFeed12Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12OpenActionPerformed(evt);
            }
        });
        add(jButtonFeed12Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 86, 20, 20));

        jButtonFeed12Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed12Close.setText("C");
        jButtonFeed12Close.setToolTipText("");
        jButtonFeed12Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed12Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed12CloseActionPerformed(evt);
            }
        });
        add(jButtonFeed12Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 86, 20, 20));

        jLabelFeed11.setFont(jLabelFeed11.getFont().deriveFont(jLabelFeed11.getFont().getSize()-2f));
        jLabelFeed11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFeed11.setText("Startup 1");
        jLabelFeed11.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelFeed11.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelFeed11.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelFeed11, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 252, 52, 14));

        jButtonFeed11Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed11Open.setText("O");
        jButtonFeed11Open.setToolTipText("");
        jButtonFeed11Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed11Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed11OpenActionPerformed(evt);
            }
        });
        add(jButtonFeed11Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 266, 20, 20));

        jButtonFeed11Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed11Close.setText("C");
        jButtonFeed11Close.setToolTipText("");
        jButtonFeed11Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed11Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed11CloseActionPerformed(evt);
            }
        });
        add(jButtonFeed11Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 266, 20, 20));

        jLabelFeed21.setFont(jLabelFeed21.getFont().deriveFont(jLabelFeed21.getFont().getSize()-2f));
        jLabelFeed21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFeed21.setText("Startup 2");
        jLabelFeed21.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelFeed21.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelFeed21.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelFeed21, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 296, 52, 14));

        jButtonFeed21Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed21Open.setText("O");
        jButtonFeed21Open.setToolTipText("");
        jButtonFeed21Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed21Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed21OpenActionPerformed(evt);
            }
        });
        add(jButtonFeed21Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 310, 20, 20));

        jButtonFeed21Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed21Close.setText("C");
        jButtonFeed21Close.setToolTipText("");
        jButtonFeed21Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed21Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed21CloseActionPerformed(evt);
            }
        });
        add(jButtonFeed21Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 310, 20, 20));

        jLabelFeed22.setFont(jLabelFeed22.getFont().deriveFont(jLabelFeed22.getFont().getSize()-2f));
        jLabelFeed22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFeed22.setText("Feed 2.1");
        jLabelFeed22.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelFeed22.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelFeed22.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelFeed22, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 156, 52, 14));

        jButtonFeed22Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed22Open.setText("O");
        jButtonFeed22Open.setToolTipText("");
        jButtonFeed22Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed22Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed22OpenActionPerformed(evt);
            }
        });
        add(jButtonFeed22Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 170, 20, 20));

        jButtonFeed22Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed22Close.setText("C");
        jButtonFeed22Close.setToolTipText("");
        jButtonFeed22Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed22Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed22CloseActionPerformed(evt);
            }
        });
        add(jButtonFeed22Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 170, 20, 20));

        jLabelFeed13.setFont(jLabelFeed13.getFont().deriveFont(jLabelFeed13.getFont().getSize()-2f));
        jLabelFeed13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFeed13.setText("Feed 1.2");
        jLabelFeed13.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelFeed13.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelFeed13.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelFeed13, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 114, 52, 14));

        jButtonFeed13Open.setBackground(new java.awt.Color(128, 0, 0));
        jButtonFeed13Open.setText("O");
        jButtonFeed13Open.setToolTipText("");
        jButtonFeed13Open.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed13Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed13OpenActionPerformed(evt);
            }
        });
        add(jButtonFeed13Open, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 128, 20, 20));

        jButtonFeed13Close.setBackground(new java.awt.Color(0, 128, 0));
        jButtonFeed13Close.setText("C");
        jButtonFeed13Close.setToolTipText("");
        jButtonFeed13Close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFeed13Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFeed13CloseActionPerformed(evt);
            }
        });
        add(jButtonFeed13Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 128, 20, 20));

        panelWidgetPump11.setChornobylPrefix("Feedwater1#Pump1");
        add(panelWidgetPump11, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 86, -1, -1));

        panelWidgetPump12.setChornobylPrefix("Feedwater1#Pump2");
        add(panelWidgetPump12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 86, -1, -1));

        panelWidgetPump21.setChornobylPrefix("Feedwater2#Pump1");
        add(panelWidgetPump21, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 86, -1, -1));

        panelWidgetPump22.setChornobylPrefix("Feedwater2#Pump2");
        add(panelWidgetPump22, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 86, -1, -1));

        panelWidgetPump3.setChornobylPrefix("Feedwater#Pump3");
        add(panelWidgetPump3, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 86, -1, -1));

        jLabelLoop1DA1Dis.setFont(jLabelLoop1DA1Dis.getFont().deriveFont(jLabelLoop1DA1Dis.getFont().getSize()-2f));
        jLabelLoop1DA1Dis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLoop1DA1Dis.setText("Loop 1");
        jLabelLoop1DA1Dis.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelLoop1DA1Dis.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelLoop1DA1Dis.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelLoop1DA1Dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 296, 52, 14));

        jButtonLoop2Open7.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open7.setText("O");
        jButtonLoop2Open7.setToolTipText("");
        jButtonLoop2Open7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open7ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open7, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 310, 20, 20));

        jButtonLoop2Close7.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close7.setText("C");
        jButtonLoop2Close7.setToolTipText("");
        jButtonLoop2Close7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close7ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close7, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 310, 20, 20));

        jLabeljLabelCaptionRegenToCooler10.setFont(jLabeljLabelCaptionRegenToCooler10.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler10.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler10.setText("DA 1");
        jLabeljLabelCaptionRegenToCooler10.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler10.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler10.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler10, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 242, 52, 14));

        jButtonLoop2Open8.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open8.setText("O");
        jButtonLoop2Open8.setToolTipText("");
        jButtonLoop2Open8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open8ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open8, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 256, 20, 20));

        jButtonLoop2Close8.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close8.setText("C");
        jButtonLoop2Close8.setToolTipText("");
        jButtonLoop2Close8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close8ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close8, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 256, 20, 20));

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()-2f));
        jLabel8.setText("Drum 2");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 314, 44, 14));

        jLabelCaptionDrain.setFont(jLabelCaptionDrain.getFont().deriveFont(jLabelCaptionDrain.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain.getFont().getSize()-2));
        jLabelCaptionDrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain.setText("Pump 2.2");
        jLabelCaptionDrain.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 70, 64, 14));

        jLabelCaptionPump11.setFont(jLabelCaptionPump11.getFont().deriveFont(jLabelCaptionPump11.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump11.getFont().getSize()-2));
        jLabelCaptionPump11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump11.setText("Pump 1.1");
        jLabelCaptionPump11.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump11.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump11.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump11, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 70, 64, 14));

        jLabelCaptionPump12.setFont(jLabelCaptionPump12.getFont().deriveFont(jLabelCaptionPump12.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump12.getFont().getSize()-2));
        jLabelCaptionPump12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump12.setText("Pump 1.2");
        jLabelCaptionPump12.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump12.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump12.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump12, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 70, 64, 14));

        jLabelCaptionDischarge.setFont(jLabelCaptionDischarge.getFont().deriveFont(jLabelCaptionDischarge.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDischarge.getFont().getSize()-2));
        jLabelCaptionDischarge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDischarge.setText("Discharge Side");
        jLabelCaptionDischarge.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDischarge.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDischarge.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDischarge, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 282, 102, 14));

        jLabelCaptionump21.setFont(jLabelCaptionump21.getFont().deriveFont(jLabelCaptionump21.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionump21.getFont().getSize()-2));
        jLabelCaptionump21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionump21.setText("Pump 2.1");
        jLabelCaptionump21.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionump21.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionump21.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionump21, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 70, 64, 14));

        jLabeljLabelCaptionRegenToCooler11.setFont(jLabeljLabelCaptionRegenToCooler11.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler11.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler11.setText("Loop 2");
        jLabeljLabelCaptionRegenToCooler11.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler11.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler11.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler11, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 296, 52, 14));

        jButtonLoop2Open9.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open9.setText("O");
        jButtonLoop2Open9.setToolTipText("");
        jButtonLoop2Open9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open9ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open9, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 310, 20, 20));

        jButtonLoop2Close9.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close9.setText("C");
        jButtonLoop2Close9.setToolTipText("");
        jButtonLoop2Close9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close9ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close9, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 310, 20, 20));

        jLabeljLabelCaptionRegenToCooler12.setFont(jLabeljLabelCaptionRegenToCooler12.getFont().deriveFont(jLabeljLabelCaptionRegenToCooler12.getFont().getSize()-2f));
        jLabeljLabelCaptionRegenToCooler12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeljLabelCaptionRegenToCooler12.setText("DA 2");
        jLabeljLabelCaptionRegenToCooler12.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler12.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabeljLabelCaptionRegenToCooler12.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabeljLabelCaptionRegenToCooler12, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 242, 52, 14));

        jButtonLoop2Open10.setBackground(new java.awt.Color(128, 0, 0));
        jButtonLoop2Open10.setText("O");
        jButtonLoop2Open10.setToolTipText("");
        jButtonLoop2Open10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Open10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Open10ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Open10, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 256, 20, 20));

        jButtonLoop2Close10.setBackground(new java.awt.Color(0, 128, 0));
        jButtonLoop2Close10.setText("C");
        jButtonLoop2Close10.setToolTipText("");
        jButtonLoop2Close10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLoop2Close10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoop2Close10ActionPerformed(evt);
            }
        });
        add(jButtonLoop2Close10, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 256, 20, 20));

        jLabelCaptionPump3.setFont(jLabelCaptionPump3.getFont().deriveFont(jLabelCaptionPump3.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionPump3.getFont().getSize()-2));
        jLabelCaptionPump3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump3.setText("Pump 3");
        jLabelCaptionPump3.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump3.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump3.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump3, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 70, 64, 14));

        jLabelCaptionSetpoints.setFont(jLabelCaptionSetpoints.getFont().deriveFont(jLabelCaptionSetpoints.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionSetpoints.getFont().getSize()-2));
        jLabelCaptionSetpoints.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSetpoints.setText("Drum Level Setpoint");
        jLabelCaptionSetpoints.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSetpoints.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSetpoints.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSetpoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 266, 124, 14));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()-2f));
        jLabel5.setText("Feed 1");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 52, 14));

        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getSize()-2f));
        jLabel20.setText("Flow");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 52, 14));

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()-2f));
        jLabel7.setText("Feed 1");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 52, 14));

        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getSize()-2f));
        jLabel19.setText("Temp");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 52, 14));

        chornobylGaugeLoop1Pressure.setChornobylMaximum(200.0F);
        chornobylGaugeLoop1Pressure.setChornobylMinimum(20.0F);
        chornobylGaugeLoop1Pressure.setChornobylTicks(new float[] {50.0f, 100.0f, 150.0f});
        chornobylGaugeLoop1Pressure.setChornobylUnitText("°C");
        add(chornobylGaugeLoop1Pressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 34, -1, -1));

        chornobylGaugeLoop1Level.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeLoop1Level.setChornobylMaximum(1800.0F);
        chornobylGaugeLoop1Level.setChornobylMinimum(0.0F);
        chornobylGaugeLoop1Level.setChornobylTicks(new float[] {0.0f, 500.0f, 1000.0f, 1600.0f});
        chornobylGaugeLoop1Level.setChornobylUnitText("kg/s");
        add(chornobylGaugeLoop1Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 4, -1, -1));

        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getSize()-2f));
        jLabel24.setText("Feed 2");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 4, 52, 14));

        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getSize()-2f));
        jLabel18.setText("Flow");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 16, 52, 14));

        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getSize()-2f));
        jLabel23.setText("Feed 2");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 34, 52, 14));

        jLabel17.setFont(jLabel17.getFont().deriveFont(jLabel17.getFont().getSize()-2f));
        jLabel17.setText("Temp");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 46, 52, 14));

        chornobylGaugeLoop2Pressure1.setChornobylMaximum(200.0F);
        chornobylGaugeLoop2Pressure1.setChornobylMinimum(20.0F);
        chornobylGaugeLoop2Pressure1.setChornobylTicks(new float[] {50.0f, 100.0f, 150.0f});
        chornobylGaugeLoop2Pressure1.setChornobylUnitText("°C");
        add(chornobylGaugeLoop2Pressure1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 34, -1, -1));

        chornobylGaugeLoop2Level1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chornobylGaugeLoop2Level1.setChornobylMaximum(1800.0F);
        chornobylGaugeLoop2Level1.setChornobylMinimum(0.0F);
        chornobylGaugeLoop2Level1.setChornobylTicks(new float[] {0.0f, 500.0f, 1000.0f, 1600.0f});
        chornobylGaugeLoop2Level1.setChornobylUnitText("kg/s");
        add(chornobylGaugeLoop2Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 4, -1, -1));

        setpointControl1.setComponent("Loop1#DrumLevelSetpoint");
        add(setpointControl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 284, -1, -1));

        setpointControl2.setComponent("Loop2#DrumLevelSetpoint");
        add(setpointControl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getSize()-2f));
        jLabel9.setText("Drum 1");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 288, 44, 14));

        jLabelCaptionDrain7.setFont(jLabelCaptionDrain7.getFont().deriveFont(jLabelCaptionDrain7.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain7.getFont().getSize()-2));
        jLabelCaptionDrain7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain7.setText("Suction Side");
        jLabelCaptionDrain7.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain7.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain7.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain7, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 226, 102, 14));

        jLabelCaptionDrain8.setFont(jLabelCaptionDrain8.getFont().deriveFont(jLabelCaptionDrain8.getFont().getStyle() | java.awt.Font.BOLD, jLabelCaptionDrain8.getFont().getSize()-2));
        jLabelCaptionDrain8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionDrain8.setText("Pump 3 System");
        jLabelCaptionDrain8.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain8.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionDrain8.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionDrain8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 208, 102, 14));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFeed23OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed23OpenActionPerformed
        controller.userAction(new ActionCommand("Feedwater2#ShutoffValve3", true));
    }//GEN-LAST:event_jButtonFeed23OpenActionPerformed

    private void jButtonFeed23CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed23CloseActionPerformed
        controller.userAction(new ActionCommand("Feedwater2#ShutoffValve3", false));
    }//GEN-LAST:event_jButtonFeed23CloseActionPerformed

    private void jButtonFeed12OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12OpenActionPerformed
        controller.userAction(new ActionCommand("Feedwater1#ShutoffValve2", true));
    }//GEN-LAST:event_jButtonFeed12OpenActionPerformed

    private void jButtonFeed12CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed12CloseActionPerformed
        controller.userAction(new ActionCommand("Feedwater1#ShutoffValve2", false));
    }//GEN-LAST:event_jButtonFeed12CloseActionPerformed

    private void jButtonFeed11OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed11OpenActionPerformed
        controller.userAction(new ActionCommand("Feedwater1#ShutoffValve1", true));
    }//GEN-LAST:event_jButtonFeed11OpenActionPerformed

    private void jButtonFeed11CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed11CloseActionPerformed
        controller.userAction(new ActionCommand("Feedwater1#ShutoffValve1", false));
    }//GEN-LAST:event_jButtonFeed11CloseActionPerformed

    private void jButtonFeed21OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed21OpenActionPerformed
        controller.userAction(new ActionCommand("Feedwater2#ShutoffValve1", true));
    }//GEN-LAST:event_jButtonFeed21OpenActionPerformed

    private void jButtonFeed21CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed21CloseActionPerformed
        controller.userAction(new ActionCommand("Feedwater2#ShutoffValve3", false));
    }//GEN-LAST:event_jButtonFeed21CloseActionPerformed

    private void jButtonFeed22OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed22OpenActionPerformed
        controller.userAction(new ActionCommand("Feedwater2#ShutoffValve2", true));
    }//GEN-LAST:event_jButtonFeed22OpenActionPerformed

    private void jButtonFeed22CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed22CloseActionPerformed
        controller.userAction(new ActionCommand("Feedwater2#ShutoffValve2", false));
    }//GEN-LAST:event_jButtonFeed22CloseActionPerformed

    private void jButtonFeed13OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed13OpenActionPerformed
        controller.userAction(new ActionCommand("Feedwater1#ShutoffValve3", true));
    }//GEN-LAST:event_jButtonFeed13OpenActionPerformed

    private void jButtonFeed13CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFeed13CloseActionPerformed
        controller.userAction(new ActionCommand("Feedwater1#ShutoffValve3", false));
    }//GEN-LAST:event_jButtonFeed13CloseActionPerformed

    private void jButtonLoop2Close10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close10ActionPerformed

    private void jButtonLoop2Open10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open10ActionPerformed

    private void jButtonLoop2Close9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close9ActionPerformed

    private void jButtonLoop2Open9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open9ActionPerformed

    private void jButtonLoop2Close8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close8ActionPerformed

    private void jButtonLoop2Open8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open8ActionPerformed

    private void jButtonLoop2Close7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Close7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Close7ActionPerformed

    private void jButtonLoop2Open7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoop2Open7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoop2Open7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop1Level;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop1Pressure;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop2Level1;
    private com.hartrusion.rbmksim.gui.elements.ChornobylGauge chornobylGaugeLoop2Pressure1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchStartupReduction1;
    private com.hartrusion.rbmksim.gui.elements.IntegralSwitch integralSwitchStartupReduction2;
    private javax.swing.JButton jButtonFeed11Close;
    private javax.swing.JButton jButtonFeed11Open;
    private javax.swing.JButton jButtonFeed12Close;
    private javax.swing.JButton jButtonFeed12Open;
    private javax.swing.JButton jButtonFeed13Close;
    private javax.swing.JButton jButtonFeed13Open;
    private javax.swing.JButton jButtonFeed21Close;
    private javax.swing.JButton jButtonFeed21Open;
    private javax.swing.JButton jButtonFeed22Close;
    private javax.swing.JButton jButtonFeed22Open;
    private javax.swing.JButton jButtonFeed23Close;
    private javax.swing.JButton jButtonFeed23Open;
    private javax.swing.JButton jButtonLoop2Close10;
    private javax.swing.JButton jButtonLoop2Close7;
    private javax.swing.JButton jButtonLoop2Close8;
    private javax.swing.JButton jButtonLoop2Close9;
    private javax.swing.JButton jButtonLoop2Open10;
    private javax.swing.JButton jButtonLoop2Open7;
    private javax.swing.JButton jButtonLoop2Open8;
    private javax.swing.JButton jButtonLoop2Open9;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCaptionDischarge;
    private javax.swing.JLabel jLabelCaptionDrain;
    private javax.swing.JLabel jLabelCaptionDrain7;
    private javax.swing.JLabel jLabelCaptionDrain8;
    private javax.swing.JLabel jLabelCaptionFeed22;
    private javax.swing.JLabel jLabelCaptionPump11;
    private javax.swing.JLabel jLabelCaptionPump12;
    private javax.swing.JLabel jLabelCaptionPump3;
    private javax.swing.JLabel jLabelCaptionSetpoints;
    private javax.swing.JLabel jLabelCaptionump21;
    private javax.swing.JLabel jLabelFeed11;
    private javax.swing.JLabel jLabelFeed12;
    private javax.swing.JLabel jLabelFeed13;
    private javax.swing.JLabel jLabelFeed21;
    private javax.swing.JLabel jLabelFeed22;
    private javax.swing.JLabel jLabelLoop1DA1Dis;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler10;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler11;
    private javax.swing.JLabel jLabeljLabelCaptionRegenToCooler12;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve11;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve12;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve13;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve21;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve22;
    private com.hartrusion.rbmksim.gui.elements.ControlLoopValve panelWidgetControlLoopValve23;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump11;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump12;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump21;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump22;
    private com.hartrusion.rbmksim.gui.widgets.PanelWidgetPump panelWidgetPump3;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControl1;
    private com.hartrusion.rbmksim.gui.elements.SetpointControl setpointControl2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        panelWidgetPump11.updateComponent(evt);
        panelWidgetPump12.updateComponent(evt);
        panelWidgetPump21.updateComponent(evt);
        panelWidgetPump22.updateComponent(evt);
        panelWidgetPump3.updateComponent(evt);
        panelWidgetControlLoopValve12.updateComponent(evt);
        panelWidgetControlLoopValve13.updateComponent(evt);
        panelWidgetControlLoopValve22.updateComponent(evt);
        panelWidgetControlLoopValve23.updateComponent(evt);
        panelWidgetControlLoopValve11.updateComponent(evt);
        panelWidgetControlLoopValve21.updateComponent(evt);
        
        integralSwitchStartupReduction1.updateComponent(evt);
        integralSwitchStartupReduction2.updateComponent(evt);
        
        switch (evt.getPropertyName()) {
            case "Feedwater1#ShutoffValve1_Pos":
                setValveButtons(jButtonFeed11Close, 
                        jButtonFeed11Open, evt.getNewValue());
                break;
            case "Feedwater2#ShutoffValve1_Pos":
                setValveButtons(jButtonFeed21Close, 
                        jButtonFeed21Open, evt.getNewValue());
                break;
            case "Feedwater1#ShutoffValve2_Pos":
                setValveButtons(jButtonFeed12Close, 
                        jButtonFeed12Open, evt.getNewValue());
                break;
            case "Feedwater2#ShutoffValve2_Pos":
                setValveButtons(jButtonFeed22Close, 
                        jButtonFeed22Open, evt.getNewValue());
                break;
            case "Feedwater1#ShutoffValve3_Pos":
                setValveButtons(jButtonFeed13Close, 
                        jButtonFeed13Open, evt.getNewValue());
                break;
            case "Feedwater2#ShutoffValve3_Pos":
                setValveButtons(jButtonFeed23Close, 
                        jButtonFeed23Open, evt.getNewValue());
                break;
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        panelWidgetControlLoopValve12.updateComponent(propertyName, newValue);
        panelWidgetControlLoopValve13.updateComponent(propertyName, newValue);
        panelWidgetControlLoopValve22.updateComponent(propertyName, newValue);
        panelWidgetControlLoopValve23.updateComponent(propertyName, newValue);
        panelWidgetControlLoopValve11.updateComponent(propertyName, newValue);
        panelWidgetControlLoopValve21.updateComponent(propertyName, newValue);
        
        setpointControl1.updateComponent(propertyName, newValue);
        setpointControl2.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
