/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.mnemonic;

import java.beans.PropertyChangeEvent;
import com.hartrusion.mvc.UpdateReceiver;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class FrameMnemonicAuxiliaryCondenser extends javax.swing.JFrame implements UpdateReceiver {
    
    /**
     * Creates new form FrameMnemonicInternalLoad
     */
    public FrameMnemonicAuxiliaryCondenser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMnemonicInternalLoad1 = new com.hartrusion.rbmksim.gui.mnemonic.PanelMnemonicAuxiliaryCondenser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aux Condenser");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(panelMnemonicInternalLoad1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hartrusion.rbmksim.gui.mnemonic.PanelMnemonicAuxiliaryCondenser panelMnemonicInternalLoad1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        panelMnemonicInternalLoad1.updateComponent(evt);
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        panelMnemonicInternalLoad1.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        panelMnemonicInternalLoad1.updateComponent(propertyName, newValue);
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
        panelMnemonicInternalLoad1.updateComponent(propertyName, newValue);
    }
}
