/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.mnemonic;

import com.hartrusion.control.ControlCommand;
import com.hartrusion.control.ValveState;
import com.hartrusion.modeling.automated.PumpState;
import static com.hartrusion.modeling.automated.PumpState.OFFLINE;
import static com.hartrusion.modeling.automated.PumpState.READY;
import static com.hartrusion.modeling.automated.PumpState.RUNNING;
import static com.hartrusion.modeling.automated.PumpState.STARTUP;
import com.hartrusion.mvc.UpdateReceiver;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelMnemonicCondensate extends javax.swing.JPanel
        implements UpdateReceiver {

    /**
     * Creates new form PanelMnemonicCondensate
     */
    public PanelMnemonicCondensate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valve1 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector1In = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector1Out = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector1Steam = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve5 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector1Condensate = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector2In = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector2Out = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector2Steam = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve10 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector2Condensate = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector3In = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector3Out = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector3Steam = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector3Condensate = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve16 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensatePump1Suction = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensatePump2Suction = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensatePump3Suction = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        pumpCondensate1 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        pumpCondensate2 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        pumpCondensate3 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        valveCondensatePump1Discharge = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensatePump2Discharge = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensatePump3Discharge = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjectorBypass = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        jLabelFromHotwell = new javax.swing.JLabel();
        jLabelToDA = new javax.swing.JLabel();
        jLabelReadingSteamInFlow = new javax.swing.JLabel();
        jLabelReadingSteamInPressure = new javax.swing.JLabel();
        jLabelReadingEjector1Level = new javax.swing.JLabel();
        jLabelReadingEjector2Level = new javax.swing.JLabel();
        jLabelReadingEjector3Level = new javax.swing.JLabel();
        jLabelReadingCondensate2Temperature = new javax.swing.JLabel();
        jLabelReadingCondensate2Pressure = new javax.swing.JLabel();
        jLabelReadingCondensate2Flow = new javax.swing.JLabel();
        jLabelReadingEjector2CondensateValve = new javax.swing.JLabel();
        jLabelReadingEjector3CondensateValve = new javax.swing.JLabel();
        jLabelReadingEjector1CondensateValve = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(652, 228));
        setMinimumSize(new java.awt.Dimension(652, 228));
        setPreferredSize(new java.awt.Dimension(652, 228));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valve1.setActive(true);
        valve1.setVertical(true);
        add(valve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 17, -1, -1));

        valveEjector1In.setVertical(true);
        add(valveEjector1In, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 152, -1, -1));

        valveEjector1Out.setVertical(true);
        add(valveEjector1Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 131, -1, -1));

        valveEjector1Steam.setVertical(true);
        add(valveEjector1Steam, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 23, -1, -1));
        add(valve5, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 71, -1, -1));

        valveEjector1Condensate.setControlIndicator(true);
        add(valveEjector1Condensate, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 111, -1, -1));

        valveEjector2In.setVertical(true);
        add(valveEjector2In, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 152, -1, -1));

        valveEjector2Out.setVertical(true);
        add(valveEjector2Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 131, -1, -1));

        valveEjector2Steam.setVertical(true);
        add(valveEjector2Steam, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 23, -1, -1));
        add(valve10, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 71, -1, -1));

        valveEjector2Condensate.setControlIndicator(true);
        add(valveEjector2Condensate, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 111, -1, -1));

        valveEjector3In.setVertical(true);
        add(valveEjector3In, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 152, -1, -1));

        valveEjector3Out.setVertical(true);
        add(valveEjector3Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 131, -1, -1));

        valveEjector3Steam.setVertical(true);
        add(valveEjector3Steam, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 23, -1, -1));

        valveEjector3Condensate.setControlIndicator(true);
        add(valveEjector3Condensate, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 111, -1, -1));
        add(valve16, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 71, -1, -1));

        valveCondensatePump1Suction.setVertical(true);
        add(valveCondensatePump1Suction, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 82, -1, -1));

        valveCondensatePump2Suction.setVertical(true);
        add(valveCondensatePump2Suction, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 82, -1, -1));

        valveCondensatePump3Suction.setVertical(true);
        add(valveCondensatePump3Suction, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 82, -1, -1));

        pumpCondensate1.setOrientation(3);
        pumpCondensate1.setPreferredSize(new java.awt.Dimension(36, 41));
        add(pumpCondensate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 125, -1, -1));

        pumpCondensate2.setOrientation(3);
        pumpCondensate2.setPreferredSize(new java.awt.Dimension(36, 41));
        add(pumpCondensate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 125, -1, -1));

        pumpCondensate3.setOrientation(3);
        pumpCondensate3.setPreferredSize(new java.awt.Dimension(36, 41));
        add(pumpCondensate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 125, -1, -1));

        valveCondensatePump1Discharge.setVertical(true);
        add(valveCondensatePump1Discharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 168, -1, -1));

        valveCondensatePump2Discharge.setVertical(true);
        add(valveCondensatePump2Discharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 168, -1, -1));

        valveCondensatePump3Discharge.setVertical(true);
        add(valveCondensatePump3Discharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 168, -1, -1));
        add(valveEjectorBypass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 203, -1, -1));

        jLabelFromHotwell.setFont(jLabelFromHotwell.getFont().deriveFont(jLabelFromHotwell.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelFromHotwell.getFont().getSize()-3));
        jLabelFromHotwell.setForeground(new java.awt.Color(14, 222, 194));
        jLabelFromHotwell.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFromHotwell.setText("Hotwell");
        add(jLabelFromHotwell, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 2, 50, -1));

        jLabelToDA.setFont(jLabelToDA.getFont().deriveFont(jLabelToDA.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelToDA.getFont().getSize()-3));
        jLabelToDA.setForeground(new java.awt.Color(14, 222, 194));
        jLabelToDA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelToDA.setText("DA");
        add(jLabelToDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 184, 26, -1));

        jLabelReadingSteamInFlow.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingSteamInFlow.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingSteamInFlow.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingSteamInFlow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingSteamInFlow.setText("__,_ kg/s");
        jLabelReadingSteamInFlow.setOpaque(true);
        add(jLabelReadingSteamInFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 30, 64, 16));

        jLabelReadingSteamInPressure.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingSteamInPressure.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingSteamInPressure.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingSteamInPressure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingSteamInPressure.setText("_,__ bar");
        jLabelReadingSteamInPressure.setOpaque(true);
        add(jLabelReadingSteamInPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 30, 64, 16));

        jLabelReadingEjector1Level.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingEjector1Level.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingEjector1Level.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingEjector1Level.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingEjector1Level.setText("__ cm");
        jLabelReadingEjector1Level.setToolTipText("");
        jLabelReadingEjector1Level.setOpaque(true);
        add(jLabelReadingEjector1Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 132, 40, 16));

        jLabelReadingEjector2Level.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingEjector2Level.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingEjector2Level.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingEjector2Level.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingEjector2Level.setText("__ cm");
        jLabelReadingEjector2Level.setToolTipText("");
        jLabelReadingEjector2Level.setOpaque(true);
        add(jLabelReadingEjector2Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 132, 40, 16));

        jLabelReadingEjector3Level.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingEjector3Level.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingEjector3Level.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingEjector3Level.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingEjector3Level.setText("__ cm");
        jLabelReadingEjector3Level.setToolTipText("");
        jLabelReadingEjector3Level.setOpaque(true);
        add(jLabelReadingEjector3Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 132, 40, 16));

        jLabelReadingCondensate2Temperature.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingCondensate2Temperature.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingCondensate2Temperature.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingCondensate2Temperature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingCondensate2Temperature.setText("___,_ °C");
        jLabelReadingCondensate2Temperature.setOpaque(true);
        add(jLabelReadingCondensate2Temperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 18, 64, 16));

        jLabelReadingCondensate2Pressure.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingCondensate2Pressure.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingCondensate2Pressure.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingCondensate2Pressure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingCondensate2Pressure.setText("__,_ bar");
        jLabelReadingCondensate2Pressure.setOpaque(true);
        add(jLabelReadingCondensate2Pressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 38, 64, 16));

        jLabelReadingCondensate2Flow.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingCondensate2Flow.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingCondensate2Flow.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingCondensate2Flow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingCondensate2Flow.setText("____ kg/s");
        jLabelReadingCondensate2Flow.setOpaque(true);
        add(jLabelReadingCondensate2Flow, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 58, 64, 16));

        jLabelReadingEjector2CondensateValve.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingEjector2CondensateValve.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingEjector2CondensateValve.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingEjector2CondensateValve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingEjector2CondensateValve.setText("___");
        jLabelReadingEjector2CondensateValve.setOpaque(true);
        add(jLabelReadingEjector2CondensateValve, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 132, 24, -1));

        jLabelReadingEjector3CondensateValve.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingEjector3CondensateValve.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingEjector3CondensateValve.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingEjector3CondensateValve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingEjector3CondensateValve.setText("___");
        jLabelReadingEjector3CondensateValve.setOpaque(true);
        add(jLabelReadingEjector3CondensateValve, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 132, 24, -1));

        jLabelReadingEjector1CondensateValve.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingEjector1CondensateValve.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingEjector1CondensateValve.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingEjector1CondensateValve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingEjector1CondensateValve.setText("___");
        jLabelReadingEjector1CondensateValve.setOpaque(true);
        add(jLabelReadingEjector1CondensateValve, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 132, 24, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hartrusion/rbmksim/gui/mnemonic/MnemonicCondensate.png"))); // NOI18N
        add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelFromHotwell;
    private javax.swing.JLabel jLabelReadingCondensate2Flow;
    private javax.swing.JLabel jLabelReadingCondensate2Pressure;
    private javax.swing.JLabel jLabelReadingCondensate2Temperature;
    private javax.swing.JLabel jLabelReadingEjector1CondensateValve;
    private javax.swing.JLabel jLabelReadingEjector1Level;
    private javax.swing.JLabel jLabelReadingEjector2CondensateValve;
    private javax.swing.JLabel jLabelReadingEjector2Level;
    private javax.swing.JLabel jLabelReadingEjector3CondensateValve;
    private javax.swing.JLabel jLabelReadingEjector3Level;
    private javax.swing.JLabel jLabelReadingSteamInFlow;
    private javax.swing.JLabel jLabelReadingSteamInPressure;
    private javax.swing.JLabel jLabelToDA;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pumpCondensate1;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pumpCondensate2;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pumpCondensate3;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve10;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve16;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve5;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump1Discharge;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump1Suction;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump2Discharge;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump2Suction;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump3Discharge;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump3Suction;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector1Condensate;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector1In;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector1Out;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector1Steam;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector2Condensate;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector2In;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector2Out;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector2Steam;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector3Condensate;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector3In;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector3Out;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector3Steam;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjectorBypass;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        switch (evt.getPropertyName()) {
            case "Condensation1#CondensatePumpSuctionValve_Pos" ->
                valveCondensatePump1Suction.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Condensation1#CondensatePumpPump_State" -> {
                switch ((PumpState) evt.getNewValue()) {
                    case OFFLINE ->
                        pumpCondensate1.setStatus(0);
                    case READY ->
                        pumpCondensate1.setStatus(1);
                    case STARTUP ->
                        pumpCondensate1.setStatus(2);
                    case RUNNING ->
                        pumpCondensate1.setStatus(3);
                }
            }
            case "Condensation1#CondensatePumpDischargeValve_Pos" ->
                valveCondensatePump1Discharge.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Condensation2#CondensatePumpSuctionValve_Pos" ->
                valveCondensatePump2Suction.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Condensation2#CondensatePumpPump_State" -> {
                switch ((PumpState) evt.getNewValue()) {
                    case OFFLINE ->
                        pumpCondensate2.setStatus(0);
                    case READY ->
                        pumpCondensate2.setStatus(1);
                    case STARTUP ->
                        pumpCondensate2.setStatus(2);
                    case RUNNING ->
                        pumpCondensate2.setStatus(3);
                }
            }
            case "Condensation2#CondensatePumpDischargeValve_Pos" ->
                valveCondensatePump2Discharge.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Condensation3#CondensatePumpSuctionValve_Pos" ->
                valveCondensatePump3Suction.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Condensation3#CondensatePumpPump_State" -> {
                switch ((PumpState) evt.getNewValue()) {
                    case OFFLINE ->
                        pumpCondensate3.setStatus(0);
                    case READY ->
                        pumpCondensate3.setStatus(1);
                    case STARTUP ->
                        pumpCondensate3.setStatus(2);
                    case RUNNING ->
                        pumpCondensate3.setStatus(3);
                }
            }
            case "Condensation3#CondensatePumpDischargeValve_Pos" ->
                valveCondensatePump3Discharge.setActive(evt.getNewValue() != ValveState.CLOSED);
                
            case "EjectorMain1#SteamValve_Pos" ->
                valveEjector1Steam.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain1#CondensateValve_Pos" ->
                valveEjector1Condensate.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain1#CondensateValveControlState" -> {
                if (evt.getNewValue() == ControlCommand.AUTOMATIC) {
                    valveEjector1Condensate.setControlIndicatorActive(true);
                } else if (evt.getNewValue() == ControlCommand.MANUAL_OPERATION) {
                    valveEjector1Condensate.setControlIndicatorActive(false);
                }
            }
            case "EjectorMain1#FlowIn_Pos" ->
                valveEjector1In.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain1#FlowOut_Pos" ->
                valveEjector1Out.setActive(evt.getNewValue() != ValveState.CLOSED);
                
            case "EjectorMain2#SteamValve_Pos" ->
                valveEjector2Steam.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain2#CondensateValve_Pos" ->
                valveEjector2Condensate.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain2#CondensateValveControlState" -> {
                if (evt.getNewValue() == ControlCommand.AUTOMATIC) {
                    valveEjector2Condensate.setControlIndicatorActive(true);
                } else if (evt.getNewValue() == ControlCommand.MANUAL_OPERATION) {
                    valveEjector2Condensate.setControlIndicatorActive(false);
                }
            }
            case "EjectorMain2#FlowIn_Pos" ->
                valveEjector2In.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain2#FlowOut_Pos" ->
                valveEjector2Out.setActive(evt.getNewValue() != ValveState.CLOSED);
                
            case "EjectorMain3#SteamValve_Pos" ->
                valveEjector3Steam.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain3#CondensateValve_Pos" ->
                valveEjector3Condensate.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain3#CondensateValveControlState" -> {
                if (evt.getNewValue() == ControlCommand.AUTOMATIC) {
                    valveEjector3Condensate.setControlIndicatorActive(true);
                } else if (evt.getNewValue() == ControlCommand.MANUAL_OPERATION) {
                    valveEjector3Condensate.setControlIndicatorActive(false);
                }
            }
            case "EjectorMain3#FlowIn_Pos" ->
                valveEjector3In.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain3#FlowOut_Pos" ->
                valveEjector3Out.setActive(evt.getNewValue() != ValveState.CLOSED);
                
            case "EjectorMain#Bypass_Pos" ->
                valveEjectorBypass.setActive(evt.getNewValue() != ValveState.CLOSED);
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        switch (propertyName) {
            case "EjectorMain#FeedwaterTemperature" ->
                jLabelReadingCondensate2Temperature.setText(
                        String.format("%5.1f", newValue) + " °C");
            case "EjectorMain#FeedwaterPressure" ->
                jLabelReadingCondensate2Pressure.setText(
                        String.format("%4.1f", newValue) + " bar");
            case "EjectorMain#FeedwaterFlow" ->
                jLabelReadingCondensate2Flow.setText(
                        String.format("%4.0f", newValue) + " kg/s");
            case "EjectorMain#SteamPressure" ->
                jLabelReadingSteamInPressure.setText(
                        String.format("%4.2f", newValue) + " bar");
            case "EjectorMain#SteamFlow" ->
                jLabelReadingSteamInFlow.setText(
                        String.format("%4.1f", newValue) + " kg/s");
            case "EjectorMain1#Level" ->
                jLabelReadingEjector1Level.setText(
                        String.format("%3.0f", newValue) + " cm");
            case "EjectorMain2#Level" ->
                jLabelReadingEjector2Level.setText(
                        String.format("%3.0f", newValue) + " cm");
            case "EjectorMain3#Level" ->
                jLabelReadingEjector3Level.setText(
                        String.format("%3.0f", newValue) + " cm");
            case "EjectorMain1#CondensateValve" ->
                jLabelReadingEjector1CondensateValve.setText(
                        String.format("%3.0f", newValue));
            case "EjectorMain2#CondensateValve" ->
                jLabelReadingEjector2CondensateValve.setText(
                        String.format("%3.0f", newValue));
            case "EjectorMain3#CondensateValve" ->
                jLabelReadingEjector3CondensateValve.setText(
                        String.format("%3.0f", newValue));
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
