/*
 * The MIT License
 *
 * Copyright 2025 Viktor Alexander Hartung.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.hartrusion.rbmksim.gui.mnemonic;

import java.beans.PropertyChangeEvent;
import com.hartrusion.mvc.UpdateReceiver;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelMnemonicCore extends javax.swing.JPanel implements UpdateReceiver {

    /**
     * Creates new form PanelMnemonicCore
     */
    public PanelMnemonicCore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelReadingFuelTemp2 = new javax.swing.JLabel();
        jLabelReadingORM = new javax.swing.JLabel();
        jLabelReadingXenon = new javax.swing.JLabel();
        jLabelReadingVoid2 = new javax.swing.JLabel();
        jLabelReadingFuelTemp1 = new javax.swing.JLabel();
        jLabelReadingVoid1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(228, 176));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelReadingFuelTemp2.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingFuelTemp2.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingFuelTemp2.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingFuelTemp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingFuelTemp2.setText("000.0");
        jLabelReadingFuelTemp2.setToolTipText("");
        jLabelReadingFuelTemp2.setOpaque(true);
        add(jLabelReadingFuelTemp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 102, 48, 16));

        jLabelReadingORM.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingORM.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingORM.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingORM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingORM.setText("000.0");
        jLabelReadingORM.setOpaque(true);
        add(jLabelReadingORM, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 150, 48, 16));

        jLabelReadingXenon.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingXenon.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingXenon.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingXenon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingXenon.setText("120.5");
        jLabelReadingXenon.setOpaque(true);
        add(jLabelReadingXenon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, 48, 16));

        jLabelReadingVoid2.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingVoid2.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingVoid2.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingVoid2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingVoid2.setText("00.0");
        jLabelReadingVoid2.setToolTipText("");
        jLabelReadingVoid2.setOpaque(true);
        add(jLabelReadingVoid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 52, 48, 16));

        jLabelReadingFuelTemp1.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingFuelTemp1.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingFuelTemp1.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingFuelTemp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingFuelTemp1.setText("000.0");
        jLabelReadingFuelTemp1.setToolTipText("");
        jLabelReadingFuelTemp1.setOpaque(true);
        add(jLabelReadingFuelTemp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 102, 48, 16));

        jLabelReadingVoid1.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingVoid1.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingVoid1.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingVoid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingVoid1.setText("00.0");
        jLabelReadingVoid1.setToolTipText("");
        jLabelReadingVoid1.setOpaque(true);
        add(jLabelReadingVoid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 52, 48, 16));

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() & ~java.awt.Font.BOLD, jLabel3.getFont().getSize()-3));
        jLabel3.setForeground(new java.awt.Color(14, 222, 194));
        jLabel3.setText("% Void");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 54, -1, -1));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() & ~java.awt.Font.BOLD, jLabel5.getFont().getSize()-3));
        jLabel5.setForeground(new java.awt.Color(14, 222, 194));
        jLabel5.setText("Fuel Temp");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 104, -1, -1));

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() & ~java.awt.Font.BOLD, jLabel7.getFont().getSize()-3));
        jLabel7.setForeground(new java.awt.Color(14, 222, 194));
        jLabel7.setText("ORM");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, -1, -1));

        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getStyle() & ~java.awt.Font.BOLD, jLabel9.getFont().getSize()-3));
        jLabel9.setForeground(new java.awt.Color(14, 222, 194));
        jLabel9.setText("Xenon (%)");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hartrusion/rbmksim/gui/mnemonic/MnemonicCore.png"))); // NOI18N
        add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelReadingFuelTemp1;
    private javax.swing.JLabel jLabelReadingFuelTemp2;
    private javax.swing.JLabel jLabelReadingORM;
    private javax.swing.JLabel jLabelReadingVoid1;
    private javax.swing.JLabel jLabelReadingVoid2;
    private javax.swing.JLabel jLabelReadingXenon;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {

    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        switch (propertyName) {
            case "Reactor#Xenon" ->
                jLabelReadingXenon.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1"));
            case "Reactor#RodAbsorption" ->
                jLabelReadingORM.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1"));
            case "Core1#Temperature" ->
                jLabelReadingFuelTemp1.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1"));
            case "Core2#Temperature" ->
                jLabelReadingFuelTemp2.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1"));
            case "Loop1#Voiding" ->
                jLabelReadingVoid1.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1"));
            case "Loop2#Voiding" ->
                jLabelReadingVoid2.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1"));
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
