/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.mnemonic;

import com.hartrusion.control.ControlCommand;
import java.beans.PropertyChangeEvent;
import com.hartrusion.control.ValveState;
import com.hartrusion.modeling.automated.PumpState;
import com.hartrusion.mvc.UpdateReceiver;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelMnemonicLoop extends javax.swing.JPanel implements UpdateReceiver {

    private int loop = 0;

    public int getLoop() {
        return loop;
    }

    public void setLoop(int loop) {
        this.loop = loop;
    }

    /**
     * Creates new form PanelMnemonicLoop
     */
    public PanelMnemonicLoop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegeneratedIn2 = new javax.swing.JLabel();
        valveMcpSuction1 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpSuction2 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpSuction3 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpSuction4 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpDischarge1 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpTrim1 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpDischarge2 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpTrim2 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpDischarge3 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpTrim3 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpDischarge4 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpTrim4 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveFeed1FlowReg = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveFeed1Gate = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMcpBypass = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveFeed2FlowReg = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveFeed2Gate = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveFeed0FlowReg = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveMainSteam = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveFeed0Gate = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveStartupRed = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        jLabelReadingFeed0PosRedValve = new javax.swing.JLabel();
        jLabelReadingFeed0Pos = new javax.swing.JLabel();
        jLabelReadingFeed1Pos = new javax.swing.JLabel();
        jLabelReadingFeed2Pos = new javax.swing.JLabel();
        pump1 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        pump2 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        pump3 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        pump4 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        jLabelBlowdownTemp = new javax.swing.JLabel();
        jLabelReadingMcpInPressure = new javax.swing.JLabel();
        jLabelReadingMcpInTemp = new javax.swing.JLabel();
        jLabelSteamFlow = new javax.swing.JLabel();
        jLabelFeedwaterFlow = new javax.swing.JLabel();
        jLabelBlowdownFlow = new javax.swing.JLabel();
        jLabelReadingFlowDowncomer = new javax.swing.JLabel();
        jLabelReadingTempToDrum = new javax.swing.JLabel();
        jLabelReadingDrumPressure = new javax.swing.JLabel();
        jLabelReadingTrim2 = new javax.swing.JLabel();
        jLabelReadingDrumTemp = new javax.swing.JLabel();
        jLabelReadingDrumLevel = new javax.swing.JLabel();
        jLabelReadingTrim3 = new javax.swing.JLabel();
        jLabelReadingTrim4 = new javax.swing.JLabel();
        jLabelReadingTrim1 = new javax.swing.JLabel();
        jLabelFeedwater = new javax.swing.JLabel();
        jLabelBlowdown = new javax.swing.JLabel();
        jLabelRegeneratedIn = new javax.swing.JLabel();
        jLabelRegeneratedIn1 = new javax.swing.JLabel();
        jLabelSteamDrum = new javax.swing.JLabel();
        jLabelCoreOut1 = new javax.swing.JLabel();
        jLabelCoreOut = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        jLabelRegeneratedIn2.setFont(jLabelRegeneratedIn2.getFont().deriveFont(jLabelRegeneratedIn2.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelRegeneratedIn2.getFont().getSize()-3));
        jLabelRegeneratedIn2.setForeground(new java.awt.Color(14, 222, 194));
        jLabelRegeneratedIn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRegeneratedIn2.setText("Regen.");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valveMcpSuction1.setVertical(true);
        add(valveMcpSuction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 368, -1, -1));

        valveMcpSuction2.setVertical(true);
        add(valveMcpSuction2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 368, -1, -1));

        valveMcpSuction3.setVertical(true);
        add(valveMcpSuction3, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 368, -1, -1));

        valveMcpSuction4.setVertical(true);
        add(valveMcpSuction4, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 368, -1, -1));

        valveMcpDischarge1.setVertical(true);
        add(valveMcpDischarge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 481, -1, -1));

        valveMcpTrim1.setVertical(true);
        add(valveMcpTrim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 523, -1, -1));

        valveMcpDischarge2.setVertical(true);
        add(valveMcpDischarge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 481, -1, -1));

        valveMcpTrim2.setVertical(true);
        add(valveMcpTrim2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 523, -1, -1));

        valveMcpDischarge3.setVertical(true);
        add(valveMcpDischarge3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 481, -1, -1));

        valveMcpTrim3.setVertical(true);
        add(valveMcpTrim3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 523, -1, -1));

        valveMcpDischarge4.setVertical(true);
        add(valveMcpDischarge4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 481, -1, -1));

        valveMcpTrim4.setVertical(true);
        add(valveMcpTrim4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 523, -1, -1));

        valveFeed1FlowReg.setControlIndicator(true);
        valveFeed1FlowReg.setVertical(true);
        add(valveFeed1FlowReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 210, -1, -1));

        valveFeed1Gate.setVertical(true);
        add(valveFeed1Gate, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 252, -1, -1));

        valveMcpBypass.setVertical(true);
        add(valveMcpBypass, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 504, -1, -1));

        valveFeed2FlowReg.setControlIndicator(true);
        valveFeed2FlowReg.setVertical(true);
        add(valveFeed2FlowReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 210, -1, -1));

        valveFeed2Gate.setVertical(true);
        add(valveFeed2Gate, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 252, -1, -1));

        valveFeed0FlowReg.setControlIndicator(true);
        valveFeed0FlowReg.setVertical(true);
        add(valveFeed0FlowReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 210, -1, -1));
        add(valveMainSteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 4, -1, -1));

        valveFeed0Gate.setVertical(true);
        add(valveFeed0Gate, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 252, -1, -1));

        valveStartupRed.setVertical(true);
        add(valveStartupRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 294, -1, -1));

        jLabelReadingFeed0PosRedValve.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingFeed0PosRedValve.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingFeed0PosRedValve.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingFeed0PosRedValve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingFeed0PosRedValve.setText("___");
        jLabelReadingFeed0PosRedValve.setOpaque(true);
        add(jLabelReadingFeed0PosRedValve, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 24, -1));

        jLabelReadingFeed0Pos.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingFeed0Pos.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingFeed0Pos.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingFeed0Pos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingFeed0Pos.setText("___");
        jLabelReadingFeed0Pos.setOpaque(true);
        add(jLabelReadingFeed0Pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 240, 24, -1));

        jLabelReadingFeed1Pos.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingFeed1Pos.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingFeed1Pos.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingFeed1Pos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingFeed1Pos.setText("___");
        jLabelReadingFeed1Pos.setOpaque(true);
        add(jLabelReadingFeed1Pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 240, 24, -1));

        jLabelReadingFeed2Pos.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingFeed2Pos.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingFeed2Pos.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingFeed2Pos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingFeed2Pos.setText("___");
        jLabelReadingFeed2Pos.setOpaque(true);
        add(jLabelReadingFeed2Pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 240, 24, -1));

        pump1.setOrientation(3);
        pump1.setPreferredSize(new java.awt.Dimension(36, 42));
        add(pump1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        pump2.setOrientation(3);
        pump2.setPreferredSize(new java.awt.Dimension(36, 42));
        add(pump2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 420, -1, -1));

        pump3.setOrientation(3);
        pump3.setPreferredSize(new java.awt.Dimension(36, 42));
        add(pump3, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 420, -1, -1));

        pump4.setOrientation(3);
        pump4.setPreferredSize(new java.awt.Dimension(36, 42));
        add(pump4, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 420, -1, -1));

        jLabelBlowdownTemp.setBackground(new java.awt.Color(77, 69, 27));
        jLabelBlowdownTemp.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelBlowdownTemp.setForeground(new java.awt.Color(231, 255, 166));
        jLabelBlowdownTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBlowdownTemp.setText("___ °C");
        jLabelBlowdownTemp.setOpaque(true);
        add(jLabelBlowdownTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 156, 56, 16));

        jLabelReadingMcpInPressure.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingMcpInPressure.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingMcpInPressure.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingMcpInPressure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingMcpInPressure.setText("___ bar");
        jLabelReadingMcpInPressure.setOpaque(true);
        add(jLabelReadingMcpInPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 56, 16));

        jLabelReadingMcpInTemp.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingMcpInTemp.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingMcpInTemp.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingMcpInTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingMcpInTemp.setText("___ °C");
        jLabelReadingMcpInTemp.setOpaque(true);
        add(jLabelReadingMcpInTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 56, 16));

        jLabelSteamFlow.setBackground(new java.awt.Color(77, 69, 27));
        jLabelSteamFlow.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelSteamFlow.setForeground(new java.awt.Color(231, 255, 166));
        jLabelSteamFlow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSteamFlow.setText("____ kg/s");
        jLabelSteamFlow.setOpaque(true);
        add(jLabelSteamFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 26, 56, 16));

        jLabelFeedwaterFlow.setBackground(new java.awt.Color(77, 69, 27));
        jLabelFeedwaterFlow.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelFeedwaterFlow.setForeground(new java.awt.Color(231, 255, 166));
        jLabelFeedwaterFlow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFeedwaterFlow.setText("____ kg/s");
        jLabelFeedwaterFlow.setOpaque(true);
        add(jLabelFeedwaterFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 186, 56, 16));

        jLabelBlowdownFlow.setBackground(new java.awt.Color(77, 69, 27));
        jLabelBlowdownFlow.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelBlowdownFlow.setForeground(new java.awt.Color(231, 255, 166));
        jLabelBlowdownFlow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBlowdownFlow.setText("____ kg/s");
        jLabelBlowdownFlow.setOpaque(true);
        add(jLabelBlowdownFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 136, 56, 16));

        jLabelReadingFlowDowncomer.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingFlowDowncomer.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingFlowDowncomer.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingFlowDowncomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingFlowDowncomer.setText("____ kg/s");
        jLabelReadingFlowDowncomer.setToolTipText("");
        jLabelReadingFlowDowncomer.setOpaque(true);
        add(jLabelReadingFlowDowncomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 56, 16));

        jLabelReadingTempToDrum.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingTempToDrum.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingTempToDrum.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingTempToDrum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingTempToDrum.setText("___ °C");
        jLabelReadingTempToDrum.setOpaque(true);
        add(jLabelReadingTempToDrum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 88, 56, 16));

        jLabelReadingDrumPressure.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingDrumPressure.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingDrumPressure.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingDrumPressure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingDrumPressure.setText("___ bar");
        jLabelReadingDrumPressure.setOpaque(true);
        add(jLabelReadingDrumPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 74, 56, 16));

        jLabelReadingTrim2.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingTrim2.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingTrim2.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingTrim2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingTrim2.setText("___");
        jLabelReadingTrim2.setOpaque(true);
        add(jLabelReadingTrim2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 538, 24, -1));

        jLabelReadingDrumTemp.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingDrumTemp.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingDrumTemp.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingDrumTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingDrumTemp.setText("___ °C");
        jLabelReadingDrumTemp.setOpaque(true);
        add(jLabelReadingDrumTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 94, 56, 16));

        jLabelReadingDrumLevel.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingDrumLevel.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingDrumLevel.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingDrumLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingDrumLevel.setText("____ cm");
        jLabelReadingDrumLevel.setOpaque(true);
        add(jLabelReadingDrumLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 54, 56, 16));

        jLabelReadingTrim3.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingTrim3.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingTrim3.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingTrim3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingTrim3.setText("___");
        jLabelReadingTrim3.setOpaque(true);
        add(jLabelReadingTrim3, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 538, 24, -1));

        jLabelReadingTrim4.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingTrim4.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingTrim4.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingTrim4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingTrim4.setText("___");
        jLabelReadingTrim4.setOpaque(true);
        add(jLabelReadingTrim4, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 538, 24, -1));

        jLabelReadingTrim1.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingTrim1.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingTrim1.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingTrim1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingTrim1.setText("___");
        jLabelReadingTrim1.setOpaque(true);
        add(jLabelReadingTrim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 538, 24, -1));

        jLabelFeedwater.setFont(jLabelFeedwater.getFont().deriveFont(jLabelFeedwater.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelFeedwater.getFont().getSize()-3));
        jLabelFeedwater.setForeground(new java.awt.Color(14, 222, 194));
        jLabelFeedwater.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFeedwater.setText("Feedwater");
        add(jLabelFeedwater, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 68, -1));

        jLabelBlowdown.setFont(jLabelBlowdown.getFont().deriveFont(jLabelBlowdown.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelBlowdown.getFont().getSize()-3));
        jLabelBlowdown.setForeground(new java.awt.Color(14, 222, 194));
        jLabelBlowdown.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBlowdown.setText("Blowdown");
        add(jLabelBlowdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 144, 66, -1));

        jLabelRegeneratedIn.setFont(jLabelRegeneratedIn.getFont().deriveFont(jLabelRegeneratedIn.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelRegeneratedIn.getFont().getSize()-3));
        jLabelRegeneratedIn.setForeground(new java.awt.Color(14, 222, 194));
        jLabelRegeneratedIn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRegeneratedIn.setText("Blowdown");
        add(jLabelRegeneratedIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 162, 62, -1));

        jLabelRegeneratedIn1.setFont(jLabelRegeneratedIn1.getFont().deriveFont(jLabelRegeneratedIn1.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelRegeneratedIn1.getFont().getSize()-3));
        jLabelRegeneratedIn1.setForeground(new java.awt.Color(14, 222, 194));
        jLabelRegeneratedIn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRegeneratedIn1.setText("return");
        add(jLabelRegeneratedIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 176, 44, -1));

        jLabelSteamDrum.setFont(jLabelSteamDrum.getFont().deriveFont(jLabelSteamDrum.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelSteamDrum.getFont().getSize()-3));
        jLabelSteamDrum.setForeground(new java.awt.Color(14, 222, 194));
        jLabelSteamDrum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSteamDrum.setText("Steam drum");
        add(jLabelSteamDrum, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 36, 88, -1));

        jLabelCoreOut1.setFont(jLabelCoreOut1.getFont().deriveFont(jLabelCoreOut1.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCoreOut1.getFont().getSize()-3));
        jLabelCoreOut1.setForeground(new java.awt.Color(14, 222, 194));
        jLabelCoreOut1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCoreOut1.setText("Core in");
        add(jLabelCoreOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 554, 52, -1));

        jLabelCoreOut.setFont(jLabelCoreOut.getFont().deriveFont(jLabelCoreOut.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelCoreOut.getFont().getSize()-3));
        jLabelCoreOut.setForeground(new java.awt.Color(14, 222, 194));
        jLabelCoreOut.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCoreOut.setText("Core out");
        add(jLabelCoreOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 62, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hartrusion/rbmksim/gui/mnemonic/MnemonicLoop.png"))); // NOI18N
        add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBlowdown;
    private javax.swing.JLabel jLabelBlowdownFlow;
    private javax.swing.JLabel jLabelBlowdownTemp;
    private javax.swing.JLabel jLabelCoreOut;
    private javax.swing.JLabel jLabelCoreOut1;
    private javax.swing.JLabel jLabelFeedwater;
    private javax.swing.JLabel jLabelFeedwaterFlow;
    private javax.swing.JLabel jLabelReadingDrumLevel;
    private javax.swing.JLabel jLabelReadingDrumPressure;
    private javax.swing.JLabel jLabelReadingDrumTemp;
    private javax.swing.JLabel jLabelReadingFeed0Pos;
    private javax.swing.JLabel jLabelReadingFeed0PosRedValve;
    private javax.swing.JLabel jLabelReadingFeed1Pos;
    private javax.swing.JLabel jLabelReadingFeed2Pos;
    private javax.swing.JLabel jLabelReadingFlowDowncomer;
    private javax.swing.JLabel jLabelReadingMcpInPressure;
    private javax.swing.JLabel jLabelReadingMcpInTemp;
    private javax.swing.JLabel jLabelReadingTempToDrum;
    private javax.swing.JLabel jLabelReadingTrim1;
    private javax.swing.JLabel jLabelReadingTrim2;
    private javax.swing.JLabel jLabelReadingTrim3;
    private javax.swing.JLabel jLabelReadingTrim4;
    private javax.swing.JLabel jLabelRegeneratedIn;
    private javax.swing.JLabel jLabelRegeneratedIn1;
    private javax.swing.JLabel jLabelRegeneratedIn2;
    private javax.swing.JLabel jLabelSteamDrum;
    private javax.swing.JLabel jLabelSteamFlow;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pump1;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pump2;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pump3;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pump4;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveFeed0FlowReg;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveFeed0Gate;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveFeed1FlowReg;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveFeed1Gate;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveFeed2FlowReg;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveFeed2Gate;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMainSteam;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpBypass;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpDischarge1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpDischarge2;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpDischarge3;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpDischarge4;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpSuction1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpSuction2;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpSuction3;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpSuction4;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpTrim1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpTrim2;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpTrim3;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveMcpTrim4;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveStartupRed;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        String command; // extracted part after the #
        if (evt.getPropertyName().startsWith("Feedwater")) {
            // check for correct loop number 
            if (Character.getNumericValue(
                    evt.getPropertyName().charAt(9)) != loop) {
                return;
            }
            command = evt.getPropertyName().substring(11);
            switch (command) {
                case "StartupReductionValve_Pos" ->
                    valveStartupRed.setActive(
                            evt.getNewValue() != ValveState.CLOSED);
                case "FlowRegulationValve1_Pos" ->
                    valveFeed0FlowReg.setActive(
                            evt.getNewValue() != ValveState.CLOSED);
                case "FlowRegulationValve1ControlState" ->
                    valveFeed0FlowReg.setControlIndicatorActive(
                            evt.getNewValue() == ControlCommand.AUTOMATIC);
                case "FlowRegulationValve2_Pos" ->
                    valveFeed1FlowReg.setActive(
                            evt.getNewValue() != ValveState.CLOSED);
                case "FlowRegulationValve2ControlState" ->
                    valveFeed1FlowReg.setControlIndicatorActive(
                            evt.getNewValue() == ControlCommand.AUTOMATIC);
                case "FlowRegulationValve3_Pos" ->
                    valveFeed2FlowReg.setActive(
                            evt.getNewValue() != ValveState.CLOSED);
                case "FlowRegulationValve3ControlState" ->
                    valveFeed2FlowReg.setControlIndicatorActive(
                            evt.getNewValue() == ControlCommand.AUTOMATIC);
                case "ShutoffValve1_Pos" ->
                    valveFeed0Gate.setActive(
                            evt.getNewValue() != ValveState.CLOSED);
                case "ShutoffValve2_Pos" ->
                    valveFeed1Gate.setActive(
                            evt.getNewValue() != ValveState.CLOSED);
                case "ShutoffValve3_Pos" ->
                    valveFeed2Gate.setActive(
                            evt.getNewValue() != ValveState.CLOSED);
            }

            return;
        }
        if (!evt.getPropertyName().startsWith("Loop")) {
            return;
        }
        // Check for correct loop number and discard everything for other loop.
        if (Character.getNumericValue(
                evt.getPropertyName().charAt(4)) != loop) {
            return;
        }
        if (evt.getPropertyName().substring(6, 9).equals("mcp")) {
            // The property name looks something like this:
            // Loop2#mcp4DischargeValve_Pos
            // Loop1#mcp1Pump_State with true/false value
            // Extract pump group number
            int nr = Character.getNumericValue(evt.getPropertyName().charAt(9));
            command = evt.getPropertyName().substring(10);
            switch (command) {
                case "DischargeValve_Pos" -> {
                    switch (nr) {
                        case 1 ->
                            valveMcpDischarge1.setActive(
                                    evt.getNewValue() != ValveState.CLOSED);
                        case 2 ->
                            valveMcpDischarge2.setActive(
                                    evt.getNewValue() != ValveState.CLOSED);
                        case 3 ->
                            valveMcpDischarge3.setActive(
                                    evt.getNewValue() != ValveState.CLOSED);
                        case 4 ->
                            valveMcpDischarge4.setActive(
                                    evt.getNewValue() != ValveState.CLOSED);
                    }
                }
                case "SuctionValve_Pos" -> {
                    switch (nr) {
                        case 1 ->
                            valveMcpSuction1.setActive(
                                    evt.getNewValue() != ValveState.CLOSED);
                        case 2 ->
                            valveMcpSuction2.setActive(
                                    evt.getNewValue() != ValveState.CLOSED);
                        case 3 ->
                            valveMcpSuction3.setActive(
                                    evt.getNewValue() != ValveState.CLOSED);
                        case 4 ->
                            valveMcpSuction4.setActive(
                                    evt.getNewValue() != ValveState.CLOSED);
                    }
                }
                case "Pump_State" -> {
                    if (PumpState.OFFLINE == (PumpState) evt.getNewValue()) {
                        switch (nr) {
                            case 1 ->
                                pump1.setStatus(0);
                            case 2 ->
                                pump2.setStatus(0);
                            case 3 ->
                                pump3.setStatus(0);
                            case 4 ->
                                pump4.setStatus(0);
                        }
                    } else if (PumpState.READY == (PumpState) evt.getNewValue()) {
                        switch (nr) {
                            case 1 ->
                                pump1.setStatus(1);
                            case 2 ->
                                pump2.setStatus(1);
                            case 3 ->
                                pump3.setStatus(1);
                            case 4 ->
                                pump4.setStatus(1);
                        }
                    } else if (PumpState.STARTUP == (PumpState) evt.getNewValue()) {
                        switch (nr) {
                            case 1 ->
                                pump1.setStatus(2);
                            case 2 ->
                                pump2.setStatus(2);
                            case 3 ->
                                pump3.setStatus(2);
                            case 4 ->
                                pump4.setStatus(2);
                        }
                    } else if (PumpState.RUNNING == (PumpState) evt.getNewValue()) {
                        switch (nr) {
                            case 1 ->
                                pump1.setStatus(3);
                            case 2 ->
                                pump2.setStatus(3);
                            case 3 ->
                                pump3.setStatus(3);
                            case 4 ->
                                pump4.setStatus(3);
                        }
                    }
                }
            }
            return;
        }
        if (evt.getPropertyName().substring(6, 16).equals("Bypass_Pos")) {
            valveMcpBypass.setActive(evt.getNewValue() != ValveState.CLOSED);
            return;
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        if (propertyName.length() == 15) { // FeedwaterN#Flow
            if (Character.getNumericValue(propertyName.charAt(9)) == loop) {
                if (propertyName.substring(11).equals("Flow")) {
                    jLabelFeedwaterFlow.setText(
                            String.format("%.0f", newValue) + " kg/s");
                    return;
                }
            }
        }
        if (propertyName.length() == 31) { // FeedwaterN#FlowRegulationValveM
            if (Character.getNumericValue(propertyName.charAt(9)) == loop) {
                if (propertyName.substring(11, 30).equals("FlowRegulationValve")) {
                    switch (Character.getNumericValue(propertyName.charAt(30))) {
                        case 1 ->
                            jLabelReadingFeed0Pos.setText(
                                    String.format("%.0f", newValue));
                        case 2 ->
                            jLabelReadingFeed1Pos.setText(
                                    String.format("%.0f", newValue));
                        case 3 ->
                            jLabelReadingFeed2Pos.setText(
                                    String.format("%.0f", newValue));
                    }

                    return;
                }
            }
        }
        // FeedwaterN#FlowRegulationValveM
        // FeedwaterN#StartupReductionValve
        if (propertyName.length() == 32) { // FeedwaterN#StartupReductionValve
            if (Character.getNumericValue(propertyName.charAt(9)) == loop) {
                if (propertyName.substring(11, 32).equals("StartupReductionValve")) {
                    jLabelReadingFeed0PosRedValve.setText(
                            String.format("%.0f", newValue));
                }
            }
        }
        if (propertyName.equals("Blowdown#CoolantOutTemp")) {
            jLabelBlowdownTemp.setText(
                    String.format("%.1f", newValue)
                            .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            return;
        }
        if (propertyName.length() == 23) {
            if (propertyName.substring(6, 23).equals("SteamFromDrumFlow")) {
                if (Character.getNumericValue(propertyName.charAt(4)) == loop) {
                    jLabelSteamFlow.setText(
                            String.format("%.0f", newValue) + " kg/s");
                    return;
                }
            }
        }
        if (propertyName.length() == 23) {
            if (propertyName.substring(6, 23).equals("SteamShutoffValve")) {
                if (Character.getNumericValue(propertyName.charAt(4)) == loop) {
                    // jLabelReadingSteamShuttoff.setText(
                    //        String.format("%.0f", newValue));
                    // - this UI label was removed.
                    // use double value instead of events for this valve
                    valveMainSteam.setActive(newValue >= 1.0);
                    return;
                }
            }
        }
        if (!propertyName.startsWith("Loop")) {
            return;
        }
        if (Character.getNumericValue(propertyName.charAt(4)) != loop) {
            return; // value is ment for the other loop.
        }
        if (propertyName.substring(6, 9).equals("mcp")) {
            // The property name looks something like this:
            // Loop2#mcp4DischargeValve_Pos
            // Loop1#mcp1Pump_State with true/false value
            // Extract pump group number
            int nr = Character.getNumericValue(propertyName.charAt(9));
            String command = propertyName.substring(10);
            switch (command) {
                case "TrimValve" -> {
                    switch (nr) {
                        case 1 -> {
                            jLabelReadingTrim1.setText(
                                    String.format("%.0f", newValue));
                            valveMcpTrim1.setActive(newValue >= 5);
                        }
                        case 2 -> {
                            jLabelReadingTrim2.setText(
                                    String.format("%.0f", newValue));
                            valveMcpTrim2.setActive(newValue >= 5);
                        }
                        case 3 -> {
                            jLabelReadingTrim3.setText(
                                    String.format("%.0f", newValue));
                            valveMcpTrim3.setActive(newValue >= 5);
                        }
                        case 4 -> {
                            jLabelReadingTrim4.setText(
                                    String.format("%.0f", newValue));
                            valveMcpTrim4.setActive(newValue >= 5);
                        }
                    }
                }
            }
        }
        String component = propertyName.substring(6);
        switch (component) {
            case "DrumTemperature" ->
                jLabelReadingDrumTemp.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "DrumPressure" ->
                jLabelReadingDrumPressure.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " bar");
            case "DrumLevel" ->
                jLabelReadingDrumLevel.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " cm");
            case "DownFlow" ->
                jLabelReadingFlowDowncomer.setText(
                        String.format("%.0f", newValue) + " kg/s");
            case "ReactorOutTemperature" ->
                jLabelReadingTempToDrum.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "McpInTemp" ->
                jLabelReadingMcpInTemp.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "McpInPressure" ->
                jLabelReadingMcpInPressure.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " bar");
            case "ReactorOutTemp" ->
                jLabelReadingTempToDrum.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "BlowdownFlowToFeedwaterIn" ->
                jLabelBlowdownFlow.setText(
                        String.format("%.0f", newValue) + " kg/s");
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
