/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.mnemonic;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelMnemonicDeaerator extends javax.swing.JPanel {

    /**
     * Creates new form PanelMnemonicDeaerator
     */
    public PanelMnemonicDeaerator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valve1 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve2 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve3 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve4 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve5 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve6 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve7 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve8 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve9 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve10 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve11 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 264));
        setPreferredSize(new java.awt.Dimension(400, 264));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valve1.setVertical(true);
        add(valve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 211, -1, -1));

        valve2.setVertical(true);
        add(valve2, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 211, -1, -1));

        valve3.setVertical(true);
        add(valve3, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 132, -1, -1));

        valve4.setVertical(true);
        add(valve4, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 150, -1, -1));

        valve5.setVertical(true);
        add(valve5, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 150, -1, -1));

        valve6.setVertical(true);
        add(valve6, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 132, -1, -1));
        add(valve7, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 76, -1, -1));
        add(valve8, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 76, -1, -1));
        add(valve9, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 11, -1, -1));
        add(valve10, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 11, -1, -1));

        valve11.setVertical(true);
        add(valve11, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 208, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hartrusion/rbmksim/gui/mnemonic/MnemonicDeaerator.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve10;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve11;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve2;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve3;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve4;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve5;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve6;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve7;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve8;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve9;
    // End of variables declaration//GEN-END:variables
}
