/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.mnemonic;

import com.hartrusion.control.ControlCommand;
import com.hartrusion.control.ValveState;
import com.hartrusion.modeling.automated.PumpState;
import static com.hartrusion.modeling.automated.PumpState.OFFLINE;
import static com.hartrusion.modeling.automated.PumpState.READY;
import static com.hartrusion.modeling.automated.PumpState.RUNNING;
import static com.hartrusion.modeling.automated.PumpState.STARTUP;
import com.hartrusion.mvc.UpdateReceiver;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelMnemonicCondensate extends javax.swing.JPanel
        implements UpdateReceiver {

    /**
     * Creates new form PanelMnemonicCondensate
     */
    public PanelMnemonicCondensate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valve1 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector1In = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector1Out = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector1Steam = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve5 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector1Condensate = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector2In = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector2Out = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector2Steam = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve10 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector2Condensate = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector3In = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector3Out = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector3Steam = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjector3Condensate = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valve16 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensatePump1Suction = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensatePump2Suction = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensatePump3Suction = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        pumpCondensate1 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        pumpCondensate2 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        pumpCondensate3 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        valveCondensatePump1Discharge = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensatePump2Discharge = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensatePump3Discharge = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveEjectorBypass = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        jLabelFromHotwell = new javax.swing.JLabel();
        jLabelToDA = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(652, 228));
        setMinimumSize(new java.awt.Dimension(652, 228));
        setPreferredSize(new java.awt.Dimension(652, 228));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valve1.setActive(true);
        valve1.setVertical(true);
        add(valve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 17, -1, -1));

        valveEjector1In.setVertical(true);
        add(valveEjector1In, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 152, -1, -1));

        valveEjector1Out.setVertical(true);
        add(valveEjector1Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 131, -1, -1));

        valveEjector1Steam.setVertical(true);
        add(valveEjector1Steam, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 23, -1, -1));
        add(valve5, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 71, -1, -1));

        valveEjector1Condensate.setControlIndicator(true);
        add(valveEjector1Condensate, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 111, -1, -1));

        valveEjector2In.setVertical(true);
        add(valveEjector2In, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 152, -1, -1));

        valveEjector2Out.setVertical(true);
        add(valveEjector2Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 131, -1, -1));

        valveEjector2Steam.setVertical(true);
        add(valveEjector2Steam, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 23, -1, -1));
        add(valve10, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 71, -1, -1));

        valveEjector2Condensate.setControlIndicator(true);
        add(valveEjector2Condensate, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 111, -1, -1));

        valveEjector3In.setVertical(true);
        add(valveEjector3In, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 152, -1, -1));

        valveEjector3Out.setVertical(true);
        add(valveEjector3Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 131, -1, -1));

        valveEjector3Steam.setVertical(true);
        add(valveEjector3Steam, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 23, -1, -1));

        valveEjector3Condensate.setControlIndicator(true);
        add(valveEjector3Condensate, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 111, -1, -1));
        add(valve16, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 71, -1, -1));

        valveCondensatePump1Suction.setVertical(true);
        add(valveCondensatePump1Suction, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 82, -1, -1));

        valveCondensatePump2Suction.setVertical(true);
        add(valveCondensatePump2Suction, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 82, -1, -1));

        valveCondensatePump3Suction.setVertical(true);
        add(valveCondensatePump3Suction, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 82, -1, -1));

        pumpCondensate1.setOrientation(3);
        pumpCondensate1.setPreferredSize(new java.awt.Dimension(36, 41));
        add(pumpCondensate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 125, -1, -1));

        pumpCondensate2.setOrientation(3);
        pumpCondensate2.setPreferredSize(new java.awt.Dimension(36, 41));
        add(pumpCondensate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 125, -1, -1));

        pumpCondensate3.setOrientation(3);
        pumpCondensate3.setPreferredSize(new java.awt.Dimension(36, 41));
        add(pumpCondensate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 125, -1, -1));

        valveCondensatePump1Discharge.setVertical(true);
        add(valveCondensatePump1Discharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 168, -1, -1));

        valveCondensatePump2Discharge.setVertical(true);
        add(valveCondensatePump2Discharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 168, -1, -1));

        valveCondensatePump3Discharge.setVertical(true);
        add(valveCondensatePump3Discharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 168, -1, -1));
        add(valveEjectorBypass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 203, -1, -1));

        jLabelFromHotwell.setFont(jLabelFromHotwell.getFont().deriveFont(jLabelFromHotwell.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelFromHotwell.getFont().getSize()-3));
        jLabelFromHotwell.setForeground(new java.awt.Color(14, 222, 194));
        jLabelFromHotwell.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFromHotwell.setText("Hotwell");
        add(jLabelFromHotwell, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 2, 50, -1));

        jLabelToDA.setFont(jLabelToDA.getFont().deriveFont(jLabelToDA.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelToDA.getFont().getSize()-3));
        jLabelToDA.setForeground(new java.awt.Color(14, 222, 194));
        jLabelToDA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelToDA.setText("DA");
        add(jLabelToDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 184, 26, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hartrusion/rbmksim/gui/mnemonic/MnemonicCondensate.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFromHotwell;
    private javax.swing.JLabel jLabelToDA;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pumpCondensate1;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pumpCondensate2;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pumpCondensate3;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve10;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve16;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valve5;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump1Discharge;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump1Suction;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump2Discharge;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump2Suction;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump3Discharge;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensatePump3Suction;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector1Condensate;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector1In;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector1Out;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector1Steam;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector2Condensate;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector2In;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector2Out;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector2Steam;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector3Condensate;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector3In;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector3Out;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjector3Steam;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveEjectorBypass;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        switch (evt.getPropertyName()) {
            case "Condensation1#CondensatePumpSuctionValve_Pos" ->
                valveCondensatePump1Suction.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Condensation1#CondensatePumpPump_State" -> {
                switch ((PumpState) evt.getNewValue()) {
                    case OFFLINE ->
                        pumpCondensate1.setStatus(0);
                    case READY ->
                        pumpCondensate1.setStatus(1);
                    case STARTUP ->
                        pumpCondensate1.setStatus(2);
                    case RUNNING ->
                        pumpCondensate1.setStatus(3);
                }
            }
            case "Condensation1#CondensatePumpDischargeValve_Pos" ->
                valveCondensatePump1Discharge.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Condensation2#CondensatePumpSuctionValve_Pos" ->
                valveCondensatePump2Suction.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Condensation2#CondensatePumpPump_State" -> {
                switch ((PumpState) evt.getNewValue()) {
                    case OFFLINE ->
                        pumpCondensate2.setStatus(0);
                    case READY ->
                        pumpCondensate2.setStatus(1);
                    case STARTUP ->
                        pumpCondensate2.setStatus(2);
                    case RUNNING ->
                        pumpCondensate2.setStatus(3);
                }
            }
            case "Condensation2#CondensatePumpDischargeValve_Pos" ->
                valveCondensatePump2Discharge.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Condensation3#CondensatePumpSuctionValve_Pos" ->
                valveCondensatePump3Suction.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Condensation3#CondensatePumpPump_State" -> {
                switch ((PumpState) evt.getNewValue()) {
                    case OFFLINE ->
                        pumpCondensate3.setStatus(0);
                    case READY ->
                        pumpCondensate3.setStatus(1);
                    case STARTUP ->
                        pumpCondensate3.setStatus(2);
                    case RUNNING ->
                        pumpCondensate3.setStatus(3);
                }
            }
            case "Condensation3#CondensatePumpDischargeValve_Pos" ->
                valveCondensatePump3Discharge.setActive(evt.getNewValue() != ValveState.CLOSED);
                
            case "EjectorMain1#SteamValve_Pos" ->
                valveEjector1Steam.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain1#CondensateValve_Pos" ->
                valveEjector1Condensate.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain1#CondensateValveControlState" -> {
                if (evt.getNewValue() == ControlCommand.AUTOMATIC) {
                    valveEjector1Condensate.setControlIndicatorActive(true);
                } else if (evt.getNewValue() == ControlCommand.MANUAL_OPERATION) {
                    valveEjector1Condensate.setControlIndicatorActive(false);
                }
            }
            case "EjectorMain1#FlowIn_Pos" ->
                valveEjector1In.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain1#FlowOut_Pos" ->
                valveEjector1Out.setActive(evt.getNewValue() != ValveState.CLOSED);
                
            case "EjectorMain2#SteamValve_Pos" ->
                valveEjector2Steam.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain2#CondensateValve_Pos" ->
                valveEjector2Condensate.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain2#CondensateValveControlState" -> {
                if (evt.getNewValue() == ControlCommand.AUTOMATIC) {
                    valveEjector2Condensate.setControlIndicatorActive(true);
                } else if (evt.getNewValue() == ControlCommand.MANUAL_OPERATION) {
                    valveEjector2Condensate.setControlIndicatorActive(false);
                }
            }
            case "EjectorMain2#FlowIn_Pos" ->
                valveEjector2In.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain2#FlowOut_Pos" ->
                valveEjector2Out.setActive(evt.getNewValue() != ValveState.CLOSED);
                
            case "EjectorMain3#SteamValve_Pos" ->
                valveEjector3Steam.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain3#CondensateValve_Pos" ->
                valveEjector3Condensate.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain3#CondensateValveControlState" -> {
                if (evt.getNewValue() == ControlCommand.AUTOMATIC) {
                    valveEjector3Condensate.setControlIndicatorActive(true);
                } else if (evt.getNewValue() == ControlCommand.MANUAL_OPERATION) {
                    valveEjector3Condensate.setControlIndicatorActive(false);
                }
            }
            case "EjectorMain3#FlowIn_Pos" ->
                valveEjector3In.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "EjectorMain3#FlowOut_Pos" ->
                valveEjector3Out.setActive(evt.getNewValue() != ValveState.CLOSED);
                
            case "EjectorMain#Bypass_Pos" ->
                valveEjectorBypass.setActive(evt.getNewValue() != ValveState.CLOSED);
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {

    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
