/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.mnemonic;

import com.hartrusion.control.ControlCommand;
import java.beans.PropertyChangeEvent;
import com.hartrusion.control.ValveState;
import com.hartrusion.modeling.automated.PumpState;
import com.hartrusion.mvc.UpdateReceiver;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelMnemonicBlowdown extends javax.swing.JPanel implements UpdateReceiver {

    /**
     * Creates new form PanelMnemonicBlowdown
     */
    public PanelMnemonicBlowdown() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valvePassiveFlow = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valvePumpsToCooler = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valvePump1Discharge = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valvePump2Discharge = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveFromDrum1 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveFromDrum2 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveFromDistributor1 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveFromDistributor2 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCoolantIn = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveDrain = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveTreatedToDrums = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveTreatmentBypass = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveOut2 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveOut1 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valvePump1Suction = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valvePump2Suction = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        pump1 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        pump2 = new com.hartrusion.rbmksim.gui.mnemonic.Pump();
        valveRegeneratorToCooler = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valvePumpsToRegenerator = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        jLabelReadingValveFromLoop1 = new javax.swing.JLabel();
        jLabelReadingCoolantValve = new javax.swing.JLabel();
        jLabelCoolerSecondaryOutTemp = new javax.swing.JLabel();
        jLabelCoolerSecondaryFlow = new javax.swing.JLabel();
        jLabelReadingCoolerPrimaryInTemp = new javax.swing.JLabel();
        jLabelReadingCoolerPrimaryFlow = new javax.swing.JLabel();
        jLabelReadingRegenPrimaryOutTemp = new javax.swing.JLabel();
        jLabelReadingInTemperature = new javax.swing.JLabel();
        jLabelReadingRegenSecondaryOutTemp = new javax.swing.JLabel();
        jLabelReadingTreatmentOutTemp = new javax.swing.JLabel();
        jLabelReadingCoolerPrimaryOutTemp = new javax.swing.JLabel();
        jLabelReadingValveFromLoop2 = new javax.swing.JLabel();
        jLabelReadingDrainValve = new javax.swing.JLabel();
        jLabelReadingDrainFlow = new javax.swing.JLabel();
        jLabelReadingReturnValve1 = new javax.swing.JLabel();
        jLabelReadingReturnValve2 = new javax.swing.JLabel();
        jLabelToDrum1 = new javax.swing.JLabel();
        jLabelToDrum2 = new javax.swing.JLabel();
        jLabelToDrum3 = new javax.swing.JLabel();
        jLabelToDrum4 = new javax.swing.JLabel();
        jLabelToDrum5 = new javax.swing.JLabel();
        jLabelToDrum6 = new javax.swing.JLabel();
        jLabelToDrum7 = new javax.swing.JLabel();
        jLabelToDrum8 = new javax.swing.JLabel();
        jLabelToDrum9 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(324, 460));
        setMinimumSize(new java.awt.Dimension(324, 460));
        setPreferredSize(new java.awt.Dimension(324, 460));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valvePassiveFlow.setVertical(true);
        add(valvePassiveFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 348, -1, -1));
        add(valvePumpsToCooler, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 265, -1, -1));

        valvePump1Discharge.setVertical(true);
        add(valvePump1Discharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 305, -1, -1));

        valvePump2Discharge.setVertical(true);
        add(valvePump2Discharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 305, -1, -1));

        valveFromDrum1.setVertical(true);
        add(valveFromDrum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 322, -1, -1));

        valveFromDrum2.setVertical(true);
        add(valveFromDrum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 322, -1, -1));
        add(valveFromDistributor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 412, -1, -1));
        add(valveFromDistributor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 412, -1, -1));
        add(valveCoolantIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 175, -1, -1));
        add(valveDrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 69, -1, -1));

        valveTreatedToDrums.setVertical(true);
        add(valveTreatedToDrums, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 106, -1, -1));

        valveTreatmentBypass.setVertical(true);
        add(valveTreatmentBypass, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 107, -1, -1));

        valveOut2.setControlIndicator(true);
        add(valveOut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 13, -1, -1));

        valveOut1.setControlIndicator(true);
        add(valveOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 13, -1, -1));

        valvePump1Suction.setVertical(true);
        add(valvePump1Suction, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 408, -1, -1));

        valvePump2Suction.setVertical(true);
        add(valvePump2Suction, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 408, -1, -1));

        pump1.setOrientation(1);
        pump1.setPreferredSize(new java.awt.Dimension(36, 42));
        add(pump1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 364, -1, -1));

        pump2.setOrientation(1);
        pump2.setFocusable(false);
        pump2.setPreferredSize(new java.awt.Dimension(36, 42));
        add(pump2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 364, -1, -1));
        add(valveRegeneratorToCooler, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 233, -1, -1));
        add(valvePumpsToRegenerator, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 265, -1, -1));

        jLabelReadingValveFromLoop1.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingValveFromLoop1.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingValveFromLoop1.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingValveFromLoop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingValveFromLoop1.setText("___");
        jLabelReadingValveFromLoop1.setOpaque(true);
        add(jLabelReadingValveFromLoop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 396, 24, -1));

        jLabelReadingCoolantValve.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingCoolantValve.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingCoolantValve.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingCoolantValve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingCoolantValve.setText("___");
        jLabelReadingCoolantValve.setOpaque(true);
        add(jLabelReadingCoolantValve, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 160, 24, -1));

        jLabelCoolerSecondaryOutTemp.setBackground(new java.awt.Color(77, 69, 27));
        jLabelCoolerSecondaryOutTemp.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelCoolerSecondaryOutTemp.setForeground(new java.awt.Color(231, 255, 166));
        jLabelCoolerSecondaryOutTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCoolerSecondaryOutTemp.setText("___ °C");
        jLabelCoolerSecondaryOutTemp.setOpaque(true);
        add(jLabelCoolerSecondaryOutTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 186, 56, 16));

        jLabelCoolerSecondaryFlow.setBackground(new java.awt.Color(77, 69, 27));
        jLabelCoolerSecondaryFlow.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelCoolerSecondaryFlow.setForeground(new java.awt.Color(231, 255, 166));
        jLabelCoolerSecondaryFlow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCoolerSecondaryFlow.setText("____ kg/s");
        jLabelCoolerSecondaryFlow.setOpaque(true);
        add(jLabelCoolerSecondaryFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 166, 56, 16));

        jLabelReadingCoolerPrimaryInTemp.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingCoolerPrimaryInTemp.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingCoolerPrimaryInTemp.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingCoolerPrimaryInTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingCoolerPrimaryInTemp.setText("___ °C");
        jLabelReadingCoolerPrimaryInTemp.setOpaque(true);
        add(jLabelReadingCoolerPrimaryInTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 226, 56, 16));

        jLabelReadingCoolerPrimaryFlow.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingCoolerPrimaryFlow.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingCoolerPrimaryFlow.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingCoolerPrimaryFlow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingCoolerPrimaryFlow.setText("____ kg/s");
        jLabelReadingCoolerPrimaryFlow.setOpaque(true);
        add(jLabelReadingCoolerPrimaryFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 206, 56, 16));

        jLabelReadingRegenPrimaryOutTemp.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingRegenPrimaryOutTemp.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingRegenPrimaryOutTemp.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingRegenPrimaryOutTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingRegenPrimaryOutTemp.setText("___ °C");
        jLabelReadingRegenPrimaryOutTemp.setOpaque(true);
        add(jLabelReadingRegenPrimaryOutTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 222, 56, 16));

        jLabelReadingInTemperature.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingInTemperature.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingInTemperature.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingInTemperature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingInTemperature.setText("___ °C");
        jLabelReadingInTemperature.setOpaque(true);
        add(jLabelReadingInTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 442, 56, 16));

        jLabelReadingRegenSecondaryOutTemp.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingRegenSecondaryOutTemp.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingRegenSecondaryOutTemp.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingRegenSecondaryOutTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingRegenSecondaryOutTemp.setText("___ °C");
        jLabelReadingRegenSecondaryOutTemp.setOpaque(true);
        add(jLabelReadingRegenSecondaryOutTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 26, 56, 16));

        jLabelReadingTreatmentOutTemp.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingTreatmentOutTemp.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingTreatmentOutTemp.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingTreatmentOutTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingTreatmentOutTemp.setText("___ °C");
        jLabelReadingTreatmentOutTemp.setOpaque(true);
        add(jLabelReadingTreatmentOutTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 56, 56, 16));

        jLabelReadingCoolerPrimaryOutTemp.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingCoolerPrimaryOutTemp.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingCoolerPrimaryOutTemp.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingCoolerPrimaryOutTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingCoolerPrimaryOutTemp.setText("___ °C");
        jLabelReadingCoolerPrimaryOutTemp.setOpaque(true);
        add(jLabelReadingCoolerPrimaryOutTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 142, 56, 16));

        jLabelReadingValveFromLoop2.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingValveFromLoop2.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingValveFromLoop2.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingValveFromLoop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingValveFromLoop2.setText("___");
        jLabelReadingValveFromLoop2.setOpaque(true);
        add(jLabelReadingValveFromLoop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 396, 24, -1));

        jLabelReadingDrainValve.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingDrainValve.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingDrainValve.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingDrainValve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingDrainValve.setText("___");
        jLabelReadingDrainValve.setOpaque(true);
        add(jLabelReadingDrainValve, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 48, 24, -1));

        jLabelReadingDrainFlow.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingDrainFlow.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingDrainFlow.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingDrainFlow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingDrainFlow.setText("____ kg/s");
        jLabelReadingDrainFlow.setOpaque(true);
        add(jLabelReadingDrainFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 92, 56, 16));

        jLabelReadingReturnValve1.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingReturnValve1.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingReturnValve1.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingReturnValve1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingReturnValve1.setText("___");
        jLabelReadingReturnValve1.setOpaque(true);
        add(jLabelReadingReturnValve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 31, 24, -1));

        jLabelReadingReturnValve2.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingReturnValve2.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReadingReturnValve2.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingReturnValve2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingReturnValve2.setText("___");
        jLabelReadingReturnValve2.setOpaque(true);
        add(jLabelReadingReturnValve2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 34, 24, -1));

        jLabelToDrum1.setFont(jLabelToDrum1.getFont().deriveFont(jLabelToDrum1.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelToDrum1.getFont().getSize()-3));
        jLabelToDrum1.setForeground(new java.awt.Color(14, 222, 194));
        jLabelToDrum1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelToDrum1.setText("Steam drum 1");
        add(jLabelToDrum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 2, 82, -1));

        jLabelToDrum2.setFont(jLabelToDrum2.getFont().deriveFont(jLabelToDrum2.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelToDrum2.getFont().getSize()-3));
        jLabelToDrum2.setForeground(new java.awt.Color(14, 222, 194));
        jLabelToDrum2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelToDrum2.setText("Steam drum 2");
        add(jLabelToDrum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 2, 78, -1));

        jLabelToDrum3.setFont(jLabelToDrum3.getFont().deriveFont(jLabelToDrum3.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelToDrum3.getFont().getSize()-3));
        jLabelToDrum3.setForeground(new java.awt.Color(14, 222, 194));
        jLabelToDrum3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelToDrum3.setText("Drum 1");
        add(jLabelToDrum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 296, 50, -1));

        jLabelToDrum4.setFont(jLabelToDrum4.getFont().deriveFont(jLabelToDrum4.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelToDrum4.getFont().getSize()-3));
        jLabelToDrum4.setForeground(new java.awt.Color(14, 222, 194));
        jLabelToDrum4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelToDrum4.setText("Drum 2");
        add(jLabelToDrum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 296, 48, -1));

        jLabelToDrum5.setFont(jLabelToDrum5.getFont().deriveFont(jLabelToDrum5.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelToDrum5.getFont().getSize()-3));
        jLabelToDrum5.setForeground(new java.awt.Color(14, 222, 194));
        jLabelToDrum5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelToDrum5.setText("MCP1");
        add(jLabelToDrum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 414, 40, -1));

        jLabelToDrum6.setFont(jLabelToDrum6.getFont().deriveFont(jLabelToDrum6.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelToDrum6.getFont().getSize()-3));
        jLabelToDrum6.setForeground(new java.awt.Color(14, 222, 194));
        jLabelToDrum6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelToDrum6.setText("MCP2");
        add(jLabelToDrum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 382, 38, -1));

        jLabelToDrum7.setFont(jLabelToDrum7.getFont().deriveFont(jLabelToDrum7.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelToDrum7.getFont().getSize()-3));
        jLabelToDrum7.setForeground(new java.awt.Color(14, 222, 194));
        jLabelToDrum7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelToDrum7.setText("Aftercooler");
        add(jLabelToDrum7, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 202, 70, -1));

        jLabelToDrum8.setFont(jLabelToDrum8.getFont().deriveFont(jLabelToDrum8.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelToDrum8.getFont().getSize()-3));
        jLabelToDrum8.setForeground(new java.awt.Color(14, 222, 194));
        jLabelToDrum8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelToDrum8.setText("Regenerator");
        add(jLabelToDrum8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 242, 78, -1));

        jLabelToDrum9.setFont(jLabelToDrum9.getFont().deriveFont(jLabelToDrum9.getFont().getStyle() & ~java.awt.Font.BOLD, jLabelToDrum9.getFont().getSize()-3));
        jLabelToDrum9.setForeground(new java.awt.Color(14, 222, 194));
        jLabelToDrum9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelToDrum9.setText("Drain");
        add(jLabelToDrum9, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 110, 34, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hartrusion/rbmksim/gui/mnemonic/MnemonicBlowdown.png"))); // NOI18N
        add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCoolerSecondaryFlow;
    private javax.swing.JLabel jLabelCoolerSecondaryOutTemp;
    private javax.swing.JLabel jLabelReadingCoolantValve;
    private javax.swing.JLabel jLabelReadingCoolerPrimaryFlow;
    private javax.swing.JLabel jLabelReadingCoolerPrimaryInTemp;
    private javax.swing.JLabel jLabelReadingCoolerPrimaryOutTemp;
    private javax.swing.JLabel jLabelReadingDrainFlow;
    private javax.swing.JLabel jLabelReadingDrainValve;
    private javax.swing.JLabel jLabelReadingInTemperature;
    private javax.swing.JLabel jLabelReadingRegenPrimaryOutTemp;
    private javax.swing.JLabel jLabelReadingRegenSecondaryOutTemp;
    private javax.swing.JLabel jLabelReadingReturnValve1;
    private javax.swing.JLabel jLabelReadingReturnValve2;
    private javax.swing.JLabel jLabelReadingTreatmentOutTemp;
    private javax.swing.JLabel jLabelReadingValveFromLoop1;
    private javax.swing.JLabel jLabelReadingValveFromLoop2;
    private javax.swing.JLabel jLabelToDrum1;
    private javax.swing.JLabel jLabelToDrum2;
    private javax.swing.JLabel jLabelToDrum3;
    private javax.swing.JLabel jLabelToDrum4;
    private javax.swing.JLabel jLabelToDrum5;
    private javax.swing.JLabel jLabelToDrum6;
    private javax.swing.JLabel jLabelToDrum7;
    private javax.swing.JLabel jLabelToDrum8;
    private javax.swing.JLabel jLabelToDrum9;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pump1;
    private com.hartrusion.rbmksim.gui.mnemonic.Pump pump2;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCoolantIn;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveDrain;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveFromDistributor1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveFromDistributor2;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveFromDrum1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveFromDrum2;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveOut1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveOut2;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valvePassiveFlow;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valvePump1Discharge;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valvePump1Suction;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valvePump2Discharge;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valvePump2Suction;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valvePumpsToCooler;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valvePumpsToRegenerator;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveRegeneratorToCooler;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveTreatedToDrums;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveTreatmentBypass;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        if (!evt.getPropertyName().startsWith("Blowdown")) {
            return;
        }
        switch (evt.getPropertyName()) {
            case "Blowdown#ValveFromLoop1_Pos":
                valveFromDistributor1.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#ValveFromLoop2_Pos":
                valveFromDistributor2.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#CooldownPump1SuctionValve_Pos":
                valvePump1Suction.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#CooldownPump1Pump_State":
                switch ((PumpState) evt.getNewValue()) {
                    case OFFLINE ->
                        pump1.setStatus(0);
                    case READY ->
                        pump1.setStatus(1);
                    case STARTUP ->
                        pump1.setStatus(2);
                    case RUNNING ->
                        pump1.setStatus(3);
                }
                break;
            case "Blowdown#CooldownPump1DischargeValve_Pos":
                valvePump1Discharge.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#CooldownPump2SuctionValve_Pos":
                valvePump2Suction.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#CooldownPump2Pump_State":
                switch ((PumpState) evt.getNewValue()) {
                    case OFFLINE ->
                        pump2.setStatus(0);
                    case READY ->
                        pump2.setStatus(1);
                    case STARTUP ->
                        pump2.setStatus(2);
                    case RUNNING ->
                        pump2.setStatus(3);
                }
                break;
            case "Blowdown#CooldownPump2DischargeValve_Pos":
                valvePump2Discharge.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#ValvePassiveFlow_Pos":
                valvePassiveFlow.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#ValvePumpsToRegenerator_Pos":
                valvePumpsToRegenerator.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#ValvePumpsToCooler_Pos":
                valvePumpsToCooler.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#ValveRegeneratorToCooler_Pos":
                valveRegeneratorToCooler.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#ValveTreatmentBypass_Pos":
                valveTreatmentBypass.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#ValveRegeneratedToDrums_Pos":
                valveTreatedToDrums.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#ReturnValve1_Pos":
                valveOut1.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#ReturnValve2_Pos":
                valveOut2.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#ValveDrain_Pos":
                valveDrain.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#BalanceControlControlState":
                if (evt.getNewValue() == ControlCommand.AUTOMATIC) {
                    valveOut1.setControlIndicatorActive(true);
                    valveOut2.setControlIndicatorActive(true);
                } else if (evt.getNewValue() == ControlCommand.MANUAL_OPERATION) {
                    valveOut1.setControlIndicatorActive(false);
                    valveOut2.setControlIndicatorActive(false);
                }
                break;
            case "Blowdown#ValveFromDrum1_Pos":
                valveFromDrum1.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
            case "Blowdown#ValveFromDrum2_Pos":
                valveFromDrum2.setActive(evt.getNewValue() != ValveState.CLOSED);
                break;
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
    /*    if (propertyName.startsWith("Loop")) {
            switch (propertyName) {
                case "Loop1#FuelInTemp" ->
                    jLabelReadingLoop1InletTemperature.setText(
                            String.format("%.1f", newValue)
                                    .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
                case "Loop2#FuelInTemp" ->
                    jLabelReadingLoop2InletTemperature.setText(
                            String.format("%.1f", newValue)
                                    .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
                case "Loop1#FuelInPressure" ->
                    jLabelReadingLoop1InletPressure.setText(
                            String.format("%.0f", newValue) + " bar");
                case "Loop2#FuelInPressure" ->
                    jLabelReadingLoop2InletPressure.setText(
                            String.format("%.0f", newValue) + " bar");
            }
        } */
        if (!propertyName.startsWith("Blowdown")) {
            return;
        }
        switch (propertyName) {
            case "Blowdown#InTemperature" ->
                jLabelReadingInTemperature.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
//            case "Blowdown#PassiveFlow" ->
//                jLabelReadingPassiveFlow.setText(
//                        String.format("%.0f", newValue) + " kg/s");
            case "Blowdown#RegeneratorPrimaryOutTemp" ->
                jLabelReadingRegenPrimaryOutTemp.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "Blowdown#CoolerPrimaryInTemp" ->
                jLabelReadingCoolerPrimaryInTemp.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "Blowdown#CoolerPrimaryFlow" ->
                jLabelReadingCoolerPrimaryFlow.setText(
                        String.format("%.0f", newValue) + " kg/s");
            case "Blowdown#CoolerPrimaryOutTemp" ->
                jLabelReadingCoolerPrimaryOutTemp.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "Blowdown#TreatmentOutTemp" ->
                jLabelReadingTreatmentOutTemp.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "Blowdown#RegeneratorSecondaryOutTemp" ->
                jLabelReadingRegenSecondaryOutTemp.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "Blowdown#CoolantOutFlow" -> {
                jLabelCoolerSecondaryFlow.setText(
                        String.format("%.0f", newValue) + " kg/s");
                valveCoolantIn.setActive(newValue >= 10);
            }
            case "Blowdown#CoolantOutTemp" ->
                jLabelCoolerSecondaryOutTemp.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "Blowdown#ValveFromLoop1" ->
                jLabelReadingValveFromLoop1.setText(
                        String.format("%.0f", newValue));
            case "Blowdown#ValveFromLoop2" ->
                jLabelReadingValveFromLoop2.setText(
                        String.format("%.0f", newValue));
            case "Blowdown#ReturnValve1" ->
                jLabelReadingReturnValve1.setText(
                        String.format("%.0f", newValue));
            case "Blowdown#ReturnValve2" ->
                jLabelReadingReturnValve2.setText(
                        String.format("%.0f", newValue));
            case "Blowdown#ValveCoolant" ->
                jLabelReadingCoolantValve.setText(
                        String.format("%.0f", newValue));

        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
