/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.mnemonic;

import com.hartrusion.control.ControlCommand;
import com.hartrusion.control.ValveState;
import com.hartrusion.mvc.UpdateReceiver;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class PanelMnemonicPreheaters extends javax.swing.JPanel implements UpdateReceiver {

    /**
     * Creates new form PanelMnemonicPreheaters
     */
    public PanelMnemonicPreheaters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valveCondensate3 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensate2 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveCondensate1 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveSteam3 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveSteam2 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        valveSteam1 = new com.hartrusion.rbmksim.gui.mnemonic.Valve();
        jLabe2 = new javax.swing.JLabel();
        jLabe3 = new javax.swing.JLabel();
        jLabe4 = new javax.swing.JLabel();
        jLabe5 = new javax.swing.JLabel();
        jLabelReadingTemp3 = new javax.swing.JLabel();
        jLabelReadingLevel3 = new javax.swing.JLabel();
        jLabelReadingTemp2 = new javax.swing.JLabel();
        jLabelReadingLevel2 = new javax.swing.JLabel();
        jLabelReadingTemp1 = new javax.swing.JLabel();
        jLabelReadingLevel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(480, 180));
        setMinimumSize(new java.awt.Dimension(480, 180));
        setPreferredSize(new java.awt.Dimension(480, 180));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valveCondensate3.setControlIndicator(true);
        add(valveCondensate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 156, -1, -1));

        valveCondensate2.setControlIndicator(true);
        add(valveCondensate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 156, -1, -1));

        valveCondensate1.setControlIndicator(true);
        add(valveCondensate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 156, -1, -1));

        valveSteam3.setVertical(true);
        add(valveSteam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 13, -1, -1));

        valveSteam2.setVertical(true);
        add(valveSteam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 13, -1, -1));

        valveSteam1.setVertical(true);
        add(valveSteam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 13, -1, -1));

        jLabe2.setFont(jLabe2.getFont().deriveFont(jLabe2.getFont().getStyle() & ~java.awt.Font.BOLD, jLabe2.getFont().getSize()-3));
        jLabe2.setForeground(new java.awt.Color(14, 222, 194));
        jLabe2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe2.setText("Turbine");
        add(jLabe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 2, 60, -1));

        jLabe3.setFont(jLabe3.getFont().deriveFont(jLabe3.getFont().getStyle() & ~java.awt.Font.BOLD, jLabe3.getFont().getSize()-3));
        jLabe3.setForeground(new java.awt.Color(14, 222, 194));
        jLabe3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe3.setText("Hotwell");
        add(jLabe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 146, 42, -1));

        jLabe4.setFont(jLabe4.getFont().deriveFont(jLabe4.getFont().getStyle() & ~java.awt.Font.BOLD, jLabe4.getFont().getSize()-3));
        jLabe4.setForeground(new java.awt.Color(14, 222, 194));
        jLabe4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe4.setText("Cond. Pumps");
        add(jLabe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 76, 68, -1));

        jLabe5.setFont(jLabe5.getFont().deriveFont(jLabe5.getFont().getStyle() & ~java.awt.Font.BOLD, jLabe5.getFont().getSize()-3));
        jLabe5.setForeground(new java.awt.Color(14, 222, 194));
        jLabe5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabe5.setText("Deaerators");
        add(jLabe5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 144, 60, -1));

        jLabelReadingTemp3.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingTemp3.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingTemp3.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingTemp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingTemp3.setText("___ °C");
        jLabelReadingTemp3.setOpaque(true);
        add(jLabelReadingTemp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 80, 56, 16));

        jLabelReadingLevel3.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingLevel3.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingLevel3.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingLevel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingLevel3.setText("___,_ cm");
        jLabelReadingLevel3.setOpaque(true);
        add(jLabelReadingLevel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 60, 56, 16));

        jLabelReadingTemp2.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingTemp2.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingTemp2.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingTemp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingTemp2.setText("___ °C");
        jLabelReadingTemp2.setOpaque(true);
        add(jLabelReadingTemp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 80, 56, 16));

        jLabelReadingLevel2.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingLevel2.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingLevel2.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingLevel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingLevel2.setText("___,_ cm");
        jLabelReadingLevel2.setOpaque(true);
        add(jLabelReadingLevel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 60, 56, 16));

        jLabelReadingTemp1.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingTemp1.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingTemp1.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingTemp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingTemp1.setText("___ °C");
        jLabelReadingTemp1.setOpaque(true);
        add(jLabelReadingTemp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 80, 56, 16));

        jLabelReadingLevel1.setBackground(new java.awt.Color(77, 69, 27));
        jLabelReadingLevel1.setFont(new java.awt.Font("Monospaced", 1, 10)); // NOI18N
        jLabelReadingLevel1.setForeground(new java.awt.Color(231, 255, 166));
        jLabelReadingLevel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingLevel1.setText("___,_ cm");
        jLabelReadingLevel1.setOpaque(true);
        add(jLabelReadingLevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 60, 56, 16));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hartrusion/rbmksim/gui/mnemonic/MnemonicPreheaters.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabe2;
    private javax.swing.JLabel jLabe3;
    private javax.swing.JLabel jLabe4;
    private javax.swing.JLabel jLabe5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelReadingLevel1;
    private javax.swing.JLabel jLabelReadingLevel2;
    private javax.swing.JLabel jLabelReadingLevel3;
    private javax.swing.JLabel jLabelReadingTemp1;
    private javax.swing.JLabel jLabelReadingTemp2;
    private javax.swing.JLabel jLabelReadingTemp3;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensate1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensate2;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveCondensate3;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveSteam1;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveSteam2;
    private com.hartrusion.rbmksim.gui.mnemonic.Valve valveSteam3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        switch (evt.getPropertyName()) {
            case "Preheater1#CondensateValve_Pos" ->
                valveCondensate1.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Preheater1#CondensateValveControlState" -> {
                if (evt.getNewValue() == ControlCommand.AUTOMATIC) {
                    valveCondensate1.setControlIndicatorActive(true);
                } else if (evt.getNewValue() == ControlCommand.MANUAL_OPERATION) {
                    valveCondensate1.setControlIndicatorActive(false);
                }
            }
            case "Preheater2#CondensateValve_Pos" ->
                valveCondensate2.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Preheater2#CondensateValveControlState" -> {
                if (evt.getNewValue() == ControlCommand.AUTOMATIC) {
                    valveCondensate2.setControlIndicatorActive(true);
                } else if (evt.getNewValue() == ControlCommand.MANUAL_OPERATION) {
                    valveCondensate2.setControlIndicatorActive(false);
                }
            }
            case "Preheater3#CondensateValve_Pos" ->
                valveCondensate3.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Preheater3#CondensateValveControlState" -> {
                if (evt.getNewValue() == ControlCommand.AUTOMATIC) {
                    valveCondensate3.setControlIndicatorActive(true);
                } else if (evt.getNewValue() == ControlCommand.MANUAL_OPERATION) {
                    valveCondensate3.setControlIndicatorActive(false);
                }
            }
            case "Turbine5#LowPressureTapValve_Pos" ->
                valveSteam1.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Turbine3#LowPressureTapValve_Pos" ->
                valveSteam2.setActive(evt.getNewValue() != ValveState.CLOSED);
            case "Turbine1#LowPressureTapValve_Pos" ->
                valveSteam3.setActive(evt.getNewValue() != ValveState.CLOSED);
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        switch (propertyName) {
            case "Preheater1#Temperature" ->
                jLabelReadingTemp1.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "Preheater1#Level" ->
                jLabelReadingLevel1.setText(
                        String.format("%.0f", newValue) + " cm");
            case "Preheater2#Temperature" ->
                jLabelReadingTemp2.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "Preheater2#Level" ->
                jLabelReadingLevel2.setText(
                        String.format("%.0f", newValue) + " cm");
            case "Preheater3#Temperature" ->
                jLabelReadingTemp3.setText(
                        String.format("%.1f", newValue)
                                .replaceAll("(\\.\\d+?)0*$", "$1") + " °C");
            case "Preheater3#Level" ->
                jLabelReadingLevel3.setText(
                        String.format("%.0f", newValue) + " cm");
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
