/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.widgets;

import com.hartrusion.modeling.automated.PumpState;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.BeanProperty;
import java.beans.PropertyChangeEvent;

/**
 * A group of buttons for starting and stopping a pump and as well buttons for
 * suction and drain valves.
 *
 * <p>
 * It has a prefix that will be used to determine if received events are for
 * this panel and this prefix will be used on all actions that are sent to the
 * controller.
 * 
 * <p>
 * The component identification strings are matching those used in HeatFluidPump
 * class.
 *
 * @author Viktor Alexander Hartung
 */
public class PanelWidgetSmallPump extends AbstractPanelWidget {

    String prefix = "Pump1#";

    /**
     * Creates new form ControlPanelMCPWidget
     */
    public PanelWidgetSmallPump() {
        initComponents();
    }

    public String getChornobylPrefix() {
        return prefix;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Prefix of actions sent to controller")
    public void setChornobylPrefix(String prefix) {
        String old = this.prefix;
        this.prefix = prefix;
        firePropertyChange("chornobylPrefix", old, prefix);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDischargeClose = new javax.swing.JButton();
        jButtonDischargeOpen = new javax.swing.JButton();
        jLabelDischarge = new javax.swing.JLabel();
        jToggleButtonPump = new javax.swing.JToggleButton();
        lightBulbReady = new com.hartrusion.rbmksim.gui.elements.LightBulb();
        lightBulbInService = new com.hartrusion.rbmksim.gui.elements.LightBulb();

        setMaximumSize(new java.awt.Dimension(52, 70));
        setMinimumSize(new java.awt.Dimension(52, 70));
        setPreferredSize(new java.awt.Dimension(52, 70));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDischargeClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonDischargeClose.setText("C");
        jButtonDischargeClose.setToolTipText("");
        jButtonDischargeClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDischargeClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDischargeCloseActionPerformed(evt);
            }
        });
        add(jButtonDischargeClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 15, 20, 20));

        jButtonDischargeOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonDischargeOpen.setText("O");
        jButtonDischargeOpen.setToolTipText("");
        jButtonDischargeOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDischargeOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDischargeOpenActionPerformed(evt);
            }
        });
        add(jButtonDischargeOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 20, 20));

        jLabelDischarge.setFont(jLabelDischarge.getFont().deriveFont(jLabelDischarge.getFont().getSize()-2f));
        jLabelDischarge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDischarge.setText("Discharge");
        jLabelDischarge.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelDischarge.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelDischarge.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelDischarge, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 52, 14));

        jToggleButtonPump.setText("←");
        jToggleButtonPump.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPumpActionPerformed(evt);
            }
        });
        add(jToggleButtonPump, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 50, 20, 20));

        lightBulbReady.setForeground(new java.awt.Color(0, 255, 0));
        add(lightBulbReady, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 41, -1, -1));

        lightBulbInService.setForeground(new java.awt.Color(255, 0, 0));
        add(lightBulbInService, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 41, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDischargeCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDischargeCloseActionPerformed
        controller.userAction(new ActionCommand(prefix + "DischargeValve", false));
    }//GEN-LAST:event_jButtonDischargeCloseActionPerformed

    private void jButtonDischargeOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDischargeOpenActionPerformed
        controller.userAction(new ActionCommand(prefix + "DischargeValve", true));
    }//GEN-LAST:event_jButtonDischargeOpenActionPerformed

    private void jToggleButtonPumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPumpActionPerformed
        if (jToggleButtonPump.isSelected()) {
            jToggleButtonPump.setText("↑");
        } else {
            jToggleButtonPump.setText("←");
        }
        controller.userAction(new ActionCommand(prefix + "Pump", jToggleButtonPump.isSelected()));
    }//GEN-LAST:event_jToggleButtonPumpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDischargeClose;
    private javax.swing.JButton jButtonDischargeOpen;
    private javax.swing.JLabel jLabelDischarge;
    private javax.swing.JToggleButton jToggleButtonPump;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbInService;
    private com.hartrusion.rbmksim.gui.elements.LightBulb lightBulbReady;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        if (!evt.getPropertyName().startsWith(prefix)) {
            return;
        }
        String component = evt.getPropertyName().substring(prefix.length());
        switch (component) {
            case "DischargeValve_Pos":
                setValveButtons(jButtonDischargeClose, 
                        jButtonDischargeOpen,evt.getNewValue());
                break;
            case "Pump_State":
                // Write the pump state back to the button as we might have an
                // initial state that is on.
                if (PumpState.RUNNING == (PumpState) evt.getNewValue()
                        && !jToggleButtonPump.isSelected()) {
                    jToggleButtonPump.setSelected(true);
                    jToggleButtonPump.setText("↑");
                }
                // Switch the little lights on top of the switch
                switch ((PumpState) evt.getNewValue()) {
                    case OFFLINE -> {
                        lightBulbReady.setActive(false);
                        lightBulbInService.setActive(false);
                    }
                    case READY -> {
                        lightBulbReady.setActive(true);
                        lightBulbInService.setActive(false);
                    }
                    case STARTUP -> {
                        lightBulbReady.setActive(true);
                        lightBulbInService.setActive(true);
                    }
                    case RUNNING -> {
                        lightBulbReady.setActive(false);
                        lightBulbInService.setActive(true);
                    }
                }
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        if (!propertyName.startsWith(prefix)) {
            return;
        }
        if (newValue instanceof Boolean) { // unwrap
            updateComponent(propertyName, (boolean) newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {

    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
