/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.widgets;

import com.hartrusion.modeling.automated.PumpState;
import com.hartrusion.mvc.ActionCommand;
import java.beans.BeanProperty;
import java.beans.PropertyChangeEvent;

/**
 * A group of buttons for starting and stopping a pump and as well buttons for
 * suction and drain valves.
 *
 * It has a prefix that will be used to determine if received events are for
 * this panel and this prefix will be used on all actions that are sent to the
 * controller.
 *
 * @author Viktor Alexander Hartung
 */
public class PanelWidgetTrimmablePump extends AbstractPanelWidget {

    String prefix = "Pump1#";

    /**
     * Creates new form ControlPanelMCPWidget
     */
    public PanelWidgetTrimmablePump() {
        initComponents();
    }

    public String getChornobylPrefix() {
        return prefix;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Prefix of actions sent to controller")
    public void setChornobylPrefix(String prefix) {
        String old = this.prefix;
        this.prefix = prefix;
        firePropertyChange("chornobylPrefix", old, prefix);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTrimNeg = new javax.swing.JButton();
        jButtonTrimPos = new javax.swing.JButton();
        jLabelCaptionTrim = new javax.swing.JLabel();
        jButtonDischargeClose = new javax.swing.JButton();
        jButtonDischargeOpen = new javax.swing.JButton();
        jLabelDischarge = new javax.swing.JLabel();
        jButtonSuctionClose = new javax.swing.JButton();
        jButtonSuctionOpen = new javax.swing.JButton();
        jLabelCaptionSuction = new javax.swing.JLabel();
        jLabelCaptionPump = new javax.swing.JLabel();
        jToggleButtonPump = new javax.swing.JToggleButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTrimNeg.setText("<");
        jButtonTrimNeg.setToolTipText("");
        jButtonTrimNeg.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTrimNeg.setMaximumSize(new java.awt.Dimension(18, 22));
        jButtonTrimNeg.setMinimumSize(new java.awt.Dimension(18, 22));
        jButtonTrimNeg.setPreferredSize(new java.awt.Dimension(18, 22));
        jButtonTrimNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonTrimNegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonTrimNegMouseReleased(evt);
            }
        });
        add(jButtonTrimNeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 14, 18, 22));

        jButtonTrimPos.setText(">");
        jButtonTrimPos.setToolTipText("");
        jButtonTrimPos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTrimPos.setMaximumSize(new java.awt.Dimension(18, 22));
        jButtonTrimPos.setMinimumSize(new java.awt.Dimension(18, 22));
        jButtonTrimPos.setPreferredSize(new java.awt.Dimension(18, 22));
        jButtonTrimPos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonTrimPosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonTrimPosMouseReleased(evt);
            }
        });
        add(jButtonTrimPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 14, 18, 22));

        jLabelCaptionTrim.setFont(jLabelCaptionTrim.getFont().deriveFont(jLabelCaptionTrim.getFont().getSize()-2f));
        jLabelCaptionTrim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionTrim.setText("Trim");
        jLabelCaptionTrim.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionTrim.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionTrim.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionTrim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 52, 14));

        jButtonDischargeClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonDischargeClose.setText("C");
        jButtonDischargeClose.setToolTipText("");
        jButtonDischargeClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDischargeClose.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonDischargeClose.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonDischargeClose.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonDischargeClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDischargeCloseActionPerformed(evt);
            }
        });
        add(jButtonDischargeClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 53, 20, 20));

        jButtonDischargeOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonDischargeOpen.setText("O");
        jButtonDischargeOpen.setToolTipText("");
        jButtonDischargeOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDischargeOpen.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonDischargeOpen.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonDischargeOpen.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonDischargeOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDischargeOpenActionPerformed(evt);
            }
        });
        add(jButtonDischargeOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 53, 20, 20));

        jLabelDischarge.setFont(jLabelDischarge.getFont().deriveFont(jLabelDischarge.getFont().getSize()-2f));
        jLabelDischarge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDischarge.setText("Discharge");
        jLabelDischarge.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelDischarge.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelDischarge.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelDischarge, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 52, 14));

        jButtonSuctionClose.setBackground(new java.awt.Color(0, 128, 0));
        jButtonSuctionClose.setText("C");
        jButtonSuctionClose.setToolTipText("");
        jButtonSuctionClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSuctionClose.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonSuctionClose.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonSuctionClose.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonSuctionClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuctionCloseActionPerformed(evt);
            }
        });
        add(jButtonSuctionClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 90, 20, 20));

        jButtonSuctionOpen.setBackground(new java.awt.Color(128, 0, 0));
        jButtonSuctionOpen.setText("O");
        jButtonSuctionOpen.setToolTipText("");
        jButtonSuctionOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSuctionOpen.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonSuctionOpen.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonSuctionOpen.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonSuctionOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuctionOpenActionPerformed(evt);
            }
        });
        add(jButtonSuctionOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 20, 20));

        jLabelCaptionSuction.setFont(jLabelCaptionSuction.getFont().deriveFont(jLabelCaptionSuction.getFont().getSize()-2f));
        jLabelCaptionSuction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionSuction.setText("Suction");
        jLabelCaptionSuction.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuction.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionSuction.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionSuction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 51, 14));

        jLabelCaptionPump.setFont(jLabelCaptionPump.getFont().deriveFont(jLabelCaptionPump.getFont().getSize()-2f));
        jLabelCaptionPump.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCaptionPump.setText("Pump");
        jLabelCaptionPump.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionPump.setPreferredSize(new java.awt.Dimension(52, 14));
        add(jLabelCaptionPump, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 52, 14));

        jToggleButtonPump.setText("—");
        jToggleButtonPump.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jToggleButtonPump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPumpActionPerformed(evt);
            }
        });
        add(jToggleButtonPump, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 126, 22, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDischargeCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDischargeCloseActionPerformed
        controller.userAction(new ActionCommand(prefix + "DischargeValve", false));
    }//GEN-LAST:event_jButtonDischargeCloseActionPerformed

    private void jButtonDischargeOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDischargeOpenActionPerformed
        controller.userAction(new ActionCommand(prefix + "DischargeValve", true));
    }//GEN-LAST:event_jButtonDischargeOpenActionPerformed

    private void jButtonSuctionCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuctionCloseActionPerformed
        controller.userAction(new ActionCommand(prefix + "SuctionValve", false));
    }//GEN-LAST:event_jButtonSuctionCloseActionPerformed

    private void jButtonSuctionOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuctionOpenActionPerformed
        controller.userAction(new ActionCommand(prefix + "SuctionValve", true));
    }//GEN-LAST:event_jButtonSuctionOpenActionPerformed

    private void jToggleButtonPumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPumpActionPerformed
        if (jToggleButtonPump.isSelected()) {
            jToggleButtonPump.setText("|");
        } else {
            jToggleButtonPump.setText("—");
        }
        controller.userAction(new ActionCommand(prefix + "Pump", jToggleButtonPump.isSelected()));
    }//GEN-LAST:event_jToggleButtonPumpActionPerformed

    private void jButtonTrimNegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTrimNegMousePressed
        controller.userAction(new ActionCommand(prefix + "TrimValve", (int) -1));
    }//GEN-LAST:event_jButtonTrimNegMousePressed

    private void jButtonTrimNegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTrimNegMouseReleased
        controller.userAction(new ActionCommand(prefix + "TrimValve", (int) 0));
    }//GEN-LAST:event_jButtonTrimNegMouseReleased

    private void jButtonTrimPosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTrimPosMousePressed
        controller.userAction(new ActionCommand(prefix + "TrimValve", (int) 1));
    }//GEN-LAST:event_jButtonTrimPosMousePressed

    private void jButtonTrimPosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTrimPosMouseReleased
        controller.userAction(new ActionCommand(prefix + "TrimValve", (int) 0));
    }//GEN-LAST:event_jButtonTrimPosMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDischargeClose;
    private javax.swing.JButton jButtonDischargeOpen;
    private javax.swing.JButton jButtonSuctionClose;
    private javax.swing.JButton jButtonSuctionOpen;
    private javax.swing.JButton jButtonTrimNeg;
    private javax.swing.JButton jButtonTrimPos;
    private javax.swing.JLabel jLabelCaptionPump;
    private javax.swing.JLabel jLabelCaptionSuction;
    private javax.swing.JLabel jLabelCaptionTrim;
    private javax.swing.JLabel jLabelDischarge;
    private javax.swing.JToggleButton jToggleButtonPump;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        if (!evt.getPropertyName().startsWith(prefix)) {
            return;
        }
        String component = evt.getPropertyName().substring(prefix.length());
        switch (component) {
            case "SuctionValve_Pos":
                setValveButtons(jButtonSuctionClose, jButtonSuctionOpen,
                        evt.getNewValue());
                break;
            case "DischargeValve_Pos":
                setValveButtons(jButtonDischargeClose, jButtonDischargeOpen,
                        evt.getNewValue());
                break;
            case "Pump_State":
                // Write the pump state back to the button as we might have an
                // initial state that is on.
                if (PumpState.RUNNING == (PumpState) evt.getNewValue()) {
                    jToggleButtonPump.setSelected(true);
                    jToggleButtonPump.setText("|");
                }
                break;
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        if (!propertyName.startsWith(prefix)) {
            return;
        }
        if (newValue instanceof Boolean) { // unwrap
            updateComponent(propertyName, (boolean) newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {

    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
