/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.widgets;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.beans.BeanProperty;
import java.beans.PropertyChangeEvent;
import com.hartrusion.control.ControlCommand;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;

/**
 * A 4 button module presumably used for feedwater control valves. This widget
 * is designed to be used by setting a prefix which will be then used to
 * identify actions and fire properties.
 *
 * <p>
 * The four buttons trigger ControlCommand actions. The letter on the right will
 * display H or A, depending on what the controllers actual state is.
 *
 * <p>
 * The display gauge in the middle displays a value between 0 and 100.
 *
 * @author Viktor Alexander Hartung
 */
public class PanelWidgetControlLoopValve extends javax.swing.JPanel
        implements UpdateReceiver {

    protected ActionReceiver controller;

    private final int[] majorTickXPositions = {25, 35, 45, 55, 65};
    private final int[] minorTickXPositions
            = {27, 29, 31, 33, 37, 39, 41, 43, 47, 49, 51, 53, 57, 59, 61, 63};

    double value = 50;
    int valueXCoord = 45;

    private String component = "undefined";
    private String componentControlCommand;
    private String componentControlState;
    private String componentControlUpdateU;
    private String componentValue;

    public String getComponent() {
        return component;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "String identification of the component")
    public void setComponent(String component) {
        String old = this.component;
        this.component = component;
        // build component identification strings
        componentControlCommand = component + "ControlCommand";
        componentControlState = component + "ControlState";
        componentControlUpdateU = component + "ControlUpdateU";
        componentValue = component + "Value";
        firePropertyChange("component", old, component);
    }

    public void registerActionReceiver(ActionReceiver controller) {
        this.controller = controller;
    }

    /**
     * Creates new form ControlPanelControlledValve
     */
    public PanelWidgetControlLoopValve() {
        initComponents();
    }

    public double getChornobylValue() {
        return value;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Sets the current display value between 0 and 100")
    public void setChornobylValue(double value) {
        if (value < 0.0) {
            value = 0.0;
        } else if (value > 100) {
            value = 100;
        }
        double old = this.value;
        updateDisplayValue(value);
        firePropertyChange("chornobylValue", old, value);
    }

    // calculates pixel value on set
    private void updateDisplayValue(double value) {
        this.value = value;
        valueXCoord = (int) (0.36 * value + 27);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUpper = new javax.swing.JButton();
        jButtonAutp = new javax.swing.JButton();
        jButtonManual = new javax.swing.JButton();
        jButtonLower = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(90, 36));
        setMinimumSize(new java.awt.Dimension(90, 36));
        setPreferredSize(new java.awt.Dimension(90, 36));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUpper.setBackground(new java.awt.Color(255, 255, 204));
        jButtonUpper.setText(">");
        jButtonUpper.setToolTipText("");
        jButtonUpper.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonUpper.setMaximumSize(new java.awt.Dimension(24, 20));
        jButtonUpper.setMinimumSize(new java.awt.Dimension(24, 20));
        jButtonUpper.setPreferredSize(new java.awt.Dimension(24, 20));
        jButtonUpper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonUpperMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonUpperMouseReleased(evt);
            }
        });
        add(jButtonUpper, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 18, 20, 16));

        jButtonAutp.setBackground(new java.awt.Color(255, 255, 204));
        jButtonAutp.setText("Ꝋ");
        jButtonAutp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAutp.setMaximumSize(new java.awt.Dimension(24, 20));
        jButtonAutp.setMinimumSize(new java.awt.Dimension(24, 20));
        jButtonAutp.setPreferredSize(new java.awt.Dimension(24, 20));
        jButtonAutp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutpActionPerformed(evt);
            }
        });
        add(jButtonAutp, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 18, 20, 16));

        jButtonManual.setBackground(new java.awt.Color(255, 255, 204));
        jButtonManual.setText("н");
        jButtonManual.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonManual.setMaximumSize(new java.awt.Dimension(24, 20));
        jButtonManual.setMinimumSize(new java.awt.Dimension(24, 20));
        jButtonManual.setPreferredSize(new java.awt.Dimension(24, 20));
        jButtonManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManualActionPerformed(evt);
            }
        });
        add(jButtonManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 18, 20, 16));

        jButtonLower.setBackground(new java.awt.Color(255, 255, 204));
        jButtonLower.setText("<");
        jButtonLower.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLower.setMaximumSize(new java.awt.Dimension(24, 20));
        jButtonLower.setMinimumSize(new java.awt.Dimension(24, 20));
        jButtonLower.setPreferredSize(new java.awt.Dimension(24, 20));
        jButtonLower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonLowerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonLowerMouseReleased(evt);
            }
        });
        add(jButtonLower, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 18, 20, 16));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() & ~java.awt.Font.BOLD, jLabel1.getFont().getSize()-2));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("H");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 8, 12));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAutpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAutpActionPerformed

    private void jButtonManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManualActionPerformed

    private void jButtonLowerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLowerMousePressed
        controller.userAction(new ActionCommand(componentControlCommand, 
                ControlCommand.OUTPUT_DECREASE));
    }//GEN-LAST:event_jButtonLowerMousePressed

    private void jButtonLowerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLowerMouseReleased
        controller.userAction(new ActionCommand(componentControlCommand,
                ControlCommand.OUTPUT_CONTINUE));
    }//GEN-LAST:event_jButtonLowerMouseReleased

    private void jButtonUpperMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpperMousePressed
        controller.userAction(new ActionCommand(componentControlCommand, 
                ControlCommand.OUTPUT_INCREASE));
    }//GEN-LAST:event_jButtonUpperMousePressed

    private void jButtonUpperMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpperMouseReleased
        controller.userAction(new ActionCommand(componentControlCommand,
                ControlCommand.OUTPUT_CONTINUE));
    }//GEN-LAST:event_jButtonUpperMouseReleased

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;

        // A rectangle with a black frame
        g2.setColor(Color.WHITE);
        g2.fillRect(20, 3, 50, 13);
        g2.setColor(Color.BLACK);
        g2.drawRect(20, 3, 50, 13);

        // Major tick lines
        for (int idx = 0; idx < majorTickXPositions.length; idx++) {
            g2.drawLine(majorTickXPositions[idx], 11,
                    majorTickXPositions[idx], 14);
        }
        // Minor tick lines
        for (int idx = 0; idx < minorTickXPositions.length; idx++) {
            g2.drawLine(minorTickXPositions[idx], 13,
                    minorTickXPositions[idx], 14);
        }
        // Value marker
        g2.drawLine(valueXCoord, 3, valueXCoord, 9);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAutp;
    private javax.swing.JButton jButtonLower;
    private javax.swing.JButton jButtonManual;
    private javax.swing.JButton jButtonUpper;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(componentControlState)) {
            switch ((ControlCommand) evt.getNewValue()) {
                case AUTOMATIC:
                    jLabel1.setText("A");
                    break;
                case MANUAL_OPERATION:
                    jLabel1.setText("M");
            }
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        if (propertyName.equals(componentControlUpdateU)) {
            if (newValue < 0.0) {
                newValue = 0.0;
            } else if (newValue > 100) {
                newValue = 100;
            }
            updateDisplayValue(newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
