/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim;

import com.hartrusion.rbmksim.gui.diagrams.DiagramPresets;
import com.hartrusion.rbmksim.gui.diagrams.InternalFrameDiagram;
import com.hartrusion.rbmksim.gui.panels.PanelCondensation;
import com.hartrusion.rbmksim.gui.panels.PanelBlowdown;
import com.hartrusion.rbmksim.gui.panels.PanelMCP;
import com.hartrusion.rbmksim.gui.panels.PanelCoreControl;
import com.hartrusion.rbmksim.gui.panels.PanelCoolant;
import com.hartrusion.rbmksim.gui.panels.PanelPreheaters;
import com.hartrusion.rbmksim.gui.panels.PanelFeedwater;
import com.hartrusion.rbmksim.gui.panels.PanelBypassValve;
import com.hartrusion.rbmksim.gui.panels.PanelAuxCondenser;
import com.hartrusion.rbmksim.gui.panels.PanelTurbine;
import com.hartrusion.rbmksim.gui.panels.PanelDeaerators;
import com.hartrusion.rbmksim.gui.panels.PanelGenerator;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.InteractiveView;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.mvc.ViewerController;
import com.hartrusion.rbmksim.gui.*;
import com.hartrusion.rbmksim.gui.diagrams.DiagramStartupPressureSetpoint;
import com.hartrusion.rbmksim.gui.widgets.*;
import com.hartrusion.rbmksim.gui.mnemonic.*;
import com.hartrusion.values.ValueHandler;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * A windows from which multiple can exist that holds various widgets and
 * windows to interact with the simulation. Can be configured individually.
 *
 * @author Viktor Alexander Hartung
 */
public class ControlPanel extends javax.swing.JFrame implements
        InteractiveView, ActionReceiver {

    private ControlPanelManager parentControlRoom;

    private ViewerController controller;

    /**
     * A reference to a value handler holding the data for plotting lines.
     */
    private ValueHandler plotData;

    /**
     * Holds a list of all interactive components which are active inside the
     * desktop pane to update them.
     */
    private final List<InternalFramePanel> panels = new ArrayList<>();

    private final List<InternalFrameMnemonic> mnemonics = new ArrayList<>();

    private final List<InternalFrameDiagram> diagrams = new ArrayList<>();

    private InternalFrameSelsyns rodPositions;

    private InternalFrameAlarmTable alarmTable;
    private List alarmList;

    private InternalFrameCoreActivity coreActivity1;
    private InternalFrameCoreActivity coreActivity2;

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new com.hartrusion.util.JDesktopPaneEnhanced();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemNewPanel = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPause = new javax.swing.JMenuItem();
        jCheckBoxMenuOnlyCore = new javax.swing.JCheckBoxMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuLoad = new javax.swing.JMenuItem();
        jMenuSave = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jMenuItemViewRodPositions = new javax.swing.JMenuItem();
        jMenuItemViewAlarmList = new javax.swing.JMenuItem();
        jMenuItemViewCore1 = new javax.swing.JMenuItem();
        jMenuItemViewCore2 = new javax.swing.JMenuItem();
        jMenuControls = new javax.swing.JMenu();
        jMenuItemCoreControl = new javax.swing.JMenuItem();
        jMenuItemRecirculation = new javax.swing.JMenuItem();
        jMenuItemBlowdown = new javax.swing.JMenuItem();
        jMenuItemDeaerators = new javax.swing.JMenuItem();
        jMenuItemFeedwater = new javax.swing.JMenuItem();
        jMenuItemAuxCond = new javax.swing.JMenuItem();
        jMenuItemTurbine = new javax.swing.JMenuItem();
        jMenuItemTurbineBypass = new javax.swing.JMenuItem();
        jMenuItemCondensation = new javax.swing.JMenuItem();
        jMenuItemPreheaters = new javax.swing.JMenuItem();
        jMenuItemGenerator = new javax.swing.JMenuItem();
        jMenuItemCoolant = new javax.swing.JMenuItem();
        jMenuMnemonics = new javax.swing.JMenu();
        jMenuItemMnemonicBlowdown = new javax.swing.JMenuItem();
        jMenuItemMnemonicLoop1 = new javax.swing.JMenuItem();
        jMenuItemMnemonicLoop2 = new javax.swing.JMenuItem();
        jMenuItemMnemonicFeedwater = new javax.swing.JMenuItem();
        jMenuItemMnemonicDeaerators = new javax.swing.JMenuItem();
        jMenuItemMnemonicAuxCondenser = new javax.swing.JMenuItem();
        jMenuItemMnemonicTurbine = new javax.swing.JMenuItem();
        jMenuItemMnemonicCondensation = new javax.swing.JMenuItem();
        jMenuItemMnemonicPreheaters = new javax.swing.JMenuItem();
        jMenuDiagrams = new javax.swing.JMenu();
        jMenuNeutronFlux = new javax.swing.JMenuItem();
        jMenuGlobalControl = new javax.swing.JMenuItem();
        jMenuDrumSeparators = new javax.swing.JMenuItem();
        jMenuItemLoop1LevelControl = new javax.swing.JMenuItem();
        jMenuItemLoop2LevelControl = new javax.swing.JMenuItem();
        jMenuItemStartupPressureSetpoint = new javax.swing.JMenuItem();
        jMenuItemTurbineHPTemperatures = new javax.swing.JMenuItem();
        jMenuItemTurbineReheaterDiag = new javax.swing.JMenuItem();
        jMenuItemPRV1 = new javax.swing.JMenuItem();
        jMenuItemPRV2 = new javax.swing.JMenuItem();
        jMenuPresets = new javax.swing.JMenu();
        jMenuItemPresetFull = new javax.swing.JMenuItem();
        jMenuItemPresetMnemonics = new javax.swing.JMenuItem();
        jMenuItemPresetReactorOperator = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPresetNone = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenuItem();
        jMenuItemHowToStart = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTriggerDisaster = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RBMK Simulator - Control Panel");
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(680, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setViewportView(jDesktopPane1);

        getContentPane().add(jScrollPane1);

        jMenuFile.setText("File");

        jMenuItemNewPanel.setText("New Panel Window");
        jMenuItemNewPanel.addActionListener(this::jMenuItemNewPanelActionPerformed);
        jMenuFile.add(jMenuItemNewPanel);
        jMenuFile.add(jSeparator5);

        jMenuItemPause.setText("Pause Simulation");
        jMenuItemPause.addActionListener(this::jMenuItemPauseActionPerformed);
        jMenuFile.add(jMenuItemPause);

        jCheckBoxMenuOnlyCore.setText("Simulate reactor only");
        jCheckBoxMenuOnlyCore.addActionListener(this::jCheckBoxMenuOnlyCoreActionPerformed);
        jMenuFile.add(jCheckBoxMenuOnlyCore);
        jMenuFile.add(jSeparator2);

        jMenuLoad.setText("Load");
        jMenuLoad.addActionListener(this::jMenuLoadActionPerformed);
        jMenuFile.add(jMenuLoad);

        jMenuSave.setText("Save as...");
        jMenuSave.setToolTipText("");
        jMenuSave.setActionCommand("Save");
        jMenuSave.addActionListener(this::jMenuSaveActionPerformed);
        jMenuFile.add(jMenuSave);
        jMenuFile.add(jSeparator3);

        jMenuItemExit.setText("Exit (Terminate)");
        jMenuItemExit.addActionListener(this::jMenuItemExitActionPerformed);
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuView.setText("View");

        jMenuItemViewRodPositions.setText("Rod Positions");
        jMenuItemViewRodPositions.addActionListener(this::jMenuItemViewRodPositionsActionPerformed);
        jMenuView.add(jMenuItemViewRodPositions);

        jMenuItemViewAlarmList.setText("Alarm List");
        jMenuItemViewAlarmList.addActionListener(this::jMenuItemViewAlarmListActionPerformed);
        jMenuView.add(jMenuItemViewAlarmList);

        jMenuItemViewCore1.setText("Core Activity 1");
        jMenuItemViewCore1.addActionListener(this::jMenuItemViewCore1ActionPerformed);
        jMenuView.add(jMenuItemViewCore1);

        jMenuItemViewCore2.setText("Core Activity 2");
        jMenuItemViewCore2.addActionListener(this::jMenuItemViewCore2ActionPerformed);
        jMenuView.add(jMenuItemViewCore2);

        jMenuBar1.add(jMenuView);

        jMenuControls.setText("Control Widgets");

        jMenuItemCoreControl.setText("Reactor Controls");
        jMenuItemCoreControl.addActionListener(this::jMenuItemCoreControlActionPerformed);
        jMenuControls.add(jMenuItemCoreControl);

        jMenuItemRecirculation.setText("Recirculation");
        jMenuItemRecirculation.addActionListener(this::jMenuItemRecirculationActionPerformed);
        jMenuControls.add(jMenuItemRecirculation);

        jMenuItemBlowdown.setText("Blowdown");
        jMenuItemBlowdown.addActionListener(this::jMenuItemBlowdownActionPerformed);
        jMenuControls.add(jMenuItemBlowdown);

        jMenuItemDeaerators.setText("Deaerators");
        jMenuItemDeaerators.addActionListener(this::jMenuItemDeaeratorsActionPerformed);
        jMenuControls.add(jMenuItemDeaerators);

        jMenuItemFeedwater.setText("Feedwater");
        jMenuItemFeedwater.addActionListener(this::jMenuItemFeedwaterActionPerformed);
        jMenuControls.add(jMenuItemFeedwater);

        jMenuItemAuxCond.setText("Auxiliary Condensers");
        jMenuItemAuxCond.addActionListener(this::jMenuItemAuxCondActionPerformed);
        jMenuControls.add(jMenuItemAuxCond);

        jMenuItemTurbine.setText("Turbine");
        jMenuItemTurbine.addActionListener(this::jMenuItemTurbineActionPerformed);
        jMenuControls.add(jMenuItemTurbine);

        jMenuItemTurbineBypass.setText("Turbine Bypass");
        jMenuItemTurbineBypass.addActionListener(this::jMenuItemTurbineBypassActionPerformed);
        jMenuControls.add(jMenuItemTurbineBypass);

        jMenuItemCondensation.setText("Condensation");
        jMenuItemCondensation.addActionListener(this::jMenuItemCondensationActionPerformed);
        jMenuControls.add(jMenuItemCondensation);

        jMenuItemPreheaters.setText("Preheater");
        jMenuItemPreheaters.addActionListener(this::jMenuItemPreheatersActionPerformed);
        jMenuControls.add(jMenuItemPreheaters);

        jMenuItemGenerator.setText("Generator");
        jMenuItemGenerator.addActionListener(this::jMenuItemGeneratorActionPerformed);
        jMenuControls.add(jMenuItemGenerator);

        jMenuItemCoolant.setText("Coolant");
        jMenuItemCoolant.addActionListener(this::jMenuItemCoolantActionPerformed);
        jMenuControls.add(jMenuItemCoolant);

        jMenuBar1.add(jMenuControls);

        jMenuMnemonics.setText("Mnemonic Displays");

        jMenuItemMnemonicBlowdown.setText("Blowdown & Aftercooler");
        jMenuItemMnemonicBlowdown.addActionListener(this::jMenuItemMnemonicBlowdownActionPerformed);
        jMenuMnemonics.add(jMenuItemMnemonicBlowdown);

        jMenuItemMnemonicLoop1.setText("Loop 1");
        jMenuItemMnemonicLoop1.addActionListener(this::jMenuItemMnemonicLoop1ActionPerformed);
        jMenuMnemonics.add(jMenuItemMnemonicLoop1);

        jMenuItemMnemonicLoop2.setText("Loop 2");
        jMenuItemMnemonicLoop2.addActionListener(this::jMenuItemMnemonicLoop2ActionPerformed);
        jMenuMnemonics.add(jMenuItemMnemonicLoop2);

        jMenuItemMnemonicFeedwater.setText("Feedwater");
        jMenuItemMnemonicFeedwater.addActionListener(this::jMenuItemMnemonicFeedwaterActionPerformed);
        jMenuMnemonics.add(jMenuItemMnemonicFeedwater);

        jMenuItemMnemonicDeaerators.setText("Deaerators");
        jMenuItemMnemonicDeaerators.addActionListener(this::jMenuItemMnemonicDeaeratorsActionPerformed);
        jMenuMnemonics.add(jMenuItemMnemonicDeaerators);

        jMenuItemMnemonicAuxCondenser.setText("Auxiliary Condenser");
        jMenuItemMnemonicAuxCondenser.addActionListener(this::jMenuItemMnemonicAuxCondenserActionPerformed);
        jMenuMnemonics.add(jMenuItemMnemonicAuxCondenser);

        jMenuItemMnemonicTurbine.setText("Turbine & Hotwell");
        jMenuItemMnemonicTurbine.addActionListener(this::jMenuItemMnemonicTurbineActionPerformed);
        jMenuMnemonics.add(jMenuItemMnemonicTurbine);

        jMenuItemMnemonicCondensation.setText("Condensation & Ejectors");
        jMenuItemMnemonicCondensation.addActionListener(this::jMenuItemMnemonicCondensationActionPerformed);
        jMenuMnemonics.add(jMenuItemMnemonicCondensation);

        jMenuItemMnemonicPreheaters.setText("Preheaters");
        jMenuItemMnemonicPreheaters.addActionListener(this::jMenuItemMnemonicPreheatersActionPerformed);
        jMenuMnemonics.add(jMenuItemMnemonicPreheaters);

        jMenuBar1.add(jMenuMnemonics);

        jMenuDiagrams.setText("Diagrams");

        jMenuNeutronFlux.setText("Neutron Flux");
        jMenuNeutronFlux.addActionListener(this::jMenuNeutronFluxActionPerformed);
        jMenuDiagrams.add(jMenuNeutronFlux);

        jMenuGlobalControl.setText("Reactor Global Control");
        jMenuGlobalControl.addActionListener(this::jMenuGlobalControlActionPerformed);
        jMenuDiagrams.add(jMenuGlobalControl);

        jMenuDrumSeparators.setText("Drum Separators");
        jMenuDrumSeparators.addActionListener(this::jMenuDrumSeparatorsActionPerformed);
        jMenuDiagrams.add(jMenuDrumSeparators);

        jMenuItemLoop1LevelControl.setText("Loop 1 Level Control");
        jMenuItemLoop1LevelControl.addActionListener(this::jMenuItemLoop1LevelControlActionPerformed);
        jMenuDiagrams.add(jMenuItemLoop1LevelControl);

        jMenuItemLoop2LevelControl.setText("Loop 2 Level Control");
        jMenuItemLoop2LevelControl.addActionListener(this::jMenuItemLoop2LevelControlActionPerformed);
        jMenuDiagrams.add(jMenuItemLoop2LevelControl);

        jMenuItemStartupPressureSetpoint.setText("Startup Pressure Setpoint");
        jMenuItemStartupPressureSetpoint.addActionListener(this::jMenuItemStartupPressureSetpointActionPerformed);
        jMenuDiagrams.add(jMenuItemStartupPressureSetpoint);

        jMenuItemTurbineHPTemperatures.setText("Turbine HP Temperatures");
        jMenuItemTurbineHPTemperatures.addActionListener(this::jMenuItemTurbineHPTemperaturesActionPerformed);
        jMenuDiagrams.add(jMenuItemTurbineHPTemperatures);

        jMenuItemTurbineReheaterDiag.setText("Turbine Superheater");
        jMenuItemTurbineReheaterDiag.addActionListener(this::jMenuItemTurbineReheaterDiagActionPerformed);
        jMenuDiagrams.add(jMenuItemTurbineReheaterDiag);

        jMenuItemPRV1.setText("Emergency PRV Loop 1");
        jMenuItemPRV1.addActionListener(this::jMenuItemPRV1ActionPerformed);
        jMenuDiagrams.add(jMenuItemPRV1);

        jMenuItemPRV2.setText("Emergency PRV Loop 2");
        jMenuItemPRV2.addActionListener(this::jMenuItemPRV2ActionPerformed);
        jMenuDiagrams.add(jMenuItemPRV2);

        jMenuBar1.add(jMenuDiagrams);

        jMenuPresets.setText("Presets");

        jMenuItemPresetFull.setText("All control widgets");
        jMenuItemPresetFull.addActionListener(this::jMenuItemPresetFullActionPerformed);
        jMenuPresets.add(jMenuItemPresetFull);

        jMenuItemPresetMnemonics.setText("All Mnemonics");
        jMenuItemPresetMnemonics.setToolTipText("");
        jMenuItemPresetMnemonics.addActionListener(this::jMenuItemPresetMnemonicsActionPerformed);
        jMenuPresets.add(jMenuItemPresetMnemonics);

        jMenuItemPresetReactorOperator.setText("Reactor Operator");
        jMenuItemPresetReactorOperator.addActionListener(this::jMenuItemPresetReactorOperatorActionPerformed);
        jMenuPresets.add(jMenuItemPresetReactorOperator);
        jMenuPresets.add(jSeparator1);

        jMenuItemPresetNone.setText("Clear (close all)");
        jMenuItemPresetNone.addActionListener(this::jMenuItemPresetNoneActionPerformed);
        jMenuPresets.add(jMenuItemPresetNone);

        jMenuBar1.add(jMenuPresets);

        jMenuHelp.setText("Help");

        jMenuAbout.setText("About");
        jMenuAbout.addActionListener(this::jMenuAboutActionPerformed);
        jMenuHelp.add(jMenuAbout);

        jMenuItemHowToStart.setText("How to start");
        jMenuItemHowToStart.addActionListener(this::jMenuItemHowToStartActionPerformed);
        jMenuHelp.add(jMenuItemHowToStart);
        jMenuHelp.add(jSeparator4);

        jMenuItemTriggerDisaster.setText("Debug: Trigger Disaster");
        jMenuItemTriggerDisaster.addActionListener(this::jMenuItemTriggerDisasterActionPerformed);
        jMenuHelp.add(jMenuItemTriggerDisaster);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPresetFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPresetFullActionPerformed
        // Presents a view with all of the controls placed to a defined grid.
        // close all:
        jMenuItemPresetNoneActionPerformed(null);

        // First, create all views if they are not yet open
        jMenuItemCoreControlActionPerformed(null);
        jMenuItemCondensationActionPerformed(null);
        jMenuItemRecirculationActionPerformed(null);
        jMenuItemFeedwaterActionPerformed(null);
        jMenuItemDeaeratorsActionPerformed(null);
        jMenuItemAuxCondActionPerformed(null);
        jMenuItemBlowdownActionPerformed(null);
        jMenuItemTurbineBypassActionPerformed(null);
        jMenuItemPreheatersActionPerformed(null);
        jMenuItemTurbineActionPerformed(null);
        jMenuItemGeneratorActionPerformed(null);
        //    jMenuItemCoolantActionPerformed(null);

        // Align them in a preset grid layout.
        // 1st row:
        jDesktopPane1.windowPlaceAtZero(
                getControlPanelInstance("Reactor Controls"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Blowdown"),
                getControlPanelInstance("Reactor Controls"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Turbine"),
                getControlPanelInstance("Blowdown"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Generator"),
                getControlPanelInstance("Turbine"));
        jDesktopPane1.windowPlaceBelow(
                getControlPanelInstance("Turbine Bypass"),
                getControlPanelInstance("Generator"));

        // 2nd row:
        jDesktopPane1.windowPlaceBelow(
                getControlPanelInstance("Recirculation"),
                getControlPanelInstance("Reactor Controls"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Feedwater"),
                getControlPanelInstance("Recirculation"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Deaerators"),
                getControlPanelInstance("Feedwater"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Condensation"),
                getControlPanelInstance("Deaerators"));

        // 3rd row:
        jDesktopPane1.windowPlaceBelow(
                getControlPanelInstance("Preheaters"),
                getControlPanelInstance("Recirculation"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Aux. Condensation"),
                getControlPanelInstance("Preheaters"));
    }//GEN-LAST:event_jMenuItemPresetFullActionPerformed

    private void jMenuItemPresetNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPresetNoneActionPerformed
        for (JInternalFrame f : jDesktopPane1.getAllFrames()) {
            f.setVisible(false);
            f.dispose();
            jDesktopPane1.remove(f);
        }
        jDesktopPane1.revalidate();
        jDesktopPane1.repaint();
        panels.clear();
        mnemonics.clear();
        diagrams.clear();
    }//GEN-LAST:event_jMenuItemPresetNoneActionPerformed

    private void jMenuItemCoreControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCoreControlActionPerformed
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Reactor Controls")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelCoreControl(), "Reactor Controls");
    }//GEN-LAST:event_jMenuItemCoreControlActionPerformed

    private void jMenuItemRecirculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRecirculationActionPerformed
        // Check if there is already an active frame using the slected class
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Recirculation")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelMCP(), "Recirculation");
    }//GEN-LAST:event_jMenuItemRecirculationActionPerformed

    private void jMenuItemBlowdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBlowdownActionPerformed
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Blowdown")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelBlowdown(), "Blowdown");
    }//GEN-LAST:event_jMenuItemBlowdownActionPerformed

    private void jMenuItemDeaeratorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeaeratorsActionPerformed
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Deaerators")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelDeaerators(), "Deaerators");
    }//GEN-LAST:event_jMenuItemDeaeratorsActionPerformed

    private void jMenuItemFeedwaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFeedwaterActionPerformed
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Feedwater")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelFeedwater(), "Feedwater");
    }//GEN-LAST:event_jMenuItemFeedwaterActionPerformed

    private void jMenuItemAuxCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAuxCondActionPerformed
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Aux. Condensation")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelAuxCondenser(), "Aux. Condensation");
    }//GEN-LAST:event_jMenuItemAuxCondActionPerformed

    private void jMenuItemTurbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurbineActionPerformed
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Turbine")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelTurbine(), "Turbine");
    }//GEN-LAST:event_jMenuItemTurbineActionPerformed

    private void jMenuItemTurbineBypassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurbineBypassActionPerformed
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Turbine Bypass")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelBypassValve(), "Turbine Bypass");
    }//GEN-LAST:event_jMenuItemTurbineBypassActionPerformed

    private void jMenuItemCondensationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCondensationActionPerformed
        // Check if there is already an active frame using the slected class
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Condensation")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelCondensation(), "Condensation");
    }//GEN-LAST:event_jMenuItemCondensationActionPerformed

    private void jMenuItemPreheatersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPreheatersActionPerformed
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Preheaters")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelPreheaters(), "Preheaters");
    }//GEN-LAST:event_jMenuItemPreheatersActionPerformed

    private void jMenuItemGeneratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGeneratorActionPerformed
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Generator")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelGenerator(), "Generator");
    }//GEN-LAST:event_jMenuItemGeneratorActionPerformed

    private void jMenuItemCoolantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCoolantActionPerformed
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals("Coolant")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelCoolant(), "Coolant");
    }//GEN-LAST:event_jMenuItemCoolantActionPerformed

    private void jMenuItemMnemonicBlowdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicBlowdownActionPerformed
        // Check if there is already an active frame using the slected class
        for (InternalFrameMnemonic mf : mnemonics) {
            if (mf.getPanelName().equals(
                    "Blowdown")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new PanelMnemonicBlowdown(), "Blowdown");
    }//GEN-LAST:event_jMenuItemMnemonicBlowdownActionPerformed

    private void jMenuItemMnemonicLoop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicLoop1ActionPerformed
        // Check if there is already an active frame using the slected class
        for (InternalFrameMnemonic mf : mnemonics) {
            if (mf.getPanelName().equals("Loop 1")) {
                return;

            }
        }
        // if theres no active frame, generate it and make it known here.
        PanelMnemonicLoop frame = new PanelMnemonicLoop();
        frame.setLoop(1);
        initializeMnemonic(frame, "Loop 1");
    }//GEN-LAST:event_jMenuItemMnemonicLoop1ActionPerformed

    private void jMenuItemMnemonicLoop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicLoop2ActionPerformed
        // Check if there is already an active frame using the slected class
        for (InternalFrameMnemonic mf : mnemonics) {
            if (mf.getPanelName().equals("Loop 2")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        PanelMnemonicLoop frame = new PanelMnemonicLoop();
        frame.setLoop(2);
        initializeMnemonic(frame, "Loop 2");
    }//GEN-LAST:event_jMenuItemMnemonicLoop2ActionPerformed

    private void jMenuItemMnemonicFeedwaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicFeedwaterActionPerformed
        // Check if there is already an active frame using the slected class
        for (InternalFrameMnemonic mf : mnemonics) {
            if (mf.getPanelName().equals("Feedwater Pumps")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new PanelMnemonicFeedwater(), "Feedwater Pumps");
    }//GEN-LAST:event_jMenuItemMnemonicFeedwaterActionPerformed

    private void jMenuItemMnemonicDeaeratorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicDeaeratorsActionPerformed
        // Check if there is already an active frame using the slected class
        for (InternalFrameMnemonic mf : mnemonics) {
            if (mf.getPanelName().equals("Deaerator")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new PanelMnemonicDeaerator(), "Deaerator");
    }//GEN-LAST:event_jMenuItemMnemonicDeaeratorsActionPerformed

    private void jMenuItemMnemonicAuxCondenserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicAuxCondenserActionPerformed
        // Check if there is already an active frame using the slected class
        for (InternalFrameMnemonic mf : mnemonics) {
            if (mf.getPanelName().equals("Aux Condenser")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new PanelMnemonicAuxiliaryCondenser(), "Aux Condenser");
    }//GEN-LAST:event_jMenuItemMnemonicAuxCondenserActionPerformed

    private void jMenuItemMnemonicTurbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicTurbineActionPerformed
        // Check if there is already an active frame using the slected class
        for (InternalFrameMnemonic mf : mnemonics) {
            if (mf.getPanelName().equals("Turbine")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new PanelMnemonicTurbine(), "Turbine");
    }//GEN-LAST:event_jMenuItemMnemonicTurbineActionPerformed

    private void jMenuItemMnemonicCondensationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicCondensationActionPerformed
        // Check if there is already an active frame using the slected class
        for (InternalFrameMnemonic mf : mnemonics) {
            if (mf.getPanelName().equals("Condensation")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new PanelMnemonicCondensate(), "Condensation");
    }//GEN-LAST:event_jMenuItemMnemonicCondensationActionPerformed

    private void jMenuItemMnemonicPreheatersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicPreheatersActionPerformed
        // Check if there is already an active frame using the slected class
        for (InternalFrameMnemonic mf : mnemonics) {
            if (mf.getPanelName().equals("Preheaters")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new PanelMnemonicPreheaters(), "Preheaters");
    }//GEN-LAST:event_jMenuItemMnemonicPreheatersActionPerformed

    private void jMenuNeutronFluxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNeutronFluxActionPerformed
        // Check if there is already an active frame using the desired class
        for (InternalFrameDiagram df : diagrams) {
            if (df.getTitle().equals("Neutron Flux")) {
                return;
            }
        }
        // if not, generate a new diagram and make it known.
        InternalFrameDiagram df = new InternalFrameDiagram();
        df.setTitle("Neutron Flux");
        DiagramPresets.neutronFlux(df.getFigure(), plotData);

        initializeDiagram(df);
    }//GEN-LAST:event_jMenuNeutronFluxActionPerformed

    private void jMenuGlobalControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGlobalControlActionPerformed
        // Check if there is already an active frame using the desired class
        for (InternalFrameDiagram df : diagrams) {
            if (df.getTitle().equals("Global Control")) {
                return;
            }
        }
        // if not, generate a new diagram and make it known.
        InternalFrameDiagram df = new InternalFrameDiagram();
        df.setTitle("Global Control");
        DiagramPresets.globalControl(df.getFigure(), plotData);

        initializeDiagram(df);
    }//GEN-LAST:event_jMenuGlobalControlActionPerformed

    private void jMenuDrumSeparatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDrumSeparatorsActionPerformed
        // Check if there is already an active frame using the desired class
        for (InternalFrameDiagram df : diagrams) {
            if (df.getTitle().equals("Drum Separators")) {
                return;
            }
        }
        // if not, generate a new diagram and make it known.
        InternalFrameDiagram df = new InternalFrameDiagram();
        df.setTitle("Drum Separators");
        DiagramPresets.drums(df.getFigure(), plotData);
        initializeDiagram(df);
    }//GEN-LAST:event_jMenuDrumSeparatorsActionPerformed

    private void jMenuItemLoop1LevelControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoop1LevelControlActionPerformed
        // Check if there is already an active frame using the desired class
        for (InternalFrameDiagram df : diagrams) {
            if (df.getTitle().equals("Loop 1 Level Control")) {
                return;
            }
        }
        // if not, generate a new diagram and make it known.
        InternalFrameDiagram df = new InternalFrameDiagram();
        df.setTitle("Loop 1 Level Control");
        DiagramPresets.loopLevelControl(df.getFigure(), plotData, 1);
        initializeDiagram(df);
    }//GEN-LAST:event_jMenuItemLoop1LevelControlActionPerformed

    private void jMenuItemLoop2LevelControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoop2LevelControlActionPerformed
        // Check if there is already an active frame using the desired class
        for (InternalFrameDiagram df : diagrams) {
            if (df.getTitle().equals("Loop 2 Level Control")) {
                return;
            }
        }
        // if not, generate a new diagram and make it known.
        InternalFrameDiagram df = new InternalFrameDiagram();
        df.setTitle("Loop 2 Level Control");
        DiagramPresets.loopLevelControl(df.getFigure(), plotData, 2);
        initializeDiagram(df);
    }//GEN-LAST:event_jMenuItemLoop2LevelControlActionPerformed

    private void jMenuItemStartupPressureSetpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStartupPressureSetpointActionPerformed
        // Check if there is already an active frame using the desired class
        for (InternalFrameDiagram df : diagrams) {
            if (df.getTitle().equals("Startup Pressure Setpoint")) {
                return;
            }
        }
        // if not, generate a new diagram and make it known.
        DiagramStartupPressureSetpoint df = new DiagramStartupPressureSetpoint();
        df.setTitle("Startup Pressure Setpoint");
        df.initPlotObjects(plotData); // this init is different from the other diagrams!
        initializeDiagram(df);
    }//GEN-LAST:event_jMenuItemStartupPressureSetpointActionPerformed

    private void jMenuItemTurbineHPTemperaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurbineHPTemperaturesActionPerformed
        // Check if there is already an active frame using the desired class
        for (InternalFrameDiagram df : diagrams) {
            if (df.getTitle().equals("Turbine: HP Temperatures")) {
                return;
            }
        }
        // if not, generate a new diagram and make it known.
        InternalFrameDiagram df = new InternalFrameDiagram();
        df.setTitle("Turbine: HP Temperatures");
        DiagramPresets.turbineHPTemperatures(df.getFigure(), plotData);
        initializeDiagram(df);
    }//GEN-LAST:event_jMenuItemTurbineHPTemperaturesActionPerformed

    private void jMenuItemPresetMnemonicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPresetMnemonicsActionPerformed
        // close all:
        jMenuItemPresetNoneActionPerformed(null);

        // Open all mnemonics:        
        jMenuItemMnemonicBlowdownActionPerformed(null);
        jMenuItemMnemonicLoop1ActionPerformed(null);
        jMenuItemMnemonicLoop2ActionPerformed(null);
        jMenuItemMnemonicFeedwaterActionPerformed(null);
        jMenuItemMnemonicDeaeratorsActionPerformed(null);
        jMenuItemMnemonicAuxCondenserActionPerformed(null);
        jMenuItemMnemonicTurbineActionPerformed(null);
        jMenuItemMnemonicCondensationActionPerformed(null);
        jMenuItemMnemonicPreheatersActionPerformed(null);

        jDesktopPane1.windowPlaceAtZero(
                getMnemonicInstance("Loop 1"));
        jDesktopPane1.windowPlaceRightTo(
                getMnemonicInstance("Blowdown"),
                getMnemonicInstance("Loop 1"));
        jDesktopPane1.windowPlaceRightTo(
                getMnemonicInstance("Loop 2"),
                getMnemonicInstance("Blowdown"));
        jDesktopPane1.windowPlaceRightTo(
                getMnemonicInstance("Aux Condenser"),
                getMnemonicInstance("Loop 2"));
        jDesktopPane1.windowPlaceRightTo(
                getMnemonicInstance("Turbine"),
                getMnemonicInstance("Aux Condenser"));

        // Below turbine, down:
        jDesktopPane1.windowPlaceBelow(
                getMnemonicInstance("Condensation"),
                getMnemonicInstance("Turbine"));
        jDesktopPane1.windowPlaceBelow(
                getMnemonicInstance("Preheaters"),
                getMnemonicInstance("Condensation"));

        // Place feedwater and DA below loop 1 and 2, not that pretty:
        jDesktopPane1.windowPlaceBelow(
                getMnemonicInstance("Feedwater Pumps"),
                getMnemonicInstance("Loop 1"));
        jDesktopPane1.windowPlaceBelow(
                getMnemonicInstance("Deaerator"),
                getMnemonicInstance("Loop 2"));
    }//GEN-LAST:event_jMenuItemPresetMnemonicsActionPerformed

    private void jMenuItemViewRodPositionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewRodPositionsActionPerformed
        if (rodPositions == null) {
            rodPositions = new InternalFrameSelsyns();
            rodPositions.setVisible(true);

            rodPositions.addInternalFrameListener(new InternalFrameAdapter() {
                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    rodPositions = null;
                }
            });
            jDesktopPane1.add(rodPositions);
        }
        try {
            rodPositions.setSelected(true);
        } catch (PropertyVetoException ex) {
            // ignore
        }
    }//GEN-LAST:event_jMenuItemViewRodPositionsActionPerformed

    private void jMenuItemViewAlarmListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewAlarmListActionPerformed
        if (alarmTable == null) {
            alarmTable = new InternalFrameAlarmTable();
            alarmTable.registerActionReceiver(controller);
            alarmTable.setVisible(true);

            alarmTable.addInternalFrameListener(new InternalFrameAdapter() {
                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    alarmTable = null;
                }
            });
            jDesktopPane1.add(alarmTable);
        }
        try {
            alarmTable.setSelected(true);
        } catch (PropertyVetoException ex) {
            // ignore
        }
    }//GEN-LAST:event_jMenuItemViewAlarmListActionPerformed

    private void jMenuItemPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPauseActionPerformed
        controller.userAction(new ActionCommand("PauseSimulation", null));
    }//GEN-LAST:event_jMenuItemPauseActionPerformed

    private void jCheckBoxMenuOnlyCoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuOnlyCoreActionPerformed
        controller.userAction(new ActionCommand("SetCoreOnly", null));
        jCheckBoxMenuOnlyCore.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxMenuOnlyCoreActionPerformed

    private void jMenuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoadActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter(
                "Initial Conditions Files (*.ic)", "ic"));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            controller.userAction(new ActionCommand(
                    "LoadSimulationState",
                    fc.getSelectedFile().getAbsolutePath()));
        }
    }//GEN-LAST:event_jMenuLoadActionPerformed

    private void jMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter(
                "Initial Conditions Files (*.ic)", "ic"));
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            // Append .ic if no extension was typed by the user
            if (!file.getName().contains(".")) {
                file = new File(file.getAbsolutePath() + ".ic");
            }

            // Warn before overwriting an existing file
            if (file.exists()) {
                int result = JOptionPane.showConfirmDialog(this,
                        "The file \"" + file.getName()
                        + "\" already exists.\nDo you want to replace it?",
                        "Confirm Save",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);
                if (result != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            controller.userAction(new ActionCommand(
                    "SaveSimulationState",
                    file.getAbsolutePath()));
        }
    }//GEN-LAST:event_jMenuSaveActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuAboutActionPerformed

    private void jMenuItemHowToStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHowToStartActionPerformed
        HowtoStartDialog dialog = new HowtoStartDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemHowToStartActionPerformed

    private void jMenuItemNewPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewPanelActionPerformed
        // call on parent as this does all the initialization.
        parentControlRoom.displayNewControlPanel();
    }//GEN-LAST:event_jMenuItemNewPanelActionPerformed

    private void jMenuItemViewCore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewCore1ActionPerformed
        if (coreActivity1 == null) {
            coreActivity1 = new InternalFrameCoreActivity();
            coreActivity1.setTitle("Core Activity 1");
            coreActivity1.setVisible(true);
            coreActivity1.addInternalFrameListener(new InternalFrameAdapter() {
                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    coreActivity1 = null;
                }
            });
            jDesktopPane1.add(coreActivity1);
        }

        try {
            coreActivity1.setSelected(true);
        } catch (PropertyVetoException ex) {
            // ignore
        }
    }//GEN-LAST:event_jMenuItemViewCore1ActionPerformed

    private void jMenuItemViewCore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewCore2ActionPerformed
        if (coreActivity2 == null) {
            coreActivity2 = new InternalFrameCoreActivity();
            coreActivity2.setTitle("Core Activity 2");
            coreActivity2.setVisible(true);
            coreActivity2.addInternalFrameListener(new InternalFrameAdapter() {
                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    coreActivity2 = null;
                }
            });
            jDesktopPane1.add(coreActivity2);
        }

        try {
            coreActivity2.setSelected(true);
        } catch (PropertyVetoException ex) {
            // ignore
        }
    }//GEN-LAST:event_jMenuItemViewCore2ActionPerformed

    private void jMenuItemPresetReactorOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPresetReactorOperatorActionPerformed
        jMenuItemPresetNoneActionPerformed(null); // close all:

        jMenuItemViewRodPositionsActionPerformed(null);
        jMenuItemViewAlarmListActionPerformed(null);
        jMenuItemViewCore1ActionPerformed(null);
        jMenuItemViewCore2ActionPerformed(null);
        jMenuItemCoreControlActionPerformed(null);
        jMenuNeutronFluxActionPerformed(null);
        jMenuGlobalControlActionPerformed(null);

        jDesktopPane1.windowPlaceAtZero(coreActivity1);
        jDesktopPane1.windowPlaceRightTo(rodPositions, coreActivity1);
        jDesktopPane1.windowPlaceRightTo(coreActivity2, rodPositions);
        jDesktopPane1.windowPlaceRightTo(alarmTable, coreActivity2);
        jDesktopPane1.windowPlaceBelow(
                getDiagramInstance("Global Control"),
                coreActivity1);
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Reactor Controls"),
                getDiagramInstance("Global Control"));
        jDesktopPane1.windowPlaceRightTo(
                getDiagramInstance("Neutron Flux"),
                getControlPanelInstance("Reactor Controls"));
    }//GEN-LAST:event_jMenuItemPresetReactorOperatorActionPerformed

    private void jMenuItemTurbineReheaterDiagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurbineReheaterDiagActionPerformed
        // Check if there is already an active frame using the desired class
        for (InternalFrameDiagram df : diagrams) {
            if (df.getTitle().equals("Turbine: Superheater Control")) {
                return;
            }
        }
        // if not, generate a new diagram and make it known.
        InternalFrameDiagram df = new InternalFrameDiagram();
        df.setTitle("Turbine: Superheater Control");
        DiagramPresets.reheaterControl(df.getFigure(), plotData);
        initializeDiagram(df);
    }//GEN-LAST:event_jMenuItemTurbineReheaterDiagActionPerformed

    private void jMenuItemTriggerDisasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTriggerDisasterActionPerformed
        controller.userAction(new ActionCommand("Reactor#TriggerPromptExcursion", null));
    }//GEN-LAST:event_jMenuItemTriggerDisasterActionPerformed

    private void jMenuItemPRV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPRV2ActionPerformed
        // Check if there is already an active frame using the desired class
        for (InternalFrameDiagram df : diagrams) {
            if (df.getTitle().equals("Loop 2 PRV")) {
                return;
            }
        }
        // if not, generate a new diagram and make it known.
        InternalFrameDiagram df = new InternalFrameDiagram();
        df.setTitle("Loop 2 PRV");
        DiagramPresets.loopPressureRelievValves(df.getFigure(), plotData, 1);
        initializeDiagram(df);
    }//GEN-LAST:event_jMenuItemPRV2ActionPerformed

    private void jMenuItemPRV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPRV1ActionPerformed
        // Check if there is already an active frame using the desired class
        for (InternalFrameDiagram df : diagrams) {
            if (df.getTitle().equals("Loop 1 PRV")) {
                return;
            }
        }
        // if not, generate a new diagram and make it known.
        InternalFrameDiagram df = new InternalFrameDiagram();
        df.setTitle("Loop 1 PRV");
        DiagramPresets.loopPressureRelievValves(df.getFigure(), plotData, 1);
        initializeDiagram(df);
    }//GEN-LAST:event_jMenuItemPRV1ActionPerformed

    /**
     * Makes some initializations to the mnemonic frame object and add it to the
     * list to have a reference to the created instance.
     *
     * @param object JFrame object that implements UpdateReceiver, this is
     * usually the new FrameMnemoicWhatever()
     */
    private void initializeMnemonic(javax.swing.JPanel object, String title) {
        // Generate a new JInteralFrame object (that will be the frame inside 
        // the desktop pane)
        InternalFrameMnemonic cpf = new InternalFrameMnemonic();
        // add the mnemonics panel and pass the title
        cpf.initPanel(object, title);
        cpf.setVisible(true);
        jDesktopPane1.add(cpf);

        cpf.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                mnemonics.remove(cpf);
            }
        });

        // Put it to front:
        try {
            cpf.setSelected(true);
        } catch (PropertyVetoException ex) {
            // ignore
        }
        cpf.toFront();
        // Add the frame to the list of active internal frames so the panel
        // frame will receive updates
        mnemonics.add(cpf);
        controller.fireLastPropertyChangesTo((UpdateReceiver) object);
    }

    /**
     * Makes some initializations to an additional control panel frame object
     * (makes the controller instance known) and add it to the list to have a
     * reference to the created instance.
     *
     * @param object An instance that is the panel
     */
    private void initializeControlPanel(AbstractPanelWidget panel,
            String title) {
        // Generate a new JInteralFrame object (that will be the frame inside 
        // the desktop pane)
        InternalFramePanel cpf = new InternalFramePanel();
        // Give the generated Panel object to that frame and make it initialize 
        // itself
        cpf.initPanel(panel, title, controller);
        cpf.setVisible(true);
        jDesktopPane1.add(cpf);
        // The frame will automatically adjust its size due to its layout.

        // Remove it from the list of windows when closing:
        cpf.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                panels.remove(cpf);
            }
        }
        );

        // Put it to front:
        try {
            cpf.setSelected(true);
        } catch (PropertyVetoException ex) {
            // ignore
        }
        cpf.toFront();
        // Add the frame to the list of active internal frames so the panel
        // frame will receive updates
        panels.add(cpf);
        controller.fireLastPropertyChangesTo(panel);
    }

    /**
     * Makes some initializations to the diagram frame object and add it to the
     * list to have a reference to the created instance.
     *
     * @param object JInternalFrame object
     */
    private void initializeDiagram(InternalFrameDiagram cpf) {
        cpf.setVisible(true);
        jDesktopPane1.add(cpf);

        cpf.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                diagrams.remove(cpf);
            }
        });

        // Put it to front:
        try {
            cpf.setSelected(true);
        } catch (PropertyVetoException ex) {
            // ignore
        }
        cpf.toFront();
        // Add the frame to the list of active internal frames so the panel
        // frame will receive updates
        diagrams.add(cpf);
    }

    private InternalFramePanel getControlPanelInstance(String designator) {
        for (InternalFramePanel pf : panels) {
            if (pf.getPanelName().equals(designator)) {
                return pf;
            }
        }
        return null;
    }

    private InternalFrameMnemonic getMnemonicInstance(String designator) {
        for (InternalFrameMnemonic mf : mnemonics) {
            if (mf.getPanelName().equals(designator)) {
                return mf;
            }
        }
        return null;
    }

    private InternalFrameDiagram getDiagramInstance(String designator) {
        for (InternalFrameDiagram df : diagrams) {
            if (df.getTitle().equals(designator)) {
                return df;
            }
        }
        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuOnlyCore;
    private com.hartrusion.util.JDesktopPaneEnhanced jDesktopPane1;
    private javax.swing.JMenuItem jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuControls;
    private javax.swing.JMenu jMenuDiagrams;
    private javax.swing.JMenuItem jMenuDrumSeparators;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuGlobalControl;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAuxCond;
    private javax.swing.JMenuItem jMenuItemBlowdown;
    private javax.swing.JMenuItem jMenuItemCondensation;
    private javax.swing.JMenuItem jMenuItemCoolant;
    private javax.swing.JMenuItem jMenuItemCoreControl;
    private javax.swing.JMenuItem jMenuItemDeaerators;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemFeedwater;
    private javax.swing.JMenuItem jMenuItemGenerator;
    private javax.swing.JMenuItem jMenuItemHowToStart;
    private javax.swing.JMenuItem jMenuItemLoop1LevelControl;
    private javax.swing.JMenuItem jMenuItemLoop2LevelControl;
    private javax.swing.JMenuItem jMenuItemMnemonicAuxCondenser;
    private javax.swing.JMenuItem jMenuItemMnemonicBlowdown;
    private javax.swing.JMenuItem jMenuItemMnemonicCondensation;
    private javax.swing.JMenuItem jMenuItemMnemonicDeaerators;
    private javax.swing.JMenuItem jMenuItemMnemonicFeedwater;
    private javax.swing.JMenuItem jMenuItemMnemonicLoop1;
    private javax.swing.JMenuItem jMenuItemMnemonicLoop2;
    private javax.swing.JMenuItem jMenuItemMnemonicPreheaters;
    private javax.swing.JMenuItem jMenuItemMnemonicTurbine;
    private javax.swing.JMenuItem jMenuItemNewPanel;
    private javax.swing.JMenuItem jMenuItemPRV1;
    private javax.swing.JMenuItem jMenuItemPRV2;
    private javax.swing.JMenuItem jMenuItemPause;
    private javax.swing.JMenuItem jMenuItemPreheaters;
    private javax.swing.JMenuItem jMenuItemPresetFull;
    private javax.swing.JMenuItem jMenuItemPresetMnemonics;
    private javax.swing.JMenuItem jMenuItemPresetNone;
    private javax.swing.JMenuItem jMenuItemPresetReactorOperator;
    private javax.swing.JMenuItem jMenuItemRecirculation;
    private javax.swing.JMenuItem jMenuItemStartupPressureSetpoint;
    private javax.swing.JMenuItem jMenuItemTriggerDisaster;
    private javax.swing.JMenuItem jMenuItemTurbine;
    private javax.swing.JMenuItem jMenuItemTurbineBypass;
    private javax.swing.JMenuItem jMenuItemTurbineHPTemperatures;
    private javax.swing.JMenuItem jMenuItemTurbineReheaterDiag;
    private javax.swing.JMenuItem jMenuItemViewAlarmList;
    private javax.swing.JMenuItem jMenuItemViewCore1;
    private javax.swing.JMenuItem jMenuItemViewCore2;
    private javax.swing.JMenuItem jMenuItemViewRodPositions;
    private javax.swing.JMenuItem jMenuLoad;
    private javax.swing.JMenu jMenuMnemonics;
    private javax.swing.JMenuItem jMenuNeutronFlux;
    private javax.swing.JMenu jMenuPresets;
    private javax.swing.JMenuItem jMenuSave;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void registerController(ViewerController controller) {
        this.controller = controller;
    }

    public void setParent(ControlPanelManager parent) {
        parentControlRoom = parent;
        // Todo: maybe there's a better way of organizing this.
        this.alarmList = parentControlRoom.getAlarmList();
    }

    public void openReactorControlPanel() {
        // To discuss - to be able to open one panel for the first opened frame
        jMenuItemCoreControlActionPerformed(null);
    }

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        for (InternalFramePanel pf : panels) {
            pf.updateComponent(evt);
        }
        for (InternalFrameMnemonic mf : mnemonics) {
            mf.updateComponent(evt);
        }

        if (rodPositions != null) {
            rodPositions.updateComponent(evt);
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        if (propertyName.equals("OutputValues")) {
            ((ValueHandler) newValue).fireAllToMvcView(this);
            plotData = (ValueHandler) newValue;

            for (InternalFrameDiagram df : diagrams) {
                df.updatePlots();
            }

            // use this event to update the alarm list also.
            if (alarmTable != null) {
                alarmTable.setAlarms(alarmList);
            }
        }

        if (coreActivity1 != null && propertyName.equals("CoreIndicator#1")) {
            coreActivity1.updateDisplay((CoreIndicator) newValue);
            return;
        }
        if (coreActivity2 != null && propertyName.equals("CoreIndicator#2")) {
            coreActivity2.updateDisplay((CoreIndicator) newValue);
            return;
        }

        for (InternalFramePanel pf : panels) {
            pf.updateComponent(propertyName, newValue);
        }
        for (InternalFrameMnemonic mf : mnemonics) {
            mf.updateComponent(propertyName, newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        for (InternalFramePanel pf : panels) {
            pf.updateComponent(propertyName, newValue);
        }
        for (InternalFrameMnemonic mf : mnemonics) {
            mf.updateComponent(propertyName, newValue);
        }
        if (rodPositions != null) {
            rodPositions.updateComponent(propertyName, newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
        for (InternalFramePanel pf : panels) {
            pf.updateComponent(propertyName, newValue);
        }
        for (InternalFrameMnemonic mf : mnemonics) {
            mf.updateComponent(propertyName, newValue);
        }
    }

    @Override
    public void userAction(ActionCommand evt) {
        controller.userAction(evt);
    }
}
