/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim;

import java.beans.PropertyChangeEvent;
import com.hartrusion.values.ValueHandler;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.InteractiveView;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.mvc.ViewerController;
import com.hartrusion.rbmksim.gui.*;
import com.hartrusion.rbmksim.gui.mnemonic.*;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class ControlRoom extends javax.swing.JFrame
        implements InteractiveView {

    private ViewerController controller;

    private FrameRodPositions frameRodPositions;
    private FrameCoreActivity frameCoreActivity;

    private FrameDiagramNeutronFlux frameDiagramNeutronFlux;
    private FrameDiagramDrums frameDiagramDrums;
    private FrameDiagramLoopLevel frameDiagramLoop1Level;
    private FrameDiagramLoopLevel frameDiagramLoop2Level;
    private FrameDiagramGlobalControl frameDiagramGlobalControl;

    private FrameAlarmTable frameAlarms;
    private List alarmList;

    private ValueHandler plotData;

    /**
     * Holds a list of all interactive components which are active inside the
     * desktop pane to update them.
     */
    private final List<ControlPanelFrame> controlPanels = new ArrayList<>();

    private final List<UpdateReceiver> mnemonics = new ArrayList<>();

    /**
     * Creates new form ControlPanel
     */
    public ControlRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jDesktopPane1 = new com.hartrusion.util.JDesktopPaneEnhanced();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemPause = new javax.swing.JMenuItem();
        jCheckBoxMenuOnlyCore = new javax.swing.JCheckBoxMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuLoad = new javax.swing.JMenuItem();
        jMenuSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuControls = new javax.swing.JMenu();
        jMenuItemPresetFull = new javax.swing.JMenuItem();
        jMenuItemPresetNone = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCoreControl = new javax.swing.JMenuItem();
        jMenuItemRecirculation = new javax.swing.JMenuItem();
        jMenuItemBlowdown = new javax.swing.JMenuItem();
        jMenuItemDeaerators = new javax.swing.JMenuItem();
        jMenuItemFeedwater = new javax.swing.JMenuItem();
        jMenuItemAuxCond = new javax.swing.JMenuItem();
        jMenuItemTurbine = new javax.swing.JMenuItem();
        jMenuItemTurbineBypass = new javax.swing.JMenuItem();
        jMenuItemCondensation = new javax.swing.JMenuItem();
        jMenuItemPreheaters = new javax.swing.JMenuItem();
        jMenuItemGenerator = new javax.swing.JMenuItem();
        jMenuItemCoolant = new javax.swing.JMenuItem();
        jMenuPanels = new javax.swing.JMenu();
        jMenuAlarms = new javax.swing.JMenuItem();
        jMenuRodPositions = new javax.swing.JMenuItem();
        jMenuCoreMatrix = new javax.swing.JMenuItem();
        jMenuMnemonics = new javax.swing.JMenu();
        jMenuItemCore = new javax.swing.JMenuItem();
        jMenuItemMnemonicBlowdown = new javax.swing.JMenuItem();
        jMenuItemMnemonicLoop1 = new javax.swing.JMenuItem();
        jMenuItemMnemonicLoop2 = new javax.swing.JMenuItem();
        jMenuItemMnemonicFeedwater = new javax.swing.JMenuItem();
        jMenuItemMnemonicDeaerators = new javax.swing.JMenuItem();
        jMenuItemMnemonicAuxCondenser = new javax.swing.JMenuItem();
        jMenuItemMnemonicTurbine = new javax.swing.JMenuItem();
        jMenuItemMnemonicCondensation = new javax.swing.JMenuItem();
        jMenuItemMnemonicPreheaters = new javax.swing.JMenuItem();
        jMenuDiagrams = new javax.swing.JMenu();
        jMenuNeutronFlux = new javax.swing.JMenuItem();
        jMenuGlobalControl = new javax.swing.JMenuItem();
        jMenuDrumSeparators = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control Panel");
        setMinimumSize(new java.awt.Dimension(580, 400));
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setViewportView(jDesktopPane1);

        getContentPane().add(jScrollPane2);

        jMenuFile.setText("File");

        jMenuItemPause.setText("Pause Simulation");
        jMenuItemPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPauseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemPause);

        jCheckBoxMenuOnlyCore.setText("Simulate reactor only");
        jCheckBoxMenuOnlyCore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuOnlyCoreActionPerformed(evt);
            }
        });
        jMenuFile.add(jCheckBoxMenuOnlyCore);
        jMenuFile.add(jSeparator2);

        jMenuLoad.setText("Load");
        jMenuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoadActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuLoad);

        jMenuSave.setText("Save as...");
        jMenuSave.setToolTipText("");
        jMenuSave.setActionCommand("Save");
        jMenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuSave);
        jMenuFile.add(jSeparator1);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuControls.setText("Control Panels");

        jMenuItemPresetFull.setText("View all (full panel)");
        jMenuItemPresetFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPresetFullActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemPresetFull);

        jMenuItemPresetNone.setText("Close all");
        jMenuItemPresetNone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPresetNoneActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemPresetNone);
        jMenuControls.add(jSeparator3);

        jMenuItemCoreControl.setText("Reactor Controls");
        jMenuItemCoreControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCoreControlActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemCoreControl);

        jMenuItemRecirculation.setText("Recirculation");
        jMenuItemRecirculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRecirculationActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemRecirculation);

        jMenuItemBlowdown.setText("Blowdown");
        jMenuItemBlowdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBlowdownActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemBlowdown);

        jMenuItemDeaerators.setText("Deaerators");
        jMenuItemDeaerators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeaeratorsActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemDeaerators);

        jMenuItemFeedwater.setText("Feedwater");
        jMenuItemFeedwater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFeedwaterActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemFeedwater);

        jMenuItemAuxCond.setText("Auxiliary Condensers");
        jMenuItemAuxCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAuxCondActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemAuxCond);

        jMenuItemTurbine.setText("Turbine");
        jMenuItemTurbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTurbineActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemTurbine);

        jMenuItemTurbineBypass.setText("Turbine Bypass");
        jMenuItemTurbineBypass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTurbineBypassActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemTurbineBypass);

        jMenuItemCondensation.setText("Condensation");
        jMenuItemCondensation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCondensationActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemCondensation);

        jMenuItemPreheaters.setText("Preheater");
        jMenuItemPreheaters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPreheatersActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemPreheaters);

        jMenuItemGenerator.setText("Generator");
        jMenuItemGenerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGeneratorActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemGenerator);

        jMenuItemCoolant.setText("Coolant");
        jMenuItemCoolant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCoolantActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemCoolant);

        jMenuBar1.add(jMenuControls);

        jMenuPanels.setText("Views");

        jMenuAlarms.setText("Alarm List");
        jMenuAlarms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlarmsActionPerformed(evt);
            }
        });
        jMenuPanels.add(jMenuAlarms);

        jMenuRodPositions.setText("Rod Positions");
        jMenuRodPositions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRodPositionsActionPerformed(evt);
            }
        });
        jMenuPanels.add(jMenuRodPositions);

        jMenuCoreMatrix.setText("Core Matrix");
        jMenuCoreMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCoreMatrixActionPerformed(evt);
            }
        });
        jMenuPanels.add(jMenuCoreMatrix);

        jMenuBar1.add(jMenuPanels);

        jMenuMnemonics.setText("Mnemonic Displays");

        jMenuItemCore.setText("Core (Debug)");
        jMenuItemCore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCoreActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemCore);

        jMenuItemMnemonicBlowdown.setText("Blowdown & Aftercooler");
        jMenuItemMnemonicBlowdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicBlowdownActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicBlowdown);

        jMenuItemMnemonicLoop1.setText("Loop 1");
        jMenuItemMnemonicLoop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicLoop1ActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicLoop1);

        jMenuItemMnemonicLoop2.setText("Loop 2");
        jMenuItemMnemonicLoop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicLoop2ActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicLoop2);

        jMenuItemMnemonicFeedwater.setText("Feedwater");
        jMenuItemMnemonicFeedwater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicFeedwaterActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicFeedwater);

        jMenuItemMnemonicDeaerators.setText("Deaerators");
        jMenuItemMnemonicDeaerators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicDeaeratorsActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicDeaerators);

        jMenuItemMnemonicAuxCondenser.setText("Auxiliary Condenser");
        jMenuItemMnemonicAuxCondenser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicAuxCondenserActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicAuxCondenser);

        jMenuItemMnemonicTurbine.setText("Turbine & Hotwell");
        jMenuItemMnemonicTurbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicTurbineActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicTurbine);

        jMenuItemMnemonicCondensation.setText("Condensation & Ejectors");
        jMenuItemMnemonicCondensation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicCondensationActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicCondensation);

        jMenuItemMnemonicPreheaters.setText("Preheaters");
        jMenuItemMnemonicPreheaters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicPreheatersActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicPreheaters);

        jMenuBar1.add(jMenuMnemonics);

        jMenuDiagrams.setText("Diagrams");

        jMenuNeutronFlux.setText("Neutron Flux");
        jMenuNeutronFlux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNeutronFluxActionPerformed(evt);
            }
        });
        jMenuDiagrams.add(jMenuNeutronFlux);

        jMenuGlobalControl.setText("Reactor Global Control");
        jMenuGlobalControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGlobalControlActionPerformed(evt);
            }
        });
        jMenuDiagrams.add(jMenuGlobalControl);

        jMenuDrumSeparators.setText("Drum Separators");
        jMenuDrumSeparators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDrumSeparatorsActionPerformed(evt);
            }
        });
        jMenuDiagrams.add(jMenuDrumSeparators);

        jMenuItem8.setText("Loop 1 Level Control");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuDiagrams.add(jMenuItem8);

        jMenuItem9.setText("Loop 2 Level Control");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuDiagrams.add(jMenuItem9);

        jMenuBar1.add(jMenuDiagrams);

        jMenuHelp.setText("Help");

        jMenuAbout.setText("About");
        jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuRodPositionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRodPositionsActionPerformed
        if (frameRodPositions == null) {
            frameRodPositions = new FrameRodPositions();
            java.awt.EventQueue.invokeLater(() -> {
                frameRodPositions.setVisible(true);
            });
            frameRodPositions.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameRodPositions = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuRodPositionsActionPerformed

    private void jMenuCoreMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCoreMatrixActionPerformed
        if (frameCoreActivity == null) {
            frameCoreActivity = new FrameCoreActivity();
            java.awt.EventQueue.invokeLater(() -> {
                frameCoreActivity.setVisible(true);
            });
            frameCoreActivity.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameCoreActivity = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuCoreMatrixActionPerformed

    private void jMenuItemMnemonicBlowdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicBlowdownActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicBlowdown")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicBlowdown());
    }//GEN-LAST:event_jMenuItemMnemonicBlowdownActionPerformed

    private void jMenuItemMnemonicLoop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicLoop1ActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicLoop")) {
                // there can be 2 instances of this Frame for both loops.
                if (((FrameMnemonicLoop) ur).getLoop() == 1) {
                    return;
                }
            }
        }
        // if theres no active frame, generate it and make it known here.
        FrameMnemonicLoop frame = new FrameMnemonicLoop();
        frame.setLoop(1);
        initializeMnemonic(frame);
    }//GEN-LAST:event_jMenuItemMnemonicLoop1ActionPerformed

    private void jMenuItemMnemonicLoop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicLoop2ActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicLoop")) {
                // there can be 2 instances of this Frame for both loops.
                if (((FrameMnemonicLoop) ur).getLoop() == 2) {
                    return;
                }
            }
        }
        // if theres no active frame, generate it and make it known here.
        FrameMnemonicLoop frame = new FrameMnemonicLoop();
        frame.setLoop(2);
        initializeMnemonic(frame);
    }//GEN-LAST:event_jMenuItemMnemonicLoop2ActionPerformed

    private void jMenuNeutronFluxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNeutronFluxActionPerformed
        if (frameDiagramNeutronFlux == null && plotData != null) {
            frameDiagramNeutronFlux = new FrameDiagramNeutronFlux();
            frameDiagramNeutronFlux.initPlots(plotData, 0);
            java.awt.EventQueue.invokeLater(() -> {
                frameDiagramNeutronFlux.setVisible(true);
            });
            frameDiagramNeutronFlux.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameDiagramNeutronFlux = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuNeutronFluxActionPerformed

    private void jMenuItemMnemonicAuxCondenserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicAuxCondenserActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicAuxiliaryCondenser")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicAuxiliaryCondenser());
    }//GEN-LAST:event_jMenuItemMnemonicAuxCondenserActionPerformed

    private void jMenuItemCoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCoreActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicCore")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicCore());
    }//GEN-LAST:event_jMenuItemCoreActionPerformed

    private void jMenuItemMnemonicFeedwaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicFeedwaterActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicFeedwater")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicFeedwater());
    }//GEN-LAST:event_jMenuItemMnemonicFeedwaterActionPerformed

    private void jMenuItemMnemonicDeaeratorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicDeaeratorsActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicDeaerator")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicDeaerator());
    }//GEN-LAST:event_jMenuItemMnemonicDeaeratorsActionPerformed

    private void jMenuDrumSeparatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDrumSeparatorsActionPerformed
        if (frameDiagramDrums == null && plotData != null) {
            frameDiagramDrums = new FrameDiagramDrums();
            frameDiagramDrums.initPlots(plotData, 0);
            java.awt.EventQueue.invokeLater(() -> {
                frameDiagramDrums.setVisible(true);
            });
            frameDiagramDrums.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameDiagramDrums = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuDrumSeparatorsActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if (frameDiagramLoop2Level == null && plotData != null) {
            frameDiagramLoop2Level = new FrameDiagramLoopLevel();
            frameDiagramLoop2Level.initPlots(plotData, 2);
            java.awt.EventQueue.invokeLater(() -> {
                frameDiagramLoop2Level.setVisible(true);
            });
            frameDiagramLoop2Level.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameDiagramLoop2Level = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if (frameDiagramLoop1Level == null && plotData != null) {
            frameDiagramLoop1Level = new FrameDiagramLoopLevel();
            frameDiagramLoop1Level.initPlots(plotData, 1);
            java.awt.EventQueue.invokeLater(() -> {
                frameDiagramLoop1Level.setVisible(true);
            });
            frameDiagramLoop1Level.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameDiagramLoop1Level = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItemCondensationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCondensationActionPerformed
        // Check if there is already an active frame using the slected class
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Condensation")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelCondensation(), "Condensation");
    }//GEN-LAST:event_jMenuItemCondensationActionPerformed

    private void jMenuItemRecirculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRecirculationActionPerformed
        // Check if there is already an active frame using the slected class
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Recirculation")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelMCP(), "Recirculation");
    }//GEN-LAST:event_jMenuItemRecirculationActionPerformed

    private void jMenuItemFeedwaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFeedwaterActionPerformed
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Feedwater")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelFeedwater(), "Feedwater");
    }//GEN-LAST:event_jMenuItemFeedwaterActionPerformed

    private void jMenuItemMnemonicTurbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicTurbineActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicTurbine")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicTurbine());
    }//GEN-LAST:event_jMenuItemMnemonicTurbineActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuAboutActionPerformed

    private void jMenuAlarmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlarmsActionPerformed
        if (frameAlarms == null) {
            frameAlarms = new FrameAlarmTable();
            frameAlarms.registerActionReceiver(controller);
            // frameAlarms.setAlarmList(alarmList);
            java.awt.EventQueue.invokeLater(() -> {
                frameAlarms.setVisible(true);
            });
            frameAlarms.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameAlarms = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuAlarmsActionPerformed

    private void jMenuGlobalControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGlobalControlActionPerformed
        if (frameDiagramGlobalControl == null && plotData != null) {
            frameDiagramGlobalControl = new FrameDiagramGlobalControl();
            frameDiagramGlobalControl.initPlots(plotData, 0);
            java.awt.EventQueue.invokeLater(() -> {
                frameDiagramGlobalControl.setVisible(true);
            });
            frameDiagramGlobalControl.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameDiagramGlobalControl = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuGlobalControlActionPerformed

    private void jMenuItemMnemonicCondensationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicCondensationActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicCondensation")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicCondensation());
    }//GEN-LAST:event_jMenuItemMnemonicCondensationActionPerformed

    private void jMenuItemDeaeratorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeaeratorsActionPerformed
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Deaerators")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelDeaerators(), "Deaerators");
    }//GEN-LAST:event_jMenuItemDeaeratorsActionPerformed

    private void jMenuItemAuxCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAuxCondActionPerformed
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Aux. Condensation")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelAuxCondenser(), "Aux. Condensation");
    }//GEN-LAST:event_jMenuItemAuxCondActionPerformed

    private void jMenuItemBlowdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBlowdownActionPerformed
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Blowdown")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelBlowdown(), "Blowdown");
    }//GEN-LAST:event_jMenuItemBlowdownActionPerformed

    private void jMenuItemCoreControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCoreControlActionPerformed
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Reactor Controls")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelCoreControl(), "Reactor Controls");
    }//GEN-LAST:event_jMenuItemCoreControlActionPerformed

    private void jMenuItemPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPauseActionPerformed
        controller.userAction(new ActionCommand("PauseSimulation", null));
    }//GEN-LAST:event_jMenuItemPauseActionPerformed

    private void jMenuItemPresetFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPresetFullActionPerformed
        // Presents a view with all of the controls placed to a defined grid.
        // First, create all views if they are not yet open
        jMenuItemCoreControlActionPerformed(null);
        jMenuItemCondensationActionPerformed(null);
        jMenuItemRecirculationActionPerformed(null);
        jMenuItemFeedwaterActionPerformed(null);
        jMenuItemDeaeratorsActionPerformed(null);
        jMenuItemAuxCondActionPerformed(null);
        jMenuItemBlowdownActionPerformed(null);
        jMenuItemTurbineBypassActionPerformed(null);
        jMenuItemPreheatersActionPerformed(null);
        jMenuItemTurbineActionPerformed(null);
        jMenuItemGeneratorActionPerformed(null);
        //    jMenuItemCoolantActionPerformed(null);

        // Align them in a preset grid layout.
        // 1st row:
        jDesktopPane1.windowPlaceAtZero(
                getControlPanelInstance("Reactor Controls"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Blowdown"),
                getControlPanelInstance("Reactor Controls"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Turbine"),
                getControlPanelInstance("Blowdown"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Generator"),
                getControlPanelInstance("Turbine"));
        jDesktopPane1.windowPlaceBelow(
                getControlPanelInstance("Turbine Bypass"),
                getControlPanelInstance("Generator"));

        // 2nd row:
        jDesktopPane1.windowPlaceBelow(
                getControlPanelInstance("Recirculation"),
                getControlPanelInstance("Reactor Controls"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Feedwater"),
                getControlPanelInstance("Recirculation"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Deaerators"),
                getControlPanelInstance("Feedwater"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Condensation"),
                getControlPanelInstance("Deaerators"));

        // 3rd row:
        jDesktopPane1.windowPlaceBelow(
                getControlPanelInstance("Preheaters"),
                getControlPanelInstance("Recirculation"));
        jDesktopPane1.windowPlaceRightTo(
                getControlPanelInstance("Aux. Condensation"),
                getControlPanelInstance("Preheaters"));
    }//GEN-LAST:event_jMenuItemPresetFullActionPerformed

    private void jMenuItemPresetNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPresetNoneActionPerformed
        for (JInternalFrame f : jDesktopPane1.getAllFrames()) {
            f.setVisible(false);
            f.dispose();
            jDesktopPane1.remove(f);
        }
        jDesktopPane1.revalidate();
        jDesktopPane1.repaint();
        controlPanels.clear();
    }//GEN-LAST:event_jMenuItemPresetNoneActionPerformed

    private void jCheckBoxMenuOnlyCoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuOnlyCoreActionPerformed
        controller.userAction(new ActionCommand("SetCoreOnly", null));
        jCheckBoxMenuOnlyCore.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxMenuOnlyCoreActionPerformed

    private void jMenuItemTurbineBypassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurbineBypassActionPerformed
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Turbine Bypass")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelBypassValve(), "Turbine Bypass");
    }//GEN-LAST:event_jMenuItemTurbineBypassActionPerformed

    private void jMenuItemPreheatersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPreheatersActionPerformed
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Preheaters")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelPreheaters(), "Preheaters");
    }//GEN-LAST:event_jMenuItemPreheatersActionPerformed

    private void jMenuItemMnemonicPreheatersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicPreheatersActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicPreheaters")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicPreheaters());
    }//GEN-LAST:event_jMenuItemMnemonicPreheatersActionPerformed

    private void jMenuItemTurbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurbineActionPerformed
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Turbine")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelTurbine(), "Turbine");
    }//GEN-LAST:event_jMenuItemTurbineActionPerformed

    private void jMenuItemGeneratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGeneratorActionPerformed
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Generator")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelGenerator(), "Generator");
    }//GEN-LAST:event_jMenuItemGeneratorActionPerformed

    private void jMenuItemCoolantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCoolantActionPerformed
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals("Coolant")) {
                pf.toFront();
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new PanelCoolant(), "Coolant");
    }//GEN-LAST:event_jMenuItemCoolantActionPerformed

    private void jMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter(
                "Initial Conditions Files (*.ic)", "ic"));
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            
            // Append .ic if no extension was typed by the user
            if (!file.getName().contains(".")) {
                file = new File(file.getAbsolutePath() + ".ic");
            }
            
            // Warn before overwriting an existing file
            if (file.exists()) {
                int result = JOptionPane.showConfirmDialog(this,
                        "The file \"" + file.getName()
                        + "\" already exists.\nDo you want to replace it?",
                        "Confirm Save",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);
                if (result != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            controller.userAction(new ActionCommand(
                    "SaveSimulationState",
                    file.getAbsolutePath()));
        }
    }//GEN-LAST:event_jMenuSaveActionPerformed

    private void jMenuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoadActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter(
                "Initial Conditions Files (*.ic)", "ic"));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            controller.userAction(new ActionCommand(
                    "LoadSimulationState",
                    fc.getSelectedFile().getAbsolutePath()));
        }
    }//GEN-LAST:event_jMenuLoadActionPerformed

    @Override // Called on startup
    public void registerController(ViewerController controller) {
        this.controller = controller;
        // Use this event to display at least the core controls
        jMenuItemCoreControlActionPerformed(null);
    }

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        // Put all events on the log output for easier monitoring
        Logger.getLogger(ControlRoom.class.getName())
                .log(Level.INFO, "Received PropertyChangeEvent "
                        + evt.getPropertyName() + ", value: "
                        + evt.getNewValue());

        for (UpdateReceiver ur : mnemonics) {
            ur.updateComponent(evt);
        }

        for (UpdateReceiver ur : controlPanels) {
            ur.updateComponent(evt);
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        if (propertyName.equals("OutputValues")) {
            ((ValueHandler) newValue).fireAllToMvcView(this);

            plotData = (ValueHandler) newValue;
            if (frameDiagramNeutronFlux != null) {
                frameDiagramNeutronFlux.updatePlots();
            }
            if (frameDiagramDrums != null) {
                frameDiagramDrums.updatePlots();
            }
            if (frameDiagramLoop1Level != null) {
                frameDiagramLoop1Level.updatePlots();
            }
            if (frameDiagramLoop2Level != null) {
                frameDiagramLoop2Level.updatePlots();
            }
            if (frameDiagramGlobalControl != null) {
                frameDiagramGlobalControl.updatePlots();
            }

            // use this event to update the alarm list also.
            if (frameAlarms != null) {
                frameAlarms.setAlarms(alarmList);
            }
        }

        for (UpdateReceiver ur : mnemonics) {
            ur.updateComponent(propertyName, newValue);
        }

        for (UpdateReceiver ur : controlPanels) {
            ur.updateComponent(propertyName, newValue);
        }

        if (frameCoreActivity != null && propertyName.equals("CoreIndicator#1")) {
            frameCoreActivity.updateDisplay((CoreIndicator) newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        if (frameRodPositions != null) {
            frameRodPositions.updateComponent(propertyName, newValue);
        }

        for (UpdateReceiver ur : mnemonics) {
            ur.updateComponent(propertyName, newValue);
        }

        for (UpdateReceiver ur : controlPanels) {
            ur.updateComponent(propertyName, newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
        if (frameRodPositions != null) {
            frameRodPositions.updateComponent(propertyName, newValue);
        }

        for (UpdateReceiver ur : mnemonics) {
            ur.updateComponent(propertyName, newValue);
        }

        for (UpdateReceiver ur : controlPanels) {
            ur.updateComponent(propertyName, newValue);
        }
    }

    /**
     * Makes some initializations to the mnemonic frame object and add it to the
     * list to have a reference to the created instance.
     *
     * @param object JFrame object that implements UpdateReceiver
     */
    private void initializeMnemonic(UpdateReceiver object) {
        // cast to frame as the object is supposed to be an instace of frame.
        javax.swing.JFrame frame = (javax.swing.JFrame) object;
        controller.fireLastPropertyChangesTo(object);

        java.awt.EventQueue.invokeLater(() -> {
            frame.setVisible(true);
        });
        mnemonics.add(object);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                mnemonics.remove(object);
            }
        });
    }

    /**
     * Makes some initializations to an additional control panel frame object
     * (makes the controller instance known) and add it to the list to have a
     * reference to the created instance.
     *
     * @param object An instance that is the panel
     */
    private void initializeControlPanel(AbstractPanelWidget panel,
            String title) {
        // Generate a new JInteralFrame object (that will be the frame inside 
        // the desktop pane)
        ControlPanelFrame cpf = new ControlPanelFrame();
        // Give the generated Panel object to that frame and make it initialize 
        // itself
        cpf.initPanel(panel, title, controller);
        cpf.setVisible(true);
        jDesktopPane1.add(cpf);
        // The frame will automatically adjust its size due to its layout.

        // Remove it from the list of windows when closing:
        cpf.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                controlPanels.remove(cpf);
            }
        }
        );

        // Put it to front:
        try {
            cpf.setSelected(true);
        } catch (PropertyVetoException ex) {
            // ignore
        }
        cpf.toFront();
        // Add the frame to the list of active internal frames so the panel
        // frame will receive updates
        controlPanels.add(cpf);
        controller.fireLastPropertyChangesTo(panel);
    }

    private ControlPanelFrame getControlPanelInstance(String designator) {
        for (ControlPanelFrame pf : controlPanels) {
            if (pf.getPanelName().equals(designator)) {
                return pf;
            }
        }
        return null;
    }

    public void setAlarmList(List alarmList) {
        // Todo: maybe there's a better way of organizing this.
        this.alarmList = alarmList;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuOnlyCore;
    private com.hartrusion.util.JDesktopPaneEnhanced jDesktopPane1;
    private javax.swing.JMenuItem jMenuAbout;
    private javax.swing.JMenuItem jMenuAlarms;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuControls;
    private javax.swing.JMenuItem jMenuCoreMatrix;
    private javax.swing.JMenu jMenuDiagrams;
    private javax.swing.JMenuItem jMenuDrumSeparators;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuGlobalControl;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAuxCond;
    private javax.swing.JMenuItem jMenuItemBlowdown;
    private javax.swing.JMenuItem jMenuItemCondensation;
    private javax.swing.JMenuItem jMenuItemCoolant;
    private javax.swing.JMenuItem jMenuItemCore;
    private javax.swing.JMenuItem jMenuItemCoreControl;
    private javax.swing.JMenuItem jMenuItemDeaerators;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemFeedwater;
    private javax.swing.JMenuItem jMenuItemGenerator;
    private javax.swing.JMenuItem jMenuItemMnemonicAuxCondenser;
    private javax.swing.JMenuItem jMenuItemMnemonicBlowdown;
    private javax.swing.JMenuItem jMenuItemMnemonicCondensation;
    private javax.swing.JMenuItem jMenuItemMnemonicDeaerators;
    private javax.swing.JMenuItem jMenuItemMnemonicFeedwater;
    private javax.swing.JMenuItem jMenuItemMnemonicLoop1;
    private javax.swing.JMenuItem jMenuItemMnemonicLoop2;
    private javax.swing.JMenuItem jMenuItemMnemonicPreheaters;
    private javax.swing.JMenuItem jMenuItemMnemonicTurbine;
    private javax.swing.JMenuItem jMenuItemPause;
    private javax.swing.JMenuItem jMenuItemPreheaters;
    private javax.swing.JMenuItem jMenuItemPresetFull;
    private javax.swing.JMenuItem jMenuItemPresetNone;
    private javax.swing.JMenuItem jMenuItemRecirculation;
    private javax.swing.JMenuItem jMenuItemTurbine;
    private javax.swing.JMenuItem jMenuItemTurbineBypass;
    private javax.swing.JMenuItem jMenuLoad;
    private javax.swing.JMenu jMenuMnemonics;
    private javax.swing.JMenuItem jMenuNeutronFlux;
    private javax.swing.JMenu jMenuPanels;
    private javax.swing.JMenuItem jMenuRodPositions;
    private javax.swing.JMenuItem jMenuSave;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
