/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim;

import com.hartrusion.rbmksim.gui.diagrams.*;
import java.beans.PropertyChangeEvent;
import com.hartrusion.values.ValueHandler;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.InteractiveView;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.mvc.ViewerController;
import com.hartrusion.rbmksim.gui.*;
import com.hartrusion.rbmksim.gui.mnemonic.*;
import com.hartrusion.rbmksim.gui.widgets.AbstractPanelWidget;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * The main control panel that controls the simulation.
 *
 * @author Viktor Alexander Hartung
 */
public class ControlRoom extends javax.swing.JFrame
        implements InteractiveView {

    private ViewerController controller;

    private FrameRodPositions frameRodPositions;
    private FrameCoreActivity frameCoreActivity;
    private FrameAlarmTable frameAlarms;
    private List alarmList;

    private ValueHandler plotData;

    /**
     * Holds a list of all open control panel windows that are attached to this
     * control room instance directly.
     */
    private final List<ControlPanel> controlPanels = new ArrayList<>();

    /**
     * Creates new form ControlPanel
     */
    public ControlRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCaptionThermalPower2 = new javax.swing.JLabel();
        jLabelCaptionThermalPower1 = new javax.swing.JLabel();
        jLabelReadingThermalPower = new javax.swing.JLabel();
        jLabelCaptionThermalPowerUnit = new javax.swing.JLabel();
        jLabelReadingGeneratorPower = new javax.swing.JLabel();
        jLabelCaptionGeneratorPowerUnit = new javax.swing.JLabel();
        jLabelCaptionGeneratorPower2 = new javax.swing.JLabel();
        jLabelCaptionGenaratorPower1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemPause = new javax.swing.JMenuItem();
        jCheckBoxMenuOnlyCore = new javax.swing.JCheckBoxMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuLoad = new javax.swing.JMenuItem();
        jMenuSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuViews = new javax.swing.JMenu();
        jMenuItemNewPanel = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAlarms = new javax.swing.JMenuItem();
        jMenuItemRodPositions = new javax.swing.JMenuItem();
        jMenuItemCoreMatrix = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulation");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(190, 76));
        jPanel1.setMinimumSize(new java.awt.Dimension(190, 76));
        jPanel1.setPreferredSize(new java.awt.Dimension(190, 76));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCaptionThermalPower2.setFont(jLabelCaptionThermalPower2.getFont().deriveFont(jLabelCaptionThermalPower2.getFont().getSize()-2f));
        jLabelCaptionThermalPower2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCaptionThermalPower2.setText("Power");
        jLabelCaptionThermalPower2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionThermalPower2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionThermalPower2.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionThermalPower2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 52, -1, -1));

        jLabelCaptionThermalPower1.setFont(jLabelCaptionThermalPower1.getFont().deriveFont(jLabelCaptionThermalPower1.getFont().getSize()-2f));
        jLabelCaptionThermalPower1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCaptionThermalPower1.setText("Thermal");
        jLabelCaptionThermalPower1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionThermalPower1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionThermalPower1.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionThermalPower1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 40, -1, -1));

        jLabelReadingThermalPower.setBackground(new java.awt.Color(0, 0, 0));
        jLabelReadingThermalPower.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabelReadingThermalPower.setForeground(new java.awt.Color(255, 153, 0));
        jLabelReadingThermalPower.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingThermalPower.setText("_____");
        jLabelReadingThermalPower.setOpaque(true);
        jPanel1.add(jLabelReadingThermalPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 40, 76, 26));

        jLabelCaptionThermalPowerUnit.setFont(jLabelCaptionThermalPowerUnit.getFont().deriveFont(jLabelCaptionThermalPowerUnit.getFont().getSize()-2f));
        jLabelCaptionThermalPowerUnit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCaptionThermalPowerUnit.setText("MW");
        jLabelCaptionThermalPowerUnit.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionThermalPowerUnit.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionThermalPowerUnit.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionThermalPowerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 46, 26, -1));

        jLabelReadingGeneratorPower.setBackground(new java.awt.Color(0, 0, 0));
        jLabelReadingGeneratorPower.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabelReadingGeneratorPower.setForeground(new java.awt.Color(0, 255, 153));
        jLabelReadingGeneratorPower.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReadingGeneratorPower.setText("_____");
        jLabelReadingGeneratorPower.setOpaque(true);
        jPanel1.add(jLabelReadingGeneratorPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 6, 76, 26));

        jLabelCaptionGeneratorPowerUnit.setFont(jLabelCaptionGeneratorPowerUnit.getFont().deriveFont(jLabelCaptionGeneratorPowerUnit.getFont().getSize()-2f));
        jLabelCaptionGeneratorPowerUnit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCaptionGeneratorPowerUnit.setText("MW");
        jLabelCaptionGeneratorPowerUnit.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionGeneratorPowerUnit.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionGeneratorPowerUnit.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionGeneratorPowerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 12, 26, -1));

        jLabelCaptionGeneratorPower2.setFont(jLabelCaptionGeneratorPower2.getFont().deriveFont(jLabelCaptionGeneratorPower2.getFont().getSize()-2f));
        jLabelCaptionGeneratorPower2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCaptionGeneratorPower2.setText("Power");
        jLabelCaptionGeneratorPower2.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionGeneratorPower2.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionGeneratorPower2.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionGeneratorPower2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 18, -1, -1));

        jLabelCaptionGenaratorPower1.setFont(jLabelCaptionGenaratorPower1.getFont().deriveFont(jLabelCaptionGenaratorPower1.getFont().getSize()-2f));
        jLabelCaptionGenaratorPower1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCaptionGenaratorPower1.setText("Generator");
        jLabelCaptionGenaratorPower1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionGenaratorPower1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabelCaptionGenaratorPower1.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabelCaptionGenaratorPower1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 6, 62, -1));

        getContentPane().add(jPanel1);

        jMenuFile.setText("File");

        jMenuItemPause.setText("Pause Simulation");
        jMenuItemPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPauseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemPause);

        jCheckBoxMenuOnlyCore.setText("Simulate reactor only");
        jCheckBoxMenuOnlyCore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuOnlyCoreActionPerformed(evt);
            }
        });
        jMenuFile.add(jCheckBoxMenuOnlyCore);
        jMenuFile.add(jSeparator2);

        jMenuLoad.setText("Load");
        jMenuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoadActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuLoad);

        jMenuSave.setText("Save as...");
        jMenuSave.setToolTipText("");
        jMenuSave.setActionCommand("Save");
        jMenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuSave);
        jMenuFile.add(jSeparator1);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuViews.setText("Window");

        jMenuItemNewPanel.setText("New Panel Window");
        jMenuItemNewPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewPanelActionPerformed(evt);
            }
        });
        jMenuViews.add(jMenuItemNewPanel);
        jMenuViews.add(jSeparator3);

        jMenuItemAlarms.setText("Alarm List");
        jMenuItemAlarms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlarmsActionPerformed(evt);
            }
        });
        jMenuViews.add(jMenuItemAlarms);

        jMenuItemRodPositions.setText("Rod Positions");
        jMenuItemRodPositions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRodPositionsActionPerformed(evt);
            }
        });
        jMenuViews.add(jMenuItemRodPositions);

        jMenuItemCoreMatrix.setText("Core Matrix");
        jMenuItemCoreMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCoreMatrixActionPerformed(evt);
            }
        });
        jMenuViews.add(jMenuItemCoreMatrix);

        jMenuBar1.add(jMenuViews);

        jMenuHelp.setText("Help");

        jMenuAbout.setText("About");
        jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuAbout);

        jMenuItem2.setText("How to start");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItem2);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRodPositionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRodPositionsActionPerformed
        if (frameRodPositions == null) {
            frameRodPositions = new FrameRodPositions();
            java.awt.EventQueue.invokeLater(() -> {
                frameRodPositions.setVisible(true);
            });
            frameRodPositions.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameRodPositions = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuItemRodPositionsActionPerformed

    private void jMenuItemCoreMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCoreMatrixActionPerformed
        if (frameCoreActivity == null) {
            frameCoreActivity = new FrameCoreActivity();
            java.awt.EventQueue.invokeLater(() -> {
                frameCoreActivity.setVisible(true);
            });
            frameCoreActivity.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameCoreActivity = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuItemCoreMatrixActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuAboutActionPerformed

    private void jMenuItemAlarmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlarmsActionPerformed
        if (frameAlarms == null) {
            frameAlarms = new FrameAlarmTable();
            frameAlarms.registerActionReceiver(controller);
            // frameAlarms.setAlarmList(alarmList);
            java.awt.EventQueue.invokeLater(() -> {
                frameAlarms.setVisible(true);
            });
            frameAlarms.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameAlarms = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuItemAlarmsActionPerformed

    private void jMenuItemPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPauseActionPerformed
        controller.userAction(new ActionCommand("PauseSimulation", null));
    }//GEN-LAST:event_jMenuItemPauseActionPerformed

    private void jCheckBoxMenuOnlyCoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuOnlyCoreActionPerformed
        controller.userAction(new ActionCommand("SetCoreOnly", null));
        jCheckBoxMenuOnlyCore.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxMenuOnlyCoreActionPerformed

    private void jMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter(
                "Initial Conditions Files (*.ic)", "ic"));
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            // Append .ic if no extension was typed by the user
            if (!file.getName().contains(".")) {
                file = new File(file.getAbsolutePath() + ".ic");
            }

            // Warn before overwriting an existing file
            if (file.exists()) {
                int result = JOptionPane.showConfirmDialog(this,
                        "The file \"" + file.getName()
                        + "\" already exists.\nDo you want to replace it?",
                        "Confirm Save",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);
                if (result != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            controller.userAction(new ActionCommand(
                    "SaveSimulationState",
                    file.getAbsolutePath()));
        }
    }//GEN-LAST:event_jMenuSaveActionPerformed

    private void jMenuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoadActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter(
                "Initial Conditions Files (*.ic)", "ic"));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            controller.userAction(new ActionCommand(
                    "LoadSimulationState",
                    fc.getSelectedFile().getAbsolutePath()));
        }
    }//GEN-LAST:event_jMenuLoadActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        HowtoStartDialog dialog = new HowtoStartDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemNewPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewPanelActionPerformed
        // Generate a new control panel object and register it in the list of 
        // active panels.
        ControlPanel p = new ControlPanel();
        p.registerController(controller);
        p.setAlarmList(alarmList);
        p.setVisible(true); // we are on the EDT already
        controlPanels.add(p);
    }//GEN-LAST:event_jMenuItemNewPanelActionPerformed

    @Override // Called on startup
    public void registerController(ViewerController controller) {
        this.controller = controller;
        // Use this event to display at least the core controls
        // jMenuItemCoreControlActionPerformed(null);
    }

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        // Put all events on the log output for easier monitoring
        Logger.getLogger(ControlRoom.class.getName())
                .log(Level.INFO, "Received PropertyChangeEvent "
                        + evt.getPropertyName() + ", value: "
                        + evt.getNewValue());

        for (UpdateReceiver ur : controlPanels) {
            ur.updateComponent(evt);
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        if (propertyName.equals("OutputValues")) {
            ((ValueHandler) newValue).fireAllToMvcView(this);
            plotData = (ValueHandler) newValue;

            // use this event to update the alarm list also.
            if (frameAlarms != null) {
                frameAlarms.setAlarms(alarmList);
            }
        }

        for (UpdateReceiver ur : controlPanels) {
            ur.updateComponent(propertyName, newValue);
        }

        if (frameCoreActivity != null && propertyName.equals("CoreIndicator#1")) {
            frameCoreActivity.updateDisplay((CoreIndicator) newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        if (frameRodPositions != null) {
            frameRodPositions.updateComponent(propertyName, newValue);
        }

        for (UpdateReceiver ur : controlPanels) {
            ur.updateComponent(propertyName, newValue);
        }

        switch (propertyName) {
            case "Generator#Power" ->
                jLabelReadingGeneratorPower.setText(
                        String.format("%05d", Math.round(newValue)));
            case "Reactor#ThermalPowerDisplay" ->
                jLabelReadingThermalPower.setText(
                        String.format("%05d", Math.round(newValue)));
        }
        
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
        if (frameRodPositions != null) {
            frameRodPositions.updateComponent(propertyName, newValue);
        }

        for (UpdateReceiver ur : controlPanels) {
            ur.updateComponent(propertyName, newValue);
        }
    }

    public void setAlarmList(List alarmList) {
        // Todo: maybe there's a better way of organizing this.
        this.alarmList = alarmList;
    }
    
    public void openControlPanelWindow() {
        // TODO - to be replaced by a better strategy. 
        jMenuItemNewPanelActionPerformed(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuOnlyCore;
    private javax.swing.JLabel jLabelCaptionGenaratorPower1;
    private javax.swing.JLabel jLabelCaptionGeneratorPower2;
    private javax.swing.JLabel jLabelCaptionGeneratorPowerUnit;
    private javax.swing.JLabel jLabelCaptionThermalPower1;
    private javax.swing.JLabel jLabelCaptionThermalPower2;
    private javax.swing.JLabel jLabelCaptionThermalPowerUnit;
    private javax.swing.JLabel jLabelReadingGeneratorPower;
    private javax.swing.JLabel jLabelReadingThermalPower;
    private javax.swing.JMenuItem jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAlarms;
    private javax.swing.JMenuItem jMenuItemCoreMatrix;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemNewPanel;
    private javax.swing.JMenuItem jMenuItemPause;
    private javax.swing.JMenuItem jMenuItemRodPositions;
    private javax.swing.JMenuItem jMenuLoad;
    private javax.swing.JMenuItem jMenuSave;
    private javax.swing.JMenu jMenuViews;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
