/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim;

import java.beans.PropertyChangeEvent;
import com.hartrusion.control.FloatSeriesVault;
import com.hartrusion.control.ParameterHandler;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.InteractiveView;
import com.hartrusion.mvc.UpdateReceiver;
import com.hartrusion.mvc.ViewerController;
import com.hartrusion.rbmksim.gui.AboutDialog;
import com.hartrusion.rbmksim.gui.ControlPanelCondensation;
import com.hartrusion.rbmksim.gui.ControlPanelFeedwater;
import com.hartrusion.rbmksim.gui.ControlPanelRecirculation;
import com.hartrusion.rbmksim.gui.FrameCoreActivity;
import com.hartrusion.rbmksim.gui.FrameDiagramDrums;
import com.hartrusion.rbmksim.gui.FrameDiagramLoopLevel;
import com.hartrusion.rbmksim.gui.FrameDiagramNeutronFlux;
import com.hartrusion.rbmksim.gui.mnemonic.FrameMnemonicBlowdown;
import com.hartrusion.rbmksim.gui.mnemonic.FrameMnemonicLoop;
import com.hartrusion.rbmksim.gui.FrameRodPositions;
import com.hartrusion.rbmksim.gui.InteractiveComponent;
import com.hartrusion.rbmksim.gui.InterimAlarmList;
import com.hartrusion.rbmksim.gui.mnemonic.FrameMnemonicCore;
import com.hartrusion.rbmksim.gui.mnemonic.FrameMnemonicDeaerator;
import com.hartrusion.rbmksim.gui.mnemonic.FrameMnemonicFeedwater;
import com.hartrusion.rbmksim.gui.mnemonic.FrameMnemonicAuxiliaryCondenser;
import com.hartrusion.rbmksim.gui.mnemonic.FrameMnemonicTurbine;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class ControlPanel extends javax.swing.JFrame
        implements InteractiveView {

    private ViewerController controller;

    private FrameRodPositions frameRodPositions;
    private FrameCoreActivity frameCoreActivity;

    private FrameDiagramNeutronFlux frameDiagramNeutronFlux;
    private FrameDiagramDrums frameDiagramDrums;
    private FrameDiagramLoopLevel frameDiagramLoop1Level;
    private FrameDiagramLoopLevel frameDiagramLoop2Level;

    private InterimAlarmList frameAlarms;
    private List alarmList;

    private FloatSeriesVault plotData;

    /**
     * Holds a list of all interactive components which are active on the screen
     * to update them.
     */
    private final List<InteractiveComponent> components = new ArrayList<>();

    private final List<UpdateReceiver> mnemonics = new ArrayList<>();

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        panelRodSelector1 = new com.hartrusion.rbmksim.gui.PanelCoreControl();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemSetCoreOnly = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuPanels = new javax.swing.JMenu();
        jMenuAlarms = new javax.swing.JMenuItem();
        jMenuRodPositions = new javax.swing.JMenuItem();
        jMenuCoreMatrix = new javax.swing.JMenuItem();
        jMenuControls = new javax.swing.JMenu();
        jMenuItemRecirculation = new javax.swing.JMenuItem();
        jMenuItemFeedwater = new javax.swing.JMenuItem();
        jMenuItemCondensation = new javax.swing.JMenuItem();
        jMenuMnemonics = new javax.swing.JMenu();
        jMenuItemCore = new javax.swing.JMenuItem();
        jMenuItemBlowdown = new javax.swing.JMenuItem();
        jMenuItemMnemonicLoop1 = new javax.swing.JMenuItem();
        jMenuItemMnemonicLoop2 = new javax.swing.JMenuItem();
        jMenuItemMnemonicFeedwater = new javax.swing.JMenuItem();
        jMenuItemMnemonicDeaerators = new javax.swing.JMenuItem();
        jMenuItemMnemonicAuxCondenser = new javax.swing.JMenuItem();
        jMenuItemMnemonicTurbine = new javax.swing.JMenuItem();
        jMenuDiagrams = new javax.swing.JMenu();
        jMenuNeutronFlux = new javax.swing.JMenuItem();
        jMenuDrumSeparators = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenuItem();

        jMenuItem10.setText("jMenuItem10");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reactor Control Panel");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(panelRodSelector1);

        jMenuFile.setText("File");

        jMenuItemSetCoreOnly.setText("Set core only mode");
        jMenuItemSetCoreOnly.setToolTipText("Deactivates the connection between thermal systems and the core simulation.");
        jMenuItemSetCoreOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSetCoreOnlyActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSetCoreOnly);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuPanels.setText("Views");

        jMenuAlarms.setText("Alarm List");
        jMenuAlarms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlarmsActionPerformed(evt);
            }
        });
        jMenuPanels.add(jMenuAlarms);

        jMenuRodPositions.setText("Rod Positions");
        jMenuRodPositions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRodPositionsActionPerformed(evt);
            }
        });
        jMenuPanels.add(jMenuRodPositions);

        jMenuCoreMatrix.setText("Core Matrix");
        jMenuCoreMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCoreMatrixActionPerformed(evt);
            }
        });
        jMenuPanels.add(jMenuCoreMatrix);

        jMenuBar1.add(jMenuPanels);

        jMenuControls.setText("Control Panels");

        jMenuItemRecirculation.setText("Recirculation");
        jMenuItemRecirculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRecirculationActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemRecirculation);

        jMenuItemFeedwater.setText("Feedwater");
        jMenuItemFeedwater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFeedwaterActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemFeedwater);

        jMenuItemCondensation.setText("Condensation");
        jMenuItemCondensation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCondensationActionPerformed(evt);
            }
        });
        jMenuControls.add(jMenuItemCondensation);

        jMenuBar1.add(jMenuControls);

        jMenuMnemonics.setText("Mnemonic Displays");

        jMenuItemCore.setText("Core (Debug)");
        jMenuItemCore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCoreActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemCore);

        jMenuItemBlowdown.setText("Blowdown & Aftercooler");
        jMenuItemBlowdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBlowdownActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemBlowdown);

        jMenuItemMnemonicLoop1.setText("Loop 1");
        jMenuItemMnemonicLoop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicLoop1ActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicLoop1);

        jMenuItemMnemonicLoop2.setText("Loop 2");
        jMenuItemMnemonicLoop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicLoop2ActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicLoop2);

        jMenuItemMnemonicFeedwater.setText("Feedwater");
        jMenuItemMnemonicFeedwater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicFeedwaterActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicFeedwater);

        jMenuItemMnemonicDeaerators.setText("Deaerators");
        jMenuItemMnemonicDeaerators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicDeaeratorsActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicDeaerators);

        jMenuItemMnemonicAuxCondenser.setText("Auxiliary Condenser");
        jMenuItemMnemonicAuxCondenser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicAuxCondenserActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicAuxCondenser);

        jMenuItemMnemonicTurbine.setText("Turbine");
        jMenuItemMnemonicTurbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMnemonicTurbineActionPerformed(evt);
            }
        });
        jMenuMnemonics.add(jMenuItemMnemonicTurbine);

        jMenuBar1.add(jMenuMnemonics);

        jMenuDiagrams.setText("Diagrams");

        jMenuNeutronFlux.setText("Neutron Flux");
        jMenuNeutronFlux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNeutronFluxActionPerformed(evt);
            }
        });
        jMenuDiagrams.add(jMenuNeutronFlux);

        jMenuDrumSeparators.setText("Drum Separators");
        jMenuDrumSeparators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDrumSeparatorsActionPerformed(evt);
            }
        });
        jMenuDiagrams.add(jMenuDrumSeparators);

        jMenuItem8.setText("Loop 1 Level Control");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuDiagrams.add(jMenuItem8);

        jMenuItem9.setText("Loop 2 Level Control");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuDiagrams.add(jMenuItem9);

        jMenuBar1.add(jMenuDiagrams);

        jMenuHelp.setText("Help");

        jMenuAbout.setText("About");
        jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuRodPositionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRodPositionsActionPerformed
        if (frameRodPositions == null) {
            frameRodPositions = new FrameRodPositions();
            java.awt.EventQueue.invokeLater(() -> {
                frameRodPositions.setVisible(true);
            });
            frameRodPositions.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameRodPositions = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuRodPositionsActionPerformed

    private void jMenuCoreMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCoreMatrixActionPerformed
        if (frameCoreActivity == null) {
            frameCoreActivity = new FrameCoreActivity();
            java.awt.EventQueue.invokeLater(() -> {
                frameCoreActivity.setVisible(true);
            });
            frameCoreActivity.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameCoreActivity = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuCoreMatrixActionPerformed

    private void jMenuItemBlowdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBlowdownActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicBlowdown")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicBlowdown());
    }//GEN-LAST:event_jMenuItemBlowdownActionPerformed

    private void jMenuItemMnemonicLoop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicLoop1ActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicLoop")) {
                // there can be 2 instances of this Frame for both loops.
                if (((FrameMnemonicLoop) ur).getLoop() == 1) {
                    return;
                }
            }
        }
        // if theres no active frame, generate it and make it known here.
        FrameMnemonicLoop frame = new FrameMnemonicLoop();
        frame.setLoop(1);
        initializeMnemonic(frame);
    }//GEN-LAST:event_jMenuItemMnemonicLoop1ActionPerformed

    private void jMenuItemMnemonicLoop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicLoop2ActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicLoop")) {
                // there can be 2 instances of this Frame for both loops.
                if (((FrameMnemonicLoop) ur).getLoop() == 2) {
                    return;
                }
            }
        }
        // if theres no active frame, generate it and make it known here.
        FrameMnemonicLoop frame = new FrameMnemonicLoop();
        frame.setLoop(2);
        initializeMnemonic(frame);
    }//GEN-LAST:event_jMenuItemMnemonicLoop2ActionPerformed

    private void jMenuNeutronFluxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNeutronFluxActionPerformed
        if (frameDiagramNeutronFlux == null && plotData != null) {
            frameDiagramNeutronFlux = new FrameDiagramNeutronFlux();
            frameDiagramNeutronFlux.initPlots(plotData);
            java.awt.EventQueue.invokeLater(() -> {
                frameDiagramNeutronFlux.setVisible(true);
            });
            frameDiagramNeutronFlux.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameDiagramNeutronFlux = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuNeutronFluxActionPerformed

    private void jMenuItemMnemonicAuxCondenserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicAuxCondenserActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicAuxiliaryCondenser")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicAuxiliaryCondenser());
    }//GEN-LAST:event_jMenuItemMnemonicAuxCondenserActionPerformed

    private void jMenuItemCoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCoreActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicCore")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicCore());
    }//GEN-LAST:event_jMenuItemCoreActionPerformed

    private void jMenuItemMnemonicFeedwaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicFeedwaterActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicFeedwater")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicFeedwater());
    }//GEN-LAST:event_jMenuItemMnemonicFeedwaterActionPerformed

    private void jMenuItemMnemonicDeaeratorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicDeaeratorsActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicDeaerator")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicDeaerator());
    }//GEN-LAST:event_jMenuItemMnemonicDeaeratorsActionPerformed

    private void jMenuDrumSeparatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDrumSeparatorsActionPerformed
        if (frameDiagramDrums == null && plotData != null) {
            frameDiagramDrums = new FrameDiagramDrums();
            frameDiagramDrums.initPlots(plotData);
            java.awt.EventQueue.invokeLater(() -> {
                frameDiagramDrums.setVisible(true);
            });
            frameDiagramDrums.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameDiagramDrums = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuDrumSeparatorsActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if (frameDiagramLoop2Level == null && plotData != null) {
            frameDiagramLoop2Level = new FrameDiagramLoopLevel();
            frameDiagramLoop2Level.initPlots(plotData, 2);
            java.awt.EventQueue.invokeLater(() -> {
                frameDiagramLoop2Level.setVisible(true);
            });
            frameDiagramLoop2Level.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameDiagramLoop2Level = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if (frameDiagramLoop1Level == null && plotData != null) {
            frameDiagramLoop1Level = new FrameDiagramLoopLevel();
            frameDiagramLoop1Level.initPlots(plotData, 1);
            java.awt.EventQueue.invokeLater(() -> {
                frameDiagramLoop1Level.setVisible(true);
            });
            frameDiagramLoop1Level.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameDiagramLoop1Level = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItemCondensationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCondensationActionPerformed
        // Check if there is already an active frame using the slected class
        for (InteractiveComponent ic : components) {
            if (ic.getClass().getSimpleName().equals(
                    "ControlPanelCondensation")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new ControlPanelCondensation());
    }//GEN-LAST:event_jMenuItemCondensationActionPerformed

    private void jMenuItemRecirculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRecirculationActionPerformed
        // Check if there is already an active frame using the slected class
        for (InteractiveComponent ic : components) {
            if (ic.getClass().getSimpleName().equals(
                    "ControlPanelRecirculation")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new ControlPanelRecirculation());
    }//GEN-LAST:event_jMenuItemRecirculationActionPerformed

    private void jMenuItemFeedwaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFeedwaterActionPerformed
        // Check if there is already an active frame using the slected class
        for (InteractiveComponent ic : components) {
            if (ic.getClass().getSimpleName().equals(
                    "ControlPanelFeedwater")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeControlPanel(new ControlPanelFeedwater());
    }//GEN-LAST:event_jMenuItemFeedwaterActionPerformed

    private void jMenuItemMnemonicTurbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMnemonicTurbineActionPerformed
        // Check if there is already an active frame using the slected class
        for (UpdateReceiver ur : mnemonics) {
            if (ur.getClass().getSimpleName().equals(
                    "FrameMnemonicTurbine")) {
                return;
            }
        }
        // if theres no active frame, generate it and make it known here.
        initializeMnemonic(new FrameMnemonicTurbine());
    }//GEN-LAST:event_jMenuItemMnemonicTurbineActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemSetCoreOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSetCoreOnlyActionPerformed
        controller.userAction(new ActionCommand("SetCoreOnly", null));
    }//GEN-LAST:event_jMenuItemSetCoreOnlyActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuAboutActionPerformed

    private void jMenuAlarmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlarmsActionPerformed
        if (frameAlarms == null) {
            frameAlarms = new InterimAlarmList();
            frameAlarms.setAlarmList(alarmList);
            java.awt.EventQueue.invokeLater(() -> {
                frameAlarms.setVisible(true);
            });
            frameAlarms.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    frameAlarms = null;
                }
            });
        }
    }//GEN-LAST:event_jMenuAlarmsActionPerformed

    @Override // Called on startup
    public void registerController(ViewerController controller) {
        this.controller = controller;
        panelRodSelector1.registerActionReceiver(controller);
    }

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        // Put all events on the log output for easier monitoring
        Logger.getLogger(ControlPanel.class.getName())
                .log(Level.INFO, "Received PropertyChangeEvent "
                        + evt.getPropertyName() + ", value: "
                        + evt.getNewValue());

        panelRodSelector1.updateComponent(evt);

        for (UpdateReceiver ur : mnemonics) {
            ur.updateComponent(evt);
        }

        for (InteractiveComponent ic : components) {
            ic.updateComponent(evt);
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {
        if (propertyName.equals("OutputValues")) {
            ((ParameterHandler) newValue).fireAllToMvcView(this);
            return;
        }
        if (propertyName.equals("PlotData")) {
            plotData = (FloatSeriesVault) newValue;
            if (frameDiagramNeutronFlux != null) {
                frameDiagramNeutronFlux.updatePlots();
            }
            if (frameDiagramDrums != null) {
                frameDiagramDrums.updatePlots();
            }
            if (frameDiagramLoop1Level != null) {
                frameDiagramLoop1Level.updatePlots();
            }
            if (frameDiagramLoop2Level != null) {
                frameDiagramLoop2Level.updatePlots();
            }
            
            // use this event to update the alarm list also.
            if (frameAlarms != null) {
                frameAlarms.updateAlarmListModel();
            }
        }
        panelRodSelector1.updateComponent(propertyName, newValue);

        for (UpdateReceiver ur : mnemonics) {
            ur.updateComponent(propertyName, newValue);
        }

        for (InteractiveComponent ic : components) {
            ic.updateComponent(propertyName, newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        panelRodSelector1.updateComponent(propertyName, newValue);

        if (frameRodPositions != null) {
            frameRodPositions.updateComponent(propertyName, newValue);
        }

        for (UpdateReceiver ur : mnemonics) {
            ur.updateComponent(propertyName, newValue);
        }

        for (InteractiveComponent ic : components) {
            ic.updateComponent(propertyName, newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
        panelRodSelector1.updateComponent(propertyName, newValue);
        if (frameRodPositions != null) {
            frameRodPositions.updateComponent(propertyName, newValue);
        }

        for (UpdateReceiver ur : mnemonics) {
            ur.updateComponent(propertyName, newValue);
        }

        for (InteractiveComponent ic : components) {
            ic.updateComponent(propertyName, newValue);
        }
    }

    /**
     * Makes some initializations to the mnemonic frame object and add it to the
     * list to have a reference to the created instance.
     *
     * @param object JFrame object that implements UpdateReceiver
     */
    private void initializeMnemonic(UpdateReceiver object) {
        // cast to frame as the object is supposed to be an instace of frame.
        javax.swing.JFrame frame = (javax.swing.JFrame) object;
        controller.fireLastPropertyChangesTo(object);

        java.awt.EventQueue.invokeLater(() -> {
            frame.setVisible(true);
        });
        mnemonics.add(object);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                mnemonics.remove(object);
            }
        });
    }

    /**
     * Makes some initializations to an additonal control panel frame object
     * (makes the controller instance known) and add it to the list to have a
     * reference to the created instance.
     *
     * @param object JFrame object that implements UpdateReceiver
     */
    private void initializeControlPanel(InteractiveComponent object) {
        // cast to frame as the object is supposed to be an instace of frame.
        javax.swing.JFrame frame = (javax.swing.JFrame) object;
        object.registerActionReceiver(controller);
        controller.fireLastPropertyChangesTo(object);
        java.awt.EventQueue.invokeLater(() -> {
            frame.setVisible(true);
        });
        components.add(object);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                components.remove(object);
            }
        });
    }
    
    public void setAlarmList(List alarmList) {
        // Todo: maybe there's a better way of organizing this.
        this.alarmList = alarmList;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuAbout;
    private javax.swing.JMenuItem jMenuAlarms;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuControls;
    private javax.swing.JMenuItem jMenuCoreMatrix;
    private javax.swing.JMenu jMenuDiagrams;
    private javax.swing.JMenuItem jMenuDrumSeparators;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemBlowdown;
    private javax.swing.JMenuItem jMenuItemCondensation;
    private javax.swing.JMenuItem jMenuItemCore;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemFeedwater;
    private javax.swing.JMenuItem jMenuItemMnemonicAuxCondenser;
    private javax.swing.JMenuItem jMenuItemMnemonicDeaerators;
    private javax.swing.JMenuItem jMenuItemMnemonicFeedwater;
    private javax.swing.JMenuItem jMenuItemMnemonicLoop1;
    private javax.swing.JMenuItem jMenuItemMnemonicLoop2;
    private javax.swing.JMenuItem jMenuItemMnemonicTurbine;
    private javax.swing.JMenuItem jMenuItemRecirculation;
    private javax.swing.JMenuItem jMenuItemSetCoreOnly;
    private javax.swing.JMenu jMenuMnemonics;
    private javax.swing.JMenuItem jMenuNeutronFlux;
    private javax.swing.JMenu jMenuPanels;
    private javax.swing.JMenuItem jMenuRodPositions;
    private com.hartrusion.rbmksim.gui.PanelCoreControl panelRodSelector1;
    // End of variables declaration//GEN-END:variables
}
