/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.elements;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.beans.BeanProperty;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class ControlLoop extends javax.swing.JPanel {

    private final int[] outMajorTickX = {34, 44, 54, 64, 74, 84};
    private final int[] outMajorTickY
            = {36, 38, 40, 42, 46, 48, 50, 52, 56, 58, 60, 62, 66, 68, 70, 72,
            76, 78, 80, 82};
 
    private static final Color COLOR_DARKGREEN = new Color(0,128,0);

    private double outValue = 50;
    private int outValueXCoord = 45;
    
    private double value = 15;
    private int valueXCoord = 50;
    
    private double setpoint = 20;
    private int setpointXCoord = 60;
    
    private double minValue = 0, maxValue = 100;
    private double minOutValue = 0, maxOutValue = 100;

    /**
     * Creates new form LoopControl
     */
    public ControlLoop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDown = new javax.swing.JButton();
        jButtonAuto = new javax.swing.JButton();
        jButtonSetpoint = new javax.swing.JButton();
        jButtonHand = new javax.swing.JButton();
        jButtonUp = new javax.swing.JButton();

        setBackground(new java.awt.Color(205, 197, 170));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(140, 38));
        setMinimumSize(new java.awt.Dimension(140, 38));
        setPreferredSize(new java.awt.Dimension(140, 38));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDown.setBackground(new java.awt.Color(229, 229, 229));
        jButtonDown.setFont(jButtonDown.getFont().deriveFont(jButtonDown.getFont().getStyle() | java.awt.Font.BOLD, jButtonDown.getFont().getSize()-2));
        jButtonDown.setText("▼");
        jButtonDown.setToolTipText("");
        jButtonDown.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDown.setMaximumSize(new java.awt.Dimension(20, 16));
        jButtonDown.setMinimumSize(new java.awt.Dimension(20, 16));
        jButtonDown.setPreferredSize(new java.awt.Dimension(20, 16));
        jButtonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownActionPerformed(evt);
            }
        });
        add(jButtonDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 20, 20, 16));

        jButtonAuto.setBackground(new java.awt.Color(229, 229, 229));
        jButtonAuto.setText("A");
        jButtonAuto.setToolTipText("");
        jButtonAuto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAuto.setMaximumSize(new java.awt.Dimension(20, 16));
        jButtonAuto.setMinimumSize(new java.awt.Dimension(20, 16));
        jButtonAuto.setPreferredSize(new java.awt.Dimension(20, 16));
        jButtonAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoActionPerformed(evt);
            }
        });
        add(jButtonAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 2, 20, 16));

        jButtonSetpoint.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSetpoint.setText("S");
        jButtonSetpoint.setToolTipText("");
        jButtonSetpoint.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSetpoint.setMaximumSize(new java.awt.Dimension(20, 16));
        jButtonSetpoint.setMinimumSize(new java.awt.Dimension(20, 16));
        jButtonSetpoint.setPreferredSize(new java.awt.Dimension(20, 16));
        jButtonSetpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetpointActionPerformed(evt);
            }
        });
        add(jButtonSetpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 20, 20, 16));

        jButtonHand.setBackground(new java.awt.Color(229, 229, 229));
        jButtonHand.setText("H");
        jButtonHand.setToolTipText("");
        jButtonHand.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonHand.setMaximumSize(new java.awt.Dimension(20, 16));
        jButtonHand.setMinimumSize(new java.awt.Dimension(20, 16));
        jButtonHand.setPreferredSize(new java.awt.Dimension(20, 16));
        jButtonHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHandActionPerformed(evt);
            }
        });
        add(jButtonHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 20, 20, 16));

        jButtonUp.setBackground(new java.awt.Color(229, 229, 229));
        jButtonUp.setFont(jButtonUp.getFont().deriveFont(jButtonUp.getFont().getStyle() | java.awt.Font.BOLD, jButtonUp.getFont().getSize()-2));
        jButtonUp.setText("▲");
        jButtonUp.setToolTipText("");
        jButtonUp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonUp.setMaximumSize(new java.awt.Dimension(20, 16));
        jButtonUp.setMinimumSize(new java.awt.Dimension(20, 16));
        jButtonUp.setPreferredSize(new java.awt.Dimension(20, 16));
        jButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpActionPerformed(evt);
            }
        });
        add(jButtonUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 20, 16));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDownActionPerformed

    private void jButtonAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAutoActionPerformed

    private void jButtonSetpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetpointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSetpointActionPerformed

    private void jButtonHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHandActionPerformed

    private void jButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpActionPerformed


    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        // Upper display
        // A rectangle with a black frame
        g2.setColor(Color.WHITE);
        g2.fillRect(29, 3, 60, 15);
        g2.setColor(Color.BLACK);
        g2.drawRect(29, 3, 60, 15);
        
        // inner scale
        for (int xPos = 36; xPos < 83; xPos = xPos + 2) {
            g2.drawLine(xPos, 10, xPos, 11);
        }
        // Scale ends
        g2.drawLine(34, 8, 34, 13);
        g2.drawLine(84, 8, 84, 13);
        
        // Reference value marker from above
         g2.setColor(COLOR_DARKGREEN);
        g2.drawLine(valueXCoord, 4, valueXCoord, 8);
        
        // Setpoint marker from below
        g2.setColor(Color.RED);
        g2.drawLine(setpointXCoord, 13, setpointXCoord, 17);
        
        // Lower display
        // A rectangle with a black frame
        g2.setColor(Color.WHITE);
        g2.fillRect(29, 21, 60, 13);
        g2.setColor(Color.BLACK);
        g2.drawRect(29, 21, 60, 13);
        // Major tick lines
        for (int idx = 0; idx < outMajorTickX.length; idx++) {
            g2.drawLine(outMajorTickX[idx], 29,
                    outMajorTickX[idx], 32);
        }
        // Minor tick lines
        for (int idx = 0; idx < outMajorTickY.length; idx++) {
            g2.drawLine(outMajorTickY[idx], 31,
                    outMajorTickY[idx], 32);
        }
        // Value marker
        g2.setColor(Color.BLUE);
        g2.drawLine(outValueXCoord, 21, outValueXCoord, 26);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAuto;
    private javax.swing.JButton jButtonDown;
    private javax.swing.JButton jButtonHand;
    private javax.swing.JButton jButtonSetpoint;
    private javax.swing.JButton jButtonUp;
    // End of variables declaration//GEN-END:variables

    
    public double getValue() {
        return value;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Current value to display")
    public void setValue(double value) {
        double old = this.value;
        this.value = value;
        firePropertyChange("value", old, value);
    }
    
    public double getSetpoint() {
        return setpoint;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Setpoint value to display")
    public void setSetpoint(double setpoint) {
        double old = this.setpoint;
        this.setpoint = setpoint;
        firePropertyChange("setpoint", old, setpoint);
    }
      
    public double getMinValue() {
        return minValue;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Scale begin for value and setpoint")
    public void setMinValue(double minValue) {
        double old = this.minValue;
        this.minValue = minValue;
        firePropertyChange("minValue", old, minValue);
    }

    public double getMaxValue() {
        return maxValue;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Scale end for value and setpoint")
    public void setMaxValue(double maxValue) {
        double old = this.maxValue;
        this.maxValue = maxValue;
        firePropertyChange("maxValue", old, maxValue);
    }
    
    public double getOutValue() {
        return outValue;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Output value to display")
    public void setOutValue(double outValue) {
        double old = this.outValue;
        this.outValue = outValue;
        firePropertyChange("outValue", old, outValue);
    }

    public double getMinOutValue() {
        return minOutValue;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Value for scale beginning of output value")
    public void setMinOutValue(double minOutValue) {
        double old = this.minOutValue;
        this.minOutValue = minOutValue;
        firePropertyChange("minOutValue", old, minOutValue);
    }

    public double getMaxOutValue() {
        return maxOutValue;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Value for scale end of output value")
    public void setMaxOutValue(double maxOutValue) {
        double old = this.maxOutValue;
        this.maxOutValue = maxOutValue;
        firePropertyChange("maxOutValue", old, maxOutValue);
    }
}
