/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.elements;

import com.hartrusion.control.ControlCommand;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import java.beans.BeanProperty;
import java.beans.PropertyChangeEvent;

/**
 * A small widget that allows controlling a control loop with a few buttons. It
 * displays the current setpoint, current value and the output value. Setpoint
 * and value have same units and scale and are displayed on one display, the
 * output can (and will most likely be) a different value with different scale
 * and has its own display.
 * <p>
 * There are two buttons for up/down, one button that toggles between setpoint
 * and output setting for the up and down buttons and two buttons to trigger
 * manual or automatic mode.
 *
 * @author Viktor Alexander Hartung
 */
public class ControlLoop extends javax.swing.JPanel
        implements UpdateReceiver {
    
    protected static final Color DARKRED = new Color(128, 0, 0);
    protected static final Color RED = new Color(255, 0, 0);

    protected ActionReceiver controller;

    private final int[] outMajorTickX = {34, 44, 54, 64, 74, 84};
    private final int[] outMajorTickY
            = {36, 38, 40, 42, 46, 48, 50, 52, 56, 58, 60, 62, 66, 68, 70, 72,
                76, 78, 80, 82};

    private static final Color COLOR_DARKGREEN = new Color(0, 128, 0);

    private double outValue = 50;
    private int outValueXCoord = 45;

    private double value = 15;
    private int valueXCoord = 50;

    private double setpoint = 20;
    private int setpointXCoord = 60;

    private double minValue = 0, maxValue = 100;
    private double minOutValue = 0, maxOutValue = 100;

    // parameters for calculation of X-coodinates from values
    private double mVal = 0.5, bVal = 34, mOut = 0.5, bOut = 34;
    
    private boolean indicatorActive = false;

    private String component = "undefined";
    private String actionCommand = "undefinedControlCommand";
    private String setpointCommand = "undefinedSetpoint";
    private String componentControlState = "undefinedControlState";

    private boolean setpointSelected;

    public String getComponent() {
        return component;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "String identification of the component")
    public void setComponent(String component) {
        String old = this.component;
        this.component = component;
        // build component identification strings
        actionCommand = component + "ControlCommand";
        setpointCommand = component + "Setpoint";
        componentControlState = component + "ControlState";
        // componentUpdateValue = component + "ControlUpdateU";
        firePropertyChange("component", old, component);
    }

    public void registerActionReceiver(ActionReceiver controller) {
        this.controller = controller;
    }

    /**
     * Creates new form LoopControl
     */
    public ControlLoop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDown = new javax.swing.JButton();
        jButtonAuto = new javax.swing.JButton();
        jButtonSetpoint = new javax.swing.JButton();
        jButtonHand = new javax.swing.JButton();
        jButtonUp = new javax.swing.JButton();

        setBackground(new java.awt.Color(205, 197, 170));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(140, 38));
        setMinimumSize(new java.awt.Dimension(140, 38));
        setPreferredSize(new java.awt.Dimension(140, 38));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDown.setBackground(new java.awt.Color(229, 229, 229));
        jButtonDown.setFont(jButtonDown.getFont().deriveFont(jButtonDown.getFont().getStyle() | java.awt.Font.BOLD, jButtonDown.getFont().getSize()-2));
        jButtonDown.setText("▼");
        jButtonDown.setToolTipText("");
        jButtonDown.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDown.setMaximumSize(new java.awt.Dimension(20, 16));
        jButtonDown.setMinimumSize(new java.awt.Dimension(20, 16));
        jButtonDown.setPreferredSize(new java.awt.Dimension(20, 16));
        jButtonDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonDownMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonDownMouseReleased(evt);
            }
        });
        add(jButtonDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 20, 20, 16));

        jButtonAuto.setBackground(new java.awt.Color(229, 229, 229));
        jButtonAuto.setText("A");
        jButtonAuto.setToolTipText("");
        jButtonAuto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAuto.setMaximumSize(new java.awt.Dimension(20, 16));
        jButtonAuto.setMinimumSize(new java.awt.Dimension(20, 16));
        jButtonAuto.setPreferredSize(new java.awt.Dimension(20, 16));
        jButtonAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoActionPerformed(evt);
            }
        });
        add(jButtonAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 2, 20, 16));

        jButtonSetpoint.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSetpoint.setText("S");
        jButtonSetpoint.setToolTipText("");
        jButtonSetpoint.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSetpoint.setMaximumSize(new java.awt.Dimension(20, 16));
        jButtonSetpoint.setMinimumSize(new java.awt.Dimension(20, 16));
        jButtonSetpoint.setPreferredSize(new java.awt.Dimension(20, 16));
        jButtonSetpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetpointActionPerformed(evt);
            }
        });
        add(jButtonSetpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 20, 20, 16));

        jButtonHand.setBackground(new java.awt.Color(229, 229, 229));
        jButtonHand.setText("H");
        jButtonHand.setToolTipText("");
        jButtonHand.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonHand.setMaximumSize(new java.awt.Dimension(20, 16));
        jButtonHand.setMinimumSize(new java.awt.Dimension(20, 16));
        jButtonHand.setPreferredSize(new java.awt.Dimension(20, 16));
        jButtonHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHandActionPerformed(evt);
            }
        });
        add(jButtonHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 20, 20, 16));

        jButtonUp.setBackground(new java.awt.Color(229, 229, 229));
        jButtonUp.setFont(jButtonUp.getFont().deriveFont(jButtonUp.getFont().getStyle() | java.awt.Font.BOLD, jButtonUp.getFont().getSize()-2));
        jButtonUp.setText("▲");
        jButtonUp.setToolTipText("");
        jButtonUp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonUp.setMaximumSize(new java.awt.Dimension(20, 16));
        jButtonUp.setMinimumSize(new java.awt.Dimension(20, 16));
        jButtonUp.setPreferredSize(new java.awt.Dimension(20, 16));
        jButtonUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonUpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonUpMouseReleased(evt);
            }
        });
        add(jButtonUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 20, 16));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoActionPerformed
        controller.userAction(new ActionCommand(actionCommand,
                ControlCommand.AUTOMATIC));
    }//GEN-LAST:event_jButtonAutoActionPerformed

    private void jButtonSetpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetpointActionPerformed
        setpointSelected = !setpointSelected;
        if (setpointSelected) {
            jButtonSetpoint.setBackground(RED);
        } else {
            jButtonSetpoint.setBackground(DARKRED);
        }
    }//GEN-LAST:event_jButtonSetpointActionPerformed

    private void jButtonHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHandActionPerformed
        controller.userAction(new ActionCommand(actionCommand,
                ControlCommand.MANUAL_OPERATION));
    }//GEN-LAST:event_jButtonHandActionPerformed

    private void jButtonUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpMousePressed
        if (setpointSelected) {
            controller.userAction(new ActionCommand(setpointCommand,
                    ControlCommand.SETPOINT_INCREASE));
        } else {
            controller.userAction(new ActionCommand(actionCommand,
                    ControlCommand.OUTPUT_INCREASE));
        }
    }//GEN-LAST:event_jButtonUpMousePressed

    private void jButtonUpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpMouseReleased
        if (setpointSelected) {
            controller.userAction(new ActionCommand(setpointCommand,
                    ControlCommand.SETPOINT_STOP));
        } else {
            controller.userAction(new ActionCommand(actionCommand,
                    ControlCommand.OUTPUT_CONTINUE));
        }
    }//GEN-LAST:event_jButtonUpMouseReleased

    private void jButtonDownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDownMousePressed
        if (setpointSelected) {
            controller.userAction(new ActionCommand(setpointCommand,
                    ControlCommand.SETPOINT_DECREASE));
        } else {
            controller.userAction(new ActionCommand(actionCommand,
                    ControlCommand.OUTPUT_DECREASE));
        }
    }//GEN-LAST:event_jButtonDownMousePressed

    private void jButtonDownMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDownMouseReleased
        if (setpointSelected) {
            controller.userAction(new ActionCommand(setpointCommand,
                    ControlCommand.SETPOINT_STOP));
        } else {
            controller.userAction(new ActionCommand(actionCommand,
                    ControlCommand.OUTPUT_CONTINUE));
        }
    }//GEN-LAST:event_jButtonDownMouseReleased

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        
        Object prevHint = g2.getRenderingHint(RenderingHints.KEY_ANTIALIASING);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        
        // Upper display
        // A rectangle with a black frame
        g2.setColor(Color.WHITE);
        g2.fillRect(29, 3, 60, 15);
        g2.setColor(Color.BLACK);
        g2.drawRect(29, 3, 60, 15);

        // inner scale
        for (int xPos = 36; xPos < 83; xPos = xPos + 2) {
            g2.drawLine(xPos, 10, xPos, 11);
        }
        // Scale ends
        g2.drawLine(34, 8, 34, 13);
        g2.drawLine(84, 8, 84, 13);

        // Reference value marker from above
        g2.setColor(COLOR_DARKGREEN);
        g2.drawLine(valueXCoord, 4, valueXCoord, 8);

        // Setpoint marker from below
        g2.setColor(Color.RED);
        g2.drawLine(setpointXCoord, 13, setpointXCoord, 17);

        // Lower display
        // A rectangle with a black frame
        g2.setColor(Color.WHITE);
        g2.fillRect(29, 21, 60, 13);
        g2.setColor(Color.BLACK);
        g2.drawRect(29, 21, 60, 13);
        // Major tick lines
        for (int idx = 0; idx < outMajorTickX.length; idx++) {
            g2.drawLine(outMajorTickX[idx], 29,
                    outMajorTickX[idx], 32);
        }
        // Minor tick lines
        for (int idx = 0; idx < outMajorTickY.length; idx++) {
            g2.drawLine(outMajorTickY[idx], 31,
                    outMajorTickY[idx], 32);
        }
        // Value marker
        g2.setColor(Color.BLUE);
        g2.drawLine(outValueXCoord, 21, outValueXCoord, 26);
        
        // A small indicator light, same as on the IntegralSwitch class
        Ellipse2D.Float circle;
        if (indicatorActive) {
            g2.setColor(Color.WHITE);
        } else {
            g2.setColor(Color.GRAY);
        }
        
        circle = new Ellipse2D.Float(102, 4, 6, 6);
        g2.fill(circle);
        // Draw the outer ring using foreground color.
        g2.setColor(getForeground());
        g2.draw(circle);
        
        // Reset the antialiasing to its previous value
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, prevHint);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAuto;
    private javax.swing.JButton jButtonDown;
    private javax.swing.JButton jButtonHand;
    private javax.swing.JButton jButtonSetpoint;
    private javax.swing.JButton jButtonUp;
    // End of variables declaration//GEN-END:variables

    public double getValue() {
        return value;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Current value to display")
    public void setValue(double value) {
        if (value > maxValue) {
            value = maxValue;
        } else if (value < minValue) {
            value = minValue;
        }
        double old = this.value;
        this.value = value;
        if (old != value) {
            valueXCoord = (int) (mVal * value + bVal);
            firePropertyChange("value", old, value);
            repaint();
        }

    }

    public double getSetpoint() {
        return setpoint;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Setpoint value to display")
    public void setSetpoint(double setpoint) {
        if (setpoint > maxValue) {
            setpoint = maxValue;
        } else if (setpoint < minValue) {
            setpoint = minValue;
        }
        double old = this.setpoint;
        this.setpoint = setpoint;
        if (old != setpoint) {
            setpointXCoord = (int) (mVal * setpoint + bVal);
            firePropertyChange("setpoint", old, setpoint);
            repaint();
        }
    }

    public double getMinValue() {
        return minValue;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Scale begin for value and setpoint")
    public void setMinValue(double minValue) {
        double old = this.minValue;
        this.minValue = minValue;
        if (minValue != maxValue) { // prevent div/0
            mVal = 50.0 / (maxValue - minValue);
            bVal = 84.0 - mVal * maxValue;
        }
        firePropertyChange("minValue", old, minValue);
    }

    public double getMaxValue() {
        return maxValue;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Scale end for value and setpoint")
    public void setMaxValue(double maxValue) {
        double old = this.maxValue;
        this.maxValue = maxValue;
        if (minValue != maxValue) { // prevent div/0
            mVal = 50.0 / (maxValue - minValue);
            bVal = 84.0 - mVal * maxValue;
        }
        firePropertyChange("maxValue", old, maxValue);
    }

    public double getOutValue() {
        return outValue;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Output value to display")
    public void setOutValue(double outValue) {
        if (outValue > maxOutValue) {
            outValue = maxOutValue;
        } else if (outValue < minOutValue) {
            outValue = minOutValue;
        }
        double old = this.outValue;
        this.outValue = outValue;
        if (old != outValue) {
            outValueXCoord = (int) (mOut * outValue + bOut);
            firePropertyChange("outValue", old, outValue);
            repaint();
        }

    }

    public double getMinOutValue() {
        return minOutValue;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Value for scale beginning of output value")
    public void setMinOutValue(double minOutValue) {
        double old = this.minOutValue;
        this.minOutValue = minOutValue;
        if (minOutValue != maxOutValue) { // prevent div/0
            mOut = 50.0 / (maxOutValue - minOutValue);
            bOut = 84.0 - mOut * maxOutValue;
        }
        firePropertyChange("minOutValue", old, minOutValue);
    }

    public double getMaxOutValue() {
        return maxOutValue;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Value for scale end of output value")
    public void setMaxOutValue(double maxOutValue) {
        double old = this.maxOutValue;
        this.maxOutValue = maxOutValue;
        if (minOutValue != maxOutValue) { // prevent div/0
            mOut = 50.0 / (maxOutValue - minOutValue);
            bOut = 84.0 - mOut * maxOutValue;
        }
        firePropertyChange("maxOutValue", old, maxOutValue);
    }
    
    public boolean getIndicatorActive() {
        return indicatorActive;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "State of the small indicator light bulb")
    public void setIndicatorActive(boolean indicatorActive) {
        boolean old = this.indicatorActive;
        this.indicatorActive = indicatorActive;
        if (old != indicatorActive) {
            firePropertyChange("indicatorActive", old, maxOutValue);
            repaint();
        }
        
    }

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(componentControlState)) {
            switch ((ControlCommand) evt.getNewValue()) {
                case AUTOMATIC:
                    setIndicatorActive(true);
                    break;
                case MANUAL_OPERATION:
                    setIndicatorActive(false);
                    break;
            }
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        if (propertyName.equals(component)) {
            setOutValue(newValue);
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
