/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.elements;

import com.hartrusion.control.ControlCommand;
import static com.hartrusion.control.ControlCommand.AUTOMATIC;
import static com.hartrusion.control.ControlCommand.MANUAL_OPERATION;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import java.beans.BeanProperty;
import java.beans.PropertyChangeEvent;
import com.hartrusion.control.ValveState;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import static java.awt.Color.GRAY;
import static java.awt.Color.WHITE;

/**
 * A panel containing two switches mainly used for manually opening and closing
 * valves with valve stop when button is released. It is called integral as the
 * valves position will be the integral of the button state.
 *
 * <p>
 * Intended as a GUI component for HeatValve class, the Strings therefore must
 * match those which are defined in this class and the monitors events.
 *
 * <p>
 * A valve has usually a ValveActuatorMonitor attached, this monitor will fire a
 * property change event that can be directed to this UpdateReceiver here. The
 * _Pos property will then be used to set the red and green lights on top of the
 * buttons.
 *
 * @author Viktor Alexander Hartung
 */
public class IntegralSwitchLoop extends javax.swing.JPanel
        implements UpdateReceiver {

    protected ActionReceiver controller;

    protected static final Color GREEN = new Color(0, 128, 0);
    protected static final Color LIME = new Color(0, 255, 0);
    protected static final Color DARKRED = new Color(128, 0, 0);
    protected static final Color RED = new Color(255, 0, 0);

    /**
     * Identifies all incoming and outgoing events, can be something like
     * "Blowdown#ValveCoolant".
     */
    private String component = "null";
    private String componentPos = "null_Pos";
    private String actionCommand = "undefinedControlCommand";
    private String componentControlState = "undefinedControlState";

    private boolean indicatorClosedActive;
    private boolean indicatorOpenActive;
    private boolean indicatorAutoActive;

    public String getComponent() {
        return component;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "String identification of the component")
    public void setComponent(String component) {
        String old = this.component;
        this.component = component;
        componentPos = component + "_Pos";
        actionCommand = component + "ControlCommand";
        componentControlState = component + "ControlState";
        firePropertyChange("component", old, component);
    }

    public void registerActionReceiver(ActionReceiver controller) {
        this.controller = controller;
    }

    /**
     * Creates new form IntegralSwitch
     */
    public IntegralSwitchLoop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPos = new javax.swing.JButton();
        jButtonNeg = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPos.setText(">");
        jButtonPos.setToolTipText("");
        jButtonPos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonPos.setPreferredSize(new java.awt.Dimension(18, 22));
        jButtonPos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonPosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonPosMouseReleased(evt);
            }
        });
        add(jButtonPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 8, 18, 18));

        jButtonNeg.setText("<");
        jButtonNeg.setToolTipText("");
        jButtonNeg.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonNeg.setPreferredSize(new java.awt.Dimension(18, 22));
        jButtonNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonNegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonNegMouseReleased(evt);
            }
        });
        add(jButtonNeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 8, 18, 18));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPosMousePressed
        controller.userAction(new ActionCommand(actionCommand,
                ControlCommand.OUTPUT_INCREASE));
    }//GEN-LAST:event_jButtonPosMousePressed

    private void jButtonPosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPosMouseReleased
        controller.userAction(new ActionCommand(actionCommand,
                ControlCommand.OUTPUT_CONTINUE));
    }//GEN-LAST:event_jButtonPosMouseReleased

    private void jButtonNegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNegMousePressed
        controller.userAction(new ActionCommand(actionCommand,
                ControlCommand.OUTPUT_DECREASE));
    }//GEN-LAST:event_jButtonNegMousePressed

    private void jButtonNegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNegMouseReleased
        controller.userAction(new ActionCommand(actionCommand,
                ControlCommand.OUTPUT_CONTINUE));
    }//GEN-LAST:event_jButtonNegMouseReleased

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        // Theres a 8 px spacing above the buttons. paint two circles there to 
        // indicate full open or full closed position.
        // Force the use of antialiasing to not look like 1997
        Object prevHint = g2d.getRenderingHint(RenderingHints.KEY_ANTIALIASING);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        
        // Left indicator - Draw background in set color
        Ellipse2D.Float circle;
        if (indicatorClosedActive) {
            g2d.setColor(LIME);
        } else {
            g2d.setColor(GREEN);
        }
        circle = new Ellipse2D.Float(6, 0, 6, 6);
        g2d.fill(circle);
        // Draw the outer ring using foreground color.
        g2d.setColor(getForeground());
        g2d.draw(circle);
        
        // Middle indicator
        if (indicatorAutoActive) {
            g2d.setColor(WHITE);
        } else {
            g2d.setColor(GRAY);
        }
        circle = new Ellipse2D.Float(15, 0, 6, 6);
        g2d.fill(circle);
        // Draw the outer ring using foreground color.
        g2d.setColor(getForeground());
        g2d.draw(circle);
        
        // Right indicator - Draw background in set color
        if (indicatorOpenActive) {
            g2d.setColor(RED);
        } else {
            g2d.setColor(DARKRED);
        }
        circle = new Ellipse2D.Float(24, 0, 6, 6);
        g2d.fill(circle);
        // Draw the outer ring using foreground color.
        g2d.setColor(getForeground());
        g2d.draw(circle);
        
        
        // Reset the antialiasing to its previous value
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, prevHint);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNeg;
    private javax.swing.JButton jButtonPos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(componentPos)) {
            switch ((ValveState) evt.getNewValue()) {
                case CLOSED:
                    indicatorClosedActive = true;
                    indicatorOpenActive = false;
                    break;
                case INTERMEDIATE:
                    indicatorClosedActive = false;
                    indicatorOpenActive = false;
                    break;
                case OPEN:
                    indicatorClosedActive = false;
                    indicatorOpenActive = true;
                    break;
            }
            repaint();
        }
        if (evt.getPropertyName().equals(componentControlState)) {
            switch ((ControlCommand) evt.getNewValue()) {
                case AUTOMATIC:
                    indicatorAutoActive = true;
                    break;
                case MANUAL_OPERATION:
                    indicatorAutoActive = false;
                    break;
            }
            repaint();
        }
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {

    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {

    }
}
