/*
 * Copyright (C) 2026 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.elements;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import java.beans.BeanProperty;

/**
 * Draws a light bulb object, that is basically a filled circle that can switch
 * its colors.
 * <p>
 * It is filled with the foreground color when active and with a dimmed variant
 * of that color when inactive.
 * <p>
 * The outline is drawn in background color.
 *
 * @author Viktor Alexander Hartung
 */
public class LightBulb extends javax.swing.JComponent {

    private boolean active;

    /**
     * Holds the color for inactive light bulb.
     */
    private Color dimmed;

    /**
     * Diameter in pixels
     */
    private float size = 6;

    /**
     * Creates new form LightBulb
     */
    public LightBulb() {
        setForeground(new Color(255, 255, 255)); // default white
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(7, 7));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(7, 7));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    // Overwrite to calculate the own inactive color from foreground on calling
    // set operation
    @Override
    public void setForeground(Color fg) {
        super.setForeground(fg);
        dimmed = halfBrightness(getForeground());
    }

    public boolean isActive() {
        return active;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Switches to the foreground color")
    public void setActive(boolean active) {
        if (this.active != active) {
            this.active = active;
            repaint();
        }
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        // Force the use of antialiasing to not look like 1997
        Object prevHint = g2d.getRenderingHint(RenderingHints.KEY_ANTIALIASING);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);

        size = (float) Math.min(getWidth()-1, getHeight()-1);

        // Draw background in set color
        Ellipse2D.Float circle;
        if (active) {
            g2d.setColor(getForeground());
        } else {
            g2d.setColor(dimmed);
        }
        circle = new Ellipse2D.Float(0, 0, size, size);
        g2d.fill(circle);
        // Draw the outer ring using background color.
        g2d.setColor(getBackground());
        g2d.draw(circle);
    }

    public static Color halfBrightness(Color color) {
        if (color == null) {
            return null;
        }
        int r = color.getRed() >> 1; // entspricht r / 2 
        int g = color.getGreen() >> 1; // entspricht g / 2 
        int b = color.getBlue() >> 1; // entspricht b / 2 
        return new Color(r, g, b, color.getAlpha());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
