/*
 * Copyright (C) 2025 Viktor Alexander Hartung
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.hartrusion.rbmksim.gui.elements;

import com.hartrusion.control.ControlCommand;
import com.hartrusion.mvc.ActionCommand;
import com.hartrusion.mvc.ActionReceiver;
import com.hartrusion.mvc.UpdateReceiver;
import java.beans.BeanProperty;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Viktor Alexander Hartung
 */
public class SetpointControl extends javax.swing.JPanel
        implements UpdateReceiver {

    protected ActionReceiver controller;

    private String component = "undefined";
    private String displayFormat = "%.1f";

    public String getComponent() {
        return component;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "String identification of the component")
    public void setComponent(String component) {
        String old = this.component;
        this.component = component;
        // componentUpdateValue = component + "ControlUpdateU";
        firePropertyChange("component", old, component);
    }
    
    public String getFormat() {
        return displayFormat;
    }

    @BeanProperty(preferred = true, visualUpdate = true, description
            = "Display format")
    public void setFormat(String displayFormat) {
        String old = this.displayFormat;
        this.displayFormat = displayFormat;
        // componentUpdateValue = component + "ControlUpdateU";
        firePropertyChange("displayFormat", old, displayFormat);
    }

    public void registerActionReceiver(ActionReceiver controller) {
        this.controller = controller;
    }

    /**
     * Creates new form SetpointControl
     */
    public SetpointControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUpper = new javax.swing.JButton();
        jButtonLower = new javax.swing.JButton();
        jLabelReading = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 239, 239));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(92, 22));
        setMinimumSize(new java.awt.Dimension(92, 22));
        setPreferredSize(new java.awt.Dimension(92, 22));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUpper.setBackground(new java.awt.Color(255, 255, 204));
        jButtonUpper.setForeground(new java.awt.Color(0, 0, 0));
        jButtonUpper.setText(">");
        jButtonUpper.setToolTipText("");
        jButtonUpper.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonUpper.setMaximumSize(new java.awt.Dimension(16, 18));
        jButtonUpper.setMinimumSize(new java.awt.Dimension(16, 18));
        jButtonUpper.setPreferredSize(new java.awt.Dimension(16, 18));
        jButtonUpper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonUpperMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonUpperMouseReleased(evt);
            }
        });
        add(jButtonUpper, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 2, 16, 18));

        jButtonLower.setBackground(new java.awt.Color(255, 255, 204));
        jButtonLower.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLower.setText("<");
        jButtonLower.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLower.setMaximumSize(new java.awt.Dimension(16, 18));
        jButtonLower.setMinimumSize(new java.awt.Dimension(16, 18));
        jButtonLower.setPreferredSize(new java.awt.Dimension(16, 18));
        jButtonLower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonLowerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonLowerMouseReleased(evt);
            }
        });
        add(jButtonLower, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 2, 16, 18));

        jLabelReading.setBackground(new java.awt.Color(51, 51, 51));
        jLabelReading.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jLabelReading.setForeground(new java.awt.Color(0, 255, 153));
        jLabelReading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReading.setText("___,_");
        jLabelReading.setMaximumSize(new java.awt.Dimension(52, 18));
        jLabelReading.setMinimumSize(new java.awt.Dimension(52, 18));
        jLabelReading.setOpaque(true);
        jLabelReading.setPreferredSize(new java.awt.Dimension(52, 18));
        add(jLabelReading, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 52, 18));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpperMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpperMousePressed
        controller.userAction(new ActionCommand(component,
                ControlCommand.SETPOINT_INCREASE));
    }//GEN-LAST:event_jButtonUpperMousePressed

    private void jButtonUpperMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpperMouseReleased
        controller.userAction(new ActionCommand(component,
                ControlCommand.SETPOINT_STOP));
    }//GEN-LAST:event_jButtonUpperMouseReleased

    private void jButtonLowerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLowerMousePressed
        controller.userAction(new ActionCommand(component,
                ControlCommand.SETPOINT_DECREASE));
    }//GEN-LAST:event_jButtonLowerMousePressed

    private void jButtonLowerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLowerMouseReleased
        controller.userAction(new ActionCommand(component,
                ControlCommand.SETPOINT_STOP));
    }//GEN-LAST:event_jButtonLowerMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLower;
    private javax.swing.JButton jButtonUpper;
    private javax.swing.JLabel jLabelReading;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateComponent(PropertyChangeEvent evt) {
        
    }

    @Override
    public void updateComponent(String propertyName, Object newValue) {

    }

    @Override
    public void updateComponent(String propertyName, double newValue) {
        if (propertyName.equals(component)) {
            jLabelReading.setText(
                String.format(displayFormat, newValue));
        }
    }

    @Override
    public void updateComponent(String propertyName, boolean newValue) {
        
    }
}
